Openbiz Framework API: BizClassLoader Class Reference
BizClassLoader Class Reference
Static Public Member Functions
static getCoreLibFilePath ($className)
static getLibFileWithPath ($className, $packageName="")
static loadClass ($className, $packageName='')
Static Public Attributes
static $coreClassMap
Detailed Description
Description of BizClassLoader
Author
k6
Definition at line 13 of file BizClassLoader.php.
Member Function Documentation
static getCoreLibFilePath ($className) static
Get core path of class
Parameters
string $className class name
Returns
string full file name of class
Definition at line 40 of file BizClassLoader.php.
References OPENBIZ_HOME.
Referenced by Resource\getCoreLibFilePath(), and getLibFileWithPath().
    {
  //echo "_getCoreLibFilePath($className, $packageName)\n";
        // use class map first
        if ( @isset( self::$coreClassMap[$className]  )) {
            $classFile = OPENBIZ_HOME . self::$coreClassMap[$className];
            //if (file_exists($classFile)) // core file always exist
            return $classFile;
        } else { // if class not yet collect on class map, scan core path.
            $classFile = $className . '.php';
            // TODO: search the file under bin/, bin/data, bin/ui. bin/service, bin/easy, bin/easy/element.
            // guess class type and folder
            $lowClassName = strtolower($className);
            if (strrpos($lowClassName,'service')>0) $corePaths = array('service/');
            else if (strrpos($lowClassName,'form')>0 || strrpos($lowClassName,'form')===0) $corePaths = array('easy/');
            else if (strrpos($lowClassName,'view')>0 || strrpos($lowClassName,'view')===0) $corePaths = array('easy/');
            else if (strrpos($lowClassName,'dataobj')>0) $corePaths = array('data/');
            else $corePaths = array('easy/element/','','data/', 'easy/', 'service/');
            //$corePaths = array('', 'data/', 'easy/', 'easy/element/', 'ui/', 'service/');
            foreach ($corePaths as $path)
            {
                $_classFile = OPENBIZ_BIN . $path . $classFile;
                //echo "file_exists($_classFile)\n";
                if (file_exists($_classFile))
                    return $_classFile;
            }
            return null;
        }
    }
static getLibFileWithPath ($className, $packageName = "") static
Get openbiz library php file path by searching modules/package, /bin/package and /bin
Parameters
string $className
Returns
string php library file path
Definition at line 77 of file BizClassLoader.php.
References APP_HOME, getCoreLibFilePath(), MODULE_EX_PATH, and MODULE_PATH.
Referenced by ObjectFactory\constructObject(), and Resource\getLibFileWithPath().
    {
        if (!$className)
            return;
  //echo "getLibFileWithPath($className, $packageName)\n";
  // search it in cache first
        $cacheKey = $className . "_path";
        if (extension_loaded('0') && ($filePath = apc_fetch($cacheKey)) != null)
            return $filePath;
        if (strpos($className, ".") > 0)
            $className = str_replace(".", "/", $className);
        $filePath = null;
        $classFile = $className . ".php";
        $classFile_0 = $className . ".php";
        // convert package name to path, add it to classfile
        $classFileIsFound = false;
        if ($packageName)
        {
            $path = str_replace(".", "/", $packageName);
            // check the leading char '@'
            $checkExtModule = true;
            if (strpos($path, '@') === 0) {
                $path = substr($path, 1);
                $checkExtModule = false;
            }
            // search in apphome/modules directory first, search in apphome/bin directory then
            $classFiles[0] = MODULE_PATH . "/" . $path . "/" . $classFile;
            $classFiles[1] = APP_HOME . "/bin/" . $path . "/" . $classFile;
            if ($checkExtModule && defined('MODULE_EX_PATH')) array_unshift($classFiles, MODULE_EX_PATH . "/" . $path . "/" . $classFile);
            foreach ($classFiles as $classFile)
            {
    //echo "file_exists($classFile)\n";
                if (file_exists($classFile))
                {
                    $filePath = $classFile;
                    $classFileIsFound = true;
                    break;
                }
            }
        }
        if (!$classFileIsFound)
            $filePath = BizClassLoader::getCoreLibFilePath($className);
        // cache it to save file search
        if ($filePath && extension_loaded('apc'))
            apc_store($cacheKey, $filePath);
        /*if (!file_exists($filePath)) {
            trigger_error("Cannot find the library file of $className", E_USER_ERROR);
        }*/
        return $filePath;
    }
static loadClass ($className, $packageName = '') static
Definition at line 17 of file BizClassLoader.php.
Referenced by __autoload_openbiz().
    {
        //echo __METHOD__ . '-' . $className . '-' . $packageName.PHP_EOL;
        if (isset(self::$_classNameCache[$packageName.$className])) return true;
        if (strpos($className, 'Zend') === 0) return true;
        $filePath = self::getLibFileWithPath($className, $packageName);
        //var_dump( $filePath);
        if ($filePath)
        {
            include_once($filePath); // auto_load
            self::$_classNameCache[$packageName.$className] = 1;
            return true;
        }
        return false;
    }
Field Documentation
$coreClassMap static
Definition at line 140 of file BizClassLoader.php.