Openbiz Framework API: doTriggerService Class Reference
doTriggerService Class Reference
Public Member Functions
__construct (&$xmlArr)
execute ($dataObj, $triggerType)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_DataObjName
$m_DOTriggerList
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
auditTrail ($argList)
callService ($argList)
createInboxItem ($argList)
executeAction ($triggerAction, $dataObj)
executeAllActions ($doTrigger, $dataObj)
executeShell ($argList)
executeSQL ($argList)
matchCondition ($doTrigger, $dataObj)
readMetadata (&$xmlArr)
sendEmail ($argList)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 38 of file doTriggerService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize chartService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 60 of file doTriggerService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
auditTrail ($argList) protected
Audit trail
Parameters
array $argList
Returns
void
Definition at line 289 of file doTriggerService.php.
References BizSystem\getObject().
    {
        $auditServiceName = $argList["AuditService"];
        $auditService = BizSystem::getObject($auditServiceName);
        if ($auditService == null)
            return;
        $dataObjName = $argList["DataObjectName"];
        $ok = $auditService->audit($dataObjName);
        if ($ok == false)
        {
            // log $auditSvc->getErrorMsg();
        }
    }
callService ($argList) protected
Definition at line 201 of file doTriggerService.php.
References BizSystem\getObject().
    {
     $svcobj = $argList['Service'];
     $method = $argList['Method'];
     $svcobj = BizSystem::getObject($svcobj);
     if(!method_exists($svcobj,$method))
     {
      return;
     }
     unset($argList['Service']);
     unset($argList['Method']);
     return call_user_func_array(array($svcobj,$method),$argList);
    }
createInboxItem ($argList) protected
Create inbox item
Parameters
array $argList
Returns
void
Definition at line 326 of file doTriggerService.php.
    {    // call inbox service
    }
execute ($dataObj, $triggerType)
Execute trigger
Parameters
BizDataObj $dataObj
<type> $triggerType
Returns
void
Definition at line 94 of file doTriggerService.php.
References executeAllActions().
    {
        /* @var $doTrigger DOTrigger */
        foreach ($this->m_DOTriggerList as $doTrigger)
        {
            if ($doTrigger->m_TriggerType == $triggerType){             ;
                $this->executeAllActions($doTrigger, $dataObj);
            }
        }
    }
executeAction ($triggerAction, $dataObj) protected
Execute action
Parameters
TriggerAction $triggerAction
BizDataObj $dataObj
Returns
void
Definition at line 161 of file doTriggerService.php.
References Expression\evaluateExpression().
Referenced by executeAllActions().
    {
        // action method
        $methodName = $triggerAction->m_Action;
        // action method arguments
        if (method_exists($this, $methodName))
        {
            // evaluate arguments as expression support
            foreach ($triggerAction->m_ArgList as $argName => $argValue)
                $argList[$argName] = Expression::evaluateExpression($argValue, $dataObj);
            // check the immediate flag
            if ($triggerAction->m_Immediate == "Y") // call the method if Immediate is "Y"
                $this->$methodName($argList);
            else
            { // put it to a passive queue
                /* $passiveQueueSvc->Push($methodName,
                                      $argList,
                                      $triggerAction->m_DelayMinutes,
                                      $triggerAction->m_RepeatMinutes); */
            }
        }
    }
executeAllActions ($doTrigger, $dataObj) protected
Execute all action
Parameters
DOTrigger $doTrigger
BizDataObj $dataObj
Returns
void
Definition at line 112 of file doTriggerService.php.
References executeAction(), and matchCondition().
Referenced by execute().
    {
        if (! $this->matchCondition($doTrigger, $dataObj))
            return;
        /* @var $triggerAction TriggerAction */
        foreach ($doTrigger->m_TriggerActions as $triggerAction)
        {
            $this->executeAction($triggerAction, $dataObj);
        }
    }
executeShell ($argList) protected
Execute shell
Parameters
array $argList
Returns
void
Definition at line 221 of file doTriggerService.php.
    {
        $Script = $argList["Script"];
        $Inputs = $argList["Inputs"];
        $command = "$Script $Inputs";
        //$result = exec($command, $output);
        exec($command);
    }
executeSQL ($argList) protected
Execute SQL
Parameters
array $argList
Returns
void
Definition at line 237 of file doTriggerService.php.
References BizSystem\dbConnection().
    {
        $dbName = $argList["DBName"];
        if (! $dbName)
            $dbName = "Default";
        $sql = $argList["SQL"];
        $db = BizSystem::dbConnection($dbName);
        try
        {
            $resultSet = $db->query($sql);
        }
        catch (Exception $e)
        {
            $errorMessage = "Error in run SQL: " . $sql . ". " . $e->getMessage();
        }
    }
matchCondition ($doTrigger, $dataObj) protected
Match condition
Parameters
DOTrigger $doTrigger
BizDataObj $dataObj
Returns
boolean
Definition at line 130 of file doTriggerService.php.
References Expression\evaluateExpression().
Referenced by executeAllActions().
    {
        // evaluate expression
        $condExpr = $doTrigger->m_TriggerCondition["Expression"];
        if ($condExpr)
        {
            $exprVal = Expression::evaluateExpression($condExpr, $dataObj);
            if ($exprVal !== true)
                return false;
        }
        // do query with extra search rule, check if there's any record returned
        $extraSearchRule = $doTrigger->m_TriggerCondition["ExtraSearchRule"];
        if ($extraSearchRule)
        {
            $realSearchRule = Expression::evaluateExpression($extraSearchRule, $dataObj);
            $recordList = array();
            // get one record of the first page with additional searchrule
            $dataObj->fetchRecords($realSearchRule, $recordList, 1, 1, false);
            if (count($recordList) == 0)
                return false;
        }
        return true;
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 72 of file doTriggerService.php.
References MetaObject\prefixPackage(), and MetaObject\readMetaCollection().
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_DataObjName = $xmlArr["PLUGINSERVICE"]["ATTRIBUTES"]["DATAOBJECTNAME"];
        $this->m_DataObjName = $this->prefixPackage($this->m_DataObjName);
        $this->readMetaCollection($xmlArr["PLUGINSERVICE"]["DOTRIGGER"], $tmpList);
        if (!$tmpList)
            return;
        foreach ($tmpList as $triggerXml)
        {
            $this->m_DOTriggerList[] = new DOTrigger($triggerXml);
        }
    }
sendEmail ($argList) protected
Send email
Parameters
array $argList
Returns
boolean|string if sending error return error messege, if success return true
Definition at line 260 of file doTriggerService.php.
References BizSystem\getObject().
    {
        // emailService
        $emailServiceName = $argList["EmailService"];
        $emailService = BizSystem::getObject($emailServiceName);
        if ($emailService == null)
            return;
        $emailService->useAccount($argList["Account"]);
        $TOs = doTriggerService::_makeArray($argList["TOs"]);
        $CCs = doTriggerService::_makeArray($argList["CCs"]);
        $BCCs = doTriggerService::_makeArray($argList["BCCs"]);
        $Attachments = doTriggerService::_makeArray($argList["Attachments"]);
        $subject = $argList["Subject"];
        $body = $argList["Body"];
        $ok = $emailService->sendEmail($TOs, $CCs, $BCCs, $subject, $body, $Attachments);
        if ($ok == false)
        {
            return $emailService->getErrorMsg();
        }
        return $ok;
    }
Field Documentation
$m_DataObjName
Definition at line 45 of file doTriggerService.php.
$m_DOTriggerList
Definition at line 52 of file doTriggerService.php.