Openbiz Framework API: DynaView Class Reference
DynaView Class Reference
Public Member Functions
__construct (&$xmlArr)
Public Member Functions inherited from EasyView
__construct (&$xmlArr)
curPageURL ()
getCurrentPageUrl ()
getSessionVars ($sessionContext)
getViewSet ()
isInFormRefLibs ($formName)
outputAttrs ()
processRule ()
render ()
setConsoleOutput ($consoleOutput)
setParameters ()
setSessionVars ($sessionContext)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
processURL ()
Protected Member Functions inherited from EasyView
_render ()
getMessage ($msgId, $params=array())
getTransKey ($name)
getTransPrefix ()
initAllForms ()
processRequest ()
readMetadata (&$xmlArr)
readTile (&$xmlArr)
setClientScripts ()
translate ()
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Additional Inherited Members
Data Fields inherited from EasyView
$m_CacheLifeTime
$m_ConsoleOutput
$m_FormRefs
$m_Height
$m_IsPopup
$m_Keywords
$m_LastRenderedForm
$m_MessageFile
$m_Tab
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_ViewSet
$m_Widgets
$m_Width
Protected Attributes inherited from EasyView
$m_Messages
Detailed Description
Definition at line 26 of file DynaView.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize DynaView with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 34 of file DynaView.php.
References processURL().
    {
        parent::__construct($xmlArr);
        $this->processURL();
    }
Member Function Documentation
processURL () protected
Process URL to get the form param and add the form in the FormRefs
Returns
void
Definition at line 46 of file DynaView.php.
References EasyView\isInFormRefLibs(), BizSystem\objectFactory(), and MetaObject\prefixPackage().
Referenced by __construct().
    {
        // if url has form=...
        $paramForm = isset($_GET['form']) ? $_GET['form'] : null;
        $paramCForm = isset($_GET['cform']) ? $_GET['cform'] : null;
        if (!$paramForm)
            return;
        // add the form in FormRefs
        if ($paramForm)
        {
         if($this->isInFormRefLibs($paramForm))
          {
             $xmlArr["ATTRIBUTES"]["NAME"] = $paramForm;
             $xmlArr["ATTRIBUTES"]["SUBFORMS"] = $paramCForm ? $paramCForm : "";
             $formRef = new FormReference($xmlArr);
             $this->m_FormRefs->set($paramForm, $formRef);
             if ($paramCForm)
             {
              if($this->isInFormRefLibs($paramCForm))
              {
                  $xmlArr["ATTRIBUTES"]["NAME"] = $paramCForm;
                  $xmlArr["ATTRIBUTES"]["SUBFORMS"] = "";
                  $cformRef = new FormReference($xmlArr);
                  $this->m_FormRefs->set($paramCForm, $cformRef);
              }
             }
         }
        }
        // check url arg as fld:name=val
        $getKeys = array_keys($_GET);
        $paramFields = null;
        foreach ($getKeys as $key)
        {
            if (substr($key, 0, 4) == "fld:")
            {
                $fieldName = substr($key, 4);
                $fieldValue = $_GET[$key];
                $paramFields[$fieldName] = $fieldValue;
            }
        }
        if (!$paramFields)
            return;
        $paramForm = $this->prefixPackage($paramForm);
        $formObj = BizSystem::objectFactory()->getObject($paramForm);
        $formObj->setRequestParams($paramFields);
    }