Openbiz Framework API: BizDataObj Class Reference
BizDataObj Class Reference
Public Member Functions
__construct (&$xmlArr)
addRecord ($recArr, &$isParentObjUpdated)
canDeleteRecord ($record=null)
canDeleteRecordCondition ()
canUpdateRecord ($record=null)
canUpdateRecordCondition ()
cleanCache ()
deleteRecord ($recArr)
deleteRecords ($condition=null)
getJoinFields ($joinDataObj)
getOnAuditFields ()
insertRecord ($recArr)
joinRecord ($joinDataObj, $joinName="")
newRecord ()
removeRecord ($recArr, &$isParentObjUpdated)
updateRecord ($recArr, $oldRecord=null)
updateRecords ($setValue, $condition=null)
validateInput ()
Public Member Functions inherited from BizDataObj_Lite
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0, $sortRule="")
fetch ()
fetchById ($id)
fetchByName ($nameVal)
fetchOne ($searchRule, $sortRule="")
fetchRecords ($searchRule, &$resultRecords, $count=-1, $offset=0, $clearSearchRule=true, $noAssociation=false)
find ()
getActiveRecord ()
getErrorFields ()
getErrorMessage ()
getField ($fieldName)
getFieldNameByColumn ($column)
getFieldValue ($fieldName)
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
setActiveRecord ($currentRecord)
setActiveRecordId ($recordId)
setSessionVars ($sessionContext)
updateRecord ($recArr, $oldRec=null)
validateInput ()
Public Member Functions inherited from BizDataObj_Abstract
__construct (&$xmlArr)
clearAllRules ()
clearOtherSQLRule ()
clearSearchRule ()
clearSortRule ()
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0)
fetch ()
find ()
getAssociation ()
getDBConnection ($type='default')
getParameter ($paramName)
getProperty ($propertyName)
getRefObject ($objName)
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
resetRules ()
setLimit ($count, $offset=0)
setOtherSQLRule ($rule)
setQueryParam ($queryStr, $paramValues)
setSearchRule ($rule, $overWrite=false)
setSessionVars ($sessionContext)
setSortRule ($rule)
updateRecord ($recArr, $oldRec=null)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
cascadeDelete ()
cascadeUpdate ()
generateId ($isBeforeInsert=true, $tableName=null, $idCloumnName=null)
processCascadeAction ($objRef, $cascadeType)
validateUniqueness ()
Protected Member Functions inherited from BizDataObj_Lite
_fetch_record (&$resultSet)
_run_search ($limit=null)
getSQLHelper ()
Protected Member Functions inherited from BizDataObj_Abstract
getMessage ($msgid, $params=array())
inheritParentObj ()
readMetadata (&$xmlArr)
setAssociation ($objRef, $asscObj)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Additional Inherited Members
Data Fields inherited from BizDataObj_Abstract
$m_AccessRule
$m_BaseOtherSQLRule
$m_BaseSearchRule
$m_BaseSortRule
$m_BizRecord
$m_CacheLifeTime
$m_Database
$m_DataPermControl
$m_DeleteCondition
$m_IdGeneration
$m_InheritFrom
$m_MainTable
$m_MessageFile
$m_ObjReferences
$m_OtherSQLRule
$m_Parameters
$m_SearchRule
$m_SortRule
$m_Stateless
$m_TableJoins
$m_Uniqueness
$m_UpdateCondition
Protected Attributes inherited from BizDataObj_Lite
$_fetch4countQuery
$m_CurrentRecord
$m_ErrorFields
$m_ErrorMessage
$m_RecordId
Detailed Description
Definition at line 27 of file BizDataObj.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize BizDataObj_Abstract with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 35 of file BizDataObj.php.
    {
        parent::__construct($xmlArr);
    }
Member Function Documentation
addRecord ($recArr, & $isParentObjUpdated)
Add a new record to current record set
Parameters
array $recArr
boolean $isParentObjUpdated
Returns
boolean
Definition at line 874 of file BizDataObj.php.
References BizDataObj_Abstract\$m_BaseSearchRule, and BizDataObj_Assoc\addRecord().
    {
     $oldBaseSearchRule=$this->m_BaseSearchRule;
     $this->m_BaseSearchRule="";
        $result = BizDataObj_Assoc::addRecord($this, $recArr, $isParentObjUpdated);
        //$this->m_BaseSearchRule=$oldBaseSearchRule;
        return $result;
    }
canDeleteRecord ($record = null)
Check if the current record can be deleted
Returns
boolean
Definition at line 191 of file BizDataObj.php.
References canDeleteRecordCondition(), DATAPERM_SERVICE, and BizDataObj_Lite\getActiveRecord().
Referenced by deleteRecord().
    {
     if($this->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         if(!$record)
         {
          $record = $this->getActiveRecord();
         }
         $result = $svcObj->checkDataPerm($record,3,$this);
         if($result == false)
         {
          return false;
         }
        }
        $result = $this->canDeleteRecordCondition();
        return $result;
    }
canDeleteRecordCondition ()
Definition at line 211 of file BizDataObj.php.
References MetaObject\allowAccess().
Referenced by canDeleteRecord(), and deleteRecords().
    {
        if ($this->m_DeleteCondition)
        {
            // return Expression::evaluateExpression($this->m_DeleteCondition,$this);
            return $this->allowAccess($this->m_DeleteCondition);
        }
        return true;
    }
canUpdateRecord ($record = null)
Check if the current record can be updated
Returns
boolean
Definition at line 156 of file BizDataObj.php.
References canUpdateRecordCondition(), DATAPERM_SERVICE, and BizDataObj_Lite\getActiveRecord().
Referenced by updateRecord().
    {
     if($this->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         if(!$record)
         {
          $record = $this->getActiveRecord();
         }
         $result = $svcObj->checkDataPerm($record,2,$this);
         if($result == false)
         {
          return false;
         }
        }
        $result = $this->canUpdateRecordCondition();
        return $result;
    }
canUpdateRecordCondition ()
Definition at line 177 of file BizDataObj.php.
References MetaObject\allowAccess().
Referenced by canUpdateRecord(), and updateRecords().
    {
        if ($this->m_UpdateCondition)
        {
            //return Expression::evaluateExpression($this->m_UpdateCondition,$this);
            return $this->allowAccess($this->m_UpdateCondition);
        }
        return true;
    }
cascadeDelete () protected
Run cascade delete
Returns
void
Definition at line 725 of file BizDataObj.php.
References processCascadeAction().
Referenced by deleteRecord().
    {
        foreach ($this->m_ObjReferences as $objRef) {
            $this->processCascadeAction($objRef, "Delete");
        }
    }
cascadeUpdate () protected
Run cascade update
Returns
void
Definition at line 736 of file BizDataObj.php.
References processCascadeAction().
Referenced by updateRecord().
    {
        foreach ($this->m_ObjReferences as $objRef) {
            $this->processCascadeAction($objRef, "Update");
        }
    }
cleanCache ()
Clean chache
BizSystem $g_BizSystem
Returns
void
Definition at line 901 of file BizDataObj.php.
References BizSystem\getService().
Referenced by deleteRecord(), deleteRecords(), insertRecord(), updateRecord(), and updateRecords().
    {
        if($this->m_CacheLifeTime > 0)
        {
            $cacheSvc = BizSystem::getService(CACHE_SERVICE,1);
            $cacheSvc->init($this->m_Name, $this->m_CacheLifeTime);
            $cacheSvc->cleanAll();
        }
    }
deleteRecord ($recArr)
Delete current record or delete the given input record
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 534 of file BizDataObj.php.
References canDeleteRecord(), cascadeDelete(), cleanCache(), BizDataObj_Lite\getActiveRecord(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Abstract\getMessage(), BizSystem\getMessage(), BizDataObj_Lite\getSQLHelper(), and BizSystem\log().
    {
        if (!$this->canDeleteRecord())
        {
            $this->m_ErrorMessage = BizSystem::getMessage("DATA_NO_PERMISSION_DELETE",$this->m_Name);
            throw new BDOException($this->m_ErrorMessage);
            return false;
        }
        if ($recArr)
            $this->m_BizRecord->setInputRecord($recArr);
        else
            $this->m_BizRecord->setInputRecord($this->getActiveRecord());
        $sql = $this->getSQLHelper()->buildDeleteSQL($this);
        if ($sql)
        {
            $db = $this->getDBConnection("WRITE");
            $db->beginTransaction();
            try
            {
                $this->cascadeDelete(); // cascade delete
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Delete Sql = $sql");
                $db->query($sql);
                $db->commit();
            }
            catch (Exception $e)
            {
                $db->rollBack();
                if ($e instanceof BDOException)
                    throw $e;
                else {
                    BizSystem::log(LOG_ERR, "DATAOBJ", "Query error : ".$e->getMessage());
                    $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
                    throw new BDOException($this->m_ErrorMessage);
                }
                return false;
            }
        }
        //clean cached data
        $this->cleanCache();
        $this->_postDeleteRecord($this->m_BizRecord->getKeyValue());
        return true;
    }
deleteRecords ($condition = null)
Definition at line 583 of file BizDataObj.php.
References canDeleteRecordCondition(), cleanCache(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Abstract\getMessage(), BizSystem\getMessage(), BizDataObj_Lite\getSQLHelper(), and BizSystem\log().
    {
        if (!$this->canDeleteRecordCondition())
        {
            throw new BDOException( BizSystem::getMessage("DATA_NO_PERMISSION_DELETE",$this->m_Name) );
            return false;
        }
        $sql = $this->getSQLHelper()->buildDeleteSQLwithCondition($this,$condition);
        $db = $this->getDBConnection("WRITE");
        try
        {
            if($sql)
            {  // delete joint table first then delete main table's data'
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Delete Sql = $sql");
                $db->query($sql);
            }
        }
        catch (Exception $e)
        {
            BizSystem::log(LOG_ERR, "DATAOBJ", "Query error : ".$e->getMessage());
            $db->rollBack(); //if one failed then rollback all
            $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
            throw new BDOException($this->m_ErrorMessage);
            return false;
        }
        //clean cached data
        $this->cleanCache();
        return true;
    }
generateId ($isBeforeInsert = true, $tableName = null, $idCloumnName = null) protected
Generate Id according to the IdGeneration attribute
Parameters
boolean $isBeforeInsert
string $tableName
string $idCloumnName
Returns
long|string|boolean
Definition at line 417 of file BizDataObj.php.
References BizDataObj_Abstract\$m_MainTable, BizDataObj_Abstract\getDBConnection(), BizDataObj_Lite\getField(), BizSystem\getMessage(), and BizSystem\getService().
Referenced by insertRecord().
    {
        // Identity type id is generated after insert is done.
        // If this method is called before insert, return null.
        if ($isBeforeInsert && $this->m_IdGeneration == 'Identity')
            return null;
        if (!$isBeforeInsert && $this->m_IdGeneration != 'Identity')
        {
            $this->m_ErrorMessage = BizSystem::getMessage( "DATA_UNABLE_GET_ID",$this->m_Name);
            return false;
        }
        /* @var $genIdService genIdService */
        $genIdService = BizSystem::getService(GENID_SERVICE);
        if($this->m_db){
         $db = $this->m_db;
        }else{
         $db = $this->getDBConnection("READ");
        }
        $dbInfo = BizSystem::Configuration()->getDatabaseInfo($this->m_Database);
        $dbType = $dbInfo["Driver"];
        $table = $tableName ? $tableName : $this->m_MainTable;
        $column = $idCloumnName ? $idCloumnName : $this->getField("Id")->m_Column;
        try
        {
            $newId = $genIdService->getNewID($this->m_IdGeneration, $db, $dbType, $table, $column);
        }
        catch (Exception $e)
        {
            $this->m_ErrorMessage = $e->getMessage();
            return false;
        }
        return $newId;
    }
getJoinFields ($joinDataObj)
Get all fields that belong to the same join of the input field
Parameters
BizDataObj $joinDataObj the join data object
Returns
array joined fields array
Definition at line 786 of file BizDataObj.php.
    {
        // get the maintable of the joindataobj
        $joinTable = $joinDataObj->m_MainTable;
        $returnRecord = array();
        // find the proper join according to the maintable
        foreach ($this->m_TableJoins as $tableJoin)
        {
            if ($tableJoin->m_Table == $joinTable)
            {
                // populate the column-fieldvalue to columnRef-fieldvalue
                // get the field mapping to the column, then get the field value
                $joinFieldName = $joinDataObj->m_BizRecord->getFieldByColumn($tableJoin->m_Column); // joined-main table
                if (!$joinFieldName) continue;
                $refFieldName = $this->m_BizRecord->getFieldByColumn($tableJoin->m_ColumnRef); // join table
                $returnRecord[$refFieldName] = $joinFieldName;
                // populate joinRecord's field to current record
                foreach ($this->m_BizRecord as $field)
                {
                    if ($field->m_Join == $tableJoin->m_Name)
                    {
                        // use join column to match joinRecord field's column
                        $jFieldName = $joinDataObj->m_BizRecord->getFieldByColumn($field->m_Column); // joined-main table
                        $returnRecord[$field->m_Name] = $jFieldName;
                    }
                }
                break;
            }
        }
        return $returnRecord;
    }
getOnAuditFields ()
Get auditable fields
Returns
array list of BizField objects who are auditable
Definition at line 748 of file BizDataObj.php.
    {
        $fieldList = array();
        foreach ($this->m_BizRecord as $field)
        {
            if ($field->m_OnAudit)
                $fieldList[] = $field;
        }
        return $fieldList;
    }
insertRecord ($recArr)
Insert record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call getErrorMessage to get the error.
Definition at line 460 of file BizDataObj.php.
References cleanCache(), generateId(), QueryStringParam\getBindValues(), QueryStringParam\getBindValueString(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Abstract\getMessage(), BizDataObj_Lite\getSQLHelper(), BizSystem\log(), QueryStringParam\reset(), and validateInput().
    {
        if ( $this->_isNeedGenerateId($recArr) )
            $recArr["Id"] = $this->generateId();    // for certain cases, id is generated before insert
        $this->m_BizRecord->setInputRecord($recArr);
        if (!$this->validateInput()) return false;
        $db = $this->getDBConnection("WRITE");
        try
        {
            $sql = $this->getSQLHelper()->buildInsertSQL($this, $joinValues);
            if($sql)
            {
                $bindValues = QueryStringParam::getBindValues();
                $bindValueString = QueryStringParam::getBindValueString();
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Insert Sql = $sql"."; BIND: $bindValueString");
                QueryStringParam::reset();
                $db->query($sql, $bindValues);
            }
            //$mainId = $db->lastInsertId();
            if ( $this->_isNeedGenerateId($recArr) )
            {
             $this->m_db = $db; //compatiable for CLI mode and also speed up of it running
                $mainId = $this->generateId(false);
                $recArr["Id"] = $mainId;
            }
            BizSystem::log(LOG_DEBUG, "DATAOBJ", "New record Id is ".$recArr["Id"]);
        }
        catch (Exception $e)
        {
            BizSystem::log(LOG_ERR, "DATAOBJ", "Query Error : " . $e->getMessage());
            $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
            throw new BDOException($this->m_ErrorMessage);
            return null;
        }
        $this->m_BizRecord->setInputRecord($recArr);
        if ($this->_postUpdateLobFields($recArr) === false)
        {
            $this->m_ErrorMessage = $db->ErrorMsg();
            return false;
        }
        $this->cleanCache();
        $this->m_RecordId = $recArr["Id"];
        $this->m_CurrentRecord = null;
        $this->_postInsertRecord($recArr);
        return $recArr["Id"];
    }
joinRecord ($joinDataObj, $joinName = "")
Pick the joined object's current record to the current record
Parameters
BizDataObj $joinDataObj
string $joinName name of join (optional)
Returns
array return a modified record with joined record data
Definition at line 829 of file BizDataObj.php.
    {
        // get the maintable of the joindataobj
        $joinTable = $joinDataObj->m_MainTable;
        $joinRecord = null;
        $returnRecord = array();
        // find the proper join according to join name and the maintable
        foreach ($this->m_TableJoins as $tableJoin)
        {
            if (($joinName == $tableJoin->m_Name || $joinName == "")
                    && $tableJoin->m_Table == $joinTable)
            {
                // populate the column-fieldvalue to columnRef-fieldvalue
                // get the field mapping to the column, then get the field value
                $joinFieldName = $joinDataObj->m_BizRecord->getFieldByColumn($tableJoin->m_Column); // joined-main table
                if (!$joinFieldName) continue;
                if (!$joinRecord)
                    $joinRecord = $joinDataObj->getActiveRecord();
                $refFieldName = $this->m_BizRecord->getFieldByColumn($tableJoin->m_ColumnRef); // join table
                $returnRecord[$refFieldName] = $joinRecord[$joinFieldName];
                // populate joinRecord's field to current record
                foreach ($this->m_BizRecord as $fld)
                {
                    if ($fld->m_Join == $tableJoin->m_Name)
                    {
                        // use join column to match joinRecord field's column
                        $jfldname = $joinDataObj->m_BizRecord->getFieldByColumn($fld->m_Column); // joined-main table
                        $returnRecord[$fld->m_Name] = $joinRecord[$jfldname];
                    }
                }
                break;
            }
        }
        // return a modified record with joined record data
        return $returnRecord;
    }
newRecord ()
Create an empty new record
Returns
array - empty record array with default values
Definition at line 389 of file BizDataObj.php.
    {
        $recArr = $this->m_BizRecord->getEmptyRecordArr();
        // if association is 1-M, set the field (pointing to the column) value as the FieldRefVal
        if ($this->m_Association["Relationship"] == "1-M")
        {
            foreach ($this->m_BizRecord as $field)
            {
                if ($field->m_Column == $this->m_Association["Column"] && !$field->m_Join)
                {
                    $recArr[$field->m_Name] = $this->m_Association["FieldRefVal"];
                    break;
                }
            }
        }
        return $recArr;
    }
processCascadeAction ($objRef, $cascadeType) protected
Definition at line 629 of file BizDataObj.php.
References BizDataObj_Lite\count(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Lite\getField(), BizDataObj_Lite\getFieldValue(), BizDataObj_Abstract\getMessage(), BizSystem\getObject(), BizDataObj_Abstract\getRefObject(), and BizSystem\log().
Referenced by cascadeDelete(), and cascadeUpdate().
    {
        if (($cascadeType=='Delete' && $objRef->m_OnDelete)
            || ($cascadeType=='Update' && $objRef->m_OnUpdate))
        {
            if ($objRef->m_Relationship == "1-M" || $objRef->m_Relationship == "1-1") {
                $table = $objRef->m_Table;
                $column = $objRef->m_Column;
                $column2 = $objRef->m_Column2;
            }
            else if ($objRef->m_Relationship == "M-M" || $objRef->m_Relationship == "Self-Self") {
                $table = $objRef->m_XTable;
                $column = $objRef->m_XColumn1;
            }
            $refField = $this->getField($objRef->m_FieldRef);
            $fieldVal = $this->getFieldValue($objRef->m_FieldRef);
            $fieldVal2 = $this->getFieldValue($objRef->m_FieldRef2);
            if (!$fieldVal) return;
            if($column2){
             if (!$fieldVal2) return;
            }
            $db = $this->getDBConnection("WRITE");
            // get the cascade action sql
            if ($cascadeType=='Delete') {
                if ($objRef->m_OnDelete == "Cascade") {
                    $sql = "DELETE FROM ".$table." WHERE ".$column."='".$fieldVal."'";
                    if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                }
                else if ($objRef->m_OnDelete == "SetNull") {
                    $sql = "UPDATE ".$table." SET $column=null WHERE ".$column."='".$fieldVal."'";
                 if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                }
                else if ($objRef->m_OnDelete == "Restrict") {
                    // check if objRef has records
                    $refObj = $this->getRefObject($objRef->m_Name);
                 $sql = "`$column`='".$refField->m_Value."'";
                    if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                    if (count($refObj->directFetch($sql,1)) == 1) {
                        throw new BDOException($this->getMessage("DATA_UNABLE_DEL_REC_CASCADE",array($objRef->m_Name)));
                    }
                    return;
                }
            }
            else if ($cascadeType=='Update') {
                // check if the column value is actually changed
                if ($refField->m_OldValue == $refField->m_Value) return;
                if ($objRef->m_OnUpdate == "Cascade") {
                    $sql = "UPDATE ".$table." SET $column='".$refField->m_Value."' WHERE ".$column."='".$refField->m_OldValue."'";
                  if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                }
                else if ($objRef->m_OnUpdate == "SetNull") {
                    $sql = "UPDATE ".$table." SET $column=null WHERE ".$column."='".$refField->m_OldValue."'";
                 if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                }
                else if ($objRef->m_OnUpdate == "Restrict") {
                    // check if objRef has records
                    $refObj = BizSystem::getObject($objRef->m_Name);
     $sql = "[".$objRef->m_FieldRef."]='".$refField->m_OldValue."'";
                    if($column2 && $fieldVal2){
                     $sql .= " AND ".$column2."='".$fieldVal2."'";
                    }
                    if (count($refObj->directFetch($sql,1)) == 1) {
                        throw new BDOException($this->getMessage("DATA_UNABLE_UPD_REC_CASCADE",array($objRef->m_Name)));
                    }
                    return;
                }
            }
            try {
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Cascade $cascadeType Sql = $sql");
                $db->query($sql);
            }
            catch (Exception $e) {
                BizSystem::log(LOG_Err, "DATAOBJ", "Cascade $cascadeType Error: ".$e->getMessage());
                $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
                throw new BDOException($this->m_ErrorMessage);
            }
        }
    }
removeRecord ($recArr, & $isParentObjUpdated)
Remove a record from current record set of current association relationship
Parameters
array $recArr
boolean &$isParentObjUpdated
Returns
boolean
Definition at line 890 of file BizDataObj.php.
References BizDataObj_Assoc\removeRecord().
    {
        return BizDataObj_Assoc::removeRecord($this, $recArr, $isParentObjUpdated);
    }
updateRecord ($recArr, $oldRecord = null)
Update record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
array $oldRecord - associated array who is the old record field name / value pairs
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 227 of file BizDataObj.php.
References canUpdateRecord(), cascadeUpdate(), cleanCache(), BizDataObj_Lite\getActiveRecord(), QueryStringParam\getBindValues(), QueryStringParam\getBindValueString(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Lite\getFieldValue(), BizDataObj_Abstract\getMessage(), BizSystem\getMessage(), BizDataObj_Lite\getSQLHelper(), BizSystem\log(), QueryStringParam\reset(), and validateInput().
    {
        if (!$this->canUpdateRecord($oldRecord))
        {
            $this->m_ErrorMessage = BizSystem::getMessage("DATA_NO_PERMISSION_UPDATE",$this->m_Name);
            throw new BDOException($this->m_ErrorMessage);
            return false;
        }
        if (!$oldRecord)
            $oldRecord = $this->getActiveRecord();
        if (!$recArr["Id"])
            $recArr["Id"] = $this->getFieldValue("Id");
        // save the old values
        $this->m_BizRecord->saveOldRecord($oldRecord);
        // set the new values
        $this->m_BizRecord->setInputRecord($recArr);
        if (!$this->validateInput()) return false;
        QueryStringParam::reset();
        $sql = $this->getSQLHelper()->buildUpdateSQL($this);
        if ($sql)
        {
            $db = $this->getDBConnection("WRITE");
            $db->beginTransaction();
            try
            {
                $this->cascadeUpdate(); // cascade update
                $bindValues = QueryStringParam::getBindValues();
                $bindValueString = QueryStringParam::getBindValueString();
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Update Sql = $sql"."; BIND: $bindValueString");
                QueryStringParam::reset();
                $db->query($sql, $bindValues);
                $db->commit();
            }
            catch (Exception $e)
            {
                $db->rollBack();
                if ($e instanceof BDOException)
                    throw $e;
                else {
                    BizSystem::log(LOG_ERR, "DATAOBJ", "Query error : ".$e->getMessage());
                    $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
                    throw new BDOException($this->m_ErrorMessage);
                }
                return false;
            }
            $this->cleanCache(); //clean cached data
            $this->_postUpdateLobFields($recArr);
            $this->m_CurrentRecord = null;
            $this->_postUpdateRecord($recArr);
        }
        return true;
    }
updateRecords ($setValue, $condition = null)
Definition at line 290 of file BizDataObj.php.
References canUpdateRecordCondition(), cleanCache(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Abstract\getMessage(), BizSystem\getMessage(), BizDataObj_Lite\getSQLHelper(), and BizSystem\log().
    {
        if (!$this->canUpdateRecordCondition())
        {
            $this->m_ErrorMessage = BizSystem::getMessage("DATA_NO_PERMISSION_UPDATE",$this->m_Name);
            return false;
        }
  /*$setValue[field]=value*/
  if(is_array($setValue)){
   $setValue_srt='';
   foreach($setValue as $key=>$value){
    if($value!=''){
     $setValue_srt.=$setValue_srt?",[$key]='$value'":"[$key]='$value'";
    }
   }
   $setValue=$setValue_srt;
  }
        $sql = $this->getSQLHelper()->buildUpdateSQLwithCondition($this,$setValue ,$condition);
        $db = $this->getDBConnection("WRITE");
        try
        {
            if($sql)
            {  // delete joint table first then delete main table's data'
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Delete Sql = $sql");
                $db->query($sql);
            }
        }
        catch (Exception $e)
        {
            BizSystem::log(LOG_ERR, "DATAOBJ", "Query error : ".$e->getMessage());
            $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
            throw new BDOException($this->m_ErrorMessage);
            return false;
        }
        //clean cached data
        $this->cleanCache();
        return true;
    }
validateInput ()
Validate user input data and trigger error message and adjust BizField if invalid.
Returns
boolean
Definition at line 46 of file BizDataObj.php.
References BizDataObj_Lite\$m_ErrorMessage, BizDataObj_Lite\count(), BizDataObj_Abstract\getMessage(), BizSystem\getService(), and validateUniqueness().
Referenced by insertRecord(), and updateRecord().
    {
        $this->m_ErrorFields = array();
        foreach($this->m_BizRecord->m_InputFields as $fld)
        {
            /* @var $bizField BizField */
            $bizField = $this->m_BizRecord->get($fld);
            if($bizField->m_Encrypted=="Y"){
             if ($bizField->checkRequired() == true &&
                     ($bizField->m_Value===null || $bizField->m_Value === ""))
             {
                 $this->m_ErrorMessage = $this->getMessage("DATA_FIELD_REQUIRED",array($fld));
                 $this->m_ErrorFields[$bizField->m_Name] = $this->m_ErrorMessage;
             }
             continue;
            }
            if ($bizField->checkRequired() == true &&
                    ($bizField->m_Value===null || $bizField->m_Value === ""))
            {
                $this->m_ErrorMessage = $this->getMessage("DATA_FIELD_REQUIRED",array($fld));
                $this->m_ErrorFields[$bizField->m_Name] = $this->m_ErrorMessage;
            }
            elseif ($bizField->m_Value!==null && $bizField->checkValueType() == false)
            {
                $this->m_ErrorMessage = $this->getMessage("DATA_FIELD_INCORRECT_TYPE", array($fld, $bizField->m_Type));
                $this->m_ErrorFields[$bizField->m_Name] = $this->m_ErrorMessage;
            }
            elseif ($bizField->m_Value!==null && $bizField->Validate() == false)
            {
                /* @var $validateService validateService */
                $validateService = BizSystem::getService(VALIDATE_SERVICE);
                $this->m_ErrorMessage = $validateService->getErrorMessage($bizField->m_Validator, $bizField->m_Name);
                if ($this->m_ErrorMessage == false)
                { //Couldn't get a clear error message so let's try this
                    $this->m_ErrorMessage = $this->getMessage("DATA_FIELD_INVALID_INPUT",array($fld,$value,$bizField->m_Validator));                //
                }
                $this->m_ErrorFields[$bizField->m_Name] = $this->m_ErrorMessage;
            }
        }
        if (count($this->m_ErrorFields)>0)
        {
            //print_r($this->m_ErrorFields);
            throw new ValidationException($this->m_ErrorFields);
            return false;
        }
        // validate uniqueness
        if ($this->validateUniqueness() == false)
            return false;
        return true;
    }
validateUniqueness () protected
Validate uniqueness Uniqueness = "fld1,fld2;fld3,fld4;..."
Returns
boolean
Definition at line 107 of file BizDataObj.php.
References BizDataObj_Lite\$m_ErrorMessage, BizDataObj_Lite\count(), BizDataObj_Lite\directFetch(), and BizDataObj_Abstract\getMessage().
Referenced by validateInput().
    {
        if (!$this->m_Uniqueness)
            return true;
        $groupList = explode(";",$this->m_Uniqueness);
        foreach ($groupList as $group)
        {
            $searchRule = "";
            $needCheck = true;
            $fields = explode(",",$group);
            foreach ($fields as $fld)
            {
                $bizField = $this->m_BizRecord->get($fld);
                if ($bizField->m_Value===null || $bizField->m_Value === "" || $bizField->m_Value==$bizField->m_OldValue)
                {
                    $needCheck = false;
                    break;
                }
                if ($searchRule == "")
                    $searchRule = "[".$bizField->m_Name."]='".addslashes($bizField->m_Value)."'";
                else
                    $searchRule .= " AND [".$bizField->m_Name."]='".addslashes($bizField->m_Value)."'";
            }
            if ($needCheck)
            {
                $recordList = $this->directFetch($searchRule, 1);
                if ($recordList->count()>0)
                {
                    $this->m_ErrorMessage = $this->getMessage("DATA_NOT_UNIQUE",array($group));
                    foreach ($fields as $fld)
                    {
                        $this->m_ErrorFields[$fld] = $this->m_ErrorMessage;
                    }
                }
            }
        }
        if (count($this->m_ErrorFields)>0)
        {
            throw new ValidationException($this->m_ErrorFields);
            return false;
        }
        return true;
    }