Openbiz Framework API: HTMLTabs Class Reference
HTMLTabs Class Reference
Public Member Functions
__construct (&$xmlArr)
isCurrentTab ($tabView, $curViewObj, $curViewName)
render ()
rerender ()
setCurrentTab ($viewName)
setCurrentTabInSession ($tview, $curViewObj, $curViewName)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_TabViews
$m_TemplateFile
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
readMetadata (&$xmlArr)
setClientScripts ($tabs, $hasForms)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_ActiveCssClassName
$m_CurrentTab
$m_InactiveCssClassName
Detailed Description
Definition at line 26 of file HTMLTabs.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize HTMLTabs with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 40 of file HTMLTabs.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
isCurrentTab ($tabView, $curViewObj, $curViewName)
Ask if the $this tab object is the current tab
Parameters
TabView $tabView
EasyView $curViewObj current View Object
string $curViewName name of the current view
Returns
boolean TRUE if on the current tab, otherwise FALSE
Definition at line 135 of file HTMLTabs.php.
Referenced by render(), and setCurrentTabInSession().
    { //--jmmz
        $currentTab = false; //this variable save 'true' if is the current tab and 'false' in otherwise --jmmz
        if ($this->m_CurrentTab)
        {
            $currentTab = ($this->m_CurrentTab == $tabView->m_Name || $this->m_CurrentTab == $tabView->m_Tab)
                    ? TRUE
                    : FALSE;
        }
        elseif ($tabView->m_ViewSet)
        {
            if ($curViewObj)
            // check if current view's viewset == tview->m_ViewSet
                $currentTab = ($curViewObj->getViewSet() == $tabView->m_ViewSet) ? true : false;
        }
        else
        {
            $currentTab = ($curViewName == $tabView->m_View || $curViewObj->m_Tab == $tabView->m_Name) ? true : false;
        }
        return $currentTab;
    }
readMetadata (& $xmlArr) protected
Read Metadata from xml array
Parameters
array $xmlArr
Definition at line 50 of file HTMLTabs.php.
Referenced by __construct().
    {
        $this->m_Name = $xmlArr["TABS"]["ATTRIBUTES"]["NAME"];
        $this->m_Package = $xmlArr["TABS"]["ATTRIBUTES"]["PACKAGE"];
        $this->m_Class = $xmlArr["TABS"]["ATTRIBUTES"]["CLASS"];
        $this->m_TemplateFile = $xmlArr["TABS"]["ATTRIBUTES"]["TEMPLATEFILE"];
        $this->m_TabViews = new MetaIterator($xmlArr["TABS"]["TABVIEWS"]["VIEW"],"TabView");
        $this->m_ActiveCssClassName = "'{$xmlArr["TABS"]["ATTRIBUTES"]["ACTIVECSSCLASSNAME"]}'";
        $this->m_InactiveCssClassName = "'{$xmlArr["TABS"]["ATTRIBUTES"]["INACTIVECSSCLASSNAME"]}'";
    }
render ()
Render the html tabs
BizSystem $g_BizSystem
Returns
string html content of the tabs
Implements iUIControl.
Definition at line 193 of file HTMLTabs.php.
References $g_BizSystem, BizSystem\getObject(), BizSystem\getService(), BizSystem\getSmartyTemplate(), BizSystem\getTplFileWithPath(), isCurrentTab(), setClientScripts(), and setCurrentTabInSession().
Referenced by rerender().
    {
        global $g_BizSystem;
        $curView = $g_BizSystem->getCurrentViewName();
        $curViewobj = ($curView) ? BizSystem::getObject($curView) : null;
        $profile = $g_BizSystem->getUserProfile();
        $svcobj = BizSystem::getService(ACCESS_SERVICE);
        $role = isset($profile["ROLE"]) ? $profile["ROLE"] : null;
        // list all views and highlight the current view
        // pass $tabs(caption, url, target, icon, current) to template
        $smarty = BizSystem::getSmartyTemplate();
        $tabs = array();
        $i = 0;
        $hasForms = false;
        foreach ($this->m_TabViews as $tview)
        {
            // tab is renderd if  no definition  is found in accessservice.xml (default)
            if ($svcobj->allowViewAccess($tview->m_View, $role))
            {
                $tabs[$i]['name']=$tview->m_Name; //Name of each tab--jmmz
                $tabs[$i]['forms']=$this->_renderJSCodeForForms($tview->m_Forms);//Configuration of the forms to hide or show--jmmz
                $tabs[$i]['caption'] = $tview->m_Caption;
                $tabs[$i]['url'] = $this->_renderURL($tview); //Call the method to render the url--jmmz
                //If I have forms to hide or show I add the event because I don't need an URL, I need an event
                if( (bool) $tview->hasForms() )
                {
                    $tabs[$i]['event']=$tabs[$i]['url']; //Assign The url rendered to the event on click
                    $tabs[$i]['url']='javascript:void(0)'; //If I put url in '' then the href want send me to another direction
                    $this->setCurrentTabInSession($tview, $curViewobj, $curView); //I set the current tab wrote in session
                    $hasForms = TRUE;
                }
                $tabs[$i]['target'] = $tview->m_Target;
                $tabs[$i]['icon'] = $tview->m_Icon;
                $tabs[$i]['current'] = $this->isCurrentTab($tview,$curViewobj, $curView); //I get the current tab.
                $i++;
            }
        }
        $this->setClientScripts($tabs, $hasForms);
        $smarty->assign("tabs", $tabs);
        $smarty->assign("tabs_Name",$this->m_Name);
        return $smarty->fetch(BizSystem::getTplFileWithPath($this->m_TemplateFile, $this->m_Package));
    }
rerender ()
Rerender the tabs
Returns
string html content of the menu
Definition at line 249 of file HTMLTabs.php.
References render().
    {
        return $this->render();
    }
setClientScripts ($tabs, $hasForms) protected
Include client javascripts or CSS in the html content
Parameters
array $tabs
boolean $hasForms
Returns
void
Definition at line 261 of file HTMLTabs.php.
References $g_BizSystem, and BizSystem\clientProxy().
Referenced by render().
    {
        global $g_BizSystem;
        BizSystem::clientProxy()->appendScripts("tabs", "tabs.js");
        BizSystem::clientProxy()->appendStyles("tabs", "tabs.css");
        if ($hasForms)
        {
            $tab_script = '<script type = "text/javascript">'.PHP_EOL;
            foreach ($tabs as $tab)
            {
                $tab_script .=   'var '.$tab['name'].'_config = '.$tab['forms'].';'.PHP_EOL;
            }
            $tab_script .=   'var '.$this->m_Name.'_active = '.$this->m_ActiveCssClassName.';'.PHP_EOL;
            $tab_script .=   'var '.$this->m_Name.'_inactive = '.$this->m_InactiveCssClassName.';'.PHP_EOL;
            $tab_script .= '</script>';
            BizSystem::clientProxy()->appendScripts("tab_forms_$this->m_Name", $tab_script, FALSE);
        }
    }
setCurrentTab ($viewName)
Set current tab with view name
Parameters
string $viewName name of a view
Returns
void
Definition at line 122 of file HTMLTabs.php.
Referenced by setCurrentTabInSession().
    {
        $this->m_CurrentTab = $viewName;
    }
setCurrentTabInSession ($tview, $curViewObj, $curViewName)
Save the current tab in the session object
Parameters
TabView $tview
EasyView $curViewObj current View Object
string $curViewName name of the current view
Returns
void
Definition at line 166 of file HTMLTabs.php.
References isCurrentTab(), BizSystem\sessionContext(), and setCurrentTab().
Referenced by render().
    {
        $sessionContext = BizSystem::sessionContext();
        if (!$sessionContext->varExists('CURRENT_TAB_'.$this->m_Name))
        {
            if ($this->isCurrentTab($tview,$curViewObj, $curViewName))
            {
                $sessionContext->setVar('CURRENT_TAB_'.$this->m_Name,$tview->m_Name);
            }
            else
            {
                //Don't set var if isn't the current var
            }
        }
        else
        {
            $this->setCurrentTab($sessionContext->getVar('CURRENT_TAB_'.$this->m_Name));
        }
    }
Field Documentation
$m_ActiveCssClassName protected
Definition at line 31 of file HTMLTabs.php.
$m_CurrentTab protected
Definition at line 30 of file HTMLTabs.php.
$m_InactiveCssClassName protected
Definition at line 32 of file HTMLTabs.php.
$m_TabViews
Definition at line 29 of file HTMLTabs.php.
$m_TemplateFile
Definition at line 28 of file HTMLTabs.php.