Openbiz Framework API: OB_ErrorHandler Class Reference
OB_ErrorHandler Class Reference
Static Public Member Functions
static errorHandler ($errNo, $errMsg, $fileName, $lineNum, $vars)
static exceptionHandler ($exc)
Static Public Attributes
static $errorMode
Detailed Description
Definition at line 27 of file ErrorHandler.php.
Member Function Documentation
static errorHandler ($errNo, $errMsg, $fileName, $lineNum, $vars) static
User error handler
Parameters
number $errNo error number
string $errMsg error message
string $fileName file name where the error occurred
number $lineNum line number where the error occurred
<type> $vars (not yet implemented)
Returns
void
Definition at line 41 of file ErrorHandler.php.
References BizSystem\clientProxy(), and BizSystem\logError().
    {
        // don't respond to the error if it
        // was suppressed with a '@'
        if (error_reporting() == 0)
            return;
        if ($errNo == E_NOTICE || $errNo == E_STRICT) { // || $errno == E_WARNING)
   //echo "errorHandler ($errNo, $errMsg, $fileName, $lineNum, $vars)\n";
   return; // ignore notice error
  }
        $debug_array = debug_backtrace();
        $back_trace = self::_errorBacktrace($debug_array);
        $err = self::_getOutputErrorMsg($errNo, $errMsg, $fileName, $lineNum, $back_trace);
        //Send Error to Log Service;
        require_once dirname(__FILE__).'/BizSystem.php';
        BizSystem::logError ($errNo, "ErrorHandler", $errMsg, null, $back_trace);
        if ((defined('CLI') && CLI) || self::$errorMode == 'text')
        {
         echo $err;
        }
        else
        {
         BizSystem::clientProxy()->showErrorMessage($err, true);
        }
        if ($errNo == E_USER_ERROR || $errNo == E_ERROR){
   BizSystem::clientProxy()->printOutput();
         exit();
        }
    }
static exceptionHandler ($exc) static
User exception handler
Parameters
object $exc hold error data
Returns
void
Definition at line 77 of file ErrorHandler.php.
References BizSystem\clientProxy(), and BizSystem\logError().
    {
        $errno = $exc->getCode();
        $errmsg = $exc->getMessage();
        $filename = $exc->getFile();
        $linenum = $exc->getLine();
        $debug_array = $exc->getTrace();
        $back_trace = self::_errorBacktrace($debug_array);
        $err = self::_getOutputErrorMsg($errno, $errmsg, $filename, $linenum, $back_trace);
        BizSystem::logError ($errno, "ExceptionHandler", $errmsg, null, $back_trace);
        if ((defined('CLI') && CLI) || self::$errorMode == 'text'){
         echo $err;
        }else{
         BizSystem::clientProxy()->showErrorMessage($err, true);
        }
        if(!$exc->no_exit)
        {
         BizSystem::clientProxy()->printOutput();
         exit();
        }
    }
Field Documentation
$errorMode static
Definition at line 29 of file ErrorHandler.php.