Openbiz Framework API: FormReference Class Reference
FormReference Class Reference
Public Member Functions
__construct ($xmlArr)
setParentForm ($formName)
setViewName ($viewName)
Data Fields
$m_Description
$m_Display
$m_Name
$m_SubForms
Protected Member Functions
getTransKey ($name)
translate ()
Protected Attributes
$m_ViewName
Detailed Description
Definition at line 463 of file EasyView.php.
Constructor & Destructor Documentation
__construct ($xmlArr)
Contructor, store form info from array to variable of class
Parameters
array $xmlArr array of form information
Definition at line 477 of file EasyView.php.
    {
     foreach($xmlArr["ATTRIBUTES"] as $name=>$value)
        {
         $name = 'm_'.ucfirst(strtolower($name));
         $this->$name = $value;
        }
        $this->m_Name = $xmlArr["ATTRIBUTES"]["NAME"];
        $this->m_SubForms = $xmlArr["ATTRIBUTES"]["SUBFORMS"];
        $this->m_Description = $xmlArr["ATTRIBUTES"]["DESCRIPTION"];
    }
Member Function Documentation
getTransKey ($name) protected
Definition at line 513 of file EasyView.php.
Referenced by translate().
    {
     $shortViewName = substr($this->m_ViewName,intval(strrpos($this->m_ViewName,'.')+1));
     return strtoupper($shortViewName.'_'.$this->m_Name.'_'.$name);
    }
setParentForm ($formName)
Set parent form
Parameters
string $formName form name @return void
Definition at line 495 of file EasyView.php.
    {
        $this->_parentForm = $formName;
    }
setViewName ($viewName)
Definition at line 500 of file EasyView.php.
References translate().
    {
        $this->m_ViewName = $viewName;
        $this->translate();
    }
translate () protected
Definition at line 506 of file EasyView.php.
References getTransKey(), and I18n\t().
Referenced by setViewName().
    {
     $module = substr($this->m_ViewName,0,intval(strpos($this->m_ViewName,'.')));
        //echo $this->getTransKey('Description');
        $this->m_Description = I18n::t($this->m_Description, $this->getTransKey('Description'), $module);
    }
Field Documentation
$m_Description
Definition at line 467 of file EasyView.php.
$m_Display
Definition at line 469 of file EasyView.php.
$m_Name
Definition at line 465 of file EasyView.php.
$m_SubForms
Definition at line 466 of file EasyView.php.
$m_ViewName protected
Definition at line 470 of file EasyView.php.