Openbiz Framework API: ImageUploader Class Reference
ImageUploader Class Reference
Public Member Functions
__construct (&$xmlArr, $formObj)
render ()
setValue ($value)
Public Member Functions inherited from FileUploader
__construct (&$xmlArr, $formObj)
render ()
setValue ($value)
Public Member Functions inherited from FileInput
getValue ()
render ()
Public Member Functions inherited from InputElement
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_PicHeight
$m_PicWidth
$m_Preview
$m_ThumbFolder
$m_ThumbHeight
$m_ThumbWidth
Data Fields inherited from FileUploader
$m_Deleteable
$m_Uploaded
$m_UploadFileType
$m_UploadFolder
$m_UploadRoot
$m_UploadRootURL
$m_UseRawName
Protected Member Functions
readMetaData (&$xmlArr)
resizeImage ($sourceFileName, $destFileName, $width, $height, $quality)
Protected Member Functions inherited from FileUploader
readMetaData (&$xmlArr)
Detailed Description
Definition at line 27 of file ImageUploader.php.
Constructor & Destructor Documentation
__construct (& $xmlArr, $formObj)
Initialize Element with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 42 of file ImageUploader.php.
References readMetaData(), and Element\translate().
    {
        parent::__construct($xmlArr, $formObj);
        $this->readMetaData($xmlArr);
        $this->translate();
    }
Member Function Documentation
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 55 of file ImageUploader.php.
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_PicWidth  = isset($xmlArr["ATTRIBUTES"]["PICWIDTH"]) ? $xmlArr["ATTRIBUTES"]["PICWIDTH"] : null;
        $this->m_PicHeight  = isset($xmlArr["ATTRIBUTES"]["PICHEIGHT"]) ? $xmlArr["ATTRIBUTES"]["PICHEIGHT"] : null;
        $this->m_PicQuality  = isset($xmlArr["ATTRIBUTES"]["PICQUALITY"]) ? $xmlArr["ATTRIBUTES"]["PICQUALITY"] : 80;
        $this->m_ThumbWidth  = isset($xmlArr["ATTRIBUTES"]["THUMBWIDTH"]) ? $xmlArr["ATTRIBUTES"]["THUMBWIDTH"] : null;
        $this->m_ThumbHeight  = isset($xmlArr["ATTRIBUTES"]["THUMBHEIGHT"]) ? $xmlArr["ATTRIBUTES"]["THUMBHEIGHT"] : null;
        $this->m_ThumbQuality = isset($xmlArr["ATTRIBUTES"]["THUMBQUALITY"]) ? $xmlArr["ATTRIBUTES"]["THUMBQUALITY"] : 50;
        $this->m_ThumbFolder  = isset($xmlArr["ATTRIBUTES"]["THUMBFOLDER"]) ? $xmlArr["ATTRIBUTES"]["THUMBFOLDER"] : null;
        $this->m_Preview  = isset($xmlArr["ATTRIBUTES"]["PREVIEW"]) ? $xmlArr["ATTRIBUTES"]["PREVIEW"] : false;
    }
render ()
Implements iUIControl.
Definition at line 226 of file ImageUploader.php.
References InputElement\getEnabled(), Element\getFunction(), Element\getStyle(), and FileInput\getValue().
    {
        $disabledStr = ($this->getEnabled() == "N") ? "disabled=\"true\"" : "";
        $style = $this->getStyle();
        $func = $this->getFunction();
        $value = $this->getValue();
        if($this->m_Preview){
         if($value){
          $preview = "<img id=\"" . $this->m_Name ."_preview\" src=\"$value\" class=\"image_preview\" />";
         }
        }
        if($this->m_Deleteable=="Y"){
         $delete_opt="<input type=\"checkbox\" name=\"" . $this->m_Name . "_DELETE\" id=\"" . $this->m_Name ."_DELETE\" >Delete";
        } else{
         $delete_opt="";
        }
        $sHTML .= "
        $preview
        <input type=\"file\" onchange=\"Openbiz.ImageUploader.updatePreview('" . $this->m_Name ."')\" name=\"$this->m_Name\" id=\"" . $this->m_Name ."\" value=\"$this->m_Value\" $disabledStr $this->m_HTMLAttr $style $func>
        $delete_opt
        ";
        return $sHTML;
    }
resizeImage ($sourceFileName, $destFileName, $width, $height, $quality) protected
Resize the image *
Parameters
string $sourceFileName
string $destFileName
number $width
number $height
int $quality
quality is optional, and ranges from 0 (worst quality, smaller file) to 100 (best quality, biggest file). The default is the default IJG quality value (about 75).
Returns
boolean true is success
Definition at line 156 of file ImageUploader.php.
Referenced by setValue().
    {
  if(!function_exists("imagejpeg"))
  {
   return ;
  }
        if($width == 0)
        {
            $width = $height;
        }
        if($height == 0)
        {
            $height = $width;
        }
        list($origWidth, $origHeight) = getimagesize($sourceFileName);
        $origRatio = $origWidth / $origHeight;
        if ( ($width / $height) > $origRatio)
        {
            $width = $height * $origRatio;
        }
        else
        {
            $height = $width / $origRatio;
        }
        $image_p = imagecreatetruecolor($width, $height);
        try{
         $image = @imagecreatefromjpeg($sourceFileName);
        }catch(Exception $e){}
        try{
         if(!$image){
          $image = @imagecreatefrompng($sourceFileName);
         }
        }catch(Exception $e){}
        try{
         if(!$image){
          $image = @imagecreatefromgif($sourceFileName);
         }
      }catch(Exception $e){}
     try{
         if(!$image){
          $image = @imagecreatefromwbmp($sourceFileName);
         }
      }catch(Exception $e){}
     try{
         if(!$image){
          $image = @imagecreatefromxbm($sourceFileName);
         }
      }catch(Exception $e){}
     try{
         if(!$image){
          $image = @imagecreatefromxpm($sourceFileName);
         }
      }catch(Exception $e){}
      if(!$image){
      return ;
     }
        imagecopyresampled($image_p, $image, 0, 0, 0, 0, $width, $height, $origWidth, $origHeight);
        return imagejpeg($image_p, $destFileName, $quality);
    }
setValue ($value)
Set value of element
Parameters
mixed $value
Returns
mixed
Definition at line 74 of file ImageUploader.php.
References MetaObject\$m_Name, $m_PicHeight, $m_PicWidth, $m_ThumbHeight, $m_ThumbWidth, BizSystem\clientProxy(), and resizeImage().
    {
     if($this->m_Deleteable=='N' )
     {
     }
     else
     {
      $delete_user_opt=BizSystem::clientProxy()->getFormInputs($this->m_Name."_DELETE");
      if($delete_user_opt)
      {
       $this->m_Value="";
       return;
      }
      else
      {
       if(count($_FILES)>0){
       }else{
        $this->m_Value = $value;
       }
      }
     }
     if(count($_FILES)>0)
  {
   if(!$this->m_Uploaded && $_FILES[$this->m_Name]["size"] > 0)
   {
    $picFileName = parent::setValue($value);
    if((int)$this->m_PicWidth>0 || (int)$this->m_PicHeight>0)
    {
     //resize picture size
     $fileName = $this->m_UploadRoot.$picFileName;
     $width = $this->m_PicWidth;
     $height = $this->m_PicHeight;
     $quality = $this->m_PicQuality;
     $this->resizeImage($fileName, $fileName, $width, $height, $quality);
    }
    if(
    ((int)$this->m_ThumbWidth>0 || (int)$this->m_ThumbHeight>0) &&
      $this->m_ThumbFolder!=""
    )
    {
     //generate thumbs picture
     if(!is_dir($this->m_UploadRoot.$this->m_ThumbFolder))
     {
      mkdir($this->m_UploadRoot.$this->m_ThumbFolder ,0777,true);
     }
     $file = $_FILES[$this->m_Name];
     $thumbPath = $this->m_ThumbFolder."/thumbs-".date("YmdHis")."-".urlencode($file['name']);
     $thumbFileName = $this->m_UploadRoot.$thumbPath;
     $width = $this->m_ThumbWidth;
     $height = $this->m_ThumbHeight;
     $quality = $this->m_ThumbQuality;
     $this->resizeImage($fileName, $thumbFileName, $width, $height, $quality);
     $result=array('picture'=>$this->m_UploadRootURL.$picFileName,'thumbpic'=>$this->m_UploadRootURL.$thumbPath);
     $this->m_Value=serialize($result);
    }
   }
  }
  else
  {
   $this->m_Value = $value;
  }
    }
Field Documentation
$m_PicHeight
Definition at line 30 of file ImageUploader.php.
Referenced by setValue().
$m_PicWidth
Definition at line 29 of file ImageUploader.php.
Referenced by setValue().
$m_Preview
Definition at line 34 of file ImageUploader.php.
$m_ThumbFolder
Definition at line 33 of file ImageUploader.php.
$m_ThumbHeight
Definition at line 32 of file ImageUploader.php.
Referenced by setValue().
$m_ThumbWidth
Definition at line 31 of file ImageUploader.php.
Referenced by setValue().