Openbiz Framework API: BizDataObj_SQLHelper Class Reference
BizDataObj_SQLHelper Class Reference
Public Member Functions
buildDeleteSQL ($dataObj)
buildDeleteSQLwithCondition ($dataObj, $condition=null)
buildInsertSQL ($dataObj, $joinValues=null)
buildQuerySQL ($dataObj)
buildUpdateSQL ($dataObj)
buildUpdateSQLwithCondition ($dataObj, $setValue, $condition=null)
ruleToSql ($dataObj, $rule)
Static Public Member Functions
static instance ()
Protected Member Functions
getDataSqlObj ()
getNewDataSqlObj ($dataObj=null)
Detailed Description
Definition at line 25 of file BizDataObj_SQLHelper.php.
Member Function Documentation
buildDeleteSQL ($dataObj)
Build delete-sql DELETE FROM table WHERE idcol1='id1' AND idcol2='id2'
Parameters
BizDataObj $dataObj
Returns
string SQL statement
Definition at line 301 of file BizDataObj_SQLHelper.php.
References DATAPERM_SERVICE.
    {
        $sql = "DELETE FROM `" . $dataObj->m_MainTable ."`";
        $whereStr = $dataObj->m_BizRecord->getKeySearchRule(false, true);  // use cur value and column name
        $sql .= " WHERE " . $whereStr;
     // append DataPerm in the WHERE clause
        if($dataObj->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $hasOwnerField = $this->_hasOwnerField($dataObj);
         $dataPermSQLRule = $svcObj->buildSqlRule($dataObj,'delete',$hasOwnerField);
         $sqlSearchRule = $this->_convertSqlExpressionWithoutPrefix($dataObj, $dataPermSQLRule);
         if($whereStr!='')
         {
          $sql .= ' AND '.$sqlSearchRule;
         }else
         {
          $sql .= $sqlSearchRule;
         }
        }
        return $sql;
    }
buildDeleteSQLwithCondition ($dataObj, $condition = null)
Definition at line 324 of file BizDataObj_SQLHelper.php.
References DATAPERM_SERVICE.
    {
        $sql = "DELETE FROM `" . $dataObj->m_MainTable . "`";
        if($condition)
        {
         $whereStr = $this->_convertSqlExpressionWithoutPrefix($dataObj, $condition);
         $sql .= " WHERE " . $whereStr;
        }
     // append DataPerm in the WHERE clause
        if($dataObj->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $hasOwnerField = $this->_hasOwnerField($dataObj);
         $dataPermSQLRule = $svcObj->buildSqlRule($dataObj,'delete',$hasOwnerField);
         $sqlSearchRule = $this->_convertSqlExpressionWithoutPrefix($dataObj, $dataPermSQLRule);
         if($whereStr!='')
         {
          $sql .= ' AND '.$sqlSearchRule;
         }else
         {
          $sql .= $sqlSearchRule;
         }
        }
        return $sql;
    }
buildInsertSQL ($dataObj, $joinValues = null)
Build insert-sql INSERT INTO table_name (column1, column2,...) VALUES (value1, value2,....)
Parameters
BizDataObj $dataObj
array $joinValues array of join values
Returns
string Insert-SQL statement
Definition at line 359 of file BizDataObj_SQLHelper.php.
References BizSystem\configuration(), and QueryStringParam\formatQueryValue().
    {
        // generate column value pairs.
        $sqlFlds = $dataObj->m_BizRecord->getToSaveFields('CREATE');
        $dbInfo = BizSystem::configuration()->getDatabaseInfo($dataObj->m_Database);
        $dbType = $dbInfo["Driver"];
        $sql_col = "";
        $sql_val = "";
        foreach($sqlFlds as $fldobj)
        {
            $col = $fldobj->m_Column;
            // if Field Id has null value and Id is an identity type, remove the Id's column from the array
            if ($fldobj->m_Name == "Id" && $dataObj->m_IdGeneration == "Identity")
                continue;
            if ($fldobj->isLobField())  // special value for blob/clob type
                $_val = $fldobj->getInsertLobValue($dbType);
            else
            {
             $_val = $fldobj->getSqlValue();
                if ($_val =='' && $fldobj->m_ValueOnCreate != "")
                    $_val = $fldobj->getValueOnCreate();
            }
            //if (!$_val || $_val == '') continue;
            // modified by jixian for not ignore 0 value
            if ( $_val === '') continue;
            $sql_col .= "`" . $col . "`, ";
            //$sql_val .= $_val. ", ";
            $sql_val .= QueryStringParam::formatQueryValue($_val). ", ";
        }
        // if joinValues is given then add join values in to the main table InsertSQL.
        if(is_array($joinValues))
        {
            foreach($joinValues as $joinColumn=>$joinValue)
            {
                if (!$joinValue || $joinValue == '') continue;
                $sql_col .= "`".$joinColumn. "`, ";
                $sql_val .= "'".$joinValue. "', ";
            }
        }
        $sql_col = substr($sql_col, 0, -2);
        $sql_val = substr($sql_val, 0, -2);
        $sql = "INSERT INTO  `" . $dataObj->m_MainTable . "` (" . $sql_col . ") VALUES (" . $sql_val.")";
        return $sql;
    }
buildQuerySQL ($dataObj)
Build the Select SQL statement based on the fields and search/sort rule
Parameters
BizDataObj $dataObj
Returns
void
Definition at line 93 of file BizDataObj_SQLHelper.php.
References DATAPERM_SERVICE, getNewDataSqlObj(), and BizSystem\getObject().
    {
        //echo "buildQuerySQL ".$dataObj->m_Name."\n";
  // TODO: the same dataobj re-uses the same datasqlobj ...
        // build the SQL statement based on the fields and search rule
        $dataSqlObj = $this->getNewDataSqlObj($dataObj);
  if ($dataSqlObj->isfresh()) {
   // add table
   $dataSqlObj->addMainTable($dataObj->m_MainTable);
   // add join table
   if ($dataObj->m_TableJoins)
   {
    foreach($dataObj->m_TableJoins as $tableJoin)
    {
     $tbl_col = $dataSqlObj->addJoinTable($tableJoin, $this);
    }
   }
   // add columns
   foreach($dataObj->m_BizRecord as $bizFld)
   {
    if ($bizFld->m_IgnoreInQuery) // field to be ignore in query - save memory
     continue;
    if ($bizFld->m_Column && $bizFld->m_Type == "Blob")   // ignore blob column
     continue;
    if ($bizFld->m_Column && !$bizFld->m_SqlExpression && (strpos($bizFld->m_Column,',') == 0))
     $dataSqlObj->addTableColumn($bizFld->m_Join, $bizFld->m_Column, $bizFld->m_Alias);
    if ($bizFld->m_SqlExpression)
    {
     $dataSqlObj->addSqlExpression($this->_convertSqlExpression($dataObj, $bizFld->m_SqlExpression),$bizFld->m_Alias);
    }
   }
  }
        $dataSqlObj->resetSQL();
        // append DataPerm in the WHERE clause
        if($dataObj->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $hasOwnerField = $this->_hasOwnerField($dataObj);
         $dataPermSQLRule = $svcObj->buildSqlRule($dataObj,'select',$hasOwnerField);
         $sqlSearchRule = $this->_ruleToSql($dataObj, $dataPermSQLRule);
         $dataSqlObj->addSqlWhere($sqlSearchRule);
        }
        // append SearchRule in the WHERE clause
        $sqlSearchRule = $this->_ruleToSql($dataObj, $dataObj->m_SearchRule);
        $dataSqlObj->addSqlWhere($sqlSearchRule);
        // append SearchRule in the ORDER BY clause
        $sqlSortRule = $this->_ruleToSql($dataObj, $dataObj->m_SortRule);
        $dataSqlObj->addOrderBy($sqlSortRule);
        // append SearchRule in the other SQL clause
        $sqlOtherSQLRule = $this->_ruleToSql($dataObj, $dataObj->m_OtherSQLRule);
        $dataSqlObj->addOtherSQL($sqlOtherSQLRule);
        // append SearchRule in the AccessRule clause
        $sqlAccessSQLRule = $this->_ruleToSql($dataObj, $dataObj->m_AccessRule);
        $dataSqlObj->addSqlWhere($sqlAccessSQLRule);
        // add association to SQL
        if ($dataObj->m_Association["AsscObjName"] != ""
                && $dataObj->m_Association["FieldRefVal"] == "")
        {
            $asscObj = BizSystem::getObject($dataObj->m_Association["AsscObjName"]);
            $dataObj->m_Association["FieldRefVal"] = $asscObj->getFieldValue($dataObj->m_Association["FieldRef"]);
        }
     if ($dataObj->m_Association["AsscObjName"] != ""
                && $dataObj->m_Association["FieldRefVal2"] == "")
        {
            $asscObj = BizSystem::getObject($dataObj->m_Association["AsscObjName"]);
            $dataObj->m_Association["FieldRefVal2"] = $asscObj->getFieldValue($dataObj->m_Association["FieldRef2"]);
        }
        if($dataObj->m_Association["Relationship"]=="Self-Self")
        {
         $dataObj->m_Association["ParentRecordIdColumn"] = $dataObj->getField("Id")->m_Column;
        }
        $dataSqlObj->addAssociation($dataObj->m_Association);
        // apply _ruleToSql to JoinCondition if any
  if ($dataSqlObj->hasJoinCondition) {
   $dataSqlObj->setTableJoinStm($this->_ruleToSql($dataObj, $dataSqlObj->getTableJoinStm()));
  }
  $querySQL = $dataSqlObj->getSqlStatement() . " ";
        //echo $querySQL."###\n";
        return $querySQL;
    }
buildUpdateSQL ($dataObj)
Build update sql UPDATE table SET col1=val1, col2=val2 ... WHERE idcol1='id1' AND idcol2='id2'
Parameters
BizDataObj $dataObj
Returns
mixed
Definition at line 195 of file BizDataObj_SQLHelper.php.
References DATAPERM_SERVICE, and QueryStringParam\formatQueryString().
    {
        // generate column value pairs. ignore those whose inputValue=fieldValue
        $sqlFlds = $dataObj->m_BizRecord->getToSaveFields('UPDATE');
        $colval_pairs = null;
        foreach($sqlFlds as $fldobj)
        {
            $col = $fldobj->m_Column;
            // ignore empty vallue for Date or Datetime
            if (($fldobj->m_Value == "" && $fldobj->m_OldValue == "")
                    && ($fldobj->m_Type == "Date" || $fldobj->m_Type == "Datetime"))
                continue;
            if ($fldobj->m_ValueOnUpdate != "") // ignore ValueOnUpdate field first
                continue;
            if ($fldobj->isLobField())  // take care of blob/clob type later
                continue;
            // ignore the column where old value is same as new value; set the column only if new value is diff than the old value
            if ($fldobj->m_OldValue == $fldobj->m_Value)
                continue;
            $_val = $fldobj->getSqlValue();
            $colval_pairs[$col] = $_val; //($_val===null || $_val === '') ? "''" : $_val;
        }
        if ($colval_pairs == null) return false;
        // take care value on update fields only
        foreach($sqlFlds as $fldobj)
        {
            $col = $fldobj->m_Column;
            if ($fldobj->m_ValueOnUpdate != "")
            {
                $_val = $fldobj->getValueOnUpdate();
                $colval_pairs[$col] = $_val; //($_val===null || $_val === '') ? "''" : $_val;
            }
        }
        $sql = "";
        foreach ($colval_pairs as $col=>$val)
        {
            $queryString = QueryStringParam::formatQueryString("`$col`", "=", $val);
            if ($sql!="") $sql .= ", $queryString";
            else $sql .= $queryString;
        }
        $sql = "UPDATE `" . $dataObj->m_MainTable . "` SET " . $sql;
        $whereStr = $dataObj->m_BizRecord->getKeySearchRule(true, true);  // use old value and column name
        $sql .= " WHERE " . $whereStr;
        // append DataPerm in the WHERE clause
        if($dataObj->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $hasOwnerField = $this->_hasOwnerField($dataObj);
         $dataPermSQLRule = $svcObj->buildSqlRule($dataObj,'update',$hasOwnerField);
         $sqlSearchRule = $this->_convertSqlExpressionWithoutPrefix($dataObj, $dataPermSQLRule);
         if($whereStr!='')
         {
          $sql .= ' AND '.$sqlSearchRule;
         }else
         {
          $sql .= $sqlSearchRule;
         }
        }
        return $sql;
    }
buildUpdateSQLwithCondition ($dataObj, $setValue, $condition = null)
Definition at line 266 of file BizDataObj_SQLHelper.php.
References DATAPERM_SERVICE.
    {
        $setValueStr = $this->_convertSqlExpressionWithoutPrefix($dataObj, $setValue);
        $sql = "UPDATE `" . $dataObj->m_MainTable ."` SET ".$setValueStr;
     if($condition)
        {
         $whereStr = $this->_convertSqlExpressionWithoutPrefix($dataObj, $condition);
         $sql .= " WHERE " . $whereStr;
        }
     // append DataPerm in the WHERE clause
        if($dataObj->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $hasOwnerField = $this->_hasOwnerField($dataObj);
         $dataPermSQLRule = $svcObj->buildSqlRule($dataObj,'update',$hasOwnerField);
         $sqlSearchRule = $this->_convertSqlExpressionWithoutPrefix($dataObj, $dataPermSQLRule);
         if($whereStr!='')
         {
          $sql .= ' AND '.$sqlSearchRule;
         }else
         {
          $sql .= $sqlSearchRule;
         }
        }
        return $sql;
    }
getDataSqlObj () protected
Get curent BizDataSql object, if object=null, create new object
Returns
BizDataSql
Definition at line 59 of file BizDataObj_SQLHelper.php.
    {
        if (!$this->_dataSqlObj)
            $this->_dataSqlObj = new BizDataSql();
        return $this->_dataSqlObj;
    }
getNewDataSqlObj ($dataObj = null) protected
Get new BizDataSql object and store on internal variable (current object)
Returns
BizDataSql
Definition at line 71 of file BizDataObj_SQLHelper.php.
Referenced by buildQuerySQL().
    {
  if ($dataObj) {
   $doName = $dataObj->m_Name;
   if (!isset($this->_dataSqlObjList[$doName])) {
    $this->_dataSqlObjList[$doName] = new BizDataSql();
   }
   $this->_dataSqlObj = $this->_dataSqlObjList[$doName];
  }
  else {
   $this->_dataSqlObj = null;
   $this->_dataSqlObj = new BizDataSql();
  }
        return $this->_dataSqlObj;
    }
static instance () static
Get the singleton instance
Returns
BizDataObj_SQLHelper BizDataObj_SQLHelper object
Definition at line 47 of file BizDataObj_SQLHelper.php.
Referenced by BizDataObj_Lite\getSQLHelper().
    {
        if (self::$_instance == null)
            self::$_instance = new BizDataObj_SQLHelper();
        return self::$_instance;
    }
ruleToSql ($dataObj, $rule)
Definition at line 412 of file BizDataObj_SQLHelper.php.
 {
  return _ruleToSql($dataObj, $rule);
 }