Openbiz Framework API: EasyForm Class Reference
EasyForm Class Reference
Public Member Functions
__construct (&$xmlArr)
allowAccess ($access=null)
autoSuggest ($input)
callService ($class, $method, $param=null)
cancel ()
canDeleteRecord ($rec)
canDisplayForm ()
close ()
copyRecord ($id=null)
deleteRecord ($id=null)
editRecord ($id=null)
fetchData ()
fetchDataSet ()
getActiveRecord ($recId=null)
getDataObj ()
getElement ($elementName)
getElementID ()
getElementSet ($panel=null)
getErrorElements ($fields)
getMessage ($messageId, $params=array())
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
getSubForms ()
getTabSet ($panel=null)
getViewObject ()
gotoPage ($page=1)
gotoSelectedPage ($elemName)
insertRecord ()
invoke ()
loadDialog ($formName, $id=null, $transId=false)
loadPicker ($formName, $elementName="")
newRecord ()
outputAttrs ()
parentSwitchForm ($formName=null, $id=null, $params=null, $target=null)
processBDOException ($e)
processDataObjError ($errCode=0)
processFormObjError ($errors)
removeRecord ()
render ()
renderParent ()
rerender ($redrawForm=true, $hasRecordChange=true)
resetSearch ()
runSearch ()
saveRecord ()
selectRecord ($recId)
setCurrentPage ($pageid)
setDataObj ($dataObj)
setFixSearchRule ($rule=null, $cleanActualRule=true)
setFormInputs ($inputArr=null)
setPageSize ($elemName)
setParentForm ($parentFormName)
setRecordId ($val)
setRequestParams ($paramFields)
setSearchRule ($searchRule, $searchRuleBindValues=null)
setSessionVars ($sessionContext)
setSubForms ($subForms)
sortRecord ($sortCol, $order='ASC')
switchForm ($formName=null, $id=null, $params=null, $target=null)
targetSwitchForm ($targetForm, $formName=null, $id=null, $params=null, $target=null)
updateFieldValue ($Id, $fld_name, $value)
updateFieldValueAdd ($id, $fld_name, $value, $min, $max)
updateFieldValueXor ($id, $fld_name, $value)
updateForm ()
updateRecord ()
validateRequest ($methodName)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$DATAFORMAT
$m_ActionPanel
$m_ActiveRecord
$m_AutoRefresh
$m_CacheLifeTime
$m_CanUpdateRecord
$m_DataObjName
$m_DataPanel
$m_DefaultForm
$m_DefaultFormName
$m_Description
$m_DirectMethodList
$m_Errors
$m_EventName
$m_FixSearchRule
$m_FormInputs
$m_FormParams
$m_FormType
$m_Height
$m_Icon
$m_InheritFrom
$m_jsClass
$m_MessageFile
$m_NavPanel
$m_Notices
$m_Panels
$m_ParentFormName
$m_QueryStringParam
$m_Range
$m_ReferenceFormName
$m_SearchPanel
$m_SearchRule
$m_SortRule
$m_SubForms
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_TotalPages
$m_Width
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
_doInsert ($inputRecord)
_doUpdate ($inputRecord, $currentRecord)
_showForm ($formName, $target, $paramFields)
commitFormElements ()
getEventLogMsg ()
getInvokingElement ()
getNewRecord ()
getOnEventElements ()
getRedirectPage ()
getTransKey ($name)
getTransPrefix ()
inheritParentObj ()
processPostAction ()
readInputRecord ()
readInputs ()
readMetadata (&$xmlArr)
renderContextMenu ()
renderHTML ()
rerenderSubForms ()
runEventLog ()
setActiveRecord ($record)
setClientScripts ()
translate ()
validateForm ($cleanError=true)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_CurrentPage
$m_DataObj
$m_DefaultFixSearchRule
$m_hasError
$m_InvokingElement
$m_Messages
$m_RecordAllowAccess
$m_RecordId
$m_RecordSet
$m_Referer
$m_RefreshData
$m_Resource
$m_SearchRuleBindValues
$m_StartItem
$m_TotalRecords
$m_ValidateErrors
Detailed Description
Definition at line 29 of file EasyForm.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize BizForm with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 137 of file EasyForm.php.
References inheritParentObj(), and readMetadata().
    {
        $this->readMetadata($xmlArr);
        //echo $_GET['referer'];
        $this->inheritParentObj();
    }
Member Function Documentation
_doInsert ($inputRecord) protected
Do insert record
Parameters
array $inputRecord
Returns
void
Definition at line 1607 of file EasyForm.php.
References BizSystem\clientProxy(), getActiveRecord(), getDataObj(), getErrorElements(), processBDOException(), processFormObjError(), and runEventLog().
Referenced by insertRecord().
    {
        $dataRec = new DataRecord(null, $this->getDataObj());
        // $inputRecord['Id'] = null; // comment it out for name PK case
        foreach ($inputRecord as $k => $v)
            $dataRec[$k] = $v; // or $dataRec->$k = $v;
        try
        {
           $dataRec->save();
        }
        catch (ValidationException $e)
        {
            $errElements = $this->getErrorElements($e->m_Errors);
            if(count($e->m_Errors)==count($errElements)){
             $this->processFormObjError($errElements);
            }else{
             $errmsg = implode("<br />",$e->m_Errors);
          BizSystem::clientProxy()->showErrorMessage($errmsg);
            }
            return;
        }
        catch (BDOException $e)
        {
            $this->processBDOException($e);
            return;
        }
  $this->m_ActiveRecord = null;
        $this->getActiveRecord($dataRec["Id"]);
        $this->runEventLog();
        return $dataRec["Id"];
    }
_doUpdate ($inputRecord, $currentRecord) protected
Do update record
Parameters
array $inputRecord
array $currentRecord
Returns
void
Definition at line 1519 of file EasyForm.php.
References BizSystem\clientProxy(), getActiveRecord(), getDataObj(), getErrorElements(), processBDOException(), processFormObjError(), and runEventLog().
Referenced by updateFieldValue(), and updateRecord().
    {
        $dataRec = new DataRecord($currentRecord, $this->getDataObj());
        foreach ($inputRecord as $k => $v){
            $dataRec[$k] = $v; // or $dataRec->$k = $v;
        }
        try
        {
            $dataRec->save();
        }
        catch (ValidationException $e)
        {
            $errElements = $this->getErrorElements($e->m_Errors);
         if(count($e->m_Errors)==count($errElements)){
             $this->processFormObjError($errElements);
            }else{
             $errmsg = implode("<br />",$e->m_Errors);
          BizSystem::clientProxy()->showErrorMessage($errmsg);
            }
            return false;
        }
        catch (BDOException $e)
        {
            $this->processBDOException($e);
            return false;
        }
  $this->m_ActiveRecord = null;
        $this->getActiveRecord($dataRec["Id"]);
        $this->runEventLog();
        return true;
    }
_showForm ($formName, $target, $paramFields) protected
Show form
Parameters
string $formName
string $target target type: Popup or other
array $paramFields
Returns
void
Definition at line 1215 of file EasyForm.php.
References $m_DefaultFormName, MetaObject\$m_Name, $m_ReferenceFormName, BizSystem\clientProxy(), getMessage(), BizSystem\log(), BizSystem\objectFactory(), and processFormObjError().
Referenced by loadDialog(), processPostAction(), and switchForm().
    {
     $formName_org = $formName;
        if (!$this->m_DefaultFormName)
      $this->m_DefaultFormName = $this->m_Name;
     if ($formName == null)
     {
      if($this->m_ReferenceFormName == null)
      {
       $formName = $this->m_DefaultFormName;
      }else{
       if($formName = $this->m_ReferenceFormName){
        //this judgement is for anti endless loop between swtich forms
        $formObj = BizSystem::objectFactory()->getObject($this->m_ReferenceFormName);
        if($formObj->m_ReferenceFormName == $this->m_Name){
         $formName = $this->m_DefaultFormName;
        }else{
         $formName = $this->m_ReferenceFormName;
        }
       }
      }
     }
     //if($this->getViewObject()->isInFormRefLibs($formName))
        {
            // get the form object
            /* @var $formObj EasyForm */
            $formObj = BizSystem::objectFactory()->getObject($formName);
            $formObj->m_DefaultFormName = $this->m_DefaultFormName;
            if($formName_org){
             //RefenerenceForm records where the from switch from
        if( $this->m_FormType!='EDIT' &&
         $this->m_FormType!='NEW' &&
         $this->m_FormType!='COPY' ){
               $formObj->m_ReferenceFormName = $this->m_Name;
       }
            }
            //if has more than Id field as params then $clearFixSearchRule is false, means join all where rules
            $paramTemp = $paramFields;
            unset($paramTemp['Id']);
            if(count($paramTemp)){
             $clearFixSearchRule = false;
            }else{
             $clearFixSearchRule = true;
            }
            foreach($paramFields as $fieldName=>$val){
             $formObj->m_FormParams[$fieldName] = $val;
                $formObj->setFixSearchRule("[$fieldName]='$val'",$clearFixSearchRule);
                if($fieldName=="Id"){
                 $formObj->setRecordId($val);
                }
            }
            if(!$formObj->canDisplayForm())
            {
             $formObj->m_ErrorMessage = $this->getMessage("FORM_OPERATION_NOT_PERMITTED",$formObj->m_Name);
          if (strtoupper($this->m_FormType) == "LIST"){
           BizSystem::log(LOG_ERR, "DATAOBJ", "DataObj error = ".$errorMsg);
           BizSystem::clientProxy()->showClientAlert($formObj->m_ErrorMessage);
          }else{
           $this->processFormObjError(array($formObj->m_ErrorMessage));
          }
             return false;
            }
            switch ($target)
            {
                case "Popup":
                    $formObj->setParentForm($this->m_Name);
                    echo $formObj->render();
                    break;
                case "Dialog":
                    $formObj->setParentForm($this->m_Name);
                    BizSystem::clientProxy()->redrawForm("DIALOG", $formObj->render());
                    break;
                default:
                    BizSystem::clientProxy()->redrawForm($this->m_Name, $formObj->render());
            }
        }
    }
allowAccess ($access = null)
if the record is now allowed to access, then deny form render instead of display an empty form
Definition at line 144 of file EasyForm.php.
Referenced by render().
    {
     if(!$this->m_RecordAllowAccess)
     {
      return false;
     }
     $result = parent::allowAccess($access);
     return $result ;
    }
autoSuggest ($input)
Generate list for AutoSuggest element Also supports elements that have hidden values
Parameters
string $input - the search string used to filter the list
Returns
void
Definition at line 1676 of file EasyForm.php.
References BizSystem\clientProxy(), and getElement().
    {
  if (defined('JSLIB_BASE') && JSLIB_BASE == 'JQUERY') {
   $value = $_GET["term"];
   // get the select from list of the element
   $element = $this->getElement($input);
   $element->setValue($value);
   $fromlist = array();
   $element->getFromList($fromlist);
   $arr = array();
   $i = 0;
   foreach ($fromlist as $item) {
    $arr[$i++] = array('label'=>$item['txt'], 'value'=>$item['val']);
   }
   echo json_encode($arr);
   return;
  }
  $foo = $_POST;
     $hidden_flag = FALSE;
        if (strpos($input, '_hidden'))
        {
            $realInput = str_replace('_hidden', '', $input);
   $hidden_flag = TRUE;
        } else
        {
            $realInput = $input;
        }
        $value = BizSystem::clientProxy()->getFormInputs($input);
        // get the select from list of the element
        $element = $this->getElement($realInput);
        $element->setValue($value);
        $fromlist = array();
        $element->getFromList($fromlist);
        echo "<ul>";
        if ($fromlist)
        {
            if ($hidden_flag = TRUE)
            {
             $count=0;
                foreach ($fromlist as $item)
                {
                    echo "<li id=" . $item['txt'] . ">" . $item['val'] . "</li>";
                    $count++;
                    if($count>=5) break;
                }
            }
            else
            {
             $count=0;
                foreach ($fromlist as $item)
                {
                    echo "<li>" . $item['txt'] . "</li>";
                    $count++;
                    if($count>=5) break;
                }
            }
        }
        echo "</ul>";
    }
callService ($class, $method, $param = null)
Call/Invoke service method, this EasyForm name is passed to the method
Parameters
string $class
string $method
string $param
Returns
mixed - return value of the service method
Definition at line 788 of file EasyForm.php.
References BizSystem\getService().
    {
        $service = BizSystem::getService($class);
        if($param){
         return $service->$method($param);
        }else{
         return $service->$method($this->m_Name);
        }
    }
cancel ()
Cancel input and do page redirection
Returns
void
Definition at line 1648 of file EasyForm.php.
References processPostAction().
    {
        $this->processPostAction();
    }
canDeleteRecord ($rec)
Definition at line 327 of file EasyForm.php.
References DATAPERM_SERVICE, and getDataObj().
Referenced by deleteRecord().
    {
     if($this->getDataObj()->m_DataPermControl=='Y')
        {
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $result = $svcObj->checkDataPerm($rec,3,$this->getDataObj());
         if($result == false)
         {
          return false;
         }
        }
        return true;
    }
canDisplayForm ()
Definition at line 298 of file EasyForm.php.
References DATAPERM_SERVICE, fetchData(), and getDataObj().
    {
     if($this->getDataObj()->m_DataPermControl=='Y')
        {
         switch(strtolower($this->m_FormType))
         {
          default:
          case 'list':
           return true;
           break;
          case 'detail':
           $permCode=1;
           break;
          case 'edit':
           $permCode=2;
           break;
         }
         $svcObj = BizSystem::GetService(DATAPERM_SERVICE);
         $result = $svcObj->checkDataPerm($this->fetchData(),$permCode,$this->getDataObj());
         if($result == false)
         {
          return false;
         }
        }
        return true;
    }
close ()
Close the popup window
Returns
void
Definition at line 838 of file EasyForm.php.
References BizSystem\clientProxy().
Referenced by PickerForm\addToParent(), insertRecord(), PickerForm\insertToParent(), PickerForm\joinToParent(), and updateRecord().
    {
        BizSystem::clientProxy()->closePopup();
    }
commitFormElements () protected
Definition at line 1554 of file EasyForm.php.
Referenced by insertRecord(), and updateRecord().
 {
  foreach ($this->m_DataPanel as $element)
  {
   if (is_a($element, "FormElement")) {
    $element->setValue('');
   }
  }
 }
copyRecord ($id = null)
Copy record to new record *
Parameters
mixed $id id of record that want to copy, it parameter not passed, id is '_selectedId'
Returns
void
Definition at line 1169 of file EasyForm.php.
References BizSystem\clientProxy(), getActiveRecord(), getMessage(), and processPostAction().
    {
        if ($id==null || $id=='')
            $id = BizSystem::clientProxy()->getFormInputs('_selectedId');
        if (!$id)
        {
            BizSystem::clientProxy()->showClientAlert($this->getMessage("PLEASE_EDIT_A_RECORD"));
            return;
        }
        $this->getActiveRecord($id);
        $this->processPostAction();
    }
deleteRecord ($id = null)
Delete Record NOTE: use redirectpage attr of eventhandler to redirect or redirect to previous page by default
Parameters
string $id
Returns
void
Definition at line 1306 of file EasyForm.php.
References canDeleteRecord(), BizSystem\clientProxy(), getDataObj(), getMessage(), BizSystem\log(), processBDOException(), processFormObjError(), processPostAction(), rerender(), and runEventLog().
    {
        if ($id==null || $id=='')
            $id = BizSystem::clientProxy()->getFormInputs('_selectedId');
        $selIds = BizSystem::clientProxy()->getFormInputs('row_selections', false);
        if ($selIds == null)
            $selIds[] = $id;
        foreach ($selIds as $id)
        {
            $dataRec = $this->getDataObj()->fetchById($id);
            $this->getDataObj()->setActiveRecord($dataRec);
            if(!$this->canDeleteRecord($dataRec))
            {
             $this->m_ErrorMessage = $this->getMessage("FORM_OPERATION_NOT_PERMITTED",$this->m_Name);
          if (strtoupper($this->m_FormType) == "LIST"){
           BizSystem::log(LOG_ERR, "DATAOBJ", "DataObj error = ".$errorMsg);
           BizSystem::clientProxy()->showClientAlert($this->m_ErrorMessage);
          }else{
           $this->processFormObjError(array($this->m_ErrorMessage));
          }
          return;
            }
            // take care of exception
            try
            {
                $dataRec->delete();
            } catch (BDOException $e)
            {
                // call $this->processBDOException($e);
                $this->processBDOException($e);
                return;
            }
        }
        if (strtoupper($this->m_FormType) == "LIST")
            $this->rerender();
        $this->runEventLog();
        $this->processPostAction();
    }
editRecord ($id = null)
Edit Record NOTE: append fld:Id=$id to the redirect page url
Parameters
mixed $id
Returns
void
Definition at line 1190 of file EasyForm.php.
References BizSystem\clientProxy(), getActiveRecord(), getMessage(), and processPostAction().
    {
        if ($id==null || $id=='')
            $id = BizSystem::clientProxy()->getFormInputs('_selectedId');
        if (!isset($id))
        {
            BizSystem::clientProxy()->showClientAlert($this->getMessage("PLEASE_EDIT_A_RECORD"));
            return;
        }
        // update the active record with new update record
        $this->getActiveRecord($id);
        $this->processPostAction();
    }
fetchData ()
Fetch single record
Returns
array one record array
Definition at line 964 of file EasyForm.php.
References $m_ActiveRecord, $m_FixSearchRule, getDataObj(), getNewRecord(), setActiveRecord(), and QueryStringParam\setBindValues().
Referenced by canDisplayForm(), and updateRecord().
    {
        // if has valid active record, return it, otherwise do a query
        if ($this->m_ActiveRecord != null)
            return $this->m_ActiveRecord;
        $dataObj = $this->getDataObj();
        if ($dataObj == null) return;
        if (strtoupper($this->m_FormType) == "NEW")
            return $this->getNewRecord();
        if (!$this->m_FixSearchRule && !$this->m_SearchRule){
         //if its a default sub form,even no search rule, but can still fetch a default record
         if(!is_array($this->getDataObj()->m_Association)){
          //only if its a default sub form and without any association then return emply array
          return array();
         }
        }else{
      QueryStringParam::setBindValues($this->m_SearchRuleBindValues);
         if ($this->m_RefreshData)   $dataObj->resetRules();
         else $dataObj->clearSearchRule();
         if ($this->m_FixSearchRule)
         {
             if ($this->m_SearchRule)
                 $searchRule = $this->m_SearchRule . " AND " . $this->m_FixSearchRule;
             else
                 $searchRule = $this->m_FixSearchRule;
         }
         $dataObj->setSearchRule($searchRule);
         QueryStringParam::setBindValues($this->m_SearchRuleBindValues);
         $dataObj->setLimit(1);
        }
        $resultRecords = $dataObj->fetch();
  if(!count($resultRecords))
  {
   $this->m_RecordAllowAccess=false;
  }
        $this->m_RecordId = $resultRecords[0]['Id'];
        $this->setActiveRecord($resultRecords[0]);
        QueryStringParam::ReSet();
     if($this->getDataObj()){
   $this->m_CanUpdateRecord = (int)$this->getDataObj()->canUpdateRecord();
     }
        return $resultRecords[0];
    }
fetchDataSet ()
Fetch record set
Returns
array array of record
Definition at line 885 of file EasyForm.php.
References $m_FixSearchRule, $m_SearchRule, $m_TotalPages, getDataObj(), and QueryStringParam\setBindValues().
    {
        $dataObj = $this->getDataObj();
        if (!$dataObj) return null;
        QueryStringParam::setBindValues($this->m_SearchRuleBindValues);
        if ($this->m_RefreshData)
            $dataObj->resetRules();
        else
            $dataObj->clearSearchRule();
        if ($this->m_FixSearchRule)
        {
            if ($this->m_SearchRule)
                $searchRule = $this->m_SearchRule . " AND " . $this->m_FixSearchRule;
            else
                $searchRule = $this->m_FixSearchRule;
        }
        else
            $searchRule = $this->m_SearchRule;
        $dataObj->setSearchRule($searchRule);
        if($this->m_StartItem>1)
        {
            $dataObj->setLimit($this->m_Range, $this->m_StartItem);
        }
        else
        {
            $dataObj->setLimit($this->m_Range, ($this->m_CurrentPage-1)*$this->m_Range);
        }
        if($this->m_SortRule && $this->m_SortRule != $this->getDataObj()->m_SortRule)
        {
          $dataObj->setSortRule($this->m_SortRule);
        }
        $resultRecords = $dataObj->fetch();
        $this->m_TotalRecords = $dataObj->count();
        if ($this->m_Range && $this->m_Range > 0)
            $this->m_TotalPages = ceil($this->m_TotalRecords/$this->m_Range);
        $selectedIndex = 0;
        //if current page is large than total pages ,then reset current page to last page
        if($this->m_CurrentPage>$this->m_TotalPages && $this->m_TotalPages>0)
        {
         $this->m_CurrentPage = $this->m_TotalPages;
         $dataObj->setLimit($this->m_Range, ($this->m_CurrentPage-1)*$this->m_Range);
         $resultRecords = $dataObj->fetch();
        }
        $this->getDataObj()->setActiveRecord($resultRecords[$selectedIndex]);
        QueryStringParam::ReSet();
  if(!$this->m_RecordId)
  {
   $this->m_RecordId = $resultRecords[0]["Id"];
  }else{
   $foundRecordId = false;
   foreach($resultRecords as $record)
   {
    if($this->m_RecordId==$record['Id'])
    {
     $foundRecordId = true;
    }
   }
   if($foundRecordId == false)
   {
    $this->m_RecordId=$result[0]['Id'];
   }
  }
        return $resultRecords;
    }
getActiveRecord ($recId = null)
Get activeRecord
Parameters
mixed $recId
Returns
array - record array
Definition at line 2292 of file EasyForm.php.
References $m_ActiveRecord, BizSystem\clientProxy(), and getDataObj().
Referenced by _doInsert(), _doUpdate(), copyRecord(), editRecord(), and updateFieldValue().
    {
        if ($this->m_ActiveRecord != null)
        {
            if($this->m_ActiveRecord['Id'] != null)
            {
                return $this->m_ActiveRecord;
            }
        }
        if ($recId==null || $recId=='')
            $recId = BizSystem::clientProxy()->getFormInputs('_selectedId');
        if ($recId==null || $recId=='')
            return null;
        $this->m_RecordId = $recId;
        // TODO: may consider cache the current record in session
        if($this->getDataObj()){
         $this->getDataObj()->setActiveRecordId($this->m_RecordId);
         $rec = $this->getDataObj()->getActiveRecord();
         // update the record row
         $this->m_DataPanel->setRecordArr($rec);
         $this->m_ActiveRecord = $rec;
        }
        return $rec;
    }
getDataObj ()
Get object instance of BizDataObj defined in it's metadata file
Returns
BizDataObj
Definition at line 480 of file EasyForm.php.
References $m_DataObj, MetaObject\$m_Name, and BizSystem\objectFactory().
Referenced by _doInsert(), _doUpdate(), PickerForm\addToParent(), canDeleteRecord(), canDisplayForm(), EasyFormWizard\commit(), deleteRecord(), fetchData(), EasyFormGrouping\fetchDataGroup(), EasyFormTree\fetchDataSet(), fetchDataSet(), getActiveRecord(), getNewRecord(), PickerForm\insertToParent(), PickerForm\joinToParent(), processDataObjError(), removeRecord(), render(), rerenderSubForms(), selectRecord(), setActiveRecord(), setRequestParams(), and sortRecord().
    {
        if (!$this->m_DataObj)
        {
            if ($this->m_DataObjName)
                $this->m_DataObj = BizSystem::objectFactory()->getObject($this->m_DataObjName);
            if($this->m_DataObj)
                $this->m_DataObj->m_BizFormName = $this->m_Name;
            else
            {
                //BizSystem::clientProxy()->showErrorMessage("Cannot get DataObj of ".$this->m_DataObjName.", please check your metadata file.");
                return null;
            }
        }
        return $this->m_DataObj;
    }
getElement ($elementName)
Get an element object
Parameters
string $elementName - name of the control
Returns
Element
Definition at line 640 of file EasyForm.php.
Referenced by autoSuggest(), getInvokingElement(), getProperty(), invoke(), PickerForm\joinToParent(), loadPicker(), and sortRecord().
    {
        if ($this->m_DataPanel->get($elementName)) return $this->m_DataPanel->get($elementName);
        if ($this->m_ActionPanel->get($elementName)) return $this->m_ActionPanel->get($elementName);
        if ($this->m_NavPanel->get($elementName)) return $this->m_NavPanel->get($elementName);
        if ($this->m_SearchPanel->get($elementName)) return $this->m_SearchPanel->get($elementName);
        if($this->m_WizardPanel)
        {
         if ($this->m_WizardPanel->get($elementName)) return $this->m_WizardPanel->get($elementName);
        }
    }
getElementID ()
Get element Id
Returns
mixed
Definition at line 1403 of file EasyForm.php.
References $m_RecordId.
    {
        $id = $this->m_DataPanel->getByField('Id')->getValue();
        if($id)
        {
            return (int)$id;
        }
        else
        {
            return (int)$this->m_RecordId;
        }
    }
getElementSet ($panel = null)
Definition at line 652 of file EasyForm.php.
References $m_DataPanel.
Referenced by outputAttrs().
    {
     if(!$panel){
      $panel = $this->m_DataPanel;
     }
     $setArr = array();
     $panel->rewind();
        while($panel->valid())
        {
         $elem = $panel->current();
         $panel->next();
         if($elem->m_ElementSet && $elem->canDisplayed()){
          //is it in array
          if(in_array($elem->m_ElementSet,$setArr)){
           continue;
          }else{
           array_push($setArr,$elem->m_ElementSet);
          }
         }
        }
        return $setArr;
    }
getErrorElements ($fields)
Get error elements
Parameters
array $fields
Returns
array
Definition at line 726 of file EasyForm.php.
Referenced by _doInsert(), and _doUpdate().
    {
        $errElements = array();
        foreach ($fields as $field=>$error)
        {
            $element = $this->m_DataPanel->getByField($field);
            $errElements[$element->m_Name]=$error;
        }
        return $errElements;
    }
getEventLogMsg () protected
Get event log message
Returns
mixed string or null
Definition at line 2116 of file EasyForm.php.
References getInvokingElement().
Referenced by runEventLog().
    {
        list($element, $eventHandler) = $this->getInvokingElement();
        $eventLogMsg = $eventHandler->m_EventLogMsg;
        if($eventLogMsg)
        {
            return $eventLogMsg;
        }
        else
        {
            return null;
        }
    }
getInvokingElement () protected
Get the element that issues the call.
Returns
array element object and event handler name
Definition at line 2230 of file EasyForm.php.
References $m_InvokingElement, BizSystem\clientProxy(), and getElement().
Referenced by getEventLogMsg(), getRedirectPage(), and validateRequest().
    {
     if ($this->m_InvokingElement)
         return $this->m_InvokingElement;
     // __this is elementName:eventHandlerName
        $elementAndEventName = BizSystem::clientProxy()->getFormInputs("__this");
        if (! $elementAndEventName)
         return array(null,null);
        list ($elementName, $eventHandlerName) = explode(":", $elementAndEventName);
        $element = $this->getElement($elementName);
        $eventHandler = $element->m_EventHandlers->get($eventHandlerName);
        $this->m_InvokingElement = array($element, $eventHandler);
        return $this->m_InvokingElement;
    }
getMessage ($messageId, $params = array())
Get message, and translate it
Parameters
string $messageId message Id
array $params
Returns
string message string
Definition at line 286 of file EasyForm.php.
References MetaObject\getModuleName(), and I18n\t().
Referenced by _showForm(), copyRecord(), deleteRecord(), editRecord(), and validateForm().
    {
        $message = isset($this->m_Messages[$messageId]) ? $this->m_Messages[$messageId] : constant($messageId);
        //$message = I18n::getInstance()->translate($message);
        $message = I18n::t($message, $messageId, $this->getModuleName($this->m_Name));
        $msg = @vsprintf($message,$params);
        if(!$msg){ //maybe in translation missing some %s can cause it returns null
         $msg = $message;
        }
        return $msg;
    }
getNewRecord () protected
Get new record
Returns
array
Definition at line 1886 of file EasyForm.php.
References getDataObj().
Referenced by fetchData().
    {
     if($this->getDataObj())
     {
         $recArr = $this->getDataObj()->newRecord();
     }
        if (! $recArr)
            return null;
        // load default values if new record value is empty
        $defaultRecArr = array();
        foreach ($this->m_DataPanel as $element)
        {
            if ($element->m_FieldName)
            {
                $defaultRecArr[$element->m_FieldName] = $element->getDefaultValue();
            }
        }
        foreach ($recArr as $field => $val)
        {
            if ($val == "" && $defaultRecArr[$field] != "")
            {
                $recArr[$field] = $defaultRecArr[$field];
            }
        }
        return $recArr;
    }
getOnEventElements () protected
Get on event elements
Returns
array element list
Definition at line 2135 of file EasyForm.php.
Referenced by runEventLog().
    {
        $elementList = array();
        foreach ($this->m_DataPanel as $element)
        {
            if ($element->m_OnEventLog=="Y")
                $elementList[] = $element->m_Value;
        }
        return $elementList;
    }
getProperty ($propertyName)
Get object property This method get element object if propertyName is "Elements[elementName]" format.
Parameters
string $propertyName
Returns
<type>
Definition at line 449 of file EasyForm.php.
References getElement().
    {
        $ret = parent::getProperty($propertyName);
        if ($ret !== null) return $ret;
        $pos1 = strpos($propertyName, "[");
        $pos2 = strpos($propertyName, "]");
        if ($pos1>0 && $pos2>$pos1)
        {
            $propType = substr($propertyName, 0, $pos1);
            $elementName = substr($propertyName, $pos1+1,$pos2-$pos1-1);
            switch(strtolower($propType))
            {
    case 'param':
             case 'params':
              $result = $this->m_FormParams[$elementName];
              break;
             default:
              $result = $this->getElement($elementName);
              break;
            }
            return $result;
        }
    }
getRecordId ()
Definition at line 2321 of file EasyForm.php.
References $m_RecordId.
{
     return $this->m_RecordId;
    }
getRedirectPage () protected
return redirect page and target array
Returns
array {redirectPage, $target}
Definition at line 2168 of file EasyForm.php.
References getInvokingElement().
Referenced by processPostAction().
    {
        // get the control that issues the call
        // __this is elementName:eventHandlerName
        list($element, $eventHandler) = $this->getInvokingElement();
        $eventHandlerName = $eventHandler->m_Name;
        $redirectPage = $element->getRedirectPage($eventHandlerName); // need to get postaction of eventhandler
        $functionType = $element->getFunctionType($eventHandlerName);
        switch ($functionType)
        {
            case "Popup":
            case "Prop_Window":
            case "Prop_Dialog":
                $target = "Popup";
                break;
            default:
                $target = "";
        }
        return array($redirectPage, $target);
    }
getSessionVars ($sessionContext)
Get/Retrieve Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 349 of file EasyForm.php.
    {
        $sessionContext->getObjVar($this->m_Name, "RecordId", $this->m_RecordId);
        $sessionContext->getObjVar($this->m_Name, "FixSearchRule", $this->m_FixSearchRule);
        $sessionContext->getObjVar($this->m_Name, "SearchRule", $this->m_SearchRule);
        $sessionContext->getObjVar($this->m_Name, "SearchRuleBindValues", $this->m_SearchRuleBindValues);
        $sessionContext->getObjVar($this->m_Name, "SubForms", $this->m_SubForms);
        $sessionContext->getObjVar($this->m_Name, "ParentFormName", $this->m_ParentFormName);
        $sessionContext->getObjVar($this->m_Name, "DefaultFormName", $this->m_DefaultFormName);
        $sessionContext->getObjVar($this->m_Name, "CurrentPage", $this->m_CurrentPage);
        $sessionContext->getObjVar($this->m_Name, "PageSize", $this->m_Range);
        $sessionContext->getObjVar($this->m_Name, "ReferenceFormName", $this->m_ReferenceFormName);
        $sessionContext->getObjVar($this->m_Name, "SearchPanelValues", $this->m_SearchPanelValues);
    }
getSubForms ()
Get sub form of this form
Returns
EasyForm
Definition at line 628 of file EasyForm.php.
References $m_SubForms.
    {
        // ask view to give its subforms if not set yet
        return $this->m_SubForms;
    }
getTabSet ($panel = null)
Definition at line 675 of file EasyForm.php.
References $m_DataPanel.
Referenced by outputAttrs().
    {
     if(!$panel){
      $panel = $this->m_DataPanel;
     }
     $setArr = array();
     $tabSetArr = array();
     $panel->rewind();
        while($panel->valid())
        {
         $elem = $panel->current();
         $panel->next();
         if($elem->m_TabSet && $elem->canDisplayed()){
          //is it in array
          if(in_array($elem->m_TabSet,$setArr)){
           continue;
          }else{
            $setArr[$elem->m_TabSetCode]=$elem->m_TabSet;
          }
         }
        }
        foreach($setArr as $tabsetCode=>$tabset)
        {
         $elemSetArr = array();
         $panel->rewind();
         while($panel->valid())
         {
          $elem = $panel->current();
          $panel->next();
          if($elem->m_ElementSet && $elem->canDisplayed()){
           //is it in array
           if( $elem->m_TabSetCode!= $tabsetCode ||
            in_array($elem->m_ElementSet,$elemSetArr)){
            continue;
           }else{
            array_push($elemSetArr,$elem->m_ElementSet);
           }
          }
         }
         $tabSetArr[$tabsetCode]['SetName'] = $tabset;
         $tabSetArr[$tabsetCode]['Elems'] = $elemSetArr;
        }
        return $tabSetArr;
    }
getTransKey ($name) protected
Definition at line 2408 of file EasyForm.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_Name,intval(strrpos($this->m_Name,'.'))+1);
     return strtoupper($shortFormName.'_'.$name);
    }
getTransPrefix () protected
Definition at line 2398 of file EasyForm.php.
Referenced by translate().
    {
     $nameArr = explode(".",$this->m_Name);
     for($i=1;$i<count($nameArr)-1;$i++)
     {
      $prefix .= strtoupper($nameArr[$i])."_";
     }
     return $prefix;
    }
getViewObject ()
Get view object
BizSystem $g_BizSystem
Returns
EasyView
Definition at line 614 of file EasyForm.php.
References $g_BizSystem, and BizSystem\getObject().
Referenced by EasyFormWizard\doCancel(), EasyFormWizard\doFinish(), EasyFormWizard\goBack(), EasyFormWizard\goNext(), EasyFormWizard\outputAttrs(), EasyFormWizard\render(), renderHTML(), and EasyFormWizard\skip().
    {
        global $g_BizSystem;
        $viewName = $g_BizSystem->getCurrentViewName();
        if (!$viewName) return null;
        $viewObj = BizSystem::getObject($viewName);
        return $viewObj;
    }
gotoPage ($page = 1)
Goto page specified by $page parameter, and ReRender If page not specified, goto page 1
Parameters
number $page
Definition at line 1023 of file EasyForm.php.
References rerender().
Referenced by gotoSelectedPage().
    {
        $tgtPage = intval($page);
        if ($tgtPage == 0) $tgtPage = 1;
        $this->m_CurrentPage = $tgtPage;
        $this->rerender();
    }
gotoSelectedPage ($elemName)
Definition at line 1030 of file EasyForm.php.
References BizSystem\clientProxy(), and gotoPage().
    {
        $page = BizSystem::clientProxy()->getFormInputs(str_replace(".","_", $this->m_Name).'_'.$elemName);
     $this->gotoPage($page);
    }
inheritParentObj () protected
Inherit from parent object. Name, Package, Class cannot be inherited
Returns
void
Definition at line 228 of file EasyForm.php.
References BizSystem\getObject(), and Resource\loadMessage().
Referenced by __construct().
    {
        if (!$this->m_InheritFrom) return;
        $parentObj = BizSystem::getObject($this->m_InheritFrom);
        $this->m_Title = $this->m_Title ? $this->m_Title : $parentObj->m_Title;
        $this->m_Icon = $this->m_Icon ? $this->m_Icon : $parentObj->m_Icon;
        $this->m_Description  = $this->m_Description ? $this->m_Description : $parentObj->m_Description;
        $this->m_jsClass   = $this->m_jsClass ? $this->m_jsClass : $parentObj->m_jsClass;
        $this->m_Height   = $this->m_Height ? $this->m_Height : $parentObj->m_Height;
        $this->m_Width   = $this->m_Width ? $this->m_Width : $parentObj->m_Width;
        $this->m_DefaultForm   = $this->m_DefaultForm ? $this->m_DefaultForm : $parentObj->m_DefaultForm;
        $this->m_TemplateEngine   = $this->m_TemplateEngine ? $this->m_TemplateEngine : $parentObj->m_TemplateEngine;
        $this->m_TemplateFile   = $this->m_TemplateFile ? $this->m_TemplateFile : $parentObj->m_TemplateFile;
        $this->m_FormType   = $this->m_FormType ? $this->m_FormType : $parentObj->m_FormType;
        $this->m_Range   = $this->m_Range ? $this->m_Range : $parentObj->m_Range;
        $this->m_FixSearchRule   = $this->m_FixSearchRule ? $this->m_FixSearchRule : $parentObj->m_FixSearchRule;
        $this->m_DefaultFixSearchRule   = $this->m_DefaultFixSearchRule ? $this->m_DefaultFixSearchRule : $parentObj->m_DefaultFixSearchRule;
        $this->m_DataObjName   = $this->m_DataObjName ? $this->m_DataObjName : $parentObj->m_DataObjName;
        $this->m_DirectMethodList   = $this->m_DirectMethodList ? $this->m_DirectMethodList : $parentObj->m_DirectMethodList;
        $this->m_EventName   = $this->m_EventName ? $this->m_EventName : $parentObj->m_EventName;
        $this->m_MessageFile   = $this->m_MessageFile ? $this->m_MessageFile : $parentObj->m_MessageFile;
        $this->m_Messages = Resource::loadMessage($this->m_MessageFile , $this->m_Package);
  $this->m_CacheLifeTime   = $this->m_CacheLifeTime ? $this->m_CacheLifeTime : $parentObj->m_CacheLifeTime;
  $this->m_CurrentPage   = $this->m_CurrentPage ? $this->m_CurrentPage : $parentObj->m_CurrentPage;
  $this->m_StartItem   = $this->m_StartItem ? $this->m_StartItem : $parentObj->m_StartItem;
        $this->m_DataPanel->merge($parentObj->m_DataPanel);
        $this->m_ActionPanel->merge($parentObj->m_ActionPanel);
        $this->m_NavPanel->merge($parentObj->m_NavPanel);
        $this->m_SearchPanel->merge($parentObj->m_SearchPanel);
        if($this->m_DataPanel->current()){
         foreach ($this->m_DataPanel as $elem)
             $elem->adjustFormName($this->m_Name);
        }
        if($this->m_ActionPanel->current()){
         foreach ($this->m_ActionPanel as $elem)
             $elem->adjustFormName($this->m_Name);
        }
        if($this->m_NavPanel->current()){
         foreach ($this->m_NavPanel as $elem)
             $elem->adjustFormName($this->m_Name);
        }
        if($this->m_SearchPanel->current()){
         foreach ($this->m_SearchPanel as $elem)
             $elem->adjustFormName($this->m_Name);
        }
  $this->m_Panels = array($this->m_DataPanel, $this->m_ActionPanel, $this->m_NavPanel, $this->m_SearchPanel);
    }
insertRecord ()
Insert new record
Returns
mixed
Definition at line 1569 of file EasyForm.php.
References _doInsert(), close(), commitFormElements(), processFormObjError(), processPostAction(), readInputRecord(), renderParent(), and setActiveRecord().
Referenced by saveRecord().
    {
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
        if (count($recArr) == 0)
            return;
        try
        {
            $this->ValidateForm();
        }
        catch (ValidationException $e)
        {
            $this->processFormObjError($e->m_Errors);
            return;
        }
        $this->_doInsert($recArr);
        $this->commitFormElements(); // commit change in FormElement
        // in case of popup form, close it, then rerender the parent form
        if ($this->m_ParentFormName)
        {
            $this->close();
            $this->renderParent();
        }
        $this->processPostAction();
    }
invoke ()
Invoke the action passed from browser
Returns
mixed the function result, or false on error.
Definition at line 390 of file EasyForm.php.
References getElement().
    {
        $argList = func_get_args();
        $param1 = array_shift($argList);
        // first one is element:eventhandler
        list ($elementName, $eventHandlerName) = explode(":", $param1);
        $element = $this->getElement($elementName);
        $eventHandler = $element->m_EventHandlers->get($eventHandlerName);
        $this->m_InvokingElement = array($element, $eventHandler);
        // find the matching function
        list($funcName, $funcParams) = $eventHandler->parseFunction($eventHandler->m_OrigFunction);
        // call the function with rest parameters
        return call_user_func_array(array($this, $funcName), $argList);
    }
loadDialog ($formName, $id = null, $transId = false)
Definition at line 765 of file EasyForm.php.
References $m_RecordId, and _showForm().
    {
     $paramFields = array();
        if ($id!=null)
            $paramFields["Id"] = $id;
        if ($transId!=false)
            $paramFields["Id"] = $this->m_RecordId;
        $this->_showForm($formName, "Dialog", $paramFields);
    }
loadPicker ($formName, $elementName = "")
Popup a selection EasyForm in a dynamically generated EasyView
Parameters
string $viewName
string $formName
string $elementName
Returns
void remote
Definition at line 746 of file EasyForm.php.
References BizSystem\clientProxy(), getElement(), BizSystem\objectFactory(), and readInputRecord().
    {
        // set the ParentFormName and ParentCtrlName of the popup form
        /* @var $pickerForm EasyForm */
        $pickerForm = BizSystem::objectFactory()->getObject($formName);
        if ($elementName != "")
        {
            // set the picker map as well
            $element = $this->getElement($elementName);
            $pickerMap = $element->m_PickerMap;
        }
  $currentRecord = $this->readInputRecord();
  $pickerForm->setParentForm($this->m_Name);
        $pickerForm->setParentFormData($this->m_Name, $elementName, $pickerMap);
        $pickerForm->m_ParentFormRecord = $currentRecord;
        BizSystem::clientProxy()->redrawForm("DIALOG", $pickerForm->render());
    }
newRecord ()
New record, be default, just redirect to the new record page
Returns
void
Definition at line 1157 of file EasyForm.php.
References processPostAction().
    {
        $this->processPostAction();
    }
outputAttrs ()
Get output attributs as array
Returns
array array of attributs
Definition at line 514 of file EasyForm.php.
References $m_CurrentPage, $m_Icon, MetaObject\$m_Name, $m_RecordId, $m_TotalPages, $m_TotalRecords, Expression\evaluateExpression(), Resource\getCurrentTheme(), getElementSet(), getTabSet(), and THEME_URL.
    {
        $output['name'] = $this->m_Name;
        $output['title'] = Expression::evaluateExpression($this->m_Title, $this);
        $output['icon'] = $this->m_Icon;
        $output['hasSubform'] = $this->m_SubForms ? 1 : 0;
        $output['currentPage'] = $this->m_CurrentPage;
        $output['currentRecordId'] = $this->m_RecordId;
        $output['totalPages'] = $this->m_TotalPages;
        $output['totalRecords'] = $this->m_TotalRecords;
        $output['description'] = str_replace('\n', "<br />", Expression::evaluateExpression($this->m_Description,$this));
        $output['elementSets'] = $this->getElementSet();
        $output['tabSets'] = $this->getTabSet();
        $output['ActionElementSets'] = $this->getElementSet($this->m_ActionPanel);
        if($output['icon'])
        {
         if(preg_match("/{.*}/si",$output['icon']))
         {
          $output['icon'] = Expression::evaluateExpression($output['icon'], null);
         }
         else
         {
          $output['icon'] = THEME_URL . "/" . Resource::getCurrentTheme() . "/images/".$output['icon'];
         }
        }
        return $output;
    }
parentSwitchForm ($formName = null, $id = null, $params = null, $target = null)
Definition at line 2208 of file EasyForm.php.
References BizSystem\getObject().
    {
     if($this->m_ParentFormName){
      $formObj = BizSystem::getObject($this->m_ParentFormName);
      return $formObj->switchForm($formName, $id, $params, $target);
     }
    }
processBDOException ($e)
Handle the exception from DataObj method, report the error as an alert window
Parameters
int $errCode
Returns
string
Definition at line 576 of file EasyForm.php.
References BizSystem\log().
Referenced by _doInsert(), _doUpdate(), EasyFormWizard\commit(), and deleteRecord().
    {
        $errorMsg = $e->getMessage();
        BizSystem::log(LOG_ERR, "DATAOBJ", "DataObj error = ".$errorMsg);
        //BizSystem::clientProxy()->showClientAlert($errorMsg);   //showErrorMessage($errorMsg);
        //BizSystem::clientProxy()->showErrorMessage($errorMsg);
        $e->no_exit=true;
     OB_ErrorHandler::ExceptionHandler($e);
    }
processDataObjError ($errCode = 0)
Handle the error from BizDataObj::getErrorMessage method, report the error as an alert window and log.
Parameters
int $errCode
Returns
void
Definition at line 549 of file EasyForm.php.
References BizSystem\clientProxy(), getDataObj(), and BizSystem\log().
Referenced by removeRecord().
    {
        $errorMsg = $this->getDataObj()->getErrorMessage();
        BizSystem::log(LOG_ERR, "DATAOBJ", "DataObj error = ".$errorMsg);
        BizSystem::clientProxy()->showErrorMessage($errorMsg);
    }
processFormObjError ($errors)
Process error of form object
Parameters
array $errors
Returns
string - HTML text of this form's read mode
Definition at line 562 of file EasyForm.php.
References rerender().
Referenced by _doInsert(), _doUpdate(), _showForm(), deleteRecord(), EasyFormWizard\doFinish(), EasyFormWizard\goNext(), insertRecord(), PickerForm\insertToParent(), and updateRecord().
    {
        $this->m_Errors = $errors;
        $this->m_hasError = true;
        return $this->rerender();
    }
processPostAction () protected
Process Post Action
Returns
void
Definition at line 2250 of file EasyForm.php.
References _showForm(), BizSystem\clientProxy(), and getRedirectPage().
Referenced by cancel(), copyRecord(), deleteRecord(), EasyFormWizard\doCancel(), EasyFormWizard\doFinish(), editRecord(), insertRecord(), newRecord(), and updateRecord().
    {
        // get the $redirectPage from eventHandler
        list($redirectPage,$target) = $this->getRedirectPage();
        if ($redirectPage)
        {
            if($this->m_hasError==false)
            {
                // if the redirectpage start with "form=", render the form to the target which is defined by FuntionType
                if (strpos($redirectPage,"form=") === 0)
                {
                    parse_str($redirectPage, $output);
                    $formName = $output['form'];
                    // parse query string. e.g. fld:Id=val&fld:name=val
                    $paramFields = array();
                    foreach ($output as $key=>$value)
                    {
                        if (substr($key, 0, 4) == "fld:")
{
                            $fieldName = substr($key, 4);
                            $paramFields[$fieldName] = $value;
                        }
                    }
                    $this->_showForm($formName, $target, $paramFields);
                }
                else
                {
                    // otherwise, do page redirection
                    BizSystem::clientProxy()->ReDirectPage($redirectPage);
                }
            }
        }
    }
readInputRecord () protected
Read user input data from UI
Returns
array - record array
Definition at line 1797 of file EasyForm.php.
References BizSystem\clientProxy().
Referenced by EasyFormWizard\doFinish(), EasyFormWizard\goBack(), EasyFormWizard\goNext(), insertRecord(), PickerForm\insertToParent(), loadPicker(), runSearch(), updateForm(), and updateRecord().
    {
        $recArr = array();
        foreach ($this->m_DataPanel as $element)
        {
            $value = BizSystem::clientProxy()->getFormInputs($element->m_Name);
            if ($value ===null && (
                !is_a($element,"FileUploader")
             && !is_subclass_of($element,"FileUploader")
             && !is_a($element,"Checkbox")
             && !is_a($element,"FormElement")
             )){
             continue;
            }
            $element->setValue($value);
            $this->m_FormInputs[$element->m_Name] = $value;
            $value = $element->getValue();
            if ( $element->m_FieldName)
                $recArr[$element->m_FieldName] = $value;
        }
        foreach ($this->m_SearchPanel as $element)
        {
            $value = BizSystem::clientProxy()->getFormInputs($element->m_Name);
            $element->setValue($value);
            $this->m_FormInputs[$element->m_Name] = $value;
            $value = $element->getValue();
            if ($value !== null && $element->m_FieldName)
                $recArr[$element->m_FieldName] = $value;
        }
        return $recArr;
    }
readInputs () protected
Read inputs
Returns
array array of input
Definition at line 1835 of file EasyForm.php.
References BizSystem\clientProxy().
    {
        $inputArr = array();
        foreach ($this->m_DataPanel as $element)
        {
            $value = BizSystem::clientProxy()->getFormInputs($element->m_Name);
            $element->setValue($value);
            $inputArr[$element->m_Name] = $value;
        }
        foreach ($this->m_SearchPanel as $element)
        {
            $value = BizSystem::clientProxy()->getFormInputs($element->m_Name);
            $element->setValue($value);
            $inputArr[$element->m_Name] = $value;
        }
        return $inputArr;
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 164 of file EasyForm.php.
References $m_Range, Resource\loadMessage(), MetaObject\prefixPackage(), and translate().
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_InheritFrom = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["INHERITFROM"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["INHERITFROM"] : null;
        $this->m_Title = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["TITLE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["TITLE"] : null;
        $this->m_Icon = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["ICON"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["ICON"] : null;
        $this->m_Description = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["DESCRIPTION"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["DESCRIPTION"] : null;
        $this->m_jsClass = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["JSCLASS"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["JSCLASS"] : null;
        $this->m_Height = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["HEIGHT"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["HEIGHT"] : null;
        $this->m_Width = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["WIDTH"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["WIDTH"] : null;
        $this->m_DefaultForm = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["DEFAULTFORM"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["DEFAULTFORM"] : null;
        $this->m_TemplateEngine = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["TEMPLATEENGINE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["TEMPLATEENGINE"] : null;
        $this->m_TemplateFile = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["TEMPLATEFILE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["TEMPLATEFILE"] : null;
        $this->m_FormType = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["FORMTYPE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["FORMTYPE"] : null;
        $this->m_Range = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["PAGESIZE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["PAGESIZE"] : $this->m_Range;
        $this->m_FixSearchRule = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["SEARCHRULE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["SEARCHRULE"] : null;
        $this->m_SortRule = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["SORTRULE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["SORTRULE"] : null;
  $this->m_DefaultFixSearchRule = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["SEARCHRULE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["SEARCHRULE"] : null;
        $this->m_Name = $this->prefixPackage($this->m_Name);
        if ($this->m_InheritFrom == '@sourceMeta') $this->m_InheritFrom = '@'.$this->m_Name;
        else $this->m_InheritFrom = $this->prefixPackage($this->m_InheritFrom);
        $this->m_DataObjName = $this->prefixPackage($xmlArr["EASYFORM"]["ATTRIBUTES"]["BIZDATAOBJ"]);
        if (isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["DIRECTMETHOD"]))
            $this->m_DirectMethodList = explode(",", strtolower(str_replace(" ", "",$xmlArr["EASYFORM"]["ATTRIBUTES"]["DIRECTMETHOD"])));
        $this->m_DataPanel = new Panel($xmlArr["EASYFORM"]["DATAPANEL"]["ELEMENT"],"",$this);
        $this->m_ActionPanel = new Panel($xmlArr["EASYFORM"]["ACTIONPANEL"]["ELEMENT"],"",$this);
        $this->m_NavPanel = new Panel($xmlArr["EASYFORM"]["NAVPANEL"]["ELEMENT"],"",$this);
        $this->m_SearchPanel = new Panel($xmlArr["EASYFORM"]["SEARCHPANEL"]["ELEMENT"],"",$this);
        $this->m_Panels = array($this->m_DataPanel, $this->m_ActionPanel, $this->m_NavPanel, $this->m_SearchPanel);
        $this->m_FormType = strtoupper($this->m_FormType);
        $this->m_EventName = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["EVENTNAME"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["EVENTNAME"] : null;
        $this->m_MessageFile = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["MESSAGEFILE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["MESSAGEFILE"] : null;
        $this->m_Messages = Resource::loadMessage($this->m_MessageFile , $this->m_Package);
        $this->m_CacheLifeTime = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["CACHELIFETIME"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["CACHELIFETIME"] : "0";
        $this->m_CurrentPage = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["STARTPAGE"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["STARTPAGE"] : 1;
        $this->m_StartItem = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["STARTITEM"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["STARTITEM"] : 1;
        $this->m_AutoRefresh = isset($xmlArr["EASYFORM"]["ATTRIBUTES"]["AUTOREFRESH"]) ? $xmlArr["EASYFORM"]["ATTRIBUTES"]["AUTOREFRESH"] : 0;
        // parse access
        if ($this->m_Access)
        {
            $arr = explode (".", $this->m_Access);
            $this->m_Resource = $arr[0];
        }
        if ($this->m_jsClass == "jbForm" && strtoupper($this->m_FormType) == "LIST") $this->m_jsClass = "Openbiz.TableForm";
        if ($this->m_jsClass == "jbForm") $this->m_jsClass = "Openbiz.Form";
  $this->translate(); // translate for multi-language support
    }
removeRecord ()
Remove the record out of the associate relationship
Returns
void
Definition at line 1354 of file EasyForm.php.
References BizSystem\clientProxy(), getDataObj(), processDataObjError(), renderParent(), rerender(), and runEventLog().
    {
     if ($id==null || $id=='')
            $id = BizSystem::clientProxy()->getFormInputs('_selectedId');
        $selIds = BizSystem::clientProxy()->getFormInputs('row_selections', false);
        if ($selIds == null)
            $selIds[] = $id;
        foreach ($selIds as $id)
        {
         $rec = $this->getDataObj()->fetchById($id);
         $ok = $this->getDataObj()->removeRecord($rec, $bPrtObjUpdated);
         if (! $ok)
             return $this->processDataObjError($ok);
        }
        $this->runEventLog();
        $this->rerender();
  if($this->m_ParentFormName)
  {
   $this->renderParent();
  }
     }
render ()
Definition at line 1921 of file EasyForm.php.
References allowAccess(), getDataObj(), BizSystem\getService(), BizSystem\log(), BizSystem\objectFactory(), renderHTML(), and setClientScripts().
    {
        if (!$this->allowAccess())
            return "";
        $this->setClientScripts();
        if($this->m_CacheLifeTime>0 && $this->m_SubForms == null)
        {
            $cache_id = md5($this->m_Name);
            //try to process cache service.
            $cacheSvc = BizSystem::getService(CACHE_SERVICE,1);
            $cacheSvc->init($this->m_Name,$this->m_CacheLifeTime);
            if($cacheSvc->test($cache_id))
            {
                BizSystem::log(LOG_DEBUG, "FORM", "Cache Hit. form name = ".$this->m_Name);
                $output = $cacheSvc->load($cache_id);
            }
            else
            {
                BizSystem::log(LOG_DEBUG, "FORM", "Set cache. form name = ".$this->m_Name);
                $output = $this->renderHTML();
                $cacheSvc->save($output, $cache_id);
            }
            return $output;
        }
        //Moved the renderHTML function infront of declaring subforms
        $renderedHTML = $this->renderHTML();
        // prepare the subforms' dataobjs, since the subform relates to parent form by dataobj association
        if ($this->m_SubForms && $this->getDataObj())
        {
            foreach ($this->m_SubForms as $subForm)
            {
                $formObj = BizSystem::objectFactory()->getObject($subForm);
                $dataObj = $this->getDataObj()->getRefObject($formObj->m_DataObjName);
                if ($dataObj)
                    $formObj->setDataObj($dataObj);
            }
        }
  if (!$this->allowAccess())
  {
           return "";
  }
        return $renderedHTML;
    }
renderContextMenu () protected
Render context menu code
Returns
string html code for context menu
Definition at line 1973 of file EasyForm.php.
    {
        $menuList = array();
        foreach ($this->m_Panels as $panel)
        {
            $panel->rewind();
            while ($element = $panel->current())
            {
                $panel->next();
                if (method_exists($element,'getContextMenu') && $menus = $element->getContextMenu())
                {
                    foreach ($menus as $m)
                        $menuList[] = $m;
                }
            }
        }
        if (count($menuList) == 0)
            return "";
        $str = "<div  class='contextMenu' id='" . $this->m_Name . "_contextmenu'>\n";
        $str .= "<div class=\"contextMenu_header\" ></div>\n";
        $str .= "<ul>\n";
        foreach ($menuList as $m)
        {
            $func = $m['func'];
            $shortcutKey = isset($m['key']) ? " (".$m['key'].")" : "";
            $str .= "<li><a href=\"javascript:void(0)\" onclick=\"$func\">".$m['text'].$shortcutKey."</a></li>\n";
        }
        $str .= "</ul>\n";
        $str .= "<div class=\"contextMenu_footer\" ></div>\n";
        $str .= "</div>\n";
  if (defined('JSLIB_BASE') && JSLIB_BASE == 'JQUERY') {
   $str .= "
<script>
$(jq('".$this->m_Name."')).removeAttr('onContextMenu');
$(jq('".$this->m_Name."'))[0].oncontextmenu=function(event){return Openbiz.Menu.show(event, '".$this->m_Name."_contextmenu');};
$(jq('".$this->m_Name."')).bind('click',Openbiz.Menu.hide);
</script>";
  }
  else {
   $str .= "
<script>
$('".$this->m_Name."').removeAttribute('onContextMenu');
$('".$this->m_Name."').oncontextmenu=function(event){return Openbiz.Menu.show(event, '".$this->m_Name."_contextmenu');};
$('".$this->m_Name."').observe('click',Openbiz.Menu.hide);
</script>";
  }
        return $str;
    }
renderHTML () protected
Render html content of this form
Returns
string - HTML text of this form's read mode
Definition at line 2071 of file EasyForm.php.
References $formHTML, MetaObject\$m_Name, getViewObject(), and FormRenderer\render().
Referenced by render(), and rerender().
    {
        $formHTML = FormRenderer::render($this);
        $otherHTML = $this->rendercontextmenu();
        if(preg_match('/iPad/si',$_SERVER['HTTP_USER_AGENT']) ||
         preg_match('/iPhone/si',$_SERVER['HTTP_USER_AGENT'])){
          $otherHTML.="
          <script>
    var a=document.getElementsByTagName('a');
    for(var i=0;i<a.length;i++)
    {
     if(a[i].getAttribute('href').indexOf('javascript:')==-1
     && a[i].getAttribute('href').indexOf('#')==-1)
      {
          a[i].onclick=function()
          {
           try{
            show_loader();
           }catch(e){
           }
              window.location=this.getAttribute('href');
              return false
          }
      }else{
      }
    }
    </script>
          ";
         }
        if(!$this->m_ParentFormName)
        {
         if (($viewObj = $this->getViewObject())!=null)
                $viewObj->m_LastRenderedForm = $this->m_Name;
        }
        return $formHTML ."\n". $otherHTML;
    }
renderParent ()
Render parent form
Returns
void
Definition at line 848 of file EasyForm.php.
References BizSystem\objectFactory().
Referenced by insertRecord(), removeRecord(), and updateRecord().
    {
        /* @var $parentForm EasyForm */
        $parentForm = BizSystem::objectFactory()->getObject($this->m_ParentFormName);
        $parentForm->rerender();
    }
rerender ($redrawForm = true, $hasRecordChange = true)
Rerender this form (form is rendered already) .
Parameters
boolean $redrawForm - whether render this form again or not, optional default true
boolean $hasRecordChange - if record change, need to render subforms, optional default true
Returns
string - HTML text of this form's read mode
Definition at line 2029 of file EasyForm.php.
References BizSystem\clientProxy(), renderHTML(), and rerenderSubForms().
Referenced by deleteRecord(), gotoPage(), processFormObjError(), removeRecord(), resetSearch(), runSearch(), selectRecord(), sortRecord(), and updateForm().
    {
        if ($redrawForm)
        {
            BizSystem::clientProxy()->redrawForm($this->m_Name, $this->renderHTML());
        }
        if ($hasRecordChange)
        {
            $this->rerenderSubForms();
        }
    }
rerenderSubForms () protected
Rerender sub forms who has dependecy on this form. This method is called when parent form's change affect the sub forms
Returns
void
Definition at line 2048 of file EasyForm.php.
References getDataObj(), and BizSystem\objectFactory().
Referenced by rerender().
    {
        if (! $this->m_SubForms)
            return;
        foreach ($this->m_SubForms as $subForm)
        {
            $formObj = BizSystem::objectFactory()->getObject($subForm);
            if($this->getDataObj() && $formObj->m_DataObjName)
            {
             $dataObj = $this->getDataObj()->getRefObject($formObj->m_DataObjName);
             if ($dataObj)
                 $formObj->setDataObj($dataObj);
            }
            $formObj->rerender();
        }
        return;
    }
resetSearch ()
Reset search
Returns
void
Definition at line 1135 of file EasyForm.php.
References rerender(), and runEventLog().
    {
        $this->m_SearchRule = "";
        $this->m_RefreshData = true;
        $this->m_CurrentPage = 1;
        $this->runEventLog();
        $this->rerender();
    }
runEventLog () protected
Run event log
Returns
void
Definition at line 2151 of file EasyForm.php.
References $m_EventName, EVENTLOG_SERVICE, getEventLogMsg(), getOnEventElements(), and BizSystem\getService().
Referenced by _doInsert(), _doUpdate(), deleteRecord(), removeRecord(), resetSearch(), and runSearch().
    {
        $logMessage = $this->getEventLogMsg();
        $eventName = $this->m_EventName;
        if($logMessage && $eventName)
        {
            $logElements = $this->getOnEventElements();
            $eventlog  = BizSystem::getService(EVENTLOG_SERVICE);
            $eventlog->log($eventName, $logMessage, $logElements);
        }
    }
runSearch ()
Run Search
Returns
void
Definition at line 1076 of file EasyForm.php.
References BizSystem\clientProxy(), QueryStringParam\getBindValues(), inputValToRule(), BizSystem\log(), readInputRecord(), rerender(), and runEventLog().
    {
        static $isSearchHelperLoaded = false;
        if (!$isSearchHelperLoaded) {
            include_once(OPENBIZ_BIN."/easy/SearchHelper.php");
            $isSearchHelperLoaded = true;
        }
        $searchRule = "";
        foreach ($this->m_SearchPanel as $element)
        {
            $searchStr = '';
         if(method_exists($element,"getSearchRule")){
          $searchStr = $element->getSearchRule();
         }else{
             if (!$element->m_FieldName)
                 continue;
             $value = BizSystem::clientProxy()->getFormInputs($element->m_Name);
             if($element->m_FuzzySearch=="Y")
             {
                 $value="*$value*";
             }
             if ($value!='')
             {
                 $searchStr = inputValToRule($element->m_FieldName, $value, $this);
             }
         }
         if($searchStr){
          if ($searchRule == "")
                    $searchRule .= $searchStr;
                else
                    $searchRule .= " AND " . $searchStr;
         }
        }
        $this->m_SearchRule = $searchRule;
        $this->m_SearchRuleBindValues = QueryStringParam::getBindValues();
        $this->m_RefreshData = true;
        $this->m_CurrentPage = 1;
        BizSystem::log(LOG_DEBUG,"FORMOBJ",$this->m_Name."::runSearch(), SearchRule=".$this->m_SearchRule);
  $recArr = $this->readInputRecord();
  $this->m_SearchPanelValues = $recArr;
        $this->runEventLog();
        $this->rerender();
    }
saveRecord ()
Save input and redirect page to a new view use redirectpage attr of eventhandler to redirect or redirect to previous page by default NOTE: For Edit/New form type
Returns
void
Definition at line 1423 of file EasyForm.php.
References insertRecord(), and updateRecord().
    {
        if (strtoupper($this->m_FormType) == "NEW")
        {
            $this->insertRecord();
        }
        else
        {
            $this->updateRecord();
        }
    }
selectRecord ($recId)
Select Record
Parameters
string $recId remote
Returns
void
Definition at line 1386 of file EasyForm.php.
References BizSystem\clientProxy(), getDataObj(), and rerender().
    {
        if ($recId==null || $recId=='')
            $recId = BizSystem::clientProxy()->getFormInputs('_selectedId');
        $this->m_RecordId = $recId;
        if($this->getDataObj()){
         $this->getDataObj()->setActiveRecordId($this->m_RecordId);
        }
        $this->rerender(false); // not redraw the this form, but draw the subforms
        //$this->rerender();
    }
setActiveRecord ($record) protected
Set active record
Parameters
array $record
Returns
void
Definition at line 2335 of file EasyForm.php.
References getDataObj().
Referenced by EasyFormWizard\doFinish(), fetchData(), EasyFormWizard\getSessionVars(), EasyFormWizard\goBack(), EasyFormWizard\goNext(), insertRecord(), PickerForm\insertToParent(), updateForm(), and updateRecord().
    {
        // update the record row
        $this->m_DataPanel->setRecordArr($record);
        if(!isset($this->m_ActiveRecord["Id"]) &&
         $this->m_RecordId!=null &&
         (strtoupper($this->m_FormType) == 'EDIT' || $this->m_FormType==null )){
          if($this->getDataObj()){
           $this->m_ActiveRecord = $this->getDataObj()->fetchById($this->m_RecordId)->toArray();
          }
        }
  if(is_array($record)){
         foreach($record as $key=>$value){
          if($key=='extend')continue;
          $this->m_ActiveRecord[$key] = $record[$key];
         }
  }
    }
setClientScripts () protected
Set client scripts, auto add javascripts code to the page
Returns
void
Definition at line 2360 of file EasyForm.php.
References BizSystem\clientProxy().
Referenced by render().
    {
        // load custom js class
        if ($this->m_jsClass != "Openbiz.Form" && $this->m_jsClass != "Openbiz.TableForm" && $this->m_jsClass != "" )
            BizSystem::clientProxy()->appendScripts($this->m_jsClass, $this->m_jsClass . ".js");
        /*
        if ($this->m_FormType == 'LIST')
        {
            BizSystem::clientProxy()->appendScripts("tablekit", "tablekit.js");
        }*/
    }
setCurrentPage ($pageid)
Definition at line 829 of file EasyForm.php.
    {
     $this->m_CurrentPage = $pageid;
    }
setDataObj ($dataObj) final
Set data object BizDataObj with specified instant from parameter
Parameters
BizDataObj $dataObj
Returns
void
Definition at line 503 of file EasyForm.php.
    {
        $this->m_DataObj = $dataObj;
    }
setFixSearchRule ($rule = null, $cleanActualRule = true)
Set the dependent search rule of the bizform, this search rule will apply on its BizDataObj. The dependent search rule (session var) will always be with bizform until it get set to other value
Parameters
string $rule - search rule has format "[fieldName1] opr1 Value1 AND/OR [fieldName2] opr2 Value2"
boolean $cleanActualRule
Returns
void
Definition at line 863 of file EasyForm.php.
References $m_DefaultFixSearchRule.
Referenced by setRequestParams().
    {
        if ($cleanActualRule)
            $this->m_FixSearchRule = $this->m_DefaultFixSearchRule;
        if ($this->m_FixSearchRule && $rule)
        {
            if (strpos($this->m_FixSearchRule, $rule) === false)
            {
                $this->m_FixSearchRule = $this->m_FixSearchRule . " AND " . $rule;
            }
        }
        if (!$this->m_FixSearchRule && $rule){
            $this->m_FixSearchRule = $rule;
        }
    }
setFormInputs ($inputArr = null)
Definition at line 1855 of file EasyForm.php.
References $m_FormInputs.
Referenced by EasyFormWizard\doFinish().
    {
        if(!$inputArr){
      $inputArr = $this->m_FormInputs;
        }
     if(!is_array($inputArr)){
      $inputArr = array();
        }
        foreach ($this->m_DataPanel as $element)
        {
            if (isset($inputArr[$element->m_Name]))
            {
             $element->setValue($inputArr[$element->m_Name]);
            }
        }
        foreach ($this->m_SearchPanel as $element)
        {
            if (isset($inputArr[$element->m_Name]))
            {
             $element->setValue($inputArr[$element->m_Name]);
            }
        }
        return $inputArr;
    }
setPageSize ($elemName)
Definition at line 1035 of file EasyForm.php.
References BizSystem\clientProxy().
    {
        $pagesize = BizSystem::clientProxy()->getFormInputs(str_replace(".","_", $this->m_Name).'_'.$elemName);
     $this->m_Range=$pagesize;
     $this->UpdateForm();
    }
setParentForm ($parentFormName)
Definition at line 775 of file EasyForm.php.
 {
  $this->m_ParentFormName = $parentFormName;
 }
setRecordId ($val)
Definition at line 2324 of file EasyForm.php.
{
     $this->m_RecordId = $val;
     return $val;
    }
setRequestParams ($paramFields)
Set request parameters
Parameters
array $paramFields
Returns
void
Definition at line 804 of file EasyForm.php.
References getDataObj(), and setFixSearchRule().
    {
        if ($paramFields)
        {
         $this->m_FixSearchRule=null; // reset fixsearchrule to clean the previous one in session
            foreach($paramFields as $fieldName=>$val)
            {
                $element = $this->m_DataPanel->getByField($fieldName);
                if($element->m_AllowURLParam=='Y')
                {
                 if(!$this->getDataObj())return;
                 if($this->getDataObj()->getField($fieldName)){
                     if($this->getDataObj()->getField($fieldName)->checkValueType($val))
                     {
                         $this->setFixSearchRule("[$fieldName]='$val'");
                         //$queryString = QueryStringParam::formatQueryString("[$fieldName]", "=", $val);
                         //$this->setFixSearchRule($queryString,false);
                         //$this->m_SearchRuleBindValues = QueryStringParam::getBindValues();
                     }
                 }
                }
            }
        }
    }
setSearchRule ($searchRule, $searchRuleBindValues = null)
Definition at line 1144 of file EasyForm.php.
    {
     $this->m_SearchRule = $searchRule;
     $this->m_SearchRuleBindValues = $searchRuleBindValues;
     $this->m_RefreshData = true;
        $this->m_CurrentPage = 1;
    }
setSessionVars ($sessionContext)
Save object variable to session context
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 370 of file EasyForm.php.
    {
        $sessionContext->setObjVar($this->m_Name, "RecordId", $this->m_RecordId);
        $sessionContext->setObjVar($this->m_Name, "FixSearchRule", $this->m_FixSearchRule);
        $sessionContext->setObjVar($this->m_Name, "SearchRule", $this->m_SearchRule);
        $sessionContext->setObjVar($this->m_Name, "SearchRuleBindValues", $this->m_SearchRuleBindValues);
        $sessionContext->setObjVar($this->m_Name, "SubForms", $this->m_SubForms);
        $sessionContext->setObjVar($this->m_Name, "ParentFormName", $this->m_ParentFormName);
        $sessionContext->setObjVar($this->m_Name, "DefaultFormName", $this->m_DefaultFormName);
        $sessionContext->setObjVar($this->m_Name, "CurrentPage", $this->m_CurrentPage);
        $sessionContext->setObjVar($this->m_Name, "PageSize", $this->m_Range);
        $sessionContext->setObjVar($this->m_Name, "ReferenceFormName", $this->m_ReferenceFormName);
        $sessionContext->setObjVar($this->m_Name, "SearchPanelValues", $this->m_SearchPanelValues);
    }
setSubForms ($subForms) final
Set the sub forms of this form. This form is parent of other forms
Parameters
string $subForms - sub controls string with format: ctrl1;ctrl2...
Returns
void
Definition at line 592 of file EasyForm.php.
References MetaObject\prefixPackage().
    {
        // sub controls string with format: ctrl1;ctrl2...
        if (!$subForms || strlen($subForms) < 1)
        {
            $this->m_SubForms = null;
            return;
        }
        $subFormArr = explode(";", $subForms);
        unset($this->m_SubForms);
        foreach ($subFormArr as $subForm)
        {
            $this->m_SubForms[] = $this->prefixPackage($subForm);
        }
    }
sortRecord ($sortCol, $order = 'ASC')
Sort Record, for list form
Parameters
string $sortCol column name to sort
string $order 'dec' (decending) or 'asc' (ascending) remote
Returns
void
Definition at line 1049 of file EasyForm.php.
References getDataObj(), getElement(), and rerender().
    {
        $element = $this->getElement($sortCol);
        // turn off the OnSort flag of the old onsort field
        $element->setSortFlag(null);
        // turn on the OnSort flag of the new onsort field
        if ($order == "ASC")
            $order = "DESC";
        else
            $order = "ASC";
        $element->setSortFlag($order);
        // change the sort rule and issue the query
        $this->getDataObj()->setSortRule("[" . $element->m_FieldName . "] " . $order);
        // move to 1st page
        $this->m_CurrentPage = 1;
        $this->m_SortRule = "";
        $this->rerender();
    }
switchForm ($formName = null, $id = null, $params = null, $target = null)
Switch to other form
Parameters
string $formName to-be-swtiched form name. if empty, then switch to default form
string $id id value of the target form
Returns
void remote
Definition at line 2197 of file EasyForm.php.
References _showForm().
    {
     $paramFields = array();
     if($params){
      parse_str(urldecode($params),$paramFields);
     }
        if ($id!=null)
            $paramFields["Id"] = $id;
        $this->_showForm($formName, $target, $paramFields);
    }
targetSwitchForm ($targetForm, $formName = null, $id = null, $params = null, $target = null)
Definition at line 2216 of file EasyForm.php.
References BizSystem\getObject().
    {
     if($targetForm){
      $formObj = BizSystem::getObject($targetForm);
      if($formObj){
       return $formObj->switchForm($formName, $id, $params, $target);
      }
     }
    }
translate () protected
Definition at line 2372 of file EasyForm.php.
References MetaObject\getModuleName(), getTransKey(), getTransPrefix(), and I18n\t().
Referenced by readMetadata().
    {
     $module = $this->getModuleName($this->m_Name);
     if (!empty($this->m_Title))
     {
      $trans_string = I18n::t($this->m_Title, $this->getTransKey('Title'), $module, $this->getTransPrefix());
      if($trans_string){
       $this->m_Title = $trans_string;
      }
     }
     if (!empty($this->m_Icon))
     {
      $trans_string = I18n::t($this->m_Icon, $this->getTransKey('Icon'), $module, $this->getTransPrefix());
      if($trans_string){
       $this->m_Icon = $trans_string;
      }
     }
     if (!empty($this->m_Description))
     {
      $trans_string = I18n::t($this->m_Description, $this->getTransKey('Description'), $module, $this->getTransPrefix());
      if($trans_string){
       $this->m_Description = $trans_string;
      }
     }
    }
updateFieldValue ($Id, $fld_name, $value)
Update record
Returns
mixed
Definition at line 1500 of file EasyForm.php.
References _doUpdate(), and getActiveRecord().
Referenced by updateFieldValueAdd(), and updateFieldValueXor().
    {
  $element = $this->m_DataPanel->get($fld_name);
  $fieldname = $element->m_FieldName;
        $currentRec = $this->getActiveRecord($Id);
        $recArr = $this->getActiveRecord($Id);
  $recArr[$fieldname]=$value;
        if ($this->_doUpdate($recArr, $currentRec) == false)
            return;
  $this->UpdateForm();
    }
updateFieldValueAdd ($id, $fld_name, $value, $min, $max)
Definition at line 1475 of file EasyForm.php.
References updateFieldValue().
    {
     if($value>=$max){
      $value = $min;
     }else{
      $value++;
     }
  return $this->updateFieldValue($id,$fld_name,$value);
    }
updateFieldValueXor ($id, $fld_name, $value)
Definition at line 1485 of file EasyForm.php.
References updateFieldValue().
    {
     if($value>0){
      $value_xor = 0;
     }else{
      $value_xor = 1;
     }
  return $this->updateFieldValue($id,$fld_name,$value_xor);
    }
updateForm ()
Update form controls
Returns
void remote
Definition at line 1659 of file EasyForm.php.
References readInputRecord(), rerender(), and setActiveRecord().
    {
        // read the input to form controls
        //@todo: read inputs but should be skipp uploaders elements
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
        $this->rerender();
    }
updateRecord ()
Update record
Returns
mixed
Definition at line 1440 of file EasyForm.php.
References _doUpdate(), close(), commitFormElements(), fetchData(), processFormObjError(), processPostAction(), readInputRecord(), renderParent(), and setActiveRecord().
Referenced by saveRecord().
    {
        $currentRec = $this->fetchData();
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
        if (count($recArr) != 0){
         try
         {
             $this->ValidateForm();
         }
         catch (ValidationException $e)
         {
             $this->processFormObjError($e->m_Errors);
             return;
         }
         if ($this->_doUpdate($recArr, $currentRec) == false)
             return;
   $this->commitFormElements(); // commit change in FormElement
        }
        // in case of popup form, close it, then rerender the parent form
        if ($this->m_ParentFormName)
        {
            $this->close();
            $this->renderParent();
        }
        $this->processPostAction();
    }
validateForm ($cleanError = true) protected
Validate input on EasyForm level default form validation do nothing. developers need to override this method to implement their logic
Returns
boolean
Definition at line 1745 of file EasyForm.php.
References getMessage(), and BizSystem\getService().
    {
        if($cleanError == true)
        {
            $this->m_ValidateErrors = array();
        }
        $this->m_DataPanel->rewind();
        while($this->m_DataPanel->valid())
        {
            /* @var $element Element */
            $element = $this->m_DataPanel->current();
            if($element->m_Label)
            {
                $elementName = $element->m_Label;
            }
            else
            {
                $elementName = $element->m_Text;
            }
            if ($element->checkRequired() === true &&
                    ($element->m_Value==null || $element->m_Value == ""))
            {
                $errorMessage = $this->getMessage("FORM_ELEMENT_REQUIRED",array($elementName));
                $this->m_ValidateErrors[$element->m_Name] = $errorMessage;
                //return false;
            }
            elseif ($element->m_Value!==null && $element->Validate() == false)
            {
                $validateService = BizSystem::getService(VALIDATE_SERVICE);
                $errorMessage = $this->getMessage("FORM_ELEMENT_INVALID_INPUT",array($elementName,$value,$element->m_Validator));
                if ($errorMessage == false)
                { //Couldn't get a clear error message so let's try this
                    $errorMessage = $validateService->getErrorMessage($element->m_Validator, $elementName);
                }
                $this->m_ValidateErrors[$element->m_Name] = $errorMessage;
                //return false;
            }
            $this->m_DataPanel->next() ;
        }
        if (count($this->m_ValidateErrors) > 0)
        {
            throw new ValidationException($this->m_ValidateErrors);
            return false;
        }
        return true;
    }
validateRequest ($methodName)
Validate request from client (browser)
Parameters
string $methodName called from the client
Returns
boolean
Definition at line 411 of file EasyForm.php.
References getInvokingElement().
    {
        $methodName = strtolower($methodName);
        if ($methodName == "selectrecord" || $methodName == "invoke" || $methodName="sortrecord")
            return true;
        // element, eventhandler
        list($element, $eventHandler) = $this->getInvokingElement();
        if ($element && $eventHandler)
        {
            if (stripos($eventHandler->m_OrigFunction, $methodName)===0)
                return true;
        }
        // scan elements to match method
        foreach ($this->m_Panels as $panel)
        {
            foreach ($panel as $elem)
                if ($elem->matchRemoteMethod($methodName)) return true;
        }
        if (is_array($this->m_DirectMethodList))
        {
            foreach ($this->m_DirectMethodList as $value)
            {
                if ($methodName == $value) return true;
            }
        }
        return false;
    }
Field Documentation
$DATAFORMAT
Definition at line 31 of file EasyForm.php.
$m_ActionPanel
Definition at line 65 of file EasyForm.php.
$m_ActiveRecord
Definition at line 100 of file EasyForm.php.
Referenced by EasyFormWizard\commit(), fetchData(), and getActiveRecord().
$m_AutoRefresh
Definition at line 126 of file EasyForm.php.
$m_CacheLifeTime
Definition at line 83 of file EasyForm.php.
$m_CanUpdateRecord
Definition at line 43 of file EasyForm.php.
$m_CurrentPage protected
Definition at line 115 of file EasyForm.php.
Referenced by outputAttrs().
$m_DataObj protected
Definition at line 98 of file EasyForm.php.
Referenced by getDataObj().
$m_DataObjName
Definition at line 38 of file EasyForm.php.
$m_DataPanel
Definition at line 60 of file EasyForm.php.
Referenced by getElementSet(), and getTabSet().
$m_DefaultFixSearchRule protected
Definition at line 107 of file EasyForm.php.
Referenced by setFixSearchRule().
$m_DefaultForm
Definition at line 41 of file EasyForm.php.
$m_DefaultFormName
Definition at line 89 of file EasyForm.php.
Referenced by _showForm().
$m_Description
Definition at line 36 of file EasyForm.php.
$m_DirectMethodList
Definition at line 44 of file EasyForm.php.
$m_Errors
Definition at line 94 of file EasyForm.php.
$m_EventName
Definition at line 81 of file EasyForm.php.
Referenced by runEventLog().
$m_FixSearchRule
Definition at line 103 of file EasyForm.php.
Referenced by fetchData(), EasyFormGrouping\fetchDataGroup(), EasyFormTree\fetchDataSet(), and fetchDataSet().
$m_FormInputs
Definition at line 101 of file EasyForm.php.
Referenced by setFormInputs().
$m_FormParams
Definition at line 84 of file EasyForm.php.
$m_FormType
Definition at line 79 of file EasyForm.php.
$m_hasError protected
Definition at line 111 of file EasyForm.php.
$m_Height
Definition at line 39 of file EasyForm.php.
$m_Icon
Definition at line 35 of file EasyForm.php.
Referenced by outputAttrs().
$m_InheritFrom
Definition at line 53 of file EasyForm.php.
$m_InvokingElement protected
Definition at line 124 of file EasyForm.php.
Referenced by getInvokingElement().
$m_jsClass
Definition at line 37 of file EasyForm.php.
$m_MessageFile
Definition at line 110 of file EasyForm.php.
$m_Messages protected
Definition at line 123 of file EasyForm.php.
$m_NavPanel
Definition at line 70 of file EasyForm.php.
$m_Notices
Definition at line 95 of file EasyForm.php.
$m_Panels
Definition at line 46 of file EasyForm.php.
$m_ParentFormName
Definition at line 87 of file EasyForm.php.
$m_QueryStringParam
Definition at line 92 of file EasyForm.php.
$m_Range
Definition at line 82 of file EasyForm.php.
Referenced by readMetadata().
$m_RecordAllowAccess protected
Definition at line 129 of file EasyForm.php.
$m_RecordId protected
Definition at line 99 of file EasyForm.php.
Referenced by getElementID(), getRecordId(), loadDialog(), and outputAttrs().
$m_RecordSet protected
Definition at line 119 of file EasyForm.php.
$m_ReferenceFormName
Definition at line 128 of file EasyForm.php.
Referenced by _showForm().
$m_Referer protected
Definition at line 109 of file EasyForm.php.
$m_RefreshData protected
Definition at line 120 of file EasyForm.php.
$m_Resource protected
Definition at line 121 of file EasyForm.php.
$m_SearchPanel
Definition at line 75 of file EasyForm.php.
$m_SearchRule
Definition at line 102 of file EasyForm.php.
Referenced by EasyFormGrouping\fetchDataGroup(), EasyFormTree\fetchDataSet(), and fetchDataSet().
$m_SearchRuleBindValues protected
Definition at line 108 of file EasyForm.php.
$m_SortRule
Definition at line 105 of file EasyForm.php.
$m_StartItem protected
Definition at line 116 of file EasyForm.php.
$m_SubForms
Definition at line 80 of file EasyForm.php.
Referenced by getSubForms().
$m_TemplateEngine
Definition at line 77 of file EasyForm.php.
$m_TemplateFile
Definition at line 78 of file EasyForm.php.
$m_Title
Definition at line 34 of file EasyForm.php.
$m_TotalPages
Definition at line 117 of file EasyForm.php.
Referenced by EasyFormGrouping\fetchDataGroup(), fetchDataSet(), and outputAttrs().
$m_TotalRecords protected
Definition at line 118 of file EasyForm.php.
Referenced by outputAttrs().
$m_ValidateErrors protected
Definition at line 112 of file EasyForm.php.
$m_Width
Definition at line 40 of file EasyForm.php.