Openbiz Framework API: FormRenderer Class Reference
FormRenderer Class Reference
Static Public Member Functions
static buildTemplateAttributes ($formObj)
static render ($formObj)
Static Protected Member Functions
static renderPHP ($formObj, $tplAttributes=Array())
static renderSmarty ($formObj, $tplAttributes=Array())
Detailed Description
Definition at line 26 of file FormRenderer.php.
Member Function Documentation
static buildTemplateAttributes ($formObj) static
Gather all template variables needed. Should play well with Smarty or Zend templates
Parameters
EasyView $formObj
Returns
array associative array holding all needed VIEW based template variables
Definition at line 61 of file FormRenderer.php.
References BizSystem\clientProxy().
Referenced by render().
    {
        // Assocative Array to hold all Template Values
        // Fill with default viewobj attributes
        $tplAttributes = array();
        $tplAttributes['title'] = $formObj->m_Title;
        $tplAttributes['errors'] = $formObj->m_Errors;
        $tplAttributes['notices'] = $formObj->m_Notices;
        $tplAttributes['formname'] = $formObj->m_Name;
        $tplAttributes['module'] = $formObj->getModuleName($formObj->m_Name);
        // if the $formobj form type is list render table, otherwise render record
        if (strtoupper($formObj->m_FormType) == 'LIST') {
            $recordSet = $formObj->fetchDataSet();
            $tplAttributes['dataPanel'] = $formObj->m_DataPanel->renderTable($recordSet);
        } else {
            $record = $formObj->fetchData();
            $tplAttributes['dataPanel'] = $formObj->m_DataPanel->renderRecord($record);
        }
        if (isset($formObj->m_SearchPanel)) {
            $search_record = $formObj->m_SearchPanelValues;
            foreach ($formObj->m_SearchPanel as $elem) {
                if (! $elem->m_FieldName)
                    continue;
                $post_value = BizSystem::clientProxy()->getFormInputs($elem->m_Name);
                if ($post_value) {
                    $search_record[$elem->m_FieldName] = $post_value;
                }
            }
            $tplAttributes['searchPanel'] = $formObj->m_SearchPanel->renderRecord($search_record);
        } else {
            $tplAttributes['searchPanel'] = $formObj->m_SearchPanel->render();
        }
        $tplAttributes['actionPanel'] = $formObj->m_ActionPanel->render();
        $tplAttributes['navPanel'] = $formObj->m_NavPanel->render();
        if($formObj->m_WizardPanel)
        {
         $tplAttributes['wizardPanel'] = $formObj->m_WizardPanel->render();
        }
        $tplAttributes['form'] = $formObj->outputAttrs();
        return $tplAttributes;
    }
static render ($formObj) static
Render form object
Parameters
EasyForm $formObj
Returns
string result of rendering process
Definition at line 35 of file FormRenderer.php.
References buildTemplateAttributes(), renderPHP(), and renderSmarty().
Referenced by EasyForm\renderHTML().
    {
        $tplEngine = $formObj->m_TemplateEngine;
        $tplAttributes = FormRenderer::buildTemplateAttributes($formObj);
        if (isset($formObj->m_jsClass)) {
            $subForms = ($formObj->m_SubForms) ? implode(";", $formObj->m_SubForms) : "";
            if ($formObj->m_StaticOutput != true) {
                $formScript = "\n<script>Openbiz.newFormObject('$formObj->m_Name','$formObj->m_jsClass','$subForms'); </script>\n";
            }
            if ($formObj->m_AutoRefresh > 0) {
                $formScript .= "\n<script>setTimeout(\"Openbiz.CallFunction('$formObj->m_Name.UpdateForm()');\",\"" . ($formObj->m_AutoRefresh * 1000) . "\") </script>\n";
            }
        }
        if ($tplEngine == "Smarty" || $tplEngine == null)
            return FormRenderer::renderSmarty($formObj, $tplAttributes) . $formScript;
        else
            return FormRenderer::renderPHP($formObj, $tplAttributes) . $formScript;
    }
static renderPHP ($formObj, $tplAttributes = Array()) static protected
Render PHP template for form object
Parameters
EasyForm $formObj
string $tplFile
Returns
string result of rendering process
Definition at line 135 of file FormRenderer.php.
References BizSystem\getTplFileWithPath(), and BizSystem\getZendTemplate().
Referenced by render().
    {
        $form = BizSystem::getZendTemplate();
        $tplFile = BizSystem::getTplFileWithPath($formObj->m_TemplateFile, $formObj->m_Package);
        $form->addScriptPath(dirname($tplFile));
        /*$formOutput = $formObj->outputAttrs();
        foreach ($formOutput as $k=>$v) {
            $form->$k = $v;
        }*/
        foreach ($tplAttributes as $key => $value) {
            if ($value == NULL) {
                $form->$key = '';
            } else {
                $form->$key = $value;
            }
        }
        // render the formobj attributes
        //$form->form = $formOutput;
        return $form->render($formObj->m_TemplateFile);
    }
static renderSmarty ($formObj, $tplAttributes = Array()) static protected
Render smarty template for form object
Parameters
EasyForm $formObj
string $tplFile
Returns
string result of rendering process
Definition at line 115 of file FormRenderer.php.
References BizSystem\getSmartyTemplate(), and BizSystem\getTplFileWithPath().
Referenced by render().
    {
        $smarty = BizSystem::getSmartyTemplate();
        $tplFile = BizSystem::getTplFileWithPath($formObj->m_TemplateFile, $formObj->m_Package);
        //Translate Array of template variables to Zend template object
        foreach ($tplAttributes as $key => $value) {
            $smarty->assign($key, $value);
        };
        return $smarty->fetch($tplFile);
    }