Openbiz Framework API: excelService Class Reference
excelService Class Reference
Public Member Functions
__construct (&$xmlArr)
importCSV ($objName)
renderCSV ($objName)
renderTSV ($objName)
Protected Member Functions
getDataTable ($objName)
render ($objName, $separator=",", $ext="csv")
reportError ($error)
strip_cell ($str)
Detailed Description
Definition at line 28 of file excelService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize excelService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 37 of file excelService.php.
    {
    }
Member Function Documentation
getDataTable ($objName) protected
Get raw data to display in the spreadsheet. header and data table
Parameters
string $objName
Returns
array
Definition at line 222 of file excelService.php.
References BizSystem\objectFactory().
Referenced by render().
    {
        /* @var $formObj EasyForm */
        $formObj = BizSystem::objectFactory()->getObject($objName); // get the existing EasyForm|BizForm object
        // if BizForm, call BizForm::renderTable
        if ($formObj instanceof BizForm)
        {
            $dataTable = $formObj->renderTable();
        }
        // if EasyForm, call EasyForm->DataPanel::renderTable
        if ($formObj instanceof EasyForm)
        {
            $recordSet = $formObj->fetchDataSet();
            $dataSet = $formObj->m_DataPanel->renderTable($recordSet);
            foreach ($dataSet['elems'] as $elem)
            {
                $labelRow[] = $elem['label'];
            }
            $dataTable = array_merge(array($labelRow), $dataSet['data']);
        }
        return $dataTable;
    }
importCSV ($objName)
Import from CSV file NOTE: This method must be called from a popup form where a file is uploaded. The parent form of the popup form is the target to import.
Parameters
string $objName
Returns
void
Definition at line 76 of file excelService.php.
References BizSystem\clientProxy(), BizSystem\getMessage(), BizSystem\log(), BizSystem\objectFactory(), and reportError().
    {
        // read in file from $_FILE
        foreach ($_FILES as $file)
        {
            $error = $file['error'];
            if ($error != 0)
            {
                $this->reportError($error);
                return;
            }
            $tmpFileName  = $file['tmp_name'];
            break;
        }
        //echo "upload file name = $tmpFileName";
        $filename = $file['name'];
        if (strpos($filename,".csv")===false)
        {
         $errorMsg = BizSystem::getMessage("EXCELSVC_INVALID_FILE",array($filename));
         BizSystem::log(LOG_ERR, "EXCEL SERVICE", "Import error = ".$errorMsg);
            BizSystem::clientProxy()->showClientAlert($errorMsg);
            return;
        }
        /* @var $formObj EasyForm */
        $formObj = BizSystem::objectFactory()->getObject($objName); // get the existing EasyForm object
        $parentFormObj = BizSystem::objectFactory()->getObject($formObj->m_ParentFormName);
        $dataObj = $parentFormObj->getDataObj();
        $handle = fopen($tmpFileName, "r");
        $fields = fgetcsv($handle, 2000, ",");
        if (!$fields || count($fields)<2)
        {
         $errorMsg = BizSystem::getMessage("EXCELSVC_INVALID_FILE",array($filename));
         BizSystem::log(LOG_ERR, "EXCEL SERVICE", "Import error = ".$errorMsg);
            BizSystem::clientProxy()->showClientAlert($errorMsg);
            return;
        }
        // convert form element names to DO field names
        foreach ($parentFormObj->m_DataPanel as $element)
        {
            $elem_fields[$element->m_Label] = $element->m_FieldName;
        }
        // validate with dataobj fields
        for ($i=0; $i<count($fields); $i++)
        {
            $fields[$i] = $elem_fields[$fields[$i]];
            $field = $fields[$i];
            if (!$dataObj->getField($field))
            {
                $errorMsg = BizSystem::getMessage("EXCELSVC_INVALID_COLUMN",array($field, $dataObj->m_Name));
                BizSystem::log(LOG_ERR, "EXCEL SERVICE", "Import error = ".$errorMsg);
                BizSystem::clientProxy()->showClientAlert($errorMsg);
                return;
            }
        }
        while (($arr = fgetcsv($handle, 2000, ",")) !== FALSE)
        {
            if (count($arr) != count($fields))
                continue;
            unset($recArr);
            $i = 0;
            for ($i=0; $i<count($arr); $i++)
            {
                $recArr[$fields[$i]] = $arr[$i];
            }
            //print_r($recArr); echo "<hr>";
            $dataRec = new DataRecord(null, $dataObj);
            foreach ($recArr as $k => $v)
                $dataRec[$k] = $v;
            $ok = $dataRec->save();
            if (! $ok)
            {
                // NOTE: EasyForm::processDataObjError() not return any value (void)
                return $formObj->processDataObjError($ok);
            }
        }
        fclose($handle);
        // in case of popup form, close it, then rerender the parent form
        if ($formObj->m_ParentFormName)
        {
            $formObj->close();
            $formObj->renderParent();
        }
    }
render ($objName, $separator = ",", $ext = "csv") protected
Render excel data
Parameters
string $objName object form name
string $separator sparator between column
string $ext file extension
Returns
void
Definition at line 178 of file excelService.php.
References getDataTable(), and strip_cell().
Referenced by renderCSV(), and renderTSV().
    {
        ob_end_clean();
        header("Pragma: public");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Cache-Control: public");
        header("Content-Description: File Transfer");
        header("Content-Type: application/vnd.ms-excel");
        header("Content-Disposition: filename=" . $objName."_".date('Y-m-d') . "." . $ext);
        header("Content-Transfer-Encoding: binary");
        $dataTable = $this->getDataTable($objName);
        foreach ($dataTable as $row)
        {
            $line = "";
            foreach ($row as $cell) {
                $txt = $this->strip_cell($cell);
                //if (!empty($txt))
    //Changed condition from empty()to is_null() to allow null fields from being truncated out when csv generated (cyril ogana 2011-11-11)
    //TODO: Need to add condition to leave out fields which have no column name e.g. the first field which has rowcheckboxes?
    if (!is_null($txt))
                    $line .= "\"" . $txt . "\"$separator";
            }
            $line = rtrim($line, $separator);
            $line = iconv("UTF-8","GB2312//IGNORE",$line);
            echo rtrim($line) . "\n";
        }
    }
renderCSV ($objName)
Render the excel output with CSV format
Parameters
string $objName object name which is the bizform name
Returns
void
Definition at line 47 of file excelService.php.
References BizSystem\log(), and render().
    {
        $this->render($objName, ",", "csv");
        //Log This Export
        BizSystem::log(LOG_INFO, "ExcelService", "Export CSV file.");
    }
renderTSV ($objName)
Render the excel output with TSV format
Parameters
string $objName object name which is the bizform name
Returns
void
Definition at line 61 of file excelService.php.
References BizSystem\log(), and render().
    {
        $this->render($objName, "\t", "tsv");
        //Log This Export
        BizSystem::log(LOG_INFO, "ExcelService", "Export TSV file.");
    }
reportError ($error) protected
Show error message
Parameters
int $error error number
Definition at line 253 of file excelService.php.
References BizSystem\clientProxy().
Referenced by importCSV().
    {
        if ($error==1)
            $errorStr = "The uploaded file exceeds the upload_max_filesize directive in php.ini";
        else if ($error==2)
            $errorStr = "The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form";
        else if ($error==3)
            $errorStr = "The uploaded file was only partially uploaded";
        else if ($error==4)
            $errorStr = "No file was uploaded";
        else if ($error==6)
            $errorStr = "Missing a temporary folder";
        else if ($error==7)
            $errorStr = "Failed to write file to disk";
        else
            $errorStr = "Error in file upload";
        BizSystem::clientProxy()->showErrorMessage($errorStr);
    }
strip_cell ($str) protected
Definition at line 208 of file excelService.php.
Referenced by render().
{
     $str = strip_tags($str);
     $str = str_replace("\n",'',$str);
     $str = str_replace("\r",'',$str);
     return $str;
    }