Openbiz Framework API: pdfService Class Reference
pdfService Class Reference
Public Member Functions
__construct ()
cleanFiles ($dir, $seconds)
output ($domPdf)
renderView ($viewName)
Detailed Description
Definition at line 25 of file pdfService.php.
Constructor & Destructor Documentation
__construct ()
Initialize pdfService
Returns
void
Definition at line 32 of file pdfService.php.
    {
    }
Member Function Documentation
cleanFiles ($dir, $seconds)
Delete (temporary) files on specified directory
Parameters
string $dir filly directori name
number $seconds
Definition at line 95 of file pdfService.php.
Referenced by output().
    {
        $currentTime = time();
        $dirHandle=opendir($dir);
        while($file = readdir($dirHandle))
        {
            if(substr($file,0,3) == 'tmp' && substr($file,-4) == '.pdf')
            {
                $path = $dir.'/'.$file;
                if($currentTime - filemtime($path) > $seconds)
                    unlink($path);
            }
        }
        closedir($dirHandle);
    }
output ($domPdf)
Save PDF to file and inform download link to client
Parameters
DOMPDF $domPdf
Definition at line 67 of file pdfService.php.
References APP_HOME, and cleanFiles().
Referenced by renderView().
    {
        //$tmpfile = getcwd()."/tmpfiles";
        $tmpDir = APP_HOME."/tmpfiles";
        //echo $tmpfile;
        $this->cleanFiles($tmpDir, 100);
        //Determine a temporary file name in the current directory
        $tmpFile = tempnam($tmpDir,'tmp');
        $fileName = $tmpFile.'.pdf';
        $fileName = str_replace("\\","/",$fileName);
        unlink($tmpFile);
        //Save PDF to file
        $pdfText = $domPdf->output();
        $fileHandle = fopen($fileName, 'w') or die("can't open pdf file to write");
        fwrite($fileHandle, $pdfText) or die("can't write to the pdf file");
        fclose($fileHandle);
        //JavaScript redirection
        $path_parts = pathinfo($fileName);
        $file_download = "tmpfiles/".$path_parts['basename'];
        echo "<HTML><BODY onload=\"window.location.href='../$file_download';\"</BODY></HTML>";
    }
renderView ($viewName)
Render the pdf output
BizSystem $g_BizSystem
Parameters
string $viewName name of view object
Returns
void
Definition at line 43 of file pdfService.php.
References BizSystem\getObject(), and output().
    {
        $viewObj = BizSystem::getObject($viewName);
        if($viewObj)
        {
            $viewObj->setConsoleOutput(false);
            $sHTML = $viewObj->render();
            //$sHTML = "Test";
            //require_once("dompdf/dompdf_config.inc.php");
            $domPdf = new DOMPDF();
            $domPdf->load_html($sHTML);
            //$dompdf->set_paper($_POST["paper"], $_POST["orientation"]);
            $domPdf->render();
            $this->output($domPdf);
            //$dompdf->stream("dompdf_out.pdf");
        }
    }