Openbiz Framework API: validateService Class Reference
validateService Class Reference
Public Member Functions
__construct (&$xmlArr)
between ($value, $min, $max, $inclusive=true)
betweenLength ($value, $min, $max)
credit ($credit)
date ($date)
email ($email)
getErrorMessage ($validator=null, $fieldName=null)
greaterThan ($value, $min)
lessThan ($value, $max)
longerThan ($value, $min)
phone ($phone)
shorterThan ($value, $max)
social ($social)
street ($street)
strongPassword ($value)
zip ($zip)
Protected Member Functions
readMetadata (&$xmlArr)
Protected Attributes
$m_ErrorMessage
$m_FieldNameMask
Detailed Description
Definition at line 29 of file validateService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize reportService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 40 of file validateService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
between ($value, $min, $max, $inclusive = true)
Built-in Zend between check. Returns true if and only if $value is between the minimum and maximum boundary values.
Parameters
integer $value
integer $min
mixed $max
boolean $inclusive
Returns
boolean Valid?
Definition at line 231 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Between.php';
        $validator = new Zend_Validate_Between($min, $max, $inclusive);
        $result = $validator->isValid($value);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_BETWEEN",array($this->m_FieldNameMask ,$min, $max));
        }
        return $result;
    }
betweenLength ($value, $min, $max)
Function to check if a value is between a $min and $max length
Parameters
string $value
integer $max
integer $min
Returns
boolean Valid?
Definition at line 94 of file validateService.php.
References BizSystem\getMessage().
    {
        if((int)$min > (int)$max)
        {
            $tmp = $min;
            $min = $max;
            $max = $tmp;
        }
        $this->m_ErrorMessage = null;
        $result = false;
        if(function_exists("mb_strlen"))
        {
            if (mb_strlen($value,'UTF-8') <= $max && mb_strlen($value,'UTF-8') >= $min)
            {
                $result = true;
            }
        }
        else
        {
            if (strlen($value) <= $max && strlen($value) >= $min)
            {
                $result = true;
            }
        }
        if (!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_BETWEEN_LENGTH",array($this->m_FieldNameMask,$min,$max));
        }
        return $result;
    }
credit ($credit)
Credit Card check for US format VISA/AMEX/DISC/MC
Parameters
string $credit
Returns
boolean Valid?
Definition at line 355 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|");
        $result = $validator->isValid($credit);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_CREDIT_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
date ($date)
Built-in Zend date check using YYYY-MM-DD
Parameters
string in date format $date
Returns
boolean Valid?
Definition at line 279 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage=null;
        require_once 'Zend/Validate/Date.php';
        $validator = new Zend_Validate_Date();
        $result = $validator->isValid($date);
        if(!$result)
        {
            $this->m_ErrorMessage = BizSystem::getMessage("VALIDATESVC_DATE_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
email ($email)
Built-in Zend email check
Parameters
string $email
Returns
boolean Valid?
Definition at line 251 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/EmailAddress.php';
        /*
         * it's a newbelogic, too complicated
        $validator = new Zend_Validate_EmailAddress();
        $result = $validator->isValid($email);
        */
  if(preg_match("/^[A-Z0-9_-][A-Z0-9._-]*@([A-Z0-9][A-Z0-9-]*\.)+[A-Z\.]{2,6}$/i",$email)){
   $result = true;
  }else{
   $result = false;
  };
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_EMAIL_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
getErrorMessage ($validator = null, $fieldName = null)
Get error message
Parameters
string $validator
string $fieldName
Returns
string
Definition at line 394 of file validateService.php.
References $m_ErrorMessage, and BizSystem\getMessage().
    {
        if($this->m_ErrorMessage != "")
        {
            if($fieldName != "")
            {
                $this->m_ErrorMessage = str_replace($this->m_FieldNameMask,
                        $fieldName,
                        $this->m_ErrorMessage);
            }
            return $this->m_ErrorMessage;
        }
        else
        {
            $validator = str_replace('{@validate:', '', $validator);
            $pos1 = strpos($validator, '(');
            $type = substr($validator, 0, $pos1);
            switch ($type)
            {
                case "date":
                    return BizSystem::getMessage("VALIDATESVC_DATE_INVALID",array($fieldName));
                    break;
                case "email":
                    return BizSystem::getMessage("VALIDATESVC_EMAIL_INVALID",array($fieldName));
                    break;
                case "phone":
                    return BizSystem::getMessage("VALIDATESVC_PHONE_INVALID",array($fieldName));
                    break;
                case "zip":
                    return BizSystem::getMessage("VALIDATESVC_ZIP_INVALID",array($fieldName));
                    break;
                case "social":
                    return BizSystem::getMessage("VALIDATESVC_SOCIAL_INVALID",array($fieldName));
                    break;
                case "credit":
                    return BizSystem::getMessage("VALIDATESVC_CREDIT_INVALID",array($fieldName));
                    break;
                case "street":
                    return BizSystem::getMessage("VALIDATESVC_STREET_INVALID",array($fieldName));
                    break;
                case "strongPassword":
                    return BizSystem::getMessage("VALIDATESVC_PASSWORD_NOT_STRONG",array($fieldName));
                    break;
            }
            return BizSystem::getMessage("VALIDATESVC_INVALID",array($fieldName));
        }
    }
greaterThan ($value, $min)
Built-in Zend greater than check. Returns true if and only if $value is greater than the minimum boundary.
Parameters
integer $value
integer $min
Returns
boolean Valid?
Definition at line 208 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/GreaterThan.php';
        $validator = new Zend_Validate_GreaterThan($min);
        $result = $validator->isValid($value);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_GREATER_THAN",array($this->m_FieldNameMask, $min));
        }
        return $result;
    }
lessThan ($value, $max)
Built-in Zend less than check. Returns true if and only if $value is less than the minimum boundary.
Parameters
integer $value
integer $max
Returns
boolean Valid?
Definition at line 166 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/LessThan.php';
        $validator = new Zend_Validate_LessThan($max);
        $result = $validator->isValid($value);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_LESS_THAN",array($this->m_FieldNameMask,$max));
        }
        return $result;
    }
longerThan ($value, $min)
Function to check if a value is longer than the $min length
Parameters
string $value
integer $min
Returns
boolean Valid?
Definition at line 132 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        $result = false;
        if(function_exists("mb_strlen"))
        {
            if (mb_strlen($value,'UTF-8') > $min)
            {
                $result = true;
            }
        }
        else
        {
            if (strlen($value) > $min)
            {
                $result = true;
            }
        }
        if (!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_LONGER_THAN",array($this->m_FieldNameMask,$min));
        }
        return $result;
    }
phone ($phone)
Phone check for US format ###-###-#### or (###)###-####
Parameters
string $phone
Returns
boolean Valid?
Definition at line 298 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("/^[0-9]{3}-[0-9]{3}-[0-9]{4}/");
        $result = $validator->isValid($phone);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_PHONE_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 51 of file validateService.php.
Referenced by __construct().
    {
    }
shorterThan ($value, $max)
Function to check if a value is shorter than the $max length
Parameters
string $value
integer $max
Returns
boolean Valid?
Definition at line 62 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        $result = false;
        if(function_exists("mb_strlen"))
        {
            if (mb_strlen($value,'UTF-8') < $max)
            {
                $result = true;
            }
        }else
        {
            if (strlen($value) < $max)
            {
                $result = true;
            }
        }
        if (!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_SHORTER_THAN",array($this->m_FieldNameMask,$max));
        }
        return $result;
    }
social ($social)
Social Security check for US format ###-###-#### or (###)###-####
Parameters
string $social
Returns
boolean Valid?
Definition at line 336 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("\b[0-9]{3}-[0-9]{2}-[0-9]{4}\b");
        $result = $validator->isValid($social);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_SOCIAL_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
street ($street)
Street Address check for US format #### Memory Lane
Parameters
string $street
Returns
boolean Valid?
Definition at line 374 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("");
        $result = $validator->isValid($street);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_STREET_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
strongPassword ($value)
Strong Password checks if the string is "strong", i.e. the password must be at least 8 characters and must contain at least one lower case letter, one upper case letter and one digit
Parameters
mixed $value
Returns
boolean Valid?
Definition at line 186 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("/^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*$/");
        $result = $validator->isValid($value);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_PASSWORD_NOT_STRONG",array($this->m_FieldNameMask));
        }
        return $result;
    }
zip ($zip)
US Zip check in ##### or #####-####
Parameters
string $zip
Returns
boolean Valid?
Definition at line 317 of file validateService.php.
References BizSystem\getMessage().
    {
        $this->m_ErrorMessage = null;
        require_once 'Zend/Validate/Regex.php';
        $validator = new Zend_Validate_Regex("/^[0-9]{5,5}([- ]?[0-9]{4,4})?$/");
        $result = $validator->isValid($zip);
        if(!$result)
        {
            $this->m_ErrorMessage= BizSystem::getMessage("VALIDATESVC_ZIP_INVALID",array($this->m_FieldNameMask));
        }
        return $result;
    }
Field Documentation
$m_ErrorMessage protected
Definition at line 31 of file validateService.php.
Referenced by getErrorMessage().
$m_FieldNameMask protected
Definition at line 32 of file validateService.php.