Openbiz Framework API: TabView Class Reference
TabView Class Reference
Public Member Functions
__construct (&$xmlArr)
hasForms ()
Data Fields
$m_Caption
$m_Forms
$m_Icon
$m_Name
$m_Target
$m_URL
$m_View
$m_ViewSet
Protected Member Functions
getTransKey ($name)
translate ($caption)
Detailed Description
Definition at line 293 of file HTMLTabs.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize TabView with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 333 of file HTMLTabs.php.
References translate().
    {
        $this->m_Name = $xmlArr["ATTRIBUTES"]["NAME"];
        $this->m_View = $xmlArr["ATTRIBUTES"]["VIEW"];
        if(array_key_exists("VIEWSET", $xmlArr["ATTRIBUTES"]))
            $this->m_ViewSet = $xmlArr["ATTRIBUTES"]["VIEWSET"];
        $this->m_Caption = $this->translate($xmlArr["ATTRIBUTES"]["CAPTION"]);
        if(array_key_exists("URL", $xmlArr["ATTRIBUTES"]))
            $this->m_URL = $xmlArr["ATTRIBUTES"]["URL"];
        if(array_key_exists("TARGET", $xmlArr["ATTRIBUTES"]))
            $this->m_Target = $xmlArr["ATTRIBUTES"]["TARGET"];
        if(array_key_exists("ICON", $xmlArr["ATTRIBUTES"]))
            $this->m_Icon = $xmlArr["ATTRIBUTES"]["ICON"];
        $this->m_Forms = NULL;
        if(array_key_exists("FORM", $xmlArr))
            $this->m_Forms = $this->_getForms($xmlArr["FORM"]);     //Get form or forms to hide or show
        //$this->m_Forms = (!is_null($xmlArr["FORM"]))?$this->getForms($xmlArr["FORM"]):null;
    }
Member Function Documentation
getTransKey ($name) protected
Definition at line 371 of file HTMLTabs.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_Name,intval(strrpos($this->m_Name,'.'))+1);
     return strtoupper($shortFormName.'_'.$name);
    }
hasForms ()
Return TRUE if the current tabView has forms related to it
Returns
bool
Definition at line 360 of file HTMLTabs.php.
References $m_Forms.
    {
        return (bool) $this->m_Forms;
    }
translate ($caption) protected
Definition at line 365 of file HTMLTabs.php.
References getTransKey(), and I18n\t().
Referenced by __construct().
    {
     $module = $this->getModuleName($this->m_Name);
     return I18n::t($caption, $this->getTransKey(caption), $module);
    }
Field Documentation
$m_Caption
Definition at line 298 of file HTMLTabs.php.
$m_Forms
Definition at line 302 of file HTMLTabs.php.
Referenced by hasForms().
$m_Icon
Definition at line 301 of file HTMLTabs.php.
$m_Name
Definition at line 295 of file HTMLTabs.php.
$m_Target
Definition at line 300 of file HTMLTabs.php.
$m_URL
Definition at line 299 of file HTMLTabs.php.
$m_View
Definition at line 296 of file HTMLTabs.php.
$m_ViewSet
Definition at line 297 of file HTMLTabs.php.