Openbiz Framework API: auditService Class Reference
auditService Class Reference
Public Member Functions
__construct (&$xmlArr)
audit ($dataObjName)
Data Fields
$m_AuditDataObj
Protected Member Functions
readMetadata (&$xmlArr)
Detailed Description
Definition at line 25 of file auditService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize auditService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 35 of file auditService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
audit ($dataObjName)
Audit DataObj
Parameters
string $dataObjName
Returns
boolean
Definition at line 58 of file auditService.php.
References BizSystem\getObject(), BizSystem\getUserProfile(), and BizSystem\log().
    {
        // get audit dataobj
        $auditDataObj = BizSystem::getObject($this->m_AuditDataObj);
        if (!$auditDataObj) return false;
        // get the source dataobj
        $srcDataObj = BizSystem::getObject($dataObjName);
        if (!$srcDataObj) return false;
        // for each onaudit field, add a record in audit dataobj
        $auditFields = $srcDataObj->getOnAuditFields();
        foreach ($auditFields as $field)
        {
            if ($field->m_OldValue == $field->m_Value)
                continue;
            $recArr = $auditDataObj->newRecord();
            if ($recArr == false)
            {
                BizSystem::log(LOG_ERR, "DATAOBJ", $auditDataObj->getErrorMessage());
                return false;
            }
            $profile = BizSystem::getUserProfile();
            $recArr['DataObjName'] = $dataObjName;
            $recArr['ObjectId'] = $srcDataObj->getFieldValue("Id");
            $recArr['FieldName'] = $field->m_Name;
            $recArr['OldValue'] = $field->m_OldValue;
            $recArr['NewValue'] = $field->m_Value;
            $recArr['ChangeTime'] = date("Y-m-d H:i:s");
            $recArr['ChangeBy'] = $profile["USERID"];
            $recArr['ChangeFrom'] = $_SERVER['REMOTE_ADDR'];
            $recArr['RequestURI'] = $_SERVER['REQUEST_URI'];
            $recArr['Timestamp'] = date("Y-m-d H:i:s");
            $ok = $auditDataObj->insertRecord($recArr);
            if ($ok == false)
            {
                BizSystem::log(LOG_ERR, "DATAOBJ", $auditDataObj->getErrorMessage());
                return false;
            }
        }
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 46 of file auditService.php.
Referenced by __construct().
    {
        $this->m_AuditDataObj  = $xmlArr["PLUGINSERVICE"]["ATTRIBUTES"]["BIZDATAOBJ"];
    }
Field Documentation
$m_AuditDataObj
Definition at line 27 of file auditService.php.