Openbiz Framework API: QueryStringParam Class Reference
QueryStringParam Class Reference
Static Public Member Functions
static formatQueryString ($field, $opr, $value)
static formatQueryValue ($value)
static getBindValues ()
static getBindValueString ()
static reset ()
static setBindValues ($params)
Static Protected Attributes
static $m_Params
Detailed Description
Definition at line 25 of file QueryStringParam.php.
Member Function Documentation
static formatQueryString ($field, $opr, $value) static
Format query string
Parameters
string $field
string $opr operator
mixed $value
Returns
string
Definition at line 51 of file QueryStringParam.php.
References $m_Params.
Referenced by BizDataObj_SQLHelper\buildUpdateSQL(), and inputValToRule().
    {
        $key = ":_v".QueryStringParam::$_counter;
        $queryString = "$field  $opr $key";
        QueryStringParam::$_counter++;
        QueryStringParam::$m_Params[$key] = $value;
        return $queryString;
    }
static formatQueryValue ($value) static
Format query value
Parameters
mixed $value
Returns
string the query string
Definition at line 67 of file QueryStringParam.php.
References $m_Params.
Referenced by BizDataObj_SQLHelper\buildInsertSQL().
    {
        $key = ":_v".QueryStringParam::$_counter;
        $queryString = "$key";
        QueryStringParam::$_counter++;
        QueryStringParam::$m_Params[$key] = $value;
        return $queryString;
    }
static getBindValues () static
Get bnd values
Returns
array
Definition at line 96 of file QueryStringParam.php.
References $m_Params.
Referenced by BizDataObj_Lite\_run_search(), BizDataObj\insertRecord(), EasyForm\runSearch(), and BizDataObj\updateRecord().
    {
        return QueryStringParam::$m_Params;
    }
static getBindValueString () static
Get bind value string
Returns
string
Definition at line 106 of file QueryStringParam.php.
References $m_Params.
Referenced by BizDataObj_Lite\_run_search(), BizDataObj\insertRecord(), and BizDataObj\updateRecord().
    {
        return implode(',', QueryStringParam::$m_Params);
    }
static reset () static
Reset query string param
Returns
void
Definition at line 116 of file QueryStringParam.php.
References $m_Params.
Referenced by OptionElement\getDOFromList(), DropDownList\getDOFromList(), BizDataObj\insertRecord(), and BizDataObj\updateRecord().
    {
        QueryStringParam::$_counter = 1;
        QueryStringParam::$m_Params = array();
    }
static setBindValues ($params) static
Set bind value
Parameters
array $params
Returns
void
Definition at line 83 of file QueryStringParam.php.
References $m_Params.
Referenced by EasyForm\fetchData(), EasyFormGrouping\fetchDataGroup(), EasyFormTree\fetchDataSet(), and EasyForm\fetchDataSet().
    {
        if (!$params)
            return;
        QueryStringParam::$m_Params = $params;
        QueryStringParam::$_counter = count($params)+1;
    }
Field Documentation
$m_Params static protected
Definition at line 34 of file QueryStringParam.php.
Referenced by formatQueryString(), formatQueryValue(), getBindValues(), getBindValueString(), reset(), and setBindValues().