Openbiz Framework API: Panel Class Reference
Panel Class Reference
Public Member Functions
__construct (&$xmlArr, $childClassName, $parentObj=null)
getByField ($fieldName)
hasFormElement ()
render ()
renderRecord (&$recArr)
renderTable (&$recSet)
setRecordArr (&$recArr)
Public Member Functions inherited from MetaIterator
__construct (&$xmlArr, $childClassName, $parentObj=null)
clear ($key)
count ()
current ()
get ($key)
key ()
merge (&$anotherMIObj)
next ()
rewind ()
set ($key, $val)
valid ()
Data Fields
$m_FormName
Protected Member Functions
getFormObj ()
Additional Inherited Members
Protected Attributes inherited from MetaIterator
$m_prtObj
$m_var
Detailed Description
Definition at line 26 of file Panel.php.
Constructor & Destructor Documentation
__construct (& $xmlArr, $childClassName, $parentObj = null)
Definition at line 30 of file Panel.php.
    {
     parent::__construct($xmlArr, $childClassName, $parentObj);
     $this->m_FormName = $parentObj->m_Name;
    }
Member Function Documentation
getByField ($fieldName)
Get element by field,
Parameters
<type> $fieldName
Returns
Element
Definition at line 167 of file Panel.php.
References MetaIterator\$m_var.
    {
        /* @var $elem Element */
     $elems =  $this->m_var;
        foreach ($elems as $elem)
        {
            if($elem->m_FieldName == $fieldName && $elem->m_Class!='RowCheckbox')
            {
                return $elem;
            }
        }
    }
getFormObj () protected
Definition at line 36 of file Panel.php.
References BizSystem\objectFactory().
Referenced by setRecordArr().
    {
        return BizSystem::objectFactory()->getObject($this->m_FormName);
    }
hasFormElement ()
Definition at line 180 of file Panel.php.
    {
        foreach ($this->m_var as $elem)
        {
            if($elem->m_Class == 'FormElement')
            {
                return true;
            }
        }
        return false;
    }
render ()
Render the Panel and return array of rendering element (html text)
Returns
string - html text
Implements iUIControl.
Definition at line 45 of file Panel.php.
Referenced by renderRecord(), and renderTable().
    {
        $panel = array();
        /* @var $elem Element */
        foreach($this->m_var as $elem)
        {
            if ($elem->canDisplayed())
            {
                $panel[$elem->m_Name]['element'] = $elem->render();
                $panel[$elem->m_Name]['type'] = $elem->m_Class;
                $panel[$elem->m_Name]['width'] = $elem->m_Width;
                $panel[$elem->m_Name]['elementset'] = $elem->m_ElementSet;
                $panel[$elem->m_Name]['elementsetcode'] = $elem->m_ElementSetCode;
                $panel[$elem->m_Name]['tabset'] = $elem->m_TabSet;
                $panel[$elem->m_Name]['tabsetcode'] = $elem->m_TabSetCode;
                $panel[$elem->m_Name]['extra'] = $elem->m_Extra;
                if (isset($elem->m_Label) && $elem->m_Label !== null)
                    $panel[$elem->m_Name]['label'] = $elem->renderLabel();
                if (isset($elem->m_Value) && $elem->m_Value !== null)
                    $panel[$elem->m_Name]['value'] = $elem->m_Value;
                if (isset($elem->m_Description) && $elem->m_Description !== null)
                    $panel[$elem->m_Name]['description'] = $elem->getDescription();
                if (isset($elem->m_Required))
                    $panel[$elem->m_Name]['required'] = $elem->m_Required;
                if (isset($elem->m_ColumnStyle))
                    $panel[$elem->m_Name]['colstyle'] = $elem->m_ColumnStyle;
            }
        }
        return $panel;
    }
renderRecord (& $recArr)
Render record
Parameters
array $recArr
Returns
string - html text
Definition at line 84 of file Panel.php.
References render(), and setRecordArr().
    {
        if ($recArr)
            $this->setRecordArr($recArr);
        return $this->render();
    }
renderTable (& $recSet)
Render table and return an array with 3 sub arraies (elems, data, ids)
Parameters
array $recSet
Returns
array
Definition at line 97 of file Panel.php.
References render(), and setRecordArr().
    {
        $table['elems'] = $this->render();
        $counter = 0;
        while (true)
        {
            $arr = $recSet[$counter];
            if (!$arr) break;
            foreach($this->m_var as $elem)  // reset the elements
                $elem->reset();
            $this->setRecordArr($arr);
            $table['ids'][] = $arr['Id'];
            /* @var $elem Element */
            foreach($this->m_var as $elem)
            {
                if ($elem->canDisplayed())
                    $tableRow[$elem->m_Name] = $elem->render();
            }
            $table['data'][] = $tableRow;
            unset($tableRow);
            $counter++;
        }
        return $table;
    }
setRecordArr (& $recArr)
Set record array TODO: change field=>value to element=>value
Parameters
array $recArr
Returns
void
Definition at line 133 of file Panel.php.
References getFormObj().
Referenced by renderRecord(), and renderTable().
    {
     if(!$recArr)
      return ;
     foreach($recArr as $key=>$value){
         $this->getFormObj()->m_ActiveRecord[$key] = $recArr[$key];
     }
        // reset elements first to avoid use stale data
        foreach ($this->m_var as $elem)
         $elem->reset();
        /* @var $elem Element */
        $this->getFormObj()->setFormInputs();
        foreach ($this->m_var as $elem)
        {
            //if (!$recArr)
            //    $elem->setValue("");
            if (key_exists($elem->m_FieldName, $recArr)) {
                $elem->setValue($recArr[$elem->m_FieldName]);
            }
            else if (key_exists($elem->m_Name, $recArr)) {
                $elem->setValue($recArr[$elem->m_Name]);
            }
        }
    }
Field Documentation
$m_FormName
Definition at line 28 of file Panel.php.