Openbiz Framework API: PickerForm Class Reference
PickerForm Class Reference
Public Member Functions
addToParent ($recIds=null)
getSessionVars ($sessionContext)
insertToParent ()
joinToParent ($recIds=null)
pickToParent ($recId=null)
setParentFormData ($formName, $elemName=null, $pickerMap=null)
setSessionVars ($sessionContext)
Public Member Functions inherited from EasyForm
__construct (&$xmlArr)
allowAccess ($access=null)
autoSuggest ($input)
callService ($class, $method, $param=null)
cancel ()
canDeleteRecord ($rec)
canDisplayForm ()
close ()
copyRecord ($id=null)
deleteRecord ($id=null)
editRecord ($id=null)
fetchData ()
fetchDataSet ()
getActiveRecord ($recId=null)
getDataObj ()
getElement ($elementName)
getElementID ()
getElementSet ($panel=null)
getErrorElements ($fields)
getMessage ($messageId, $params=array())
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
getSubForms ()
getTabSet ($panel=null)
getViewObject ()
gotoPage ($page=1)
gotoSelectedPage ($elemName)
insertRecord ()
invoke ()
loadDialog ($formName, $id=null, $transId=false)
loadPicker ($formName, $elementName="")
newRecord ()
outputAttrs ()
parentSwitchForm ($formName=null, $id=null, $params=null, $target=null)
processBDOException ($e)
processDataObjError ($errCode=0)
processFormObjError ($errors)
removeRecord ()
render ()
renderParent ()
rerender ($redrawForm=true, $hasRecordChange=true)
resetSearch ()
runSearch ()
saveRecord ()
selectRecord ($recId)
setCurrentPage ($pageid)
setDataObj ($dataObj)
setFixSearchRule ($rule=null, $cleanActualRule=true)
setFormInputs ($inputArr=null)
setPageSize ($elemName)
setParentForm ($parentFormName)
setRecordId ($val)
setRequestParams ($paramFields)
setSearchRule ($searchRule, $searchRuleBindValues=null)
setSessionVars ($sessionContext)
setSubForms ($subForms)
sortRecord ($sortCol, $order='ASC')
switchForm ($formName=null, $id=null, $params=null, $target=null)
targetSwitchForm ($targetForm, $formName=null, $id=null, $params=null, $target=null)
updateFieldValue ($Id, $fld_name, $value)
updateFieldValueAdd ($id, $fld_name, $value, $min, $max)
updateFieldValueXor ($id, $fld_name, $value)
updateForm ()
updateRecord ()
validateRequest ($methodName)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_ParentFormElemName
$m_ParentFormRecord
$m_PickerMap
Data Fields inherited from EasyForm
$DATAFORMAT
$m_ActionPanel
$m_ActiveRecord
$m_AutoRefresh
$m_CacheLifeTime
$m_CanUpdateRecord
$m_DataObjName
$m_DataPanel
$m_DefaultForm
$m_DefaultFormName
$m_Description
$m_DirectMethodList
$m_Errors
$m_EventName
$m_FixSearchRule
$m_FormInputs
$m_FormParams
$m_FormType
$m_Height
$m_Icon
$m_InheritFrom
$m_jsClass
$m_MessageFile
$m_NavPanel
$m_Notices
$m_Panels
$m_ParentFormName
$m_QueryStringParam
$m_Range
$m_ReferenceFormName
$m_SearchPanel
$m_SearchRule
$m_SortRule
$m_SubForms
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_TotalPages
$m_Width
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
_parsePickerMap ($pickerMap)
Protected Member Functions inherited from EasyForm
_doInsert ($inputRecord)
_doUpdate ($inputRecord, $currentRecord)
_showForm ($formName, $target, $paramFields)
commitFormElements ()
getEventLogMsg ()
getInvokingElement ()
getNewRecord ()
getOnEventElements ()
getRedirectPage ()
getTransKey ($name)
getTransPrefix ()
inheritParentObj ()
processPostAction ()
readInputRecord ()
readInputs ()
readMetadata (&$xmlArr)
renderContextMenu ()
renderHTML ()
rerenderSubForms ()
runEventLog ()
setActiveRecord ($record)
setClientScripts ()
translate ()
validateForm ($cleanError=true)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Additional Inherited Members
Protected Attributes inherited from EasyForm
$m_CurrentPage
$m_DataObj
$m_DefaultFixSearchRule
$m_hasError
$m_InvokingElement
$m_Messages
$m_RecordAllowAccess
$m_RecordId
$m_RecordSet
$m_Referer
$m_RefreshData
$m_Resource
$m_SearchRuleBindValues
$m_StartItem
$m_TotalRecords
$m_ValidateErrors
Detailed Description
Definition at line 25 of file PickerForm.php.
Member Function Documentation
_parsePickerMap ($pickerMap) protected
Parse Picker Map into an array
Parameters
string $pickerMap pickerMap defined in metadata
Returns
array picker map array
Definition at line 317 of file PickerForm.php.
Referenced by joinToParent().
    {
        $returnList = array();
        $pickerList = explode(",", $pickerMap);
        foreach ($pickerList as $pair)
        {
            $controlMap = explode(":", $pair);
            $controlMap[0] = trim($controlMap[0]);
            $controlMap[1] = trim($controlMap[1]);
            $returnList[] = $controlMap;
        }
        return $returnList;
    }
addToParent ($recIds = null)
Add a record (popup) to the parent form if OK button clicked, (M-M or M-1/1-1)
Returns
void
Definition at line 265 of file PickerForm.php.
References EasyForm\close(), EasyForm\getDataObj(), BizSystem\getObject(), and BizSystem\objectFactory().
Referenced by insertToParent(), and pickToParent().
    {
     if(!is_array($recIds))
     {
      $recIdArr = array();
      $recIdArr[] = $recIds;
     }else{
      $recIdArr = $recIds;
     }
     /* @var $parentForm EasyForm */
     $parentForm = BizSystem::objectFactory()->getObject($this->m_ParentFormName);
     foreach($recIdArr as $recId)
     {
         //clear parent form search rules
         $this->m_SearchRule="";
         $parentForm->getDataObj()->clearSearchRule();
         $do = $this->getDataObj();
         $baseSearchRule = $do->m_BaseSearchRule;
         $do->m_BaseSearchRule = "";
         $do->clearSearchRule();
         $rec = $do->fetchById($recId);
   $do->m_BaseSearchRule = $baseSearchRule;
   if(!$rec){
    $rec=BizSystem::getObject($do->m_Name,1)->fetchById($recId);
   }
         // add record to parent form's dataObj who is M-M or M-1/1-1 to its parent dataobj
         $ok = $parentForm->getDataObj()->addRecord($rec, $bPrtObjUpdated);
         if (!$ok){
             return $parentForm->processDataObjError($ok);
         }
     }
        $this->close();
        $parentForm->rerender();
  if($parentForm->m_ParentFormName){
   $parentForm->renderParent();
  }
    }
getSessionVars ($sessionContext)
Get/Retrieve Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 46 of file PickerForm.php.
    {
        parent::getSessionVars($sessionContext);
        $sessionContext->getObjVar($this->m_Name, "ParentFormElemName", $this->m_ParentFormElemName);
        $sessionContext->getObjVar($this->m_Name, "PickerMap", $this->m_PickerMap);
        $sessionContext->getObjVar($this->m_Name, "ParentFormRecord", $this->m_ParentFormRecord);
    }
insertToParent ()
Definition at line 113 of file PickerForm.php.
References addToParent(), EasyForm\close(), EasyForm\getDataObj(), BizSystem\objectFactory(), EasyForm\processFormObjError(), EasyForm\readInputRecord(), and EasyForm\setActiveRecord().
    {
  $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
        if (count($recArr) == 0)
            return;
        try
        {
            $this->ValidateForm();
        }
        catch (ValidationException $e)
        {
            $this->processFormObjError($e->m_Errors);
            return;
        }
        if (!$this->m_ParentFormElemName)
        {
         //its only supports 1-m assoc now
         $parentForm = BizSystem::objectFactory()->getObject($this->m_ParentFormName);
         //$parentForm->getDataObj()->clearSearchRule();
         $parentDo = $parentForm->getDataObj();
         $column = $parentDo->m_Association['Column'];
      $field = $parentDo->getFieldNameByColumn($column);
      $parentRefVal = $parentDo->m_Association["FieldRefVal"];
   $recArr[$field] = $parentRefVal;
      if($parentDo->m_Association['Relationship']=='1-M'){
       $cond_column = $parentDo->m_Association['CondColumn'];
       $cond_value = $parentDo->m_Association['CondValue'];
       if($cond_column)
       {
        $cond_field = $parentDo->getFieldNameByColumn($cond_column);
        $recArr[$cond_field] = $cond_value;
       }
       $recId = $parentDo->InsertRecord($recArr);
      }else{
       $recId = $this->getDataObj()->InsertRecord($recArr);
       $this->addToParent($recId);
      }
        }
        if ($this->m_ParentFormElemName && $this->m_PickerMap)
        {
            return ; //not supported yet
        }
        $selIds[] = $recId;
        $this->close();
        if($parentForm->m_ParentFormName){
         $parentParentForm = BizSystem::objectFactory()->getObject($parentForm->m_ParentFormName);
         $parentParentForm->rerender();
        }
        else
        {
         $parentForm->rerender();
        }
    }
joinToParent ($recIds = null)
Join a record (popup) to parent form
Parameters
<type> $recId
Returns
void
Definition at line 184 of file PickerForm.php.
References $m_ParentFormRecord, _parsePickerMap(), BizSystem\clientProxy(), EasyForm\close(), EasyForm\getDataObj(), EasyForm\getElement(), and BizSystem\objectFactory().
Referenced by pickToParent().
    {
     if(!is_array($recIds))
     {
      $recIdArr = array();
      $recIdArr[] = $recIds;
     }else{
      $recIdArr = $recIds;
     }
     $parentForm = BizSystem::objectFactory()->getObject($this->m_ParentFormName);
     $updArray = array();
     $updRec = $this->m_ParentFormRecord;
     foreach($recIdArr as $recId)
     {
         $rec = $this->getDataObj()->fetchById($recId);
         // get the picker map of the control
         if ($this->m_PickerMap)
         {
             $pickerList = $this->_parsePickerMap($this->m_PickerMap);
             foreach ($pickerList as $ctrlPair)
             {
                 $this_ctrl = $this->getElement($ctrlPair[1]);
                 if (!$this_ctrl)
                     continue;
                 $this_ctrl_val = $rec[$this_ctrl->m_FieldName];
                 $other_ctrl = $parentForm->getElement($ctrlPair[0]);
                 if ($other_ctrl)
                 {
                  if(!$updArray[$other_ctrl->m_Name]){
                   $updArray[$other_ctrl->m_Name] = $this_ctrl_val;
                   $updRec[$other_ctrl->m_FieldName] = $this_ctrl_val;
                  }else{
                   $updArray[$other_ctrl->m_Name] .= ';'.$this_ctrl_val;
                   $updRec[$other_ctrl->m_FieldName] .= ';'.$this_ctrl_val;
                  }
                 }
             }
         }
         else
             return;
     }
        $this->close();
        $elem = $parentForm->getElement($this->m_ParentFormElemName);
        if($elem->m_UpdateForm=='Y'){
         $parentForm->setActiveRecord($updRec);
         $parentForm->rerender();
        }else{
         BizSystem::clientProxy()->updateFormElements($parentForm->m_Name, $updArray);
         foreach($updArray as $elemName=>$value)
         {
          $elem = $parentForm->getElement($elemName);
           $elemEvents = $elem->getEvents();
           foreach($elemEvents as $event=>$function)
           {
            if(strtolower($event)=='onchange')
            {
             if(is_array($function)){
        foreach($function as $f){
         $function_str.=$f.";";
        }
       }else{
        $function_str .= $function;
       }
             BizSystem::clientProxy()->runClientScript("<script>$function_str</script>");
            }
           }
         }
        }
    }
pickToParent ($recId = null)
Pick data to parent form
Parameters
<type> $recId
Returns
void remote
Definition at line 90 of file PickerForm.php.
References addToParent(), BizSystem\clientProxy(), and joinToParent().
    {
     if ($recId==null || $recId=='')
            $recId = BizSystem::clientProxy()->getFormInputs('_selectedId');
        $selIds = BizSystem::clientProxy()->getFormInputs('row_selections', false);
        if ($selIds == null)
            $selIds[] = $recId;
        // if no parent elem or picker map, call AddToParent
        if (!$this->m_ParentFormElemName)
        {
            $this->addToParent($selIds);
        }
        // if has parent elem and picker map, call JoinToParent
        if ($this->m_ParentFormElemName && $this->m_PickerMap)
        {
            $this->joinToParent($selIds);
        }
    }
setParentFormData ($formName, $elemName = null, $pickerMap = null)
Set parent form data/informations
Parameters
string $formName
string $elemName
string $pickerMap
Returns
void
Definition at line 76 of file PickerForm.php.
    {
        $this->m_ParentFormName = $formName;
        $this->m_ParentFormElemName = $elemName;
        $this->m_PickerMap = $pickerMap;
    }
setSessionVars ($sessionContext)
Save object variable to session context
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 60 of file PickerForm.php.
    {
        parent::setSessionVars($sessionContext);
        $sessionContext->setObjVar($this->m_Name, "ParentFormElemName", $this->m_ParentFormElemName);
        $sessionContext->setObjVar($this->m_Name, "PickerMap", $this->m_PickerMap);
        $sessionContext->setObjVar($this->m_Name, "ParentFormRecord", $this->m_ParentFormRecord);
    }
Field Documentation
$m_ParentFormElemName
Definition at line 31 of file PickerForm.php.
$m_ParentFormRecord
Definition at line 39 of file PickerForm.php.
Referenced by joinToParent().
$m_PickerMap
Definition at line 37 of file PickerForm.php.