Openbiz Framework API: queryService Class Reference
queryService Class Reference
Public Member Functions
__construct ()
fetchAll ($doName, $searchRule)
fetchField ($doName, $searchRule, $fieldName)
fetchRecord ($doName, $searchRule)
Detailed Description
Definition at line 25 of file queryService.php.
Constructor & Destructor Documentation
__construct ()
Initialize queryService
Returns
void
Definition at line 33 of file queryService.php.
    {
    }
Member Function Documentation
fetchAll ($doName, $searchRule)
Fetch all data from specified data object
Parameters
string $doName data object name
string $searchRule rule of serach
Returns
array array of records
Definition at line 45 of file queryService.php.
References BizSystem\getObject().
    {
        $do = BizSystem::getObject($doName);
        if (!$do)
        {
            throw new Exception("System cannot get object of $doName.");
            return;
        }
        return $do->directFetch($searchRule);
    }
fetchField ($doName, $searchRule, $fieldName)
Fetch field
Parameters
string $doName data object name
string $searchRule search rule
string $fieldName field name
Returns
mixed
Definition at line 85 of file queryService.php.
References fetchRecord().
    {
        $rec = $this->fetchRecord($doName, $searchRule);
        if ($rec)
            return $rec[$fieldName];
        return null;
    }
fetchRecord ($doName, $searchRule)
Fetch record
Parameters
string $doName data object name
string $searchRule rule of search
Returns
mixed
Definition at line 63 of file queryService.php.
References BizSystem\getObject().
Referenced by fetchField().
    {
        $do = BizSystem::getObject($doName);
        if (!$do)
        {
            throw new Exception("System cannot get object of $doName.");
            return;
        }
        $r = $do->directFetch($searchRule, 1);
        if (count($r)>0)
            return $r[0];
        return null;
    }