Openbiz Framework API: OptionElement Class Reference
OptionElement Class Reference
Public Member Functions
getFromList (&$list, $selectFrom=null)
getSQLFromList (&$list)
render ()
Public Member Functions inherited from InputElement
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_SelectedList
$m_SelectFrom
$m_SelectFromSQL
Data Fields inherited from InputElement
$m_DefaultValue
$m_DefaultValueRename
$m_Description
$m_Enabled
$m_FieldName
$m_Hint
$m_Label
$m_Required
$m_Text
Data Fields inherited from Element
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getDOFromList (&$list, $selectFrom)
getSelectedList ()
getSelectFrom ()
getSelectFromSQL ()
getSimpleFromList (&$list, $selectFrom)
getTransLOVPrefix ()
getXMLFromList (&$list, $selectFrom)
readMetaData (&$xmlArr)
translateList (&$list, $tag)
Protected Member Functions inherited from InputElement
addSCKeyScript ()
getEnabled ()
getRequired ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 34 of file OptionElement.php.
Member Function Documentation
getDOFromList (& $list, $selectFrom) protected
Definition at line 159 of file OptionElement.php.
References BizSystem\getObject(), and QueryStringParam\reset().
Referenced by getFromList().
    {
        $pos0 = strpos($selectFrom, "[");
        $pos1 = strpos($selectFrom, "]");
        if ($pos0 > 0 && $pos1 > $pos0)
        {  // select from bizObj
            // support BizObjName[BizFieldName] or
            // BizObjName[BizFieldName4Text:BizFieldName4Value] or
            // BizObjName[BizFieldName4Text:BizFieldName4Value:BizFieldName4Pic]
            $bizObjName = substr($selectFrom, 0, $pos0);
            $pos3 = strpos($selectFrom, ":");
            if($pos3 > $pos0 && $pos3 < $pos1)
            {
                $fieldName = substr($selectFrom, $pos0 + 1, $pos3 - $pos0 - 1);
                $fieldName_v = substr($selectFrom, $pos3 + 1, $pos1 - $pos3 - 1);
            }
            else
            {
                $fieldName = substr($selectFrom, $pos0 + 1, $pos1 - $pos0 - 1);
                $fieldName_v = $fieldName;
            }
            $pos4 = strpos($fieldName_v, ":");
            if($pos4){
             $fieldName_v_mixed = $fieldName_v;
             $fieldName_v = substr($fieldName_v_mixed,0,$pos4);
             $fieldName_p = substr($fieldName_v_mixed, $pos4+1, strlen($fieldName_v_mixed)-$pos4-1);
             unset($fieldName_v_mixed);
            }
            $commaPos = strpos($selectFrom, ",", $pos1);
            if ($commaPos > $pos1)
                $searchRule = trim(substr($selectFrom, $commaPos + 1));
            /* @var $bizObj BizDataObj */
            $bizObj = BizSystem::getObject($bizObjName);
            if (!$bizObj)
                return false;
            $recList = array();
            $oldAssoc = $bizObj->m_Association;
            $bizObj->m_Association = null;
            QueryStringParam::reset();
            $recList = $bizObj->directFetch($searchRule);
            $bizObj->m_Association = $oldAssoc;
            foreach ($recList as $rec)
            {
                $list[$i]['val'] = $rec[$fieldName_v];
                $list[$i]['txt'] = $rec[$fieldName];
                $list[$i]['pic'] = $rec[$fieldName_p];
                $i++;
            }
            return true;
        }
        return false;
    }
getFromList (& $list, $selectFrom = null)
Get from list
Parameters
array $list
Returns
void
Definition at line 93 of file OptionElement.php.
References getDOFromList(), getSelectFrom(), getSimpleFromList(), getSQLFromList(), and getXMLFromList().
Referenced by TreeLabelText\render(), ImageSelector\render(), Radio\render(), CheckListbox\render(), Textarea\render(), Listbox\render(), LabelList\render(), Checkbox\render(), EditCombobox\render(), ColumnListbox\render(), and ColumnList\render().
    {
        if (!$selectFrom) {
            $selectFrom = $this->getSelectFrom();
        }
        if (!$selectFrom) {
         return $this->getSQLFromList($list);
        }
        $this->getXMLFromList($list, $selectFrom);
        if ($list != null)
            return;
        $this->getDOFromList($list, $selectFrom);
        if ($list != null)
            return;
        $this->getSimpleFromList($list, $selectFrom);
        if ($list != null)
            return;
        return;
    }
getSelectedList () protected
Definition at line 65 of file OptionElement.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by CheckListbox\render().
    {
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_SelectedList, $formobj);
    }
getSelectFrom () protected
Get select from
Returns
string
Definition at line 59 of file OptionElement.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by getFromList(), Checkbox\getValue(), and Checkbox\render().
    {
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_SelectFrom, $formobj);
    }
getSelectFromSQL () protected
Definition at line 71 of file OptionElement.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by getSQLFromList().
    {
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_SelectFromSQL, $formobj);
    }
getSimpleFromList (& $list, $selectFrom) protected
Definition at line 216 of file OptionElement.php.
Referenced by getFromList().
    {
        // in case of a|b|c
        if (strpos($selectFrom, "[") > 0 || strpos($selectFrom, "(") > 0)
            return;
        $recList = explode('|',$selectFrom);
        foreach ($recList as $rec)
        {
            $list[$i]['val'] = $rec;
            $list[$i]['txt'] = $rec;
            $list[$i]['pic'] = $rec;
            $i++;
        }
    }
getSQLFromList (& $list)
Definition at line 231 of file OptionElement.php.
References Element\getFormObj(), getSelectFromSQL(), and BizSystem\log().
Referenced by getFromList().
    {
     $sql = $this->getSelectFromSQL();
     if (!$sql) return;
     $formObj = $this->getFormObj();
     $do = $formObj->getDataObj();
     $db = $do->getDBConnection();
     try {
      $resultSet = $db->query($sql);
      $recList = $resultSet->fetchAll();
      foreach ($recList as $rec)
         {
             $list[$i]['val'] = $rec[0];
             $list[$i]['txt'] = isset($rec[1]) ? $rec[1] : $rec[0];
             $i++;
         }
     }
     catch (Exception $e)
        {
            BizSystem::log(LOG_ERR, "DATAOBJ", "Query Error: ".$e->getMessage());
            $this->m_ErrorMessage = "Error in SQL query: ".$sql.". ".$e->getMessage();
            throw new BDOException($this->m_ErrorMessage);
            return null;
        }
    }
getTransLOVPrefix () protected
Definition at line 269 of file OptionElement.php.
Referenced by translateList().
    {
     $nameArr = explode(".",$this->m_SelectFrom);
     for($i=1;$i<count($nameArr)-1;$i++)
     {
      $prefix .= strtoupper($nameArr[$i])."_";
     }
     return $prefix;
    }
getXMLFromList (& $list, $selectFrom) protected
Definition at line 114 of file OptionElement.php.
References BizSystem\getXmlArray(), and translateList().
Referenced by getFromList().
    {
        $pos0 = strpos($selectFrom, "(");
        $pos1 = strpos($selectFrom, ")");
        if ($pos0>0 && $pos1 > $pos0)
        {  // select from xml file
            $xmlFile = substr($selectFrom, 0, $pos0);
            $tag = substr($selectFrom, $pos0 + 1, $pos1 - $pos0-1);
            $tag = strtoupper($tag);
            $xmlFile = BizSystem::GetXmlFileWithPath ($xmlFile);
            if (!$xmlFile) return false;
            $xmlArr = &BizSystem::getXmlArray($xmlFile);
            if ($xmlArr)
            {
                $i = 0;
                if (!key_exists($tag, $xmlArr["SELECTION"]))
                    return false;
                if(!$xmlArr["SELECTION"][$tag][0]){
                 $array = $xmlArr["SELECTION"][$tag];
                 unset($xmlArr["SELECTION"][$tag]);
                 $xmlArr["SELECTION"][$tag][0]=$array;
                }
                foreach($xmlArr["SELECTION"][$tag] as $node)
                {
                    $list[$i]['val'] = $node["ATTRIBUTES"]["VALUE"];
                    $list[$i]['pic'] = $node["ATTRIBUTES"]["PICTURE"];
                    if ($node["ATTRIBUTES"]["TEXT"])
                    {
                        $list[$i]['txt'] = $node["ATTRIBUTES"]["TEXT"];
                    }
                    else
                    {
                        $list[$i]['txt'] = $list[$i]['val'];
                    }
                    $i++;
                }
                $this->translateList($list, $tag); // supprot multi-language
            }
            return true;
        }
        return false;
    }
readMetaData (& $xmlArr) protected
Read metadata info from metadata array and store to class variable
Parameters
array $xmlArr metadata array
Returns
void
Definition at line 46 of file OptionElement.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_SelectFrom = isset($xmlArr["ATTRIBUTES"]["SELECTFROM"]) ? $xmlArr["ATTRIBUTES"]["SELECTFROM"] : null;
        $this->m_SelectedList = isset($xmlArr["ATTRIBUTES"]["SELECTEDLIST"]) ? $xmlArr["ATTRIBUTES"]["SELECTEDLIST"] : null;
        $this->m_SelectFromSQL = isset($xmlArr["ATTRIBUTES"]["SELECTFROMSQL"]) ? $xmlArr["ATTRIBUTES"]["SELECTFROMSQL"] : null;
    }
render ()
Render, draw the control according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 82 of file OptionElement.php.
    {
        return "";
    }
translateList (& $list, $tag) protected
Definition at line 257 of file OptionElement.php.
References MetaObject\getModuleName(), getTransLOVPrefix(), and I18n\t().
Referenced by getXMLFromList().
    {
     $module = $this->getModuleName($this->m_SelectFrom);
        if (empty($module))
            $module = $this->getModuleName($this->m_FormName);
     for ($i=0; $i<count($list); $i++)
     {
      $key = 'SELECTION_'.strtoupper($tag).'_'.$i.'_TEXT';
      $list[$i]['txt'] = I18n::t($list[$i]['txt'], $key, $module, $this->getTransLOVPrefix());
     }
    }
Field Documentation
$m_SelectedList
Definition at line 38 of file OptionElement.php.
$m_SelectFrom
Definition at line 36 of file OptionElement.php.
Referenced by AutoSuggest\render().
$m_SelectFromSQL
Definition at line 37 of file OptionElement.php.