Openbiz Framework API: HTMLMenus Class Reference
HTMLMenus Class Reference
Public Member Functions
__construct (&$xmlArr)
render ()
rerender ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
getTransKey ($name)
readMetadata (&$xmlArr)
renderMenuItems (&$menuItemArray)
renderSingleMenuItem (&$menuItem)
translate ($caption)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_MenuItemsXml
Additional Inherited Members
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Detailed Description
Definition at line 26 of file HTMLMenus.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize HTMLMenus with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 36 of file HTMLMenus.php.
References BizSystem\clientProxy(), and readMetadata().
    {
        $this->readMetadata($xmlArr);
        BizSystem::clientProxy()->appendStyles("menu", "menu.css");
        BizSystem::clientProxy()->appendScripts("menu-ie-js", '<!--[if gte IE 5.5]>
  <script language="JavaScript" src="".Resource::getJsUrl()."/ie_menu.js" type="text/JavaScript"></script>
  <![endif]-->', false);
    }
Member Function Documentation
getTransKey ($name) protected
Definition at line 166 of file HTMLMenus.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_Name,intval(strrpos($this->m_Name,'.'))+1);
     return strtoupper($shortFormName.'_'.$name);
    }
readMetadata (& $xmlArr) protected
Read Metadata from xml array
Parameters
array $xmlArr
Returns
void
Definition at line 51 of file HTMLMenus.php.
Referenced by __construct().
    {
        $this->m_Name = $xmlArr["MENU"]["ATTRIBUTES"]["NAME"];
        $this->m_Package = $xmlArr["MENU"]["ATTRIBUTES"]["PACKAGE"];
        $this->m_Class = $xmlArr["MENU"]["ATTRIBUTES"]["CLASS"];
        $this->m_MenuItemsXml = $xmlArr["MENU"]["MENUITEM"];
    }
render ()
Render the html menu
Returns
string html content of the menu
Implements iUIControl.
Definition at line 64 of file HTMLMenus.php.
References renderMenuItems().
Referenced by rerender().
    {
        // list all views and highlight the current view
        $sHTML = "<ul id='navmenu'>\n";
        $sHTML .= $this->renderMenuItems($this->m_MenuItemsXml);
        $sHTML .= "</ul>";
        return $sHTML;
    }
renderMenuItems (& $menuItemArray) protected
Render menu items
Parameters
array $menuItemArray menu item array
Returns
string html content of the menu items
Definition at line 79 of file HTMLMenus.php.
References renderSingleMenuItem().
Referenced by render(), and renderSingleMenuItem().
    {
        $sHTML = "";
        if (isset($menuItemArray["ATTRIBUTES"]))
        {
            $sHTML .= $this->renderSingleMenuItem($menuItemArray);
        }
        else
        {
            foreach ($menuItemArray as $menuItem)
            {
                $sHTML .= $this->renderSingleMenuItem($menuItem);
            }
        }
        return $sHTML;
    }
renderSingleMenuItem (& $menuItem) protected
Render single menu item
Parameters
array $menuItem menu item metadata xml array
Returns
string html content of each menu item
Definition at line 102 of file HTMLMenus.php.
References BizSystem\getService(), BizSystem\getUserProfile(), renderMenuItems(), and translate().
Referenced by renderMenuItems().
    {
        $profile = BizSystem::getUserProfile();
        $svcobj = BizSystem::getService(ACCESS_SERVICE);
        $role = isset($profile["ROLE"]) ? $profile["ROLE"] : null;
        if (array_key_exists('URL', $menuItem["ATTRIBUTES"]))
        {
            $url = $menuItem["ATTRIBUTES"]["URL"];
        }
        elseif (array_key_exists('VIEW', $menuItem["ATTRIBUTES"]))
        {
            $view = $menuItem["ATTRIBUTES"]["VIEW"];
            // menuitem's containing VIEW attribute is renderd if access is granted in accessservice.xml
            // menuitem's are rendered if no definition is found in accessservice.xml (default)
            if ($svcobj->allowViewAccess($view, $role))
            {
                $url="javascript:GoToView('".$view."')";
            }
            else
            {
                return '';
            }
        }
        $caption = $this->translate($menuItem["ATTRIBUTES"]["CAPTION"]);
        $target = $menuItem["ATTRIBUTES"]["TARGET"];
        $icon = $menuItem["ATTRIBUTES"]["ICON"];
        $img = $icon ? "<img src='".Resource::getImageUrl()."/$icon' class=menu_img> " : "";
        if ($view)
            $url="javascript:GoToView('".$view."')";
        if ($target)
            $sHTML .= "<li><a href=\"".$url."\" target='$target'>$img".$caption."</a>";
        else
            $sHTML .= "<li><a href=\"".$url."\">$img".$caption."</a>";
        if ($menuItem["MENUITEM"])
        {
            $sHTML .= "\n<ul>\n";
            $sHTML .= $this->renderMenuItems($menuItem["MENUITEM"]);
            $sHTML .= "</ul>";
        }
        $sHTML .= "</li>\n";
        return $sHTML;
    }
rerender ()
Rerender the menu
Returns
string html content of the menu
Definition at line 155 of file HTMLMenus.php.
References render().
    {
        return $this->render();
    }
translate ($caption) protected
Definition at line 160 of file HTMLMenus.php.
References MetaObject\getModuleName(), getTransKey(), and I18n\t().
Referenced by renderSingleMenuItem().
    {
     $module = $this->getModuleName($this->m_Name);
     return I18n::t($caption, $this->getTransKey(caption), $module);
    }
Field Documentation
$m_MenuItemsXml protected
Definition at line 28 of file HTMLMenus.php.