Openbiz Framework API: securityRule_Abstract Class Reference
securityRule_Abstract Class Reference
Public Member Functions
__construct (&$xmlArr)
checkEffectiveTime ()
getErrorMessage ()
process ()
Data Fields
$m_Action
$m_EffectiveTime
$m_ErrorMessage
$m_Match
$m_Name
$m_Status
Protected Member Functions
readMetadata (&$xmlArr)
Detailed Description
Definition at line 199 of file securityService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize reportService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 214 of file securityService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
checkEffectiveTime ()
Check Effective Time
Returns
boolean
Definition at line 259 of file securityService.php.
Referenced by URLFilterRule\process(), DomainFilterRule\process(), AgentFilterRule\process(), IPFilterRule\process(), PostFilterRule\process(), and GetFilterRule\process().
    {
        sscanf( $this->m_EffectiveTime, "%2d%2d-%2d%2d",
                $start_hour, $start_min,
                $end_hour, $end_min
        );
        $startTime  = strtotime(date("Y-m-d ").$start_hour.":".$start_min) ? strtotime(date("Y-m-d ").$start_hour.":".$start_min) : strtotime(date("Y-m-d 00:00"));
        $endTime    = strtotime(date("Y-m-d ").$end_hour.":".$end_min) ? strtotime(date("Y-m-d ").$end_hour.":".$end_min) : strtotime(date("Y-m-d 23:59:59"));
        $nowTime    = time();
        if($startTime>0 && $endTime>0)
        {
            //auto convert start time and end time
            if($endTime < $startTime)
            {
                $tmpTime = $startTime;
                $startTime = $endTime;
                $endTime = $tmpTime;
            }
            if($startTime < $nowTime && $nowTime < $endTime )
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
getErrorMessage ()
Get message error
Returns
string
Definition at line 249 of file securityService.php.
References $m_ErrorMessage.
    {
        return $this->m_ErrorMessage;
    }
process ()
Proses security rule
Returns
string
Implements iSecurityRule.
Definition at line 239 of file securityService.php.
    {
        return true;
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 225 of file securityService.php.
Referenced by __construct().
    {
        $this->m_Name  = $xmlArr["ATTRIBUTES"]["NAME"];
        $this->m_Action = $xmlArr["ATTRIBUTES"]["ACTION"];
        $this->m_Status = $xmlArr["ATTRIBUTES"]["STATUS"];
        $this->m_Match  = $xmlArr["ATTRIBUTES"]["MATCH"];
        $this->m_EffectiveTime = $xmlArr["ATTRIBUTES"]["EFFECTIVETIME"];
    }
Field Documentation
$m_Action
Definition at line 202 of file securityService.php.
$m_EffectiveTime
Definition at line 205 of file securityService.php.
$m_ErrorMessage
Definition at line 206 of file securityService.php.
Referenced by getErrorMessage().
$m_Match
Definition at line 203 of file securityService.php.
$m_Name
Definition at line 201 of file securityService.php.
$m_Status
Definition at line 204 of file securityService.php.