Openbiz Framework API: openbiz/bin/util/block.t.php File Reference
block.t.php File Reference
Namespaces
namespace smarty
Functions
smarty_block_t ($params, $text, &$smarty)
smarty_gettext_strarg ($str)
Function Documentation
smarty_block_t ($params, $text, & $smarty)
Smarty block function, provides gettext support for smarty.
The block content is the text that should be translated.
Any parameter that is sent to the function will be represented as n in the translation text, where n is 1 for the first parameter. The following parameters are reserved:
escape - sets escape mode:
'html' for HTML escaping, this is the default.
'js' for javascript escaping.
'url' for url escaping.
'no'/'off'/0 - turns off escaping
plural - The plural version of the text (2nd parameter of ngettext())
count - The item count for plural mode (3rd parameter of ngettext())
Definition at line 73 of file block.t.php.
References smarty_gettext_strarg(), and I18n\t().
{
 $text = stripslashes($text);
 // set escape mode
 if (isset($params['escape'])) {
  $escape = $params['escape'];
  unset($params['escape']);
 }
 // set plural version
 if (isset($params['plural'])) {
  $plural = $params['plural'];
  unset($params['plural']);
  // set count
  if (isset($params['count'])) {
   $count = $params['count'];
   unset($params['count']);
  }
 }
 //debut modif lolo
 //utilisons Zend_translate
 // use plural if required parameters are set
 /*if (isset($count) && isset($plural)) {
  $text = ngettext($text, $plural, $count);
 } else { // use normal
  $text = gettext($text);
 }*/
 //$text=I18n::getInstance()->translate($text);
 $module = $smarty->_tpl_vars['module'];
 $key = strtoupper('STRING_'.md5($text));
 $text = I18n::t($text, $key, $module);
 //fin modif lolo
 // run strarg if there are parameters
 if (count($params)) {
  $text = smarty_gettext_strarg($text, $params);
 }
 if (!isset($escape) || $escape == 'html') { // html escape, default
    $text = nl2br(htmlspecialchars($text));
   } elseif (isset($escape)) {
  switch ($escape) {
   case 'javascript':
   case 'js':
    // javascript escape
    $text = str_replace('\'', '\\\'', stripslashes($text));
    break;
   case 'url':
    // url escape
    $text = urlencode($text);
    break;
  }
 }
 return $text;
}
smarty_gettext_strarg ($str)
Replaces arguments in a string with their values. Arguments are represented by % followed by their number.
Parameters
string Source string
mixed Arguments, can be passed in an array or through single variables.
Returns
string Modified string
Definition at line 38 of file block.t.php.
Referenced by smarty_block_t().
{
 $tr = array();
 $p = 0;
 for ($i=1; $i < func_num_args(); $i++) {
  $arg = func_get_arg($i);
  if (is_array($arg)) {
   foreach ($arg as $aarg) {
    $tr['%'.++$p] = $aarg;
   }
  } else {
   $tr['%'.++$p] = $arg;
  }
 }
 return strtr($str, $tr);
}