Openbiz Framework API: TypeManager Class Reference
TypeManager Class Reference
Public Member Functions
__construct ($localeCode="")
convertDatetimeFormat ($oldFormattedValue, $oldFormat, $newFormat)
formattedStringToValue ($type, $format, $formattedString)
setLocaleInfo ($localeInfo)
valueToFormattedString ($type, $format, $value)
Protected Member Functions
currencyToValue ($format, $formattedValue)
datetimeToValue ($format, $formattedValue)
dateToValue ($format, $formattedValue)
numberToValue ($format, $formattedValue)
phoneToValue ($mask, $formattedValue)
textToValue ($format, $formattedValue)
valueToCurrency ($format, $value)
valueToDate ($format, $value)
valueToDatetime ($fmt, $value)
valueToNumber ($format, $value)
valueToPhone ($mask, $value)
valueToText ($format, $value)
Protected Attributes
$_localeInfo
Detailed Description
Definition at line 25 of file TypeManager.php.
Constructor & Destructor Documentation
__construct ($localeCode = "")
Constructor of TypeManager, set locale with $localCode parameter
Parameters
string $localeCode
Returns
void
Definition at line 39 of file TypeManager.php.
References I18n\getCurrentLangCode().
    {
        //try to set correct locale for current language as defined in app.inc section I18n
        $currentLanguage = I18n::getCurrentLangCode();
        $localeCode = $GLOBALS["local"][$currentLanguage];
        setlocale(LC_ALL, $localeCode);
        $this->_localeInfo = localeconv();
        if ($this->_localeInfo['frac_digits'] > 10)
            $this->_localeInfo = null;
    }
Member Function Documentation
convertDatetimeFormat ($oldFormattedValue, $oldFormat, $newFormat)
Convert a formatted datetime to another format
Parameters
$oldFormattedValue - old formated value
$oldFormat - old format of value
$newFormat - new format of value
Returns
string new formatted datetime value
Definition at line 320 of file TypeManager.php.
Referenced by datetimeToValue(), and dateToValue().
    {
        if ($oldFormat == $newFormat)
            return $oldFormattedValue;
        $timeStamp = $this->_parseDate($oldFormat, $oldFormattedValue);
        return strftime($newFormat, $timeStamp);
    }
currencyToValue ($format, $formattedValue) protected
Unformat a currency to value
Parameters
string $format - type format
string $formattedValue - formatted string value
Returns
mixed - value
Definition at line 259 of file TypeManager.php.
Referenced by formattedStringToValue().
    {
        if (! $this->_localeInfo)
            return $formattedValue;
        $tmp = str_replace($this->_localeInfo["currency_symbol"], null, $formattedValue);
        $tmp = str_replace($this->_localeInfo['thousands_sep'], null, $tmp);
        return (float) $tmp;
    }
datetimeToValue ($format, $formattedValue) protected
Unformat a datetime to value
Parameters
string $format - type format
string $formattedValue - formatted string
Returns
mix $stdFormat - ISO format YYYY-MM-DD HH:MM:SS
Definition at line 227 of file TypeManager.php.
References convertDatetimeFormat().
Referenced by formattedStringToValue().
    {
        if (! $formattedValue)
            return '';
        $stdFormat = $this->convertDatetimeFormat($formattedValue, $format, '%Y-%m-%d %H:%M:%S');
        return $stdFormat;
    }
dateToValue ($format, $formattedValue) protected
Unformat a date to value
Parameters
string $format - type format
string $formattedValue - formatted string
Returns
mixed $stdFormat - ISO format YYYY-MM-DD
Definition at line 195 of file TypeManager.php.
References convertDatetimeFormat().
Referenced by formattedStringToValue().
    {
        if (! $formattedValue)
            return '';
        $stdFormat = $this->convertDatetimeFormat($formattedValue, $format, '%Y-%m-%d');
        return $stdFormat;
    }
formattedStringToValue ($type, $format, $formattedString)
Convert Formatted String To Value
Parameters
string $type - field type
string $format - type format
string $formattedString - formatted string
Returns
mixed
Definition at line 58 of file TypeManager.php.
References currencyToValue(), datetimeToValue(), dateToValue(), numberToValue(), phoneToValue(), and textToValue().
    {
        if ($formattedString === null || $formattedString === "")
            return null;
        switch ($type)
        {
            case "Number": return $this->numberToValue($format, $formattedString);
            case "Text": return $this->textToValue($format, $formattedString);
            case "Date": return $this->dateToValue($format, $formattedString);
            case "Datetime": return $this->datetimeToValue($format, $formattedString);
            case "Currency": return $this->currencyToValue($format, $formattedString);
            case "Phone": return $this->phoneToValue($format, $formattedString);
            default: return $formattedString;
        }
    }
numberToValue ($format, $formattedValue) protected
Unformat a number to value
Parameters
string $format - type format
string $formattedValue - formatted string
Returns
mixed
Definition at line 125 of file TypeManager.php.
Referenced by formattedStringToValue().
    {
        if ($formattedValue === false || $formattedValue === true)
            return null;
        if ($format[0] == "%")
            return sscanf($formattedValue, $format);
        if (! $this->_localeInfo)
            return $formattedValue;
        $tmp = str_replace($this->_localeInfo['thousands_sep'], null, $formattedValue);
        $tmp = str_replace($this->_localeInfo['decimal_point'], ".", $tmp);
        if ($format == "Int")
            return (int) $tmp;
        return $tmp;
    }
phoneToValue ($mask, $formattedValue) protected
Unformat a phone to value
Parameters
string $fmt - type format
string $formattedValue - formatted string
Returns
mixed
Definition at line 305 of file TypeManager.php.
Referenced by formattedStringToValue().
    {
        if ($formattedValue[0] == "*")
            return $formattedValue;
        return ereg_replace("[^0-9]", null, $formattedValue);
    }
setLocaleInfo ($localeInfo)
Definition at line 391 of file TypeManager.php.
    {
        $this->_localeInfo = $localeInfo;
    }
textToValue ($format, $formattedValue) protected
Unformat a text to value
Parameters
string $format - type format
string $formattedValue - formatted string
Returns
mixed
Definition at line 159 of file TypeManager.php.
Referenced by formattedStringToValue().
    {
        if ($formattedValue === false)
            $formattedValue = "";
        return $formattedValue;
    }
valueToCurrency ($format, $value) protected
Format value to currency
Parameters
string $format - type format
string $value - value
Returns
string - formatted string
Definition at line 242 of file TypeManager.php.
Referenced by valueToFormattedString().
    {
        if (! $value)
            return "";
        if (! $this->_localeInfo)
            return $value;
        $fmtNum = number_format($value, $this->_localeInfo['frac_digits'], $this->_localeInfo['mon_decimal_point'], $this->_localeInfo['mon_thousands_sep']);
        return $this->_localeInfo["currency_symbol"] . $fmtNum;
    }
valueToDate ($format, $value) protected
Format value to date
Parameters
string $format - type format
string $value - value
Returns
string - Empty string or formatted Time/Date
Definition at line 173 of file TypeManager.php.
Referenced by valueToDatetime(), and valueToFormattedString().
    {
        // ISO format YYYY-MM-DD as input
        if ($value == "0000-00-00")
            return "";
        if (! $value)
            return "";
        if (strlen(trim($value)) < 1)
            return "";
        $tt = strtotime($value);
        if ($tt != - 1)
            return strftime($format, strtotime($value));
        return "";
    }
valueToDatetime ($fmt, $value) protected
Format value to date time
Parameters
string $fmt - type format
string $value - value
Returns
string - formatted string
Definition at line 210 of file TypeManager.php.
References valueToDate().
Referenced by valueToFormattedString().
    {
        // ISO format YYYY-MM-DD HH:MM:SS as input
        if ($value == "0000-00-00 00:00:00")
            return "";
        if ($fmt == null)
            $fmt = DATETIME_FORMAT;
        return $this->valueToDate($fmt, $value);
    }
valueToFormattedString ($type, $format, $value)
Convert Value To Formatted String
Parameters
string $type - field type
string $format - type format
string $value - value
Returns
string - formatted string
Definition at line 82 of file TypeManager.php.
References valueToCurrency(), valueToDate(), valueToDatetime(), valueToNumber(), valueToPhone(), and valueToText().
    {
        switch ($type)
        {
            case "Number": return $this->valueToNumber($format, $value);
            case "Text": return $this->valueToText($format, $value);
            case "Date": return $this->valueToDate($format, $value);
            case "Datetime": return $this->valueToDatetime($format, $value);
            case "Currency": return $this->valueToCurrency($format, $value);
            case "Phone": return $this->valueToPhone($format, $value);
            default: return $value;
        }
    }
valueToNumber ($format, $value) protected
Format value to number
Parameters
string $format - type format
string $value - value
Returns
string formatted number
Definition at line 103 of file TypeManager.php.
Referenced by valueToFormattedString().
    {
        if ($format[0] == "%")
            return sprintf($format, $value);
        if (! $this->_localeInfo)
            return $value;
        $formattedNumber = $value;
        if ($format == "Int")
            $formattedNumber = number_format($value, 0, $this->_localeInfo['decimal_point'], $this->_localeInfo['thousands_sep']);
        else
        if ($format == "Float")
            $formattedNumber = number_format($value, $this->_localeInfo['frac_digits'], $this->_localeInfo['decimal_point'], $this->_localeInfo['thousands_sep']);
        return $formattedNumber;
    }
valueToPhone ($mask, $value) protected
Format value to phone number
Parameters
string $fmt - type format
string $value - value
Returns
string - formatted string
Definition at line 275 of file TypeManager.php.
Referenced by valueToFormattedString().
    {
        if (substr($value, 0, 1) == "*") // if phone starts with "*", it's an international number, don't convert it
            return $value;
        if (trim($value) == "")
            return $value;
        $maskLen = strlen($mask);
        $ph_len = strlen($value);
        $ph_fmt = $mask;
        $j = 0;
        for ($i = 0; $i < $maskLen; $i ++)
        {
            if ($mask[$i] == "#")
            {
                $ph_fmt[$i] = $value[$j];
                $j ++;
                if ($j == $ph_len)
                    break;
            }
        }
        return substr($ph_fmt, 0, $i + 1);
    }
valueToText ($format, $value) protected
Format value to text
Parameters
string $format - type format
string $value - value
Returns
string formatted string
Definition at line 147 of file TypeManager.php.
Referenced by valueToFormattedString().
    {
        return $value;
    }
Field Documentation
$_localeInfo protected
Definition at line 31 of file TypeManager.php.