Openbiz Framework API: EventHandler Class Reference
EventHandler Class Reference
Public Member Functions
__construct (&$xmlArr)
adjustFormName ($formName)
getFormedFunction ()
getInvokeAction ()
parseFunction ($funcString)
setFormName ($formName, $elemName)
Data Fields
$m_ContextMenu
$m_Event
$m_EventLogMsg
$m_FormedFunction
$m_Function
$m_FunctionType
$m_Name
$m_Parameter
$m_PostAction
$m_RedirectPage
$m_ShortcutKey
$m_URL
Protected Member Functions
getTransKey ($name)
translate ()
Detailed Description
Definition at line 624 of file Element.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize EventHandler with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 649 of file Element.php.
References $m_Function.
    {
        $this->m_Name = isset($xmlArr["ATTRIBUTES"]["NAME"]) ? $xmlArr["ATTRIBUTES"]["NAME"] : null;
        $this->m_Event = isset($xmlArr["ATTRIBUTES"]["EVENT"]) ? $xmlArr["ATTRIBUTES"]["EVENT"] : null;
        $this->m_Function = isset($xmlArr["ATTRIBUTES"]["FUNCTION"]) ? $xmlArr["ATTRIBUTES"]["FUNCTION"] : null;
        $this->m_OrigFunction = $this->m_Function;
        $this->m_FunctionType = isset($xmlArr["ATTRIBUTES"]["FUNCTIONTYPE"]) ? $xmlArr["ATTRIBUTES"]["FUNCTIONTYPE"] : null;
        $this->m_PostAction = isset($xmlArr["ATTRIBUTES"]["POSTACTION"]) ? $xmlArr["ATTRIBUTES"]["POSTACTION"] : null;
        $this->m_ShortcutKey = isset($xmlArr["ATTRIBUTES"]["SHORTCUTKEY"]) ? $xmlArr["ATTRIBUTES"]["SHORTCUTKEY"] : null;
        $this->m_ContextMenu = isset($xmlArr["ATTRIBUTES"]["CONTEXTMENU"]) ? $xmlArr["ATTRIBUTES"]["CONTEXTMENU"] : null;
        $this->m_RedirectPage = isset($xmlArr["ATTRIBUTES"]["REDIRECTPAGE"]) ? $xmlArr["ATTRIBUTES"]["REDIRECTPAGE"] : null;
  $this->m_Parameter = isset($xmlArr["ATTRIBUTES"]["PARAMETER"]) ? $xmlArr["ATTRIBUTES"]["PARAMETER"] : null;
        $this->m_EventLogMsg = isset($xmlArr["ATTRIBUTES"]["EVENTLOGMSG"]) ? $xmlArr["ATTRIBUTES"]["EVENTLOGMSG"] : null;
        $this->m_URL = isset($xmlArr["ATTRIBUTES"]["URL"]) ? $xmlArr["ATTRIBUTES"]["URL"] : null;
    }
Member Function Documentation
adjustFormName ($formName)
Adjust form name
Parameters
string $formName
Returns
void
Definition at line 695 of file Element.php.
    {
        $this->_formName = $formName;
        // if no class name, add default class name. i.e. NewRecord => ObjName.NewRecord
        if ($this->m_Function)
        {
         if(strtolower(substr($this->m_Function,0,3))!='js:'){
    $pos0 = strpos($this->m_Function, "(");
    $len = strlen($this->m_Function);
    if ($pos0 > 0)
     $pos = strrpos($this->m_Function, ".", $pos0-$len);
    else
     $pos = strrpos($this->m_Function, ".");
    if ($pos > 0)
     $this->m_Function = $this->_formName.".".substr($this->m_Function, $pos+1);
   }
        }
    }
getFormedFunction ()
Get formed function
Returns
string
Definition at line 719 of file Element.php.
References $m_FormedFunction, $m_Name, Expression\evaluateExpression(), and BizSystem\objectFactory().
    {
        //return $this->getInvokeAction();
        $name = $this->_elemName;
        $ehName = $this->m_Name;
        $formobj = BizSystem::objectFactory()->getObject($this->_formName);
        if ($this->m_FormedFunction)
        {
            return $this->m_FormedFunction;
        }
        if (!$this->m_FormedFunction || $isDataPanelElement==true)
        {
            // add direct URL support
            if ($this->m_URL)
            {
                $_func = "loadPage('" . $this->m_URL . "');";
                $_func = Expression::evaluateExpression($_func, $formobj);
            }
            else if (strpos($this->m_Function, "js:") === 0)
            {
                $_func = substr($this->m_Function, 3).";";
                $_func = Expression::evaluateExpression($_func, $formobj);
            }
            else
            {
                //$temp = ($this->m_FunctionType==null) ? "" : ",'".$this->m_FunctionType."'";
                //$_func = "SetOnElement('$name:$ehName'); $selectRecord CallFunction('" . $this->m_Function . "'$temp);";
                //$_func = "Openbiz.CallFunction('" . $this->m_Function . "'$temp);";
                $_func = Expression::evaluateExpression($this->m_Function, $formobj);
                $options = "{'type':'$this->m_FunctionType','target':'','evthdl':'$name:$ehName'}";
                $_func = "Openbiz.CallFunction('$_func',$options);";
            }
            $this->m_FormedFunction = $_func;
        }
        return $this->m_FormedFunction;
    }
getInvokeAction ()
Definition at line 756 of file Element.php.
References $m_FormedFunction, $m_Name, Expression\evaluateExpression(), BizSystem\objectFactory(), and parseFunction().
    {
        if ($this->m_FormedFunction)
            return $this->m_FormedFunction;
     $name = $this->_elemName;
        $ehName = $this->m_Name;
        $formobj = BizSystem::objectFactory()->getObject($this->_formName);
        if (!$this->m_FormedFunction)
        {
            // add direct URL support
            if ($this->m_URL)
                $_func = "loadPage('" . $this->m_URL . "');";
            else if (strpos($this->m_Function, "js:") === 0)
                $_func = substr($this->m_Function, 3).";";
            else
            {
                $temp = ($this->m_FunctionType==null) ? "" : ",'".$this->m_FunctionType."'";
                //$_func = "SetOnElement('$name:$ehName'); Openbiz.CallFunction('" . $this->m_Function . "'$temp);";
                list($funcName, $funcParams) = $this->parseFunction($this->m_Function);
                $funcParams = Expression::evaluateExpression($funcParams, $formobj);
                $action = "$name:$ehName";
                // TODO: encrypt paramString to add more security
                $_func = "Openbiz.invoke('$this->_formName','$action','$funcParams'$temp);";
            }
            //$_func = Expression::evaluateExpression($_func, $formobj);
            $this->m_FormedFunction = $_func;
        }
        return $this->m_FormedFunction;
    }
getTransKey ($name) protected
Definition at line 808 of file Element.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_FormName,intval(strrpos($this->m_FormName,'.'))+1);
     return strtoupper($shortFormName.'_'.$this->m_Name.'_'.$name);
    }
parseFunction ($funcString)
Definition at line 788 of file Element.php.
Referenced by getInvokeAction().
    {
        $pos = strpos($funcString, "(");
        $pos1 = strpos($funcString, ")");
        if ($pos>0 && $pos1>$pos)
        {
            $funcName = substr($funcString,0,$pos);
            $funcParams = substr($funcString,$pos+1,$pos1-$pos-1);
            return array($funcName, $funcParams);
        }
        return null;
    }
setFormName ($formName, $elemName)
Set form name that contain element and EventHandler
Parameters
string $formName
string $elemName
Returns
void
Definition at line 672 of file Element.php.
References $m_Function, and translate().
    {
        $this->_formName = $formName;
        $this->_elemName = $elemName;
        if (strpos($this->m_Function, "js:")===0)
            return;
        // if no class name, add default class name. i.e. NewRecord => ObjName.NewRecord
        if ($this->m_Function)
        {
            $pos_dot = strpos($this->m_Function, ".");
            $pos_lpt = strpos($this->m_Function, "(");
            if (!$pos_dot || $pos_lpt < $pos_dot)
                $this->m_Function = $this->_formName.".".$this->m_Function;
        }
        $this->translate(); // translate for multi-language support
    }
translate () protected
Definition at line 801 of file Element.php.
References getTransKey(), and I18n\t().
Referenced by setFormName().
    {
     $module = substr($this->_formName,0,intval(strpos($this->_formName,'.')));
     if (!empty($this->m_ContextMenu))
      $this->m_ContextMenu = I18n::t($this->m_ContextMenu, $this->getTransKey('ContextMenu'), $module);
    }
Field Documentation
$m_ContextMenu
Definition at line 632 of file Element.php.
$m_Event
Definition at line 627 of file Element.php.
$m_EventLogMsg
Definition at line 635 of file Element.php.
$m_FormedFunction
Definition at line 636 of file Element.php.
Referenced by getFormedFunction(), and getInvokeAction().
$m_Function
Definition at line 628 of file Element.php.
Referenced by __construct(), and setFormName().
$m_FunctionType
Definition at line 629 of file Element.php.
$m_Name
Definition at line 626 of file Element.php.
Referenced by getFormedFunction(), and getInvokeAction().
$m_Parameter
Definition at line 634 of file Element.php.
$m_PostAction
Definition at line 630 of file Element.php.
$m_RedirectPage
Definition at line 633 of file Element.php.
$m_ShortcutKey
Definition at line 631 of file Element.php.
$m_URL
Definition at line 641 of file Element.php.