Openbiz Framework API: SessionContext Class Reference
SessionContext Class Reference
Public Member Functions
__construct ()
cleanObj ($objName, $stateful=false)
clearSessionObjects ($keepObjects=false)
clearVar ($varName)
destroy ()
getNamespace ()
getObjVar ($objName, $varName, &$value, $stateful=false)
getVar ($varName)
getViewHistory ($formName)
isTimeout ()
isUserValid ()
mergeVar ($varName, $value)
retrieveSessionObjects ()
saveJSONArray ($jsonValue, $jsonName=NULL)
saveSessionObjects ()
setObjVar ($objName, $varName, &$value, $stateful=false)
setVar ($varName, $value)
setViewHistory ($formName, $historyInfo)
varExists ($varName)
Protected Attributes
$_lastAccessTime
$_prevViewObjNames
$_sessObjArr
$_statefulSessObjArr
$_timeOut
$_viewHistory
Detailed Description
Definition at line 34 of file SessionContext.php.
Constructor & Destructor Documentation
__construct ()
Constructor of SessionContext, init session and set session file path
Returns
void
Definition at line 48 of file SessionContext.php.
References TIMEOUT.
    {
        // get session save handler MC or DB
        if (defined("SESSION_HANDLER") && SESSION_HANDLER != "" && defined('USE_CUSTOM_SESSION_HANDLER') && USE_CUSTOM_SESSION_HANDLER ==true) {
            include_once SESSION_HANDLER.".php";
        }
        else {
         if(!file_exists(SESSION_PATH)){
          @mkdir(SESSION_PATH,0777,true);
         }
            // default is file session
            if (defined('SESSION_PATH') && is_writable(SESSION_PATH))
                session_save_path(SESSION_PATH);
            // we cannot write in the session save path; aborting
            if(!is_writable(session_save_path()))
                trigger_error("Unable to write in the session save path [".session_save_path()."]", E_USER_ERROR);
        }
        ini_set('session.gc_probability', 1);   // force gc
        ini_set('session.gc_divisor', 100);
        if (defined('TIMEOUT') && TIMEOUT > 0)
            ini_set("session.gc_maxlifetime", TIMEOUT);
        else
            ini_set("session.gc_maxlifetime", 21600); // 6 hours
        if (!defined('CLI') || CLI == 0) {
            if(isset($_REQUEST['cubi_sess_id'])){
                session_id($_REQUEST['cubi_sess_id']);
            }
            session_start();
        }
        // record access time
        $curTime = time();
        if (isset($_SESSION["LastAccessTime"]))
            $this->_lastAccessTime = $_SESSION["LastAccessTime"];
        else
            $this->_lastAccessTime = $curTime;
        $_SESSION["LastAccessTime"] =$curTime;
        // see if timeout
        $this->_timeOut = false;
        if ((TIMEOUT > 0) && (($curTime - $this->_lastAccessTime) > TIMEOUT))
            $this->_timeOut = true;
    }
Member Function Documentation
cleanObj ($objName, $stateful = false)
Clean Object
Parameters
string $objName object name
boolean $stateful
Returns
void
Definition at line 193 of file SessionContext.php.
References getNamespace().
    {
     if(preg_match('/\./si',$objName)){
         $objName = $this->getNamespace().'#'.$objName;
     }
        if (!$stateful)
            unset($this->_sessObjArr[$objName]);
        else
            unset($this->_statefulSessObjArr[$objName]);
    }
clearSessionObjects ($keepObjects = false)
Clear session variables of all stateful objects
Parameters
boolean $keepObjects
Returns
void
Definition at line 294 of file SessionContext.php.
    {
        if ($keepObjects == false)
        {
            unset($this->_sessObjArr);
            $this->_sessObjArr = array();
        }
        else // add previous view's session object names in to a map
        {
            if (isset($this->_sessObjArr))
            {
                foreach($this->_sessObjArr as $objName=>$sessobj)
                {
                    //echo "save sess $objName <br/>";
                    $this->_prevViewObjNames[$objName] = 1;
                }
            }
        }
    }
clearVar ($varName)
Clear/Unset single session variable NOTE: NYU - not yet used
Parameters
string $varName
Returns
void
Definition at line 139 of file SessionContext.php.
    {
        unset($_SESSION[$varName]);
    }
destroy ()
Destroy/free all session data of the current session
Returns
void
Definition at line 373 of file SessionContext.php.
    {
        unset($this->_viewHistory);
        unset($this->_sessObjArr);
        unset($this->_statefulSessObjArr);
        session_destroy();
    }
getNamespace ()
Definition at line 156 of file SessionContext.php.
References BizSystem\instance().
Referenced by cleanObj(), getObjVar(), and setObjVar().
    {
        $view = BizSystem::instance()->getCurrentViewName();
        if ($view)
            $namespace = $view;
        else
            $namespace = 'DEFAULT_NS';
        return $namespace;
    }
getObjVar ($objName, $varName, & $value, $stateful = false)
Get single session variable of a stateful object
Parameters
string $objName - object name
string $varName - vaiable name
mixed $value - reference of the value (in/out)
boolean $stateful - is stateful?
Returns
void
Definition at line 213 of file SessionContext.php.
References getNamespace().
    {
     if(preg_match('/\./si',$objName)){
         $objName = $this->getNamespace().'#'.$objName;
     }
        if (!$stateful)
        {
            if (!$this->_sessObjArr)
                return;
            if (isset($this->_sessObjArr[$objName][$varName]))
                $value = $this->_sessObjArr[$objName][$varName];
        }
        else
        {
            if (!$this->_statefulSessObjArr)
                return;
            if (isset($this->_statefulSessObjArr[$objName][$varName]))
                $value = $this->_statefulSessObjArr[$objName][$varName];
        }
    }
getVar ($varName)
Get single session variable
Parameters
string $varName name of session variable
Returns
string
Definition at line 125 of file SessionContext.php.
Referenced by isUserValid(), and retrieveSessionObjects().
    {
        if (!isset($_SESSION[$varName]))
            return "";
        return $_SESSION[$varName];
    }
getViewHistory ($formName)
Get view history data of given BizForm/EasyForm from saved in session file
Parameters
string $formName - name of BizForm/EasyForm
Returns
array - view history data represented by an associated array
Definition at line 344 of file SessionContext.php.
References BizSystem\instance().
    {
        $view = BizSystem::instance()->getCurrentViewName();
        $view_form = $formName; //$view."_".$formname;
        return $this->_viewHistory[$view_form];
    }
isTimeout ()
Check if current session is timeout
Returns
boolean
Definition at line 403 of file SessionContext.php.
References $_timeOut.
    {
        return $this->_timeOut;
    }
isUserValid ()
Check if user logged in or not NOTE: NYU - not yet used
Returns
boolean
Definition at line 388 of file SessionContext.php.
References getVar().
    {
        if (CHECKUSER == "N")
            return true;
        if ($this->getVar("UserId") != "")
            return true;
        else
            return false;
    }
mergeVar ($varName, $value)
Definition at line 107 of file SessionContext.php.
    {
        $var = $_SESSION[$varName];
        if(is_array($var)){
         foreach($value as $key=>$value){
          $var[$key]=$value;
         }
         $_SESSION[$varName] = $var;
        }else{
         $_SESSION[$varName] = $value;
        }
    }
retrieveSessionObjects ()
Retrieve/Get session variables of all stateful objects from sessionid_obj file
Returns
void
Definition at line 272 of file SessionContext.php.
References getVar(), OB_STATEFUL_DATA_SESSION_INDEX, and OB_TRANSIENT_DATA_SESSION_INDEX.
    {
        $this->_sessObjArr = $this->getVar(OB_TRANSIENT_DATA_SESSION_INDEX);
        $this->_statefulSessObjArr = $this->getVar(OB_STATEFUL_DATA_SESSION_INDEX);
        if (!is_array($this->_sessObjArr))
            $this->_sessObjArr = array();
        if (!is_array($this->_statefulSessObjArr))
            $this->_statefulSessObjArr = array();
        $this->_viewHistory = array_key_exists('ViewHist', $this->_sessObjArr)
            ? $this->_sessObjArr["ViewHist"]
            : NULL;
        return TRUE;
    }
saveJSONArray ($jsonValue, $jsonName = NULL)
Save a JSON array in session
Parameters
string $jsonValue
string $jsonName
Returns
void
Definition at line 321 of file SessionContext.php.
References setVar().
    {
        $jsonArray = json_decode($jsonValue);
        if((bool)$jsonName)
        { //If I want save all array in session I send the name of the array in session
            $this->setVar($jsonName, $jsonArray);
        }
        else
        {//I save each value in session
            foreach($jsonArray as $varName=>$value)
            {
                $this->setVar($varName, $value);
            }
        }
    }
saveSessionObjects ()
Save session variables of all stateful objects into sessionid_obj file
Returns
void
Definition at line 239 of file SessionContext.php.
References $_viewHistory, BizSystem\log(), OB_STATEFUL_DATA_SESSION_INDEX, OB_TRANSIENT_DATA_SESSION_INDEX, BizSystem\objectFactory(), and setVar().
    {
        // loop all objects (bizview, bizform, bizdataobj) collect their session vars
        $allobjs = BizSystem::objectFactory()->getAllObjects();
        foreach ($allobjs as $obj)
        {
            if (method_exists($obj, "SetSessionVars"))
            {
                //after calling $obj->setSessionVars SessObjArr and StatefulSessObjArr are filled
                $obj->setSessionVars($this);
            }
            // if previous view's object is used in current view, don't discard its session data
            if (isset($obj->m_Name) && key_exists($obj->m_Name, $this->_prevViewObjNames)) {
                unset($this->_prevViewObjNames[$obj->m_Name]);
                BizSystem::log(LOG_ERR, "SESSION", "unset ".$obj->m_Name);
            }
        }
        // discard useless previous view's session objects
        //foreach($this->_prevViewObjNames as $objName=>$tmp)
        //    unset($this->_sessObjArr[$objName]);
        $this->_sessObjArr["ViewHist"] = $this->_viewHistory;
        $this->setVar(OB_TRANSIENT_DATA_SESSION_INDEX, $this->_sessObjArr);
        $this->setVar(OB_STATEFUL_DATA_SESSION_INDEX, $this->_statefulSessObjArr);
    }
setObjVar ($objName, $varName, & $value, $stateful = false)
Set single session variable of a stateful object
Parameters
string $objName - object name
string $varName - vaiable name
mixed $value - reference of the value (in/out)
boolean $stateful - is stateful?
Returns
void
Definition at line 175 of file SessionContext.php.
References getNamespace().
    {
     if(preg_match('/\./si',$objName)){
         $objName = $this->getNamespace().'#'.$objName;
     }
        if (!$stateful)
            $this->_sessObjArr[$objName][$varName] = $value;
        else
            $this->_statefulSessObjArr[$objName][$varName] = $value;
    }
setVar ($varName, $value)
Set single session variable
Parameters
string $varName
mixed $value
Returns
void
Definition at line 102 of file SessionContext.php.
Referenced by saveJSONArray(), and saveSessionObjects().
    {
        $_SESSION[$varName] = $value;
    }
setViewHistory ($formName, $historyInfo)
Set view history data of given bizform into session file
Parameters
string $formName - name of bizform
array $historyInfo - view history data represented by an associated array
Returns
void
Definition at line 358 of file SessionContext.php.
References BizSystem\instance().
    {
        $view = BizSystem::instance()->getCurrentViewName();
        $view_form = $formName; //$view."_".$formname;
        if (!$historyInfo)
            unset($this->_viewHistory[$view_form]);
        else
            $this->_viewHistory[$view_form] = $historyInfo;
    }
varExists ($varName)
Is variable exist in the session
Parameters
string $varName variable name that checked
Returns
boolean TRUE if the var exists in the session, otherwise FALSE
Definition at line 150 of file SessionContext.php.
    {
        $exists =  (array_key_exists($varName, $_SESSION)) ? TRUE : FALSE;
        return $exists;
    }
Field Documentation
$_lastAccessTime protected
Definition at line 36 of file SessionContext.php.
$_prevViewObjNames protected
Definition at line 41 of file SessionContext.php.
$_sessObjArr protected
Definition at line 38 of file SessionContext.php.
$_statefulSessObjArr protected
Definition at line 39 of file SessionContext.php.
$_timeOut protected
Definition at line 37 of file SessionContext.php.
Referenced by isTimeout().
$_viewHistory protected
Definition at line 40 of file SessionContext.php.
Referenced by saveSessionObjects().