Openbiz Framework API: ColorPicker Class Reference
ColorPicker Class Reference
Public Member Functions
getFunctionByEvent ($event_name)
render ()
Public Member Functions inherited from InputText
render ()
Public Member Functions inherited from InputElement
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_Config
$m_Mode
Protected Member Functions
readMetaData (&$xmlArr)
Protected Member Functions inherited from InputText
readMetaData (&$xmlArr)
Protected Member Functions inherited from InputElement
addSCKeyScript ()
getEnabled ()
getRequired ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 18 of file ColorPicker.php.
Member Function Documentation
getFunctionByEvent ($event_name)
Definition at line 151 of file ColorPicker.php.
References MetaObject\$m_Name, and Element\getFormObj().
{
        $name = $this->m_Name;
        // loop through the event handlers
        $func = "";
        if ($this->m_EventHandlers == null)
            return null;
        $formobj = $this->getFormObj();
        foreach($this->m_EventHandlers as $eventHandler){
         if($eventHandler->m_Event==$event_name){
          break;
         }
        }
        $ehName = $eventHandler->m_Name;
        $event = $eventHandler->m_Event;
        $type = $eventHandler->m_FunctionType;
        if (!$event) return;
        if($events[$event]!=""){
           $events[$event]=array_merge(array($events[$event]),array($eventHandler->getFormedFunction()));
        }else{
           $events[$event]=$eventHandler->getFormedFunction();
        }
  foreach ($events as $event=>$function){
   if(is_array($function)){
    foreach($function as $f){
     $function_str.=$f.";";
    }
    $func .= $function_str;
   }else{
    $func .= $function;
   }
  }
        return $func;
 }
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 27 of file ColorPicker.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_cssClass = isset($xmlArr["ATTRIBUTES"]["CSSCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSCLASS"] : "input_text_s";
  $this->m_cssErrorClass = isset($xmlArr["ATTRIBUTES"]["CSSERRORCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSERRORCLASS"] : $this->m_cssClass."_error";
  $this->m_cssFocusClass = isset($xmlArr["ATTRIBUTES"]["CSSFOCUSCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSFOCUSCLASS"] : $this->m_cssClass."_focus";
        $this->m_Mode = isset($xmlArr["ATTRIBUTES"]["MODE"]) ? $xmlArr["ATTRIBUTES"]["MODE"] : null;
        $this->m_Config = isset($xmlArr["ATTRIBUTES"]["CONFIG"]) ? $xmlArr["ATTRIBUTES"]["CONFIG"] : null;
    }
render ()
Implements iUIControl.
Definition at line 37 of file ColorPicker.php.
References MetaObject\$m_Name, Element\$m_Value, BizSystem\clientProxy(), Element\getDefaultValue(), InputElement\getEnabled(), Element\getFunction(), Element\getStyle(), and Element\getText().
{
  BizSystem::clientProxy()->includeColorPickerScripts();
  if($this->m_Value!=null){
      $value = $this->m_Value;
     }else{
      $value = $this->getText();
     }
        $disabledStr = ($this->getEnabled() == "N") ? "READONLY=\"true\"" : "";
        $style = $this->getStyle();
        $func = $this->getFunction();
        $func_org = $func;
        $formobj = $this->GetFormObj();
     if($formobj->m_Errors[$this->m_Name]){
   $func .= "onchange=\"this.className='$this->m_cssClass'\"";
  }else{
   $func .= "onfocus=\"this.className='$this->m_cssFocusClass'\" onblur=\"this.className='$this->m_cssClass'\"";
  }
        $elementName = $this->m_Name;
        $elementTrigger=array();
  if($value){
   $default_color = "color: '#$value',";
  }else{
   $default_color = "";
   $value=$this->getDefaultValue() ? $this->getDefaultValue() : "";
  }
  switch(strtolower($this->m_Mode)){
   case "viewonly":
    $sHTML .= "<span id=\"colorpreview_$elementName\" $func_org class=\"colorpicker_preview\" style=\"background-color:#$value;width:98px;\" ></span>";
    $elementTrigger = array();
    break;
   case "widget":
    $config = "
       onShow: function (colpkr) {
        if(\$j(colpkr).css('display')=='none'){
         \$j(colpkr).fadeIn(300);
        }
        return false;
       },
       onHide: function (colpkr) {
        \$j(colpkr).fadeOut(300);
        return false;
       },
       onSubmit: function(hsb, hex, rgb, el) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       },
       onChange: function (hsb, hex, rgb) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       }
       ";
    $sHTML .= "<span id=\"colorpreview_$elementName\" class=\"colorpicker_preview\" style=\"background-color:#$value;\" $func ></span>";
    $sHTML .= "<INPUT NAME=\"" . $this->m_Name . "\" ID=\"" . $this->m_Name ."\" VALUE=\"" . $value . "\" type=\"hidden\" />";
    $elementTrigger = array("colorpreview_$elementName");
    break;
   case "flat":
    $config = "flat: true,
       onSubmit: function(hsb, hex, rgb, el) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       },
       onChange: function (hsb, hex, rgb) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       }
    ";
    $sHTML .= "<span id=\"colorpreview_$elementName\" class=\"colorpicker_preview\" style=\"background-color:#$value;\" ></span>";
    $sHTML .= "<INPUT NAME=\"" . $this->m_Name . "\" ID=\"" . $this->m_Name ."\" VALUE=\"" . $value . "\" $disabledStr $this->m_HTMLAttr $style $func />";
    $sHTML .= "<div id=\"colorpicker_$elementName\" style=\"float:left\"></div>";
    $elementTrigger = array("colorpicker_".$elementName);
    break;
   default:
    $config = "
       onShow: function (colpkr) {
        if(\$j(colpkr).css('display')=='none'){
         \$j(colpkr).fadeIn(300);
        }
        return false;
       },
       onHide: function (colpkr) {
        \$j(colpkr).fadeOut(300);
        return false;
       },
       onSubmit: function(hsb, hex, rgb, el) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       },
       onChange: function (hsb, hex, rgb) {
        $('$this->m_Name').value=hex;
        \$j('#colorpreview_$this->m_Name').css('backgroundColor', '#' + hex);
       }
       ";
    $sHTML .= "<span id=\"colorpreview_$elementName\" class=\"colorpicker_preview\" style=\"background-color:#$value;\" ></span>";
    $sHTML .= "<INPUT NAME=\"" . $this->m_Name . "\" ID=\"" . $this->m_Name ."\" VALUE=\"" . $value . "\" $disabledStr $this->m_HTMLAttr $style $func />";
    $elementTrigger = array($elementName,"colorpreview_$elementName");
    break;
  }
  if($this->m_Config){
   $config .= ",".$this->m_Config;
  }
  $config = "{".$default_color.$config."}";
  foreach($elementTrigger as $trigger){
   $sHTML .= "<script>\$j('#$trigger').ColorPicker($config);</script>\n";
  }
        return $sHTML;
 }
Field Documentation
$m_Config
Definition at line 19 of file ColorPicker.php.
$m_Mode
Definition at line 20 of file ColorPicker.php.