Openbiz Framework API: chartService Class Reference
chartService Class Reference
Public Member Functions
__construct (&$xmlArr)
& getPlotData (&$bizObj, $fields, $labelField)
pieGraphRender (&$bizObj, &$xmlArr)
Public render ($objName)
renderPiePlot (&$data, &$xmlArr)
renderXYPlot (&$data, &$xmlArr)
xyGraphRender (&$bizObj, &$xmlArr)
Data Fields
$m_PlotList
Detailed Description
Definition at line 25 of file chartService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize chartService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 40 of file chartService.php.
    {
    }
Member Function Documentation
& getPlotData (& $bizObj, $fields, $labelField)
Get plot data array
Parameters
BizObj $bizObj object reference of bizobj
array $fields list of bizobj fields
array $labelField label field of bizobj
Returns
array reference of the array [field][index]
Definition at line 94 of file chartService.php.
Referenced by pieGraphRender(), and xyGraphRender().
    {
        $oldCacheMode = $bizObj->GetCacheMode();
        $bizObj->SetCacheMode(0);    // turn off cache mode, not affect the current cache
        $bizObj->runSearch(-1);  // don't use page search
        while (1)
        {
            $recArray = $bizObj->GetRecord(1);
            if (!$recArray) break;
            $bizObj->UnformatInputRecArr($recArray);
            foreach($fields as $fld)
                $recMatrix[$fld][] = $recArray[$fld];   // get data without format
            $recMatrix[$labelField][] = $recArray[$labelField];   // get symbol with format
        }
        $bizObj->SetCacheMode($oldCacheMode);
        return $recMatrix;
    }
pieGraphRender (& $bizObj, & $xmlArr)
draw the Pie type graph (can have 1 pie plot)
Parameters
BizObj $bizObj object reference of bizobj
array $xmlArr xml array reference
Returns
void
Definition at line 188 of file chartService.php.
References getPlotData(), and renderPiePlot().
Referenced by render().
    {
        include_once (JPGRAPH_DIR.'/jpgraph.php');
        include_once (JPGRAPH_DIR.'/jpgraph_pie.php');
        include_once (JPGRAPH_DIR.'/jpgraph_pie3d.php');
        $graph = new PieGraph($xmlArr["ATTRIBUTES"]["WIDTH"],$xmlArr["ATTRIBUTES"]["HEIGHT"]);
        //$graph->SetAntiAliasing();
        // get the data set - only support one data
        $fields[0] = $xmlArr['DATASET']['DATAPIE']["ATTRIBUTES"]["FIELD"];
        $legendFld = $xmlArr['DATASET']['DATAPIE']["ATTRIBUTES"]["LEGENDFIELD"];
        $recArray = &$this->getPlotData($bizObj, $fields, $legendFld);
        $chartData = $xmlArr['DATASET']['DATAPIE'];
        $plot = $this->renderPiePlot($recArray[$fields[0]], $chartData);
        $plot->SetLegends($recArray[$legendFld]);
        $graph->Add($plot);
        // render titles
        $graph->title->Set($xmlArr['TITLE']['ATTRIBUTES']['CAPTION']);
        $this->_drawString($graph->title,$xmlArr['TITLE']['ATTRIBUTES']['FONT'],$xmlArr['TITLE']['ATTRIBUTES']['COLOR']);
        // render legend
        $this->_drawLegend($graph->legend,$xmlArr['LEGEND']['ATTRIBUTES']['POSITION'],
                $xmlArr['LEGEND']['ATTRIBUTES']['LAYOUT'], $xmlArr['LEGEND']['ATTRIBUTES']['FONT'],
                $xmlArr['LEGEND']['ATTRIBUTES']['COLOR'], $xmlArr['LEGEND']['ATTRIBUTES']['FILLCOLOR']);
        $graph->Stroke();
    }
Public render ($objName)
Render the chart output
Parameters
string $objName object name which is the bizform name
Returns
void
Definition at line 50 of file chartService.php.
References BizSystem\clientProxy(), BizSystem\getObject(), BizSystem\getXmlArray(), pieGraphRender(), and xyGraphRender().
    {
        // get the value of the control that issues the call
        $chartName = BizSystem::clientProxy()->getFormInputs("__this");
        // get the current UI bizobj
        $formObj = BizSystem::getObject($objName);    // get the existing bizform object
        $bizDataObj = $formObj->getDataObj();
        // get chart config xml file
        $chartXmlFile = BizSystem::GetXmlFileWithPath($objName."_chart");
        $xmlArr = BizSystem::getXmlArray($chartXmlFile);
        ob_clean();
        // get the chart section from config xml file
        foreach($xmlArr["BIZFORM_CHART"]["CHARTLIST"]["CHART"] as $chart)
        {
            if (count($xmlArr["BIZFORM_CHART"]["CHARTLIST"]["CHART"]) == 1)
                $chart = $xmlArr["BIZFORM_CHART"]["CHARTLIST"]["CHART"];
            // try to match the chartName, if no chartName given, always draw the first chart defined in xml file
            if (($chartName && $chart["ATTRIBUTES"]["NAME"] == $chartName) || !$chartName)
            {
                if ($chart["ATTRIBUTES"]["GRAPHTYPE"] == 'XY')
                {
                    $this->xyGraphRender($bizDataObj, $chart);
                    break;
                }
                if ($chart["ATTRIBUTES"]["GRAPHTYPE"] == 'Pie')
                {
                    $this->pieGraphRender($bizDataObj, $chart);
                    break;
                }
            }
        }
    }
renderPiePlot (& $data, & $xmlArr)
chartService::renderPiePlot() - draw the Pie type plot
Parameters
array $data plot data array reference
array $xmlArr xml array reference
Returns
object refernce Pie plot object reference
Definition at line 293 of file chartService.php.
Referenced by pieGraphRender().
    {
        $id = $xmlArr['ATTRIBUTES']['ID'];
        $field = $xmlArr['ATTRIBUTES']['FIELD'];
        $chartType = $xmlArr['ATTRIBUTES']['CHARTTYPE'];
        $size = $xmlArr['ATTRIBUTES']['SIZE'];
        $center = $xmlArr['ATTRIBUTES']['CENTER'];
        $height = $xmlArr['ATTRIBUTES']['HEIGHT'];
        $angle = $xmlArr['ATTRIBUTES']['ANGLE'];
        $labelPos = $xmlArr['ATTRIBUTES']['LABELPOS'];
        $legendField = $xmlArr['ATTRIBUTES']['LAGENDFIELD'];
        if ($chartType == "Pie")
        {
            $plot = new PiePlot($data);
            $plot->SetLabelPos($labelPos);
        }
        else if ($chartType == "Pie3D")
        {
            $plot = new PiePlot3D($data);
            $plot->SetHeight($height);
            $plot->SetAngle($angle);
        }
        list($c1, $c2) = explode(',', $center);
        $plot->SetCenter($c1,$c2);
        $plot->SetSize($size);
        $this->_drawString($plot->value,$xmlArr['VALUE']['ATTRIBUTES']['FONT'],$xmlArr['VALUE']['ATTRIBUTES']['COLOR']);
        return $plot;
    }
renderXYPlot (& $data, & $xmlArr)
Draw the XY type plot
Parameters
array $data plot data array reference
array $xmlArr xml array reference
Returns
object refernce XY plot object reference
Definition at line 226 of file chartService.php.
Referenced by xyGraphRender().
    {
        $id = $xmlArr['ATTRIBUTES']['ID'];
        $field = $xmlArr['ATTRIBUTES']['FIELD'];
        $chartType = $xmlArr['ATTRIBUTES']['CHARTTYPE'];
        $pointType = $xmlArr['ATTRIBUTES']['POINTTYPE'];
        $weight = $xmlArr['ATTRIBUTES']['WEIGHT'];
        $color = $xmlArr['ATTRIBUTES']['COLOR'];
        $fillColor = $xmlArr['ATTRIBUTES']['FILLCOLOR'];
        $showVal = $xmlArr['ATTRIBUTES']['SHOWVALUE'];
        $legend = $xmlArr['ATTRIBUTES']['LEGENDFIELD'];
        $visible = $xmlArr['ATTRIBUTES']['VISIBLE'];
        if ($chartType == 'Line' or $chartType == 'Bar')
        {
            if ($chartType == 'Line')
            {
                include_once (JPGRAPH_DIR.'/jpgraph_line.php');
                $plot = new LinePlot($data);
                $this->_drawMark($plot->mark,
                        $xmlArr['POINTMARK']['ATTRIBUTES']['TYPE'], $xmlArr['POINTMARK']['ATTRIBUTES']['COLOR'],
                        $xmlArr['POINTMARK']['ATTRIBUTES']['FILLCOLOR'], $xmlArr['POINTMARK']['ATTRIBUTES']['SIZE']);
                $plot->SetBarCenter();
                $plot->SetCenter();
            }
            else if ($chartType == 'Bar')
            {
                include_once (JPGRAPH_DIR.'/jpgraph_bar.php');
                $plot = new BarPlot($data);
                $plot->SetAlign('center');
            }
            if ($color) $plot->SetColor($color);
            if ($fillColor) $plot->SetFillColor($fillColor);
            if ($weight) $plot->SetWeight($weight);
            if ($showVal == 1) $plot->value->Show();
            if ($legend) $plot->SetLegend($legend);
            $this->_drawString($plot->value,$xmlArr['VALUE']['ATTRIBUTES']['FONT'],$xmlArr['VALUE']['ATTRIBUTES']['COLOR']);
        }
        if ($chartType == 'GroupBar' or $chartType == 'AccBar')
        {
            $children = $xmlArr['ATTRIBUTES']['CHILDREN'];
            $childList = explode(",",$children);
            foreach($childList as $child)
            {
                $childPlotList[] = $this->m_PlotList[$child];
            }
            if ($chartType == 'GroupBar')
                $plot = new GroupBarPlot($childPlotList);
            else if ($chartType == 'AccBar')
                $plot = new AccBarPlot($childPlotList);
        }
        $this->m_PlotList[$id] = $plot;
        if ($visible == 1)
            return $plot;
        return null;
    }
xyGraphRender (& $bizObj, & $xmlArr)
Draw the XY type graph (can have > 1 plots)
Parameters
BizObj $bizObj object reference of bizobj
array $xmlArr xml array reference
Returns
void
Definition at line 120 of file chartService.php.
References getPlotData(), and renderXYPlot().
Referenced by render().
    {
        include_once (JPGRAPH_DIR.'/jpgraph.php');
        $graph = new Graph($xmlArr["ATTRIBUTES"]["WIDTH"],$xmlArr["ATTRIBUTES"]["HEIGHT"],"auto");
        //$graph->img->SetAntiAliasing();
        $graph->SetScale("textlin");
        $graph->yaxis->scale->SetGrace(10);
        list($m1, $m2, $m3, $m4) = explode(',', $xmlArr["ATTRIBUTES"]["MARGIN"]);
        $graph->img->SetMargin($m1, $m2, $m3, $m4);
        // get the data set
        foreach($xmlArr['DATASET']['DATA'] as $dtmp)
        {
            if ($xmlArr['DATASET']['DATA']['ATTRIBUTES'])
                $dtmp = $xmlArr['DATASET']['DATA'];
            $fieldName = $dtmp["ATTRIBUTES"]["FIELD"];
            if ($fieldName)
                $fields[$fieldName] = $fieldName;
        }
        $labelFld = $xmlArr['XAXIS']['ATTRIBUTES']['LABELFIELD'];
        $recArray = &$this->getPlotData($bizObj, $fields, $labelFld);
        $i = 0;
        foreach($xmlArr['DATASET']['DATA'] as $dtmp)
        {
            if ($xmlArr['DATASET']['DATA']['ATTRIBUTES'])
                $dtmp = $xmlArr['DATASET']['DATA'];
            $data = $recArray[$dtmp["ATTRIBUTES"]["FIELD"]];
            $plot = $this->renderXYPlot($data, $dtmp);
            if ($plot)
                $graph->Add($plot);
            $i++;
        }
        // render titles
        $graph->title->Set($xmlArr['TITLE']['ATTRIBUTES']['CAPTION']);
        $this->_drawString($graph->title,$xmlArr['TITLE']['ATTRIBUTES']['FONT'],$xmlArr['TITLE']['ATTRIBUTES']['COLOR']);
        // render xaxis
        $this->_drawAxis($graph->xaxis, $recArray[$labelFld],
                $xmlArr['XAXIS']['ATTRIBUTES']['FONT'], $xmlArr['XAXIS']['ATTRIBUTES']['COLOR'],
                $xmlArr['XAXIS']['ATTRIBUTES']['LABELANGLE'], $xmlArr['XAXIS']['ATTRIBUTES']['TITLE'],
                $xmlArr['XAXIS']['ATTRIBUTES']['TITLEFONT'], $xmlArr['XAXIS']['ATTRIBUTES']['TITLECOLOR'],
                $xmlArr['XAXIS']['ATTRIBUTES']['TITLEMARGIN']);
        // render yaxis
        $this->_drawAxis($graph->yaxis, null,
                $xmlArr['YAXIS']['ATTRIBUTES']['FONT'], $xmlArr['YAXIS']['ATTRIBUTES']['COLOR'],
                $xmlArr['YAXIS']['ATTRIBUTES']['LABELANGLE'], $xmlArr['YAXIS']['ATTRIBUTES']['TITLE'],
                $xmlArr['YAXIS']['ATTRIBUTES']['TITLEFONT'], $xmlArr['YAXIS']['ATTRIBUTES']['TITLECOLOR'],
                $xmlArr['YAXIS']['ATTRIBUTES']['TITLEMARGIN']);
        // render legend
        $this->_drawLegend($graph->legend,$xmlArr['LAGEND']['ATTRIBUTES']['POSITION'],
                $xmlArr['LAGEND']['ATTRIBUTES']['LAYOUT'], $xmlArr['legend']['ATTRIBUTES']['FONT'],
                $xmlArr['LAGEND']['ATTRIBUTES']['COLOR'], $xmlArr['legend']['ATTRIBUTES']['FILLCOLOR']);
        $graph->Stroke();
    }
Field Documentation
$m_PlotList
Definition at line 32 of file chartService.php.