Openbiz Framework API: ObjectFactory Class Reference
ObjectFactory Class Reference
Public Member Functions
__construct ()
__destruct ()
createObject ($objName, &$xmlArr=null)
getAllObjects ()
getObject ($objectName, $new=0)
setObject ($objName, $obj)
Protected Member Functions
constructObject ($objName, &$xmlArr=null)
Protected Attributes
$_objsRefMap
Detailed Description
Definition at line 26 of file ObjectFactory.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 34 of file ObjectFactory.php.
    {
    }
__destruct ()
Definition at line 38 of file ObjectFactory.php.
    {
    }
Member Function Documentation
constructObject ($objName, & $xmlArr = null) protected
Construct an instance of an object
Parameters
string $objName object name
array $xmlArr xml array
Returns
object the instance of the object
Definition at line 102 of file ObjectFactory.php.
References BizClassLoader\getLibFileWithPath(), and BizSystem\getXmlArray().
Referenced by createObject(), and getObject().
    {
        if (!$xmlArr)
        {
            $xmlFile = BizSystem::GetXmlFileWithPath ($objName);
            if (!$xmlFile)
            {
                $dotPos = strrpos($objName, ".");
                $package = $dotPos>0 ? substr($objName, 0, $dotPos) : null;
                $class = $dotPos>0 ? substr($objName, $dotPos+1) : $objName;
            }
            else
                $xmlArr = BizSystem::getXmlArray($xmlFile);
        }
        if ($xmlArr)
        {
            $keys = array_keys($xmlArr);
            $root = $keys[0];
            // add by mr_a_ton , atrubut name must match with object name
            $dotPos = strrpos($objName, ".");
            $shortObjectName  = $dotPos > 0 ? substr($objName, $dotPos+1) : $objName;
            if ($xmlArr[$root]["ATTRIBUTES"]["NAME"]=="")
            {
                $xmlArr[$root]["ATTRIBUTES"]["NAME"]=$shortObjectName;
            }
            else
            {
                if ($shortObjectName != $xmlArr[$root]["ATTRIBUTES"]["NAME"] )
                {
                    trigger_error("Metadata file parsing error for object $objName. Name attribut [".$xmlArr[$root]["ATTRIBUTES"]["NAME"]."] not same with object name. Please double check your metadata xml file again.", E_USER_ERROR);
                }
            }
            //$package = $xmlArr[$root]["ATTRIBUTES"]["PACKAGE"];
            $class = $xmlArr[$root]["ATTRIBUTES"]["CLASS"];
            // if class has package name as prefix, change the package to the prefix
            $dotPos = strrpos($class, ".");
            $classPrefix = $dotPos>0 ? substr($class, 0, $dotPos) : null;
            $classPackage = $classPrefix ? $classPrefix : null;
            if ($classPrefix) $class = substr($class, $dotPos+1);
            // set object package
            $dotPos = strrpos($objName, ".");
            $package = $dotPos>0 ? substr($objName, 0, $dotPos) : null;
            if (strpos($package, '@') === 0) $package = substr($package, 1);
            if (!$classPackage) $classPackage = $package;
            $xmlArr[$root]["ATTRIBUTES"]["PACKAGE"] = $package;
        }
        if ($class == "BizObj")  // convert BizObj to BizDataObj, support <1.2 version
            $class = "BizDataObj";
        if (!class_exists($class, false))
        {
            $classFile= BizClassLoader::getLibFileWithPath($class, $classPackage);
            if (!$classFile)
            {
                if ($package)
                    trigger_error("Cannot find the class with name as $package.$class", E_USER_ERROR);
                else
                    trigger_error("Cannot find the class with name as $class of $objName", E_USER_ERROR);
                exit();
            }
            include_once($classFile);
        }
        if (class_exists($class, false))
        {
            //if ($objName == "collab.calendar.form.EventListForm") { print_r($xmlArr); exit; }
            $obj_ref = new $class($xmlArr);
            if ($obj_ref)
            {
                return $obj_ref;
            }
        }
        else{
         if(function_exists("ioncube_read_file"))
   {
    $data = ioncube_read_file($classFile);
    if (!strpos($data,"ionCube Loader")) {
     trigger_error("Cannot find the class with name as $class in $classFile", E_USER_ERROR);
    }else{
    }
   }
        }
        return null;
    }
createObject ($objName, & $xmlArr = null)
Create a new metadata based object instance
Parameters
string $objName name of object will be create
array $xmlArr propery array of object
Returns
object
Definition at line 74 of file ObjectFactory.php.
References constructObject().
    {
        $obj = $this->constructObject($objName, $xmlArr);
        return $obj;
    }
getAllObjects ()
Get all object from the internal object array (object cache)
Returns
array array of object
Definition at line 90 of file ObjectFactory.php.
References $_objsRefMap.
    {
        return $this->_objsRefMap;
    }
getObject ($objectName, $new = 0)
Get a metadata based object instance. It returns the instance the internal object map or create a new one and save it in the map.
Parameters
string $objectName name of object that want to get
Returns
object
Definition at line 49 of file ObjectFactory.php.
References $objectName, constructObject(), and BizSystem\sessionContext().
    {
        if (array_key_exists($objectName, $this->_objsRefMap) && $new==0)
        {
            return $this->_objsRefMap[$objectName];
        }
        $obj = $this->constructObject($objectName);
        if ($obj)
            $this->_objsRefMap[$objectName] = $obj; // save object to cache
        if($new!=1){
         if (method_exists($obj, "GetSessionVars"))
             $obj->getSessionVars(BizSystem::sessionContext());
        }
        return $obj;
    }
setObject ($objName, $obj)
Definition at line 80 of file ObjectFactory.php.
    {
        $this->_objsRefMap[$objName] = $obj;
    }
Field Documentation
$_objsRefMap protected
Definition at line 32 of file ObjectFactory.php.
Referenced by getAllObjects().