Openbiz Framework API: BizSystem Class Reference
BizSystem Class Reference
Public Member Functions
__destruct ()
getClientProxy ()
getConfiguration ()
getCurrentViewName ()
getCurrentViewSet ()
getDBConnection ($dbName=null)
getObjectFactory ()
getSessionContext ()
getTypeManager ()
removeDBConnection ($dbName=null)
setCurrentViewName ($viewname)
setCurrentViewSet ($viewSet)
Static Public Member Functions
static allowUserAccess ($resourceAction)
static clientProxy ()
static configuration ()
static currentPageURL ()
static dbConnection ($dbName=null)
static getCompiledFileWithPath ($xmlObj)
static getDataObject ($objectName)
static getDefaultPerm ($group)
static getFormObject ($objectName)
static getGroupName ($groupId)
static getLibFileWithPath ($className, $packageName="")
static getMacroValue ($var, $key)
static getMessage ($msgid, $params=array())
static getObject ($objectName, $isNew=0)
static getProfileEmail ($accountId)
static getProfileId ($accountId)
static getProfileName ($accountId, $type='full')
static getService ($service, $new=0)
static getSmartyTemplate ()
static getTplFileWithPath ($templateFile, $packageName)
static getUserPreference ($attribute=null)
static getUserProfile ($attribute=null)
static getVersion ()
static getViewObject ($objectName)
static & getXmlArray ($xmlFile)
static getXmlFileWithPath ($xmlObj)
static getZendTemplate ()
static initUserProfile ($userId)
static instance ()
static loadClass ($className, $packageName='')
static log ($priority, $subject, $message)
static logError ($priority, $subject, $message, $fileName=NULL)
static objectFactory ()
static resetDBConnection ($dbName=null)
static sessionContext ()
static typeManager ()
Detailed Description
Definition at line 40 of file BizSystem.php.
Constructor & Destructor Documentation
__destruct ()
Destruct object: save object session variables
Returns
void
Definition at line 91 of file BizSystem.php.
    {
        // save object session vars
        //$this->_sessionContext->saveSessionObjects();
        //echo "<br>destruct bizSystem";
    }
Member Function Documentation
static allowUserAccess ($resourceAction) static
Check if user can access the given resource action
Parameters
string $resourceAction resource action
Returns
boolean true or false
Definition at line 337 of file BizSystem.php.
References getService().
Referenced by MetaObject\allowAccess().
    {
        $serviceObj = BizSystem::getService(ACL_SERVICE);
        return $serviceObj->allowAccess($resourceAction);
    }
static clientProxy () static
Get the ClientProxy object this static method wrapping the GetClientProxy method
Returns
ClientProxy the ClientProxy object
Definition at line 209 of file BizSystem.php.
References instance().
Referenced by HTMLMenus\__construct(), EasyForm\_doInsert(), EasyForm\_doUpdate(), EasyForm\_showForm(), InputElement\addSCKeyScript(), EasyForm\autoSuggest(), FormRenderer\buildTemplateAttributes(), ViewRenderer\buildTemplateAttributes(), EasyForm\close(), EasyForm\copyRecord(), EasyForm\deleteRecord(), BizController\dispatchRequest(), EasyForm\editRecord(), OB_ErrorHandler\errorHandler(), OB_ErrorHandler\exceptionHandler(), EasyForm\getActiveRecord(), EasyForm\getInvokingElement(), InputDateRangePicker\getSearchRule(), InputPassword\getValue(), EasyForm\gotoSelectedPage(), excelService\importCSV(), ioService\importXML(), ClientProxy\includeBaseClientScripts(), BizController\invoke(), PickerForm\joinToParent(), EasyForm\loadPicker(), PickerForm\pickToParent(), EasyForm\processDataObjError(), EasyForm\processPostAction(), EasyForm\readInputRecord(), EasyForm\readInputs(), ClientProxy\redirectView(), EasyForm\removeRecord(), RichText\render(), ColorPicker\render(), AutoSuggest\render(), InputDate\render(), InputDatetime\render(), CKEditor\render(), chartService\render(), EasyViewWizard\renderStep(), ioService\reportError(), excelService\reportError(), EasyForm\rerender(), EasyForm\runSearch(), EasyForm\selectRecord(), HTMLTabs\setClientScripts(), EasyView\setClientScripts(), EasyForm\setClientScripts(), EasyForm\setPageSize(), ImageUploader\setValue(), and FileUploader\setValue().
    {
        return BizSystem::instance()->getClientProxy();
    }
static configuration () static
Get the Configuration object this static method wrapping the Configuration method
Returns
Configuration the Configuration object
Definition at line 183 of file BizSystem.php.
References instance().
Referenced by BizDataObj_SQLHelper\buildInsertSQL().
    {
        return BizSystem::instance()->getConfiguration();
    }
static currentPageURL () static
Get current page URL NOTE: NYU not yet used
Returns
string current page URL
Definition at line 525 of file BizSystem.php.
    {
        if ($_REQUEST['__url'])
            return $_REQUEST['__url'];
        else
            return $_SERVER['REQUEST_URI'];
    }
static dbConnection ($dbName = null) static
Get database connection
Parameters
string $dbName database name
Returns
Zend_Db_Adapter_Abstract database connection
Definition at line 614 of file BizSystem.php.
References instance().
Referenced by doTriggerService\executeSQL(), BizDataObj_Abstract\getDBConnection(), and profileService\getDBProfile().
    {
        return BizSystem::instance()->getDBConnection($dbName);
    }
getClientProxy ()
Get the ClientProxy object
Returns
ClientProxy the ClientProxy object
Definition at line 193 of file BizSystem.php.
    {
        if (!$this->_clientProxy)
        {
            include_once(OPENBIZ_BIN."ClientProxy.php");
            $this->_clientProxy = new ClientProxy();
        }
        return $this->_clientProxy;
    }
static getCompiledFileWithPath ($xmlObj) static
Definition at line 720 of file BizSystem.php.
    {
        return Resource::GetCompiledFileWithPath($xmlObj);
    }
getConfiguration ()
Get the Configuration object
Returns
Configuration the Configuration object
Definition at line 167 of file BizSystem.php.
Referenced by getDBConnection().
    {
        if (!$this->_confgiuration)
        {
            include_once(OPENBIZ_BIN."Configuration.php");
            $this->_confgiuration = new Configuration();
        }
        return $this->_confgiuration;
    }
getCurrentViewName ()
Get the current view name
Returns
string current view name
Definition at line 478 of file BizSystem.php.
References getSessionContext().
    {
        if ($this->_currentViewName == "")
            $this->_currentViewName = $this->getSessionContext()->getVar("CVN");   // CVN stands for CurrentViewName
        return $this->_currentViewName;
    }
getCurrentViewSet ()
Get the current view set
Returns
string current view set
Definition at line 501 of file BizSystem.php.
References getSessionContext().
    {
        if ($this->_currentViewSet == "")
            $this->_currentViewSet = $this->getSessionContext()->getVar("CVS");   // CVS stands for CurrentViewSet
        return $this->_currentViewSet;
    }
static getDataObject ($objectName) static
Examples:
/example/DataObject.php.
Definition at line 286 of file BizSystem.php.
References $objectName.
    {
        $obj = BizSystem::ObjectFactory()->getObject($objectName, 0);
        if(is_a($obj,'BizDataObj'))
        {
         return $obj;
        }
    }
getDBConnection ($dbName = null)
Get the database connection object
Parameters
string $dbname,database name declared in config.xml
Returns
Zend_Db_Adapter_Abstract
Definition at line 554 of file BizSystem.php.
References getConfiguration().
Referenced by removeDBConnection().
    {
        $rDBName = (!$dbName) ? "Default" : $dbName;
        if (isset($this->_dbConnection[$rDBName])){
          $db =  $this->_dbConnection[$rDBName];
          if(!CLI){
           return $db;
          }
        }
        $dbInfo = $this->getConfiguration()->getDatabaseInfo($rDBName);
        require_once 'Zend/Db.php';
        $params = array (
                'host'     => $dbInfo["Server"],
                'username' => $dbInfo["User"],
                'password' => $dbInfo["Password"],
                'dbname'   => $dbInfo["DBName"],
                'port'     => $dbInfo["Port"],
                'charset'  => $dbInfo["Charset"]
        );
        if ($dbInfo["Options"]) {
         $options = explode(";",$dbInfo["Options"]);
         foreach ($options as $opt) {
          list($k,$v) = explode("=",$opt);
          $params[$k] = $v;
         }
        }
        foreach ($params as $name=>$val) {
         if (empty($val)) unset($params[$name]);
        }
        if(strtoupper($dbInfo["Driver"])=="PDO_MYSQL")
        {
         $pdoParams = array(
       PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => true
   );
   $params["driver_options"]=$pdoParams;
        }
        $db = Zend_Db::factory($dbInfo["Driver"], $params);
        $db->setFetchMode(PDO::FETCH_NUM);
        if(strtoupper($dbInfo["Driver"])=="PDO_MYSQL" &&
                $dbInfo["Charset"]!="")
        {
            $db->query("SET NAMES '".$params['charset']."'");
        }
        $this->_dbConnection[$rDBName] = $db;
        return $db;
    }
static getDefaultPerm ($group) static
Definition at line 441 of file BizSystem.php.
References DEFAULT_GROUP_PERM, DEFAULT_OTHER_PERM, DEFAULT_OWNER_PERM, and getUserPreference().
    {
     $group = strtolower($group);
     switch($group){
      default:
      case 'owner':
       $setting = BizSystem::getUserPreference('owner_perm');
       if($setting!=''){
        $perm_code = $setting;
       }else{
        $perm_code = DEFAULT_OWNER_PERM;
       }
       break;
      case 'group':
       $setting = BizSystem::getUserPreference('owner_group');
       if($setting!=''){
        $perm_code = $setting;
       }else{
        $perm_code = DEFAULT_GROUP_PERM;
       }
       break;
      case 'other':
       $setting = BizSystem::getUserPreference('owner_other');
       if($setting!=''){
        $perm_code = $setting;
       }else{
        $perm_code = DEFAULT_OTHER_PERM;
       }
       break;
     }
     return $perm_code;
    }
static getFormObject ($objectName) static
Examples:
/example/FormObject.php.
Definition at line 304 of file BizSystem.php.
References $objectName.
    {
        $obj = BizSystem::ObjectFactory()->getObject($objectName, 0);
        if(is_a($obj,'EasyForm'))
        {
         return $obj;
        }
    }
static getGroupName ($groupId) static
Definition at line 436 of file BizSystem.php.
References getService().
{
     $profileService = BizSystem::getService(PROFILE_SERVICE);
     return $profileService->getGroupName($groupId);
    }
static getLibFileWithPath ($className, $packageName = "") static
Get openbiz library php file path by searching modules/package, /bin/package and /bin
Parameters
string $className
Returns
string php library file path
Definition at line 758 of file BizSystem.php.
References Resource\getLibFileWithPath().
Referenced by loadClass().
    {
        return Resource::getLibFileWithPath($className, $packageName);
    }
static getMacroValue ($var, $key) static
Evaluate macro, this method can only be used to get profile in 2.0 For example, :macro_key. i.e. :ROLE
Parameters
string $var,macro name
string $key,macro key
Returns
string
Definition at line 627 of file BizSystem.php.
References instance().
Referenced by Expression\replaceMacrosExpr().
    {
        if ($var == "profile")
        {
            return BizSystem::instance()->getUserProfile($key);
        }
        return null;
    }
static getMessage ($msgid, $params = array()) static
Get message resource enhanced by Jixian
Parameters
<type> $msgid string id of message
<type> $params array array of parameters
Returns
string message
Definition at line 798 of file BizSystem.php.
References Resource\getMessage().
Referenced by validateService\between(), validateService\betweenLength(), validateService\credit(), validateService\date(), BizDataObj\deleteRecord(), BizDataObj\deleteRecords(), validateService\email(), BizDataObj\generateId(), Configuration\getDatabaseInfo(), validateService\getErrorMessage(), Resource\getTplFileWithPath(), validateService\greaterThan(), excelService\importCSV(), BizController\invoke(), validateService\lessThan(), validateService\longerThan(), validateService\phone(), URLFilterRule\process(), DomainFilterRule\process(), AgentFilterRule\process(), IPFilterRule\process(), PostFilterRule\process(), GetFilterRule\process(), validateService\shorterThan(), validateService\social(), validateService\street(), validateService\strongPassword(), BizDataObj\updateRecord(), BizDataObj\updateRecords(), and validateService\zip().
    {
        return Resource::getMessage($msgid, $params);
    }
static getObject ($objectName, $isNew = 0) static
Get the metadata object by object name
Parameters
string $objectName object name
number $isNew 0 = not new, 1 new object
Returns
object
Definition at line 272 of file BizSystem.php.
References $objectName.
Referenced by PickerForm\addToParent(), auditService\audit(), doTriggerService\auditTrail(), authService\authDBUser(), BizDataObj_SQLHelper\buildQuerySQL(), ViewRenderer\buildTemplateAttributes(), doTriggerService\callService(), ioService\exportXML(), queryService\fetchAll(), queryService\fetchRecord(), BizField\getDataObj(), TreeListbox\getDOFromList(), OptionElement\getDOFromList(), DropDownList\getDOFromList(), BizDataObj_Abstract\getRefObject(), getService(), EasyForm\getViewObject(), ioService\importXML(), EasyForm\inheritParentObj(), BizDataObj_Abstract\inheritParentObj(), BizController\invoke(), emailService\logEmail(), EasyForm\parentSwitchForm(), BizDataObj\processCascadeAction(), chartService\render(), reportService\render(), FormElement\render(), HTMLTabs\render(), pdfService\renderView(), BizController\renderView(), Expression\replaceVarExpr(), doTriggerService\sendEmail(), ClientProxy\showErrorMessage(), and EasyForm\targetSwitchForm().
    {
        return BizSystem::ObjectFactory()->getObject($objectName, $isNew);
    }
getObjectFactory ()
Get the ObjectFactory object
Returns
ObjectFactory the ObjectFactory object
Definition at line 114 of file BizSystem.php.
    {
        if (!$this->_objectFactory)
        {
            include_once(OPENBIZ_BIN."ObjectFactory.php");
            $this->_objectFactory = new ObjectFactory();
        }
        return $this->_objectFactory;
    }
static getProfileEmail ($accountId) static
Get profile email
Parameters
type $accountId
Returns
type
Definition at line 421 of file BizSystem.php.
References getService().
{
     $profileService = BizSystem::getService(PROFILE_SERVICE);
     return $profileService->getProfileEmail($accountId);
    }
static getProfileId ($accountId) static
Get profile ID
Parameters
type $accountId
Returns
type
Definition at line 431 of file BizSystem.php.
References getService().
{
     $profileService = BizSystem::getService(PROFILE_SERVICE);
     return $profileService->getProfileId($accountId);
    }
static getProfileName ($accountId, $type = 'full') static
Get profile name
Parameters
type $accountId
type $type
Returns
type
Definition at line 411 of file BizSystem.php.
References getService().
{
     $profileService = BizSystem::getService( PROFILE_SERVICE );
     return $profileService->GetProfileName( $accountId, $type );
    }
static getService ($service, $new = 0) static
Get the service object
Parameters
string $service service name
Returns
object the service object
Definition at line 255 of file BizSystem.php.
References getObject().
Referenced by EasyView\_render(), BizDataObj_Lite\_run_search(), allowUserAccess(), EasyForm\callService(), BizField\checkValueType(), BizDataObj\cleanCache(), BizDataObj\generateId(), getGroupName(), getProfileEmail(), getProfileId(), getProfileName(), BizRecord\getRecordArr(), getTypeManager(), getUserPreference(), getUserProfile(), initUserProfile(), log(), logError(), BizController\processSecurityFilters(), HTMLTabs\render(), EasyForm\render(), HTMLMenus\renderSingleMenuItem(), EasyViewWizard\renderStep(), Expression\replaceVarExpr(), EasyForm\runEventLog(), BizRecord\setInputRecord(), EasyForm\validateForm(), and BizDataObj\validateInput().
    {
        $defaultPackage = "service";
        $serviceName = $service;
        if (strpos($service, ".") === false)
            $serviceName = $defaultPackage . "." . $service;
        return BizSystem::getObject($serviceName, $new);
    }
getSessionContext ()
Get the SessionContext object
Returns
SessionContext the SessionContext object
Definition at line 140 of file BizSystem.php.
Referenced by getCurrentViewName(), getCurrentViewSet(), setCurrentViewName(), and setCurrentViewSet().
    {
        if ($this->_sessionContext)
            return $this->_sessionContext;
        include_once(OPENBIZ_BIN."SessionContext.php");
        $this->_sessionContext = new SessionContext();
        // retrieve object session vars
        $this->_sessionContext->retrieveSessionObjects();
        return $this->_sessionContext;
    }
static getSmartyTemplate () static
Get smarty template
Returns
Smarty smarty object
Definition at line 641 of file BizSystem.php.
References Resource\getSmartyTemplate().
Referenced by reportService\render(), HTMLTabs\render(), FormRenderer\renderSmarty(), and ViewRenderer\renderSmarty().
    {
        return Resource::getSmartyTemplate();
    }
static getTplFileWithPath ($templateFile, $packageName) static
Get openbiz template file path by searching modules/package, /templates
Parameters
string $className
Returns
string php library file path
Definition at line 731 of file BizSystem.php.
References Resource\getTplFileWithPath().
Referenced by HTMLTabs\render(), FormRenderer\renderPHP(), ViewRenderer\renderPHP(), FormRenderer\renderSmarty(), and ViewRenderer\renderSmarty().
    {
        return Resource::getTplFileWithPath($templateFile, $packageName);
    }
getTypeManager ()
Get the TypeManager object
Returns
TypeManager the TypeManager object
Definition at line 219 of file BizSystem.php.
References getService().
    {
        if (!$this->_typeManager)
        {
            include_once(OPENBIZ_BIN."TypeManager.php");
            $this->_typeManager = new TypeManager();
            /* @var $localeInfoService localeInfoService */
            $localeInfoService = BizSystem::getService(LOCALEINFO_SERVICE);
            $localeInfo = $localeInfoService->getLocaleInfo();
            if ($localeInfo)
            {
                $this->_typeManager->setLocaleInfo($localeInfo);
            }
        }
        return $this->_typeManager;
    }
static getUserPreference ($attribute = null) static
Get user preference
Parameters
string $attribute key that representing attribute
Returns
mixed
Definition at line 390 of file BizSystem.php.
References getService(), PREFERENCE_SERVICE, and sessionContext().
Referenced by I18n\getCurrentLangCode(), Resource\getCurrentTheme(), and getDefaultPerm().
    {
     if(!BizSystem::GetXmlFileWithPath (PREFERENCE_SERVICE)){
      return null;
     }
        $preferenceService = BizSystem::getService(PREFERENCE_SERVICE);
        if (method_exists($preferenceService,'getPreference'))
            return $preferenceService->getPreference($attribute);
        else
        {
            $preference = BizSystem::sessionContext()->getVar("_USER_PREFERENCE");
            return isset( $preference[$attribute] ) ? $preference[$attribute] : "";
        }
    }
static getUserProfile ($attribute = null) static
Get user profile
Parameters
string $attribute user attribute
Returns
array user profile array
Definition at line 368 of file BizSystem.php.
References getService(), and sessionContext().
Referenced by auditService\audit(), HTMLMenus\renderSingleMenuItem(), and Expression\replaceVarExpr().
    {
     if ( !BizSystem::GetXmlFileWithPath( PROFILE_SERVICE ) ) {
      return null;
     }
        $profileService = BizSystem::getService(PROFILE_SERVICE);
        if (method_exists($profileService,'getProfile')) {
            return $profileService->getProfile($attribute);
        }
        else
        {
            $profile = BizSystem::sessionContext()->getVar("_USER_PROFILE");
            return isset($profile[$attribute]) ? $profile[$attribute] : "";
        }
    }
static getVersion () static
Definition at line 104 of file BizSystem.php.
    {
        return '3.1';
    }
static getViewObject ($objectName) static
Examples:
/example/ViewObject.php.
Definition at line 322 of file BizSystem.php.
References $objectName.
    {
        return BizSystem::ObjectFactory()->getObject($objectName, 0);
        if(is_a($obj,'EasyView'))
        {
         return $obj;
        }
    }
static& getXmlArray ($xmlFile) static
Get Xml Array. If xml file has been compiled (has .cmp), load the cmp file as array; otherwise, compile the .xml to .cmp first new 2.2.3, .cmp files will be created in app/cache/metadata_cmp directory. replace '/' with '_' for example, /module/demo/BOEvent.xml has cmp file as _module_demo_BOEvent.xml
Parameters
string $xmlFile
Returns
array
Definition at line 785 of file BizSystem.php.
References Resource\getXmlArray().
Referenced by Configuration\__construct(), ObjectFactory\constructObject(), OptionElement\getXMLFromList(), DropDownList\getXMLFromList(), and chartService\render().
    {
        return Resource::getXmlArray($xmlFile);
    }
static getXmlFileWithPath ($xmlObj) static
Get Xml file with path
Search the object metedata file as objname+.xml in metedata directories name convension: demo.BOEvent points to metadata/demo/BOEvent.xml new in 2.2.3, demo.BOEvent can point to modules/demo/BOEvent.xml
Parameters
string $xmlObj xml object
Returns
string xml config file path
Definition at line 715 of file BizSystem.php.
    {
        return Resource::GetXmlFileWithPath($xmlObj);
    }
static getZendTemplate () static
Get Zend Template
Returns
Zend_View zend view template object
Definition at line 651 of file BizSystem.php.
References Resource\getZendTemplate().
Referenced by FormRenderer\renderPHP(), and ViewRenderer\renderPHP().
    {
        return Resource::getZendTemplate();
    }
static initUserProfile ($userId) static
Initialize User Profile
Parameters
string $userId
Returns
array Profile array
Definition at line 349 of file BizSystem.php.
References getService(), and sessionContext().
    {
        $profileService = BizSystem::getService(PROFILE_SERVICE);
        if (method_exists($profileService,'InitProfile'))
            $profile = $profileService->InitProfile($userId);
        else
            $profile = $profileService->getProfile($userId);
        BizSystem::sessionContext()->setVar("_USER_PROFILE", $profile);
        return $profile;
    }
static instance () static
Create instant of BizSystem
Returns
BizSystem instant of BizSystem
Definition at line 63 of file BizSystem.php.
Referenced by clientProxy(), configuration(), dbConnection(), ClientProxy\getAppendedScripts(), getMacroValue(), SessionContext\getNamespace(), SessionContext\getViewHistory(), objectFactory(), BizController\renderView(), resetDBConnection(), sessionContext(), SessionContext\setViewHistory(), and typeManager().
    {
        if (self::$_instance == null)
            self::$_instance = new BizSystem();
        return self::$_instance;
    }
static loadClass ($className, $packageName = '') static
Definition at line 736 of file BizSystem.php.
References getLibFileWithPath().
Referenced by MetaIterator\__construct(), and MetaObject\getElementObject().
    {
        //echo "loadClass($className, $packageName)\n";
  if (class_exists($className, false)) return true;
  if (isset(self::$_classNameCache[$packageName.$className])) return true;
        if (strpos($className, 'Zend') === 0) return true;
        $filePath = BizSystem::getLibFileWithPath($className, $packageName);
        if ($filePath)
        {
            include_once($filePath);
            self::$_classNameCache[$packageName.$className] = 1;
            return true;
        }
        return false;
    }
static log ($priority, $subject, $message) static
Log message to log file
Parameters
integer $priority,. it can be one of following value LOG_EMERG system is unusable = 1 LOG_ALERT action must be taken immediately = LOG_EMERG LOG_CRIT critical conditions = LOG_EMERG LOG_ERR error conditions = 4 LOG_WARNING warning conditions = 5 LOG_NOTICE normal, but significant, condition = 6 LOG_INFO informational message = LOG_NOTICE LOG_DEBUG debug-level message = LOG_NOTICE
So LOG_EMERG, LOG_ERR, LOG_WARNING and LOG_DEBUG are valid inputs
string $subject,. the log subject decided by caller function
string $message,. the message to be logged in log file
Returns
void
Definition at line 673 of file BizSystem.php.
References getService().
Referenced by EasyView\_render(), BizDataObj_Lite\_run_search(), EasyForm\_showForm(), auditService\audit(), BizDataObj\deleteRecord(), EasyForm\deleteRecord(), BizDataObj\deleteRecords(), OptionElement\getSQLFromList(), DropDownList\getSQLFromList(), excelService\importCSV(), BizDataObj\insertRecord(), emailService\logEmail(), EasyForm\processBDOException(), BizDataObj\processCascadeAction(), EasyForm\processDataObjError(), EasyForm\render(), excelService\renderCSV(), excelService\renderTSV(), EasyForm\runSearch(), SessionContext\saveSessionObjects(), BizDataObj\updateRecord(), and BizDataObj\updateRecords().
    {
        $svcobj = BizSystem::getService(LOG_SERVICE);
        $svcobj->log($priority, $subject, $message);
    }
static logError ($priority, $subject, $message, $fileName = NULL) static
Log message to log file
BizSystem $g_BizSystem
Parameters
integer $priority,. it can be one of following value LOG_EMERG system is unusable = 1 LOG_ALERT action must be taken immediately = LOG_EMERG LOG_CRIT critical conditions = LOG_EMERG LOG_ERR error conditions = 4 LOG_WARNING warning conditions = 5 LOG_NOTICE normal, but significant, condition = 6 LOG_INFO informational message = LOG_NOTICE LOG_DEBUG debug-level message = LOG_NOTICE
So LOG_EMERG, LOG_ERR, LOG_WARNING and LOG_DEBUG are valid inputs
Parameters
string $subject,. the log subject decided by caller function
string $message,. the message to be logged in log file
string $fileName file to save to
Returns
void
Definition at line 699 of file BizSystem.php.
References getService().
Referenced by OB_ErrorHandler\errorHandler(), and OB_ErrorHandler\exceptionHandler().
    {
        $svcobj = BizSystem::getService(LOG_SERVICE);
        $svcobj->logError($priority, $subject, $message, $fileName);
    }
static objectFactory () static
Get get the ObjectFactory object as static method this static method wrapping the GetObjectFactory method
Returns
ObjectFactory the ObjectFactory object
Definition at line 130 of file BizSystem.php.
References instance().
Referenced by EasyForm\_showForm(), PickerForm\addToParent(), EasyViewWizard\cancel(), EasyViewWizard\commit(), EasyForm\getDataObj(), excelService\getDataTable(), EventHandler\getFormedFunction(), EasyViewWizard\getFormInputs(), Panel\getFormObj(), Element\getFormObj(), EventHandler\getInvokeAction(), excelService\importCSV(), EasyView\initAllForms(), PickerForm\insertToParent(), PickerForm\joinToParent(), EasyForm\loadPicker(), EasyView\processRequest(), DynaView\processURL(), EasyView\render(), EasyForm\render(), EasyForm\renderParent(), EasyViewWizard\renderStep(), EasyForm\rerenderSubForms(), and SessionContext\saveSessionObjects().
    {
        return BizSystem::instance()->getObjectFactory();
    }
removeDBConnection ($dbName = null)
Definition at line 539 of file BizSystem.php.
References getDBConnection().
{
     $rDBName = (!$dbName) ? "Default" : $dbName;
        if (isset($this->_dbConnection[$rDBName])){
            $this->_dbConnection[$rDBName]->closeConnection();
            unset($this->_dbConnection[$rDBName]);
        }
        return $this->getDBConnection($rDBName);
    }
static resetDBConnection ($dbName = null) static
Definition at line 534 of file BizSystem.php.
References instance().
    {
        return BizSystem::instance()->removeDBConnection($dbName);
    }
static sessionContext () static
Get the SessionContext object this static method wrapping the GetObjectFactory method
Returns
SessionContext the SessionContext object
Definition at line 157 of file BizSystem.php.
References instance().
Referenced by bizsystem_shutdown(), EasyFormWizard\cancel(), BizController\dispatchRequest(), I18n\getCurrentLangCode(), Resource\getCurrentTheme(), ObjectFactory\getObject(), getUserPreference(), getUserProfile(), initUserProfile(), BizController\renderView(), HTMLTabs\setCurrentTabInSession(), ColumnListbox\setValue(), and ColumnInputText\setValue().
    {
        return BizSystem::instance()->getSessionContext();
    }
setCurrentViewName ($viewname)
Set the current view name
Parameters
string $viewname new current view name
Definition at line 490 of file BizSystem.php.
References getSessionContext().
    {
        $this->_currentViewName = $viewname;
        $this->getSessionContext()->setVar("CVN", $this->_currentViewName);   // CVN stands for CurrentViewName
    }
setCurrentViewSet ($viewSet)
Set current view set
Parameters
<type> $viewSet
Definition at line 513 of file BizSystem.php.
References getSessionContext().
    {
        $this->_currentViewSet = $viewSet;
        $this->getSessionContext()->setVar("CVS", $this->_currentViewSet);   // CVS stands for CurrentViewSet
    }
static typeManager () static
Get the TypeManager object this static method wrapping the GetTypeManager method
Returns
TypeManager the TypeManager object
Definition at line 244 of file BizSystem.php.
References instance().
Referenced by BizField\getValue(), inputValToRule(), and BizRecord\setInputRecord().
    {
        return BizSystem::instance()->getTypeManager();
    }