Openbiz Framework API: emailService Class Reference
emailService Class Reference
Public Member Functions
__construct (&$xmlArr)
getErrorMsg ()
logEmail ($result, $subject, $body=NULL, $TOs=NULL, $CCs=NULL, $BCCs=NULL)
sendEmail ($TOs=null, $CCs=null, $BCCs=null, $subject, $body, $attachments=null, $isHTML=false)
useAccount ($accountName)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_Accounts
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
readMetadata (&$xmlArr)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_UseAccount
Detailed Description
Definition at line 29 of file emailService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize emailService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 87 of file emailService.php.
References readMetadata(), and useAccount().
    {
        $this->readMetadata($xmlArr);
        $this->_constructMail();
        $acct = $this->m_Accounts->current();
        if (! $acct)
            return; //TODO Throw exception
        $this->useAccount($acct->m_Name);
    }
Member Function Documentation
getErrorMsg ()
Get error message
Returns
string
Definition at line 120 of file emailService.php.
    {
        return $this->_errorMessage;
    }
logEmail ($result, $subject, $body = NULL, $TOs = NULL, $CCs = NULL, $BCCs = NULL)
Log that an email attemp was made. We assume it was successfull, since Zend_Mail throws an exception otherwise
Parameters
string $subject
array $To
array $CCs
array $BCCs
Returns
mixed boolean|string|void
Definition at line 275 of file emailService.php.
References BizSystem\getObject(), and BizSystem\log().
Referenced by sendEmail().
    {
        //Log the email attempt
        $recipients = '';
    // add TO addresses
        if ($TOs)
        {
            foreach ($TOs as $to)
            {
             if(is_array($to))
             {
                 $recipients .= $to['name']."<".$to['email'].">;";
             }
             else
             {
              $recipients .= $to.";";
             }
            }
        }
        // add CC addresses
        if ($CCs)
        {
            foreach ($CCs as $cc)
            {
                if(is_array($cc))
                {
              $recipients .= $cc['name']."<".$cc['email'].">;";
                }
                else
                {
                 $recipients .= $cc.";";
                }
            }
        }
        // add BCC addresses
        if ($BCCs)
        {
            foreach ($BCCs as $bcc)
            {
                if(is_array($bcc))
                {
              $recipients .= $bcc['name']."<".$bcc['email'].">;";
                }
                else
                {
                 $recipients .= $bcc.";";
                }
            }
        }
        if ($this->_logType == 'DB')
        {
            $account = $this->m_Accounts->get($this->m_UseAccount);
            $sender_name = $account->m_FromName;
            $sender = $account->m_FromEmail;
            // Store the message log
            $boMessageLog = BizSystem::getObject($this->_logObject);
            $mlArr = $boMessageLog->newRecord();
            $mlArr["sender"] = $sender;
            $mlArr["sender_name"] = $sender_name;
            $mlArr["recipients"] = $recipients;
            $mlArr["subject"] = $subject;
            $mlArr["content"] = $body;
            $mlArr["result"] = $result;
   /*
    * as long as data could read from db, its no longer need to addslashes
            //Escape Data since this may contain quotes or other goodies
            foreach ($mlArr as $key => $value)
            {
                $mlArr[$key] = addslashes($value);
            }
   */
            $ok = $boMessageLog->insertRecord($mlArr);
            if (! $ok)
            {
                return $boMessageLog->getErrorMessage();
            }
            else
            {
                return TRUE;
            }
        }
        else
        {
            $back_trace = debug_backtrace();
            if ($result == 'Success')
            {
                $logNum = LOG_INFO;
            } else
            {
                $logNum = LOG_ERR;
            }
            BizSystem::log($logNum, "EmailService", "Sent email with subject - \"$subject\" and body - $body to - $recipients with result $result.", NULL, $back_trace);
        }
    }
readMetadata (& $xmlArr) protected
Read array meta-data, and store to meta-object
Parameters
array $xmlArr
Returns
void
Definition at line 103 of file emailService.php.
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_Accounts = new MetaIterator($xmlArr["PLUGINSERVICE"]["ACCOUNTS"]["ACCOUNT"], "EmailAccount");
        $this->_logEnabled = $xmlArr["PLUGINSERVICE"]["LOGGING"]["ATTRIBUTES"]["ENABLED"];
        if ($this->_logEnabled)
        {
            $this->_logType = $xmlArr["PLUGINSERVICE"]["LOGGING"]["ATTRIBUTES"]["TYPE"];
            $this->_logObject = $xmlArr["PLUGINSERVICE"]["LOGGING"]["ATTRIBUTES"]["OBJECT"];
        }
    }
sendEmail ($TOs = null, $CCs = null, $BCCs = null, $subject, $body, $attachments = null, $isHTML = false)
A convenience function that will issue an email based on the parameter provided Will log email attempts but will NOT run the body through a template
Parameters
array $TOs
array $CCs
array $BCCs
array $subject
array $body
array $attachments
boolean $isHTML
Returns
boolean $result - TRUE on success, FALSE on failure
Definition at line 188 of file emailService.php.
References logEmail().
    {
        $mail = $this->_mail;
        // add TO addresses
        if ($TOs)
        {
            foreach ($TOs as $to)
            {
             if(is_array($to))
             {
                 $mail->addTo($to['email'],$to['name']);
             }
             else
             {
              $mail->addTo($to);
             }
            }
        }
        // add CC addresses
        if ($CCs)
        {
            foreach ($CCs as $cc)
            {
                if(is_array($cc))
                {
              $mail->AddCC($cc['email'],$cc['name']);
                }
                else
                {
                 $mail->AddCC($cc);
                }
            }
        }
        // add BCC addresses
        if ($BCCs)
        {
            foreach ($BCCs as $bcc)
            {
                if(is_array($bcc))
                {
              $mail->AddBCC($bcc['email'],$bcc['name']);
                }
                else
                {
                 $mail->AddBCC($bcc);
                }
            }
        }
        // add attachments
        if ($attachments)
            foreach ($attachments as $att)
                $mail->CreateAttachment(file_get_contents($att));
        $mail->setSubject($subject);
        $body = str_replace("\\n", "\n", $body);
        if ($isHTML == TRUE)
        {
            $mail->setBodyHTML($body);
        }
        else
        {
            $mail->setBodyText($body);
        }
        try
        {
            $result = $mail->Send(); //Will throw an exception if sending fails
            $this->logEmail('Success', $subject, $body, $TOs, $CCs, $BCCs);
            return TRUE;
        }
        catch (Exception $e)
        {
            $result = "ERROR: ".$e->getMessage();
            $this->logEmail($result, $subject, $body, $TOs, $CCs, $BCCs);
            return FALSE;
        }
    }
useAccount ($accountName)
Will set the Default Transport object for the mail object based on the supplied accountname
Parameters
string $accountName
Returns
boolean TRUE/FALSE
Definition at line 142 of file emailService.php.
Referenced by __construct().
    {
        //If a mail object exists, overwrite with new object
        if ($this->_mail)
            $this->_constructMail();
        $this->m_UseAccount = $accountName;
        $account = $this->m_Accounts->get($accountName);
        if ($account->m_IsSMTP == "Y")
        {
            require_once 'Zend/Mail/Transport/Smtp.php';
            if ($account->m_SMTPAuth == "Y")
            {
                $config = array('auth' =>'login', 'username'=>$account->m_Username , 'password'=>$account->m_Password, "port"=>$account->m_Port, 'ssl'=>$account->m_SSL);
            }
            else
            {
                $config = array();
            }
            $mailTransport = new Zend_Mail_Transport_Smtp($account->m_Host, $config);
            $this->_mail->setDefaultTransport($mailTransport);
        }
        else
        {
            require_once 'Zend/Mail/Transport/Sendmail.php';
            $mailTransport = new Zend_Mail_Transport_Sendmail();
            $this->_mail->setDefaultTransport($mailTransport);
        }
        $this->_mail->setFrom($account->m_FromEmail, $account->m_FromName);
        return $this;
    }
Field Documentation
$m_Accounts
Definition at line 36 of file emailService.php.
$m_UseAccount protected
Definition at line 50 of file emailService.php.