Openbiz Framework API: BizField Class Reference
BizField Class Reference
Public Member Functions
__construct (&$xmlArr, $bizObj)
adjustBizObjName ($bizObjName)
checkRequired ()
checkValueType ($value=null)
getDefaultValue ()
getInsertLobValue ($dbType)
getProperty ($propertyName)
getSqlValue ($input=null)
getValue ($formatted=true)
getValueOnCreate ()
getValueOnUpdate ()
isLobField ()
lookupValue ()
saveOldValue ($oldValue=null)
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$_getValueCache
$m_Alias
$m_BizObjName
$m_ClearText
$m_Column
$m_DefaultValue
$m_Encrypted
$m_Format
$m_IgnoreInQuery
$m_Index
$m_Join
$m_Length
$m_OldValue
$m_OnAudit
$m_Required
$m_SqlExpression
$m_Type
$m_Validator
$m_Value
$m_ValueExpression
$m_ValueOnCreate
$m_ValueOnUpdate
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getDataObj ()
useDefaultFormat ()
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$_prevValue
Detailed Description
Definition at line 25 of file BizField.php.
Constructor & Destructor Documentation
__construct (& $xmlArr, $bizObj)
Initialize BizField with xml array
Parameters
array $xmlArr xml array
BizDataObj $bizObj BizDataObj instance
Returns
void
Definition at line 103 of file BizField.php.
References MetaObject\prefixPackage(), and useDefaultFormat().
    {
        $this->m_Name = isset($xmlArr["ATTRIBUTES"]["NAME"]) ? $xmlArr["ATTRIBUTES"]["NAME"] : null;
        $this->m_BizObjName = $bizObj->m_Name;
        $this->m_Package = $bizObj->m_Package;
        $this->m_Join = isset($xmlArr["ATTRIBUTES"]["JOIN"]) ? $xmlArr["ATTRIBUTES"]["JOIN"] : null;
        $this->m_Column = isset($xmlArr["ATTRIBUTES"]["COLUMN"]) ? $xmlArr["ATTRIBUTES"]["COLUMN"] : null;
        $this->m_Alias = isset($xmlArr["ATTRIBUTES"]["ALIAS"]) ? $xmlArr["ATTRIBUTES"]["ALIAS"] : null;
        $this->m_ValueExpression = isset($xmlArr["ATTRIBUTES"]["VALUE"]) ? $xmlArr["ATTRIBUTES"]["VALUE"] : null;
        $this->m_DefaultValue = isset($xmlArr["ATTRIBUTES"]["DEFAULTVALUE"]) ? $xmlArr["ATTRIBUTES"]["DEFAULTVALUE"] : null;
        $this->m_Type = isset($xmlArr["ATTRIBUTES"]["TYPE"]) ? $xmlArr["ATTRIBUTES"]["TYPE"] : null;
        $this->m_Format = isset($xmlArr["ATTRIBUTES"]["FORMAT"]) ? $xmlArr["ATTRIBUTES"]["FORMAT"] : null;
        $this->m_Length = isset($xmlArr["ATTRIBUTES"]["LENGTH"]) ? $xmlArr["ATTRIBUTES"]["LENGTH"] : null;
        $this->m_Required = isset($xmlArr["ATTRIBUTES"]["REQUIRED"]) ? $xmlArr["ATTRIBUTES"]["REQUIRED"] : null;
        $this->m_Encrypted = isset($xmlArr["ATTRIBUTES"]["ENCRYPTED"]) ? strtoupper($xmlArr["ATTRIBUTES"]["ENCRYPTED"]) :"N";
//        if($this->m_Encrypted=='Y'){
//         $this->m_ClearText="N";
//        }else{
//         $this->m_ClearText="Y";
//        }
        $this->m_Validator = isset($xmlArr["ATTRIBUTES"]["VALIDATOR"]) ? $xmlArr["ATTRIBUTES"]["VALIDATOR"] : null;
        $this->m_SqlExpression = isset($xmlArr["ATTRIBUTES"]["SQLEXPR"]) ? $xmlArr["ATTRIBUTES"]["SQLEXPR"] : null;
        $this->m_ValueOnCreate = isset($xmlArr["ATTRIBUTES"]["VALUEONCREATE"]) ? $xmlArr["ATTRIBUTES"]["VALUEONCREATE"] : null;
        $this->m_ValueOnUpdate = isset($xmlArr["ATTRIBUTES"]["VALUEONUPDATE"]) ? $xmlArr["ATTRIBUTES"]["VALUEONUPDATE"] : null;
        if (isset($xmlArr["ATTRIBUTES"]["ONAUDIT"]) && $xmlArr["ATTRIBUTES"]["ONAUDIT"]=='Y')
            $this->m_OnAudit = true;
        $this->m_BizObjName = $this->prefixPackage($this->m_BizObjName);
        if (!$this->m_Format) $this->useDefaultFormat();
    }
Member Function Documentation
adjustBizObjName ($bizObjName)
Change the BizDataObj name. This function is used in case of the current BizDataObj inheriting from another BizDataObj, BizField's BizDataObj name should be changed to current BizDataObj name, not the parent object name.
Parameters
string $bizObjName the name of BizDataObj object
Returns
void
Definition at line 171 of file BizField.php.
    {
        if ($this->m_BizObjName != $bizObjName)
            $this->m_BizObjName = $bizObjName;
    }
checkRequired ()
Check if the field is a required field
Returns
boolean true if the field is a required field
Definition at line 348 of file BizField.php.
References Expression\evaluateExpression(), and getDataObj().
    {
        if (!$this->m_Required || $this->m_Required == "")
            return false;
        elseif ($this->m_Required == "Y")
            $required = true;
        elseif($required != "N")
            $required = false;
        else
            $required = Expression::evaluateExpression($this->m_Required, $this->getDataObj());
        return $required;
    }
checkValueType ($value = null)
Check value type
Parameters
mixed $value
Returns
mixed|boolean
Definition at line 368 of file BizField.php.
References $m_Value, and BizSystem\getService().
    {
        if(!$value)
        {
            $value = $this->m_Value;
        }
        $validator = BizSystem::getService(VALIDATE_SERVICE);
        switch ($this->m_Type)
        {
            case "Number":
                $result = is_numeric($value);
                break;
            case "Text":
                $result = is_string($value);
                break;
            case "Date":
                $result = $validator->date($value);
                break;
            /*
            case "Datetime":    // zend doesn't support date time
             $result = $validator->date($value);
             break;
            case "Currency":
             $result = $validator->date($value);
             break;
            */
            case "Phone":
                $result = $validator->phone($value);
                break;
            default:
                $result = true;
                break;
        }
        return $result;
    }
getDataObj () protected
Get the BizDataObj instance
Returns
BizDataObj BizDataObj instance
Definition at line 338 of file BizField.php.
References BizSystem\getObject().
Referenced by checkRequired(), getDefaultValue(), getValue(), getValueOnCreate(), getValueOnUpdate(), lookupValue(), and validate().
    {
        return BizSystem::getObject($this->m_BizObjName);
    }
getDefaultValue ()
Get default value of the field
Returns
string the default value of the field
Definition at line 302 of file BizField.php.
References Expression\evaluateExpression(), and getDataObj().
    {
        if($this->m_DefaultValue !== null)
            return Expression::evaluateExpression($this->m_DefaultValue, $this->getDataObj());
        return "";
    }
getInsertLobValue ($dbType)
Get insert lob value when execute insert SQL. For a lob column, insert SQL first inserts an empty entry in the lob column. Then use update to actually add the lob data.
Parameters
string $dbType database type
Returns
string the insert string for the lob column
Definition at line 220 of file BizField.php.
    {
        if ($dbType == 'oracle' || $dbType == 'oci8')
        {
            if ($this->m_Type != 'Blob') return 'empty_blob()';
            if ($this->m_Type != 'Clob') return 'empty_clob()';
        }
        return 'null';
    }
getProperty ($propertyName)
Get property value
Parameters
string $propertyName property name
Returns
mixed property value
Definition at line 154 of file BizField.php.
References lookupValue().
    {
        $ret = parent::getProperty($propertyName);
        if ($ret) return $ret;
        //if ($propertyName == "Value") return $this->getValue();
  if ($propertyName == "Value") return $this->lookupValue();
        return $this->$propertyName;
    }
getSqlValue ($input = null)
Get string used in sql - with single quote, or without single quote in case of number
Parameters
mixed $input the value to add quote. If null, use the current field value
Returns
string string used in sql
Definition at line 183 of file BizField.php.
Referenced by getValueOnCreate(), and getValueOnUpdate().
    {
        $value = ($input !== null) ? $input : $this->m_Value;
        if ($value === null)
        {
            return "";
        }
        /*
        if ($this->m_Type != 'Number')
        {
            if (get_magic_quotes_gpc() == 0) {
                $val = addcslashes($value, "\000\n\r\\'\"\032");
            }
            return "'$value'";
        }
        */
        return $value;
    }
getValue ($formatted = true)
Get the value of the field.
Parameters
boolean $formatted true if want to get the formatted value
Returns
mixed string or number depending on the field type
Definition at line 248 of file BizField.php.
References $_getValueCache, $m_Value, Expression\evaluateExpression(), getDataObj(), and BizSystem\typeManager().
Referenced by lookupValue().
    {
        // need to ensure that value are retrieved from source/cache
        //if ($this->getDataObj()->CheckDataRetrieved() == false)
        //$this->getDataObj()->getActiveRecord();
  if ($this->_prevValue == $this->m_Value) return $this->_getValueCache;
        $value = stripcslashes($this->m_Value);
        $value = $this->m_Value;
        if ($this->m_ValueExpression && trim($this->m_Column) == "")
        {
            $value = Expression::evaluateExpression($this->m_ValueExpression,$this->getDataObj());
        }
        if ($this->m_Format && $formatted)
        {
            $value = BizSystem::typeManager()->valueToFormattedString($this->m_Type, $this->m_Format, $value);
        }
  $this->_prevValue = $this->m_Value;
  $this->_getValueCache = $value;
        return $value;
    }
getValueOnCreate ()
Get the value when a new record is created
Returns
mixed the value of the field
Definition at line 314 of file BizField.php.
References Expression\evaluateExpression(), getDataObj(), and getSqlValue().
    {
        if($this->m_ValueOnCreate !== null)
            return $this->getSqlValue(Expression::evaluateExpression($this->m_ValueOnCreate, $this->getDataObj()));
        return "";
    }
getValueOnUpdate ()
Get the value when a record is updated
Returns
mixed the value of the field
Definition at line 326 of file BizField.php.
References Expression\evaluateExpression(), getDataObj(), and getSqlValue().
    {
        if($this->m_ValueOnUpdate !== null)
            return $this->getSqlValue(Expression::evaluateExpression($this->m_ValueOnUpdate, $this->getDataObj()));
        return "";
    }
isLobField ()
Check if the field is a LOB type column
Returns
boolean true if the field points a LOB type column
Definition at line 208 of file BizField.php.
    {
        return ($this->m_Type == 'Blob' || $this->m_Type == 'Clob');
    }
lookupValue ()
Lookup the value of the field. Typically used in expression @:Field[name].Value
Parameters
boolean $formatted true if want to get the formatted value
Returns
mixed string or number depending on the field type
Definition at line 236 of file BizField.php.
References getDataObj(), and getValue().
Referenced by getProperty().
 {
  $this->getDataObj()->getActiveRecord();
  return $this->getValue();
 }
saveOldValue ($oldValue = null)
Save the old value to an internal variable
Parameters
mixed $oldValue
Returns
void
Definition at line 289 of file BizField.php.
References $m_Value.
    {
        if ($oldValue)
            $this->m_OldValue = $oldValue;
        else
            $this->m_OldValue = $this->m_Value;
    }
setValue ($value)
Set the value of the field.
Parameters
mixed $value
Returns
void
Definition at line 278 of file BizField.php.
    {
        $this->m_Value = $value;
    }
useDefaultFormat () protected
Use default format if no format is given
Returns
void
Definition at line 140 of file BizField.php.
Referenced by __construct().
    {
        if ($this->m_Type == "Date")
            $this->m_Format = '%Y-%m-%d';
        elseif ($this->m_Type == "Datetime")
            $this->m_Format = '%Y-%m-%d %H:%M:%S';
    }
validate ()
Check if the field has valid value
Returns
boolean true if validation is good
Definition at line 414 of file BizField.php.
References Expression\evaluateExpression(), and getDataObj().
    {
        $ret = true;
        if ($this->m_Validator)
            $ret = Expression::evaluateExpression($this->m_Validator, $this->getDataObj());
        return $ret;
    }
Field Documentation
$_getValueCache
Definition at line 94 of file BizField.php.
Referenced by getValue().
$_prevValue protected
Definition at line 94 of file BizField.php.
$m_Alias
Definition at line 35 of file BizField.php.
$m_BizObjName
Definition at line 32 of file BizField.php.
$m_ClearText
Definition at line 68 of file BizField.php.
$m_Column
Definition at line 34 of file BizField.php.
$m_DefaultValue
Definition at line 74 of file BizField.php.
$m_Encrypted
Definition at line 67 of file BizField.php.
$m_Format
Definition at line 49 of file BizField.php.
$m_IgnoreInQuery
Definition at line 92 of file BizField.php.
$m_Index
Definition at line 36 of file BizField.php.
$m_Join
Definition at line 33 of file BizField.php.
$m_Length
Definition at line 56 of file BizField.php.
$m_OldValue
Definition at line 91 of file BizField.php.
$m_OnAudit
Definition at line 83 of file BizField.php.
$m_Required
Definition at line 64 of file BizField.php.
$m_SqlExpression
Definition at line 66 of file BizField.php.
$m_Type
Definition at line 42 of file BizField.php.
$m_Validator
Definition at line 65 of file BizField.php.
$m_Value
Definition at line 90 of file BizField.php.
Referenced by checkValueType(), getValue(), and saveOldValue().
$m_ValueExpression
Definition at line 57 of file BizField.php.
$m_ValueOnCreate
Definition at line 75 of file BizField.php.
$m_ValueOnUpdate
Definition at line 76 of file BizField.php.