Openbiz Framework API: ColumnShare Class Reference
ColumnShare Class Reference
Public Member Functions
getValue ()
hasOwnerField ()
render ()
setValue ($value)
Public Member Functions inherited from ColumnText
matchRemoteMethod ($method)
renderLabel ()
setSortFlag ($flag=null)
Public Member Functions inherited from LabelText
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_DefaultImg
$m_GroupSharedImg
$m_hasOwnerField
$m_MyAssignedImg
$m_MyDistributedImg
$m_MyPrivateImg
$m_MySharedImg
$m_OtherSharedImg
$m_RecordCreatorId
$m_RecordGroupId
$m_RecordGroupPerm
$m_RecordOtherPerm
$m_RecordOwnerId
Data Fields inherited from ColumnText
$m_ColumnStyle
$m_Sortable
Data Fields inherited from LabelText
$m_DisplayFormat
$m_FieldName
$m_Label
$m_Link
$m_MaxLength
$m_Percent
$m_StripTags
$m_Target
$m_Text
Data Fields inherited from Element
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
readMetaData (&$xmlArr)
Protected Member Functions inherited from ColumnText
readMetaData (&$xmlArr)
Protected Member Functions inherited from LabelText
getLink ()
getTarget ()
getText ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_RecordGroupId_AutoLoad
$m_RecordGroupPerm_AutoLoad
$m_RecordOtherPerm_AutoLoad
$m_RecordOwnerId_AutoLoad
Detailed Description
Definition at line 28 of file ColumnShare.php.
Member Function Documentation
getValue ()
Definition at line 111 of file ColumnShare.php.
References Element\$m_Value, and hasOwnerField().
Referenced by render().
{
     $user_id  = BizSystem::GetUserProfile("Id");
  $groups  = BizSystem::GetUserProfile("groups");
        if (!$groups) $groups = array();
  $this->m_hasOwnerField = $this->hasOwnerField();
       if($this->m_hasOwnerField){
   if($this->m_RecordOwnerId != $this->m_RecordCreatorId)
   {
    if($this->m_RecordOwnerId == $user_id)
    {
     $this->m_Value = 4;
     return $this->m_Value ;
    }
    elseif($this->m_RecordCreatorId == $user_id)
    {
     $this->m_Value = 5;
     return $this->m_Value ;
    }
   }
       }
     if($user_id == $this->m_RecordOwnerId)
  {
   if((int)$this->m_RecordGroupPerm>0 || (int)$this->m_RecordOtherPerm>0 )
   {
    $this->m_Value = 1;
   }
   else
   {
    $this->m_Value = 0;
   }
  }
  elseif($this->m_RecordOtherPerm>0)
  {
   $this->m_Value = 3;
  }
  else
  {
            foreach($groups as $group_id)
   {
    if($group_id == $this->m_RecordGroupId)
    {
     $this->m_Value = 2;
     break;
    }
   }
  }
  return $this->m_Value;
    }
hasOwnerField ()
Definition at line 231 of file ColumnShare.php.
References Element\getFormObj().
Referenced by getValue(), and setValue().
{
  $field = $this->getFormObj()->getDataObj()->getField('owner_id');
  if($field){
   return true;
  }
  else{
   return false;
  }
 }
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 57 of file ColumnShare.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_MyPrivateImg = isset($xmlArr["ATTRIBUTES"]["MYPRIVATEIMG"]) ? $xmlArr["ATTRIBUTES"]["MYPRIVATEIMG"] : "{RESOURCE_URL}/common/images/icon_data_private.gif";
        $this->m_MySharedImg  = isset($xmlArr["ATTRIBUTES"]["MYSHAREDIMG"])  ? $xmlArr["ATTRIBUTES"]["MYSHAREDIMG"] : "{RESOURCE_URL}/common/images/icon_data_shared.gif";
        $this->m_MyAssignedImg  = isset($xmlArr["ATTRIBUTES"]["MYASSIGNEDIMG"])  ? $xmlArr["ATTRIBUTES"]["MYASSIGNEDIMG"] : "{RESOURCE_URL}/common/images/icon_data_assigned.gif";
        $this->m_MyDistributedImg  = isset($xmlArr["ATTRIBUTES"]["MYDISTRIBUTEDIMG"])  ? $xmlArr["ATTRIBUTES"]["MYDISTRIBUTEDIMG"] : "{RESOURCE_URL}/common/images/icon_data_distributed.gif";
        $this->m_GroupSharedImg = isset($xmlArr["ATTRIBUTES"]["GROUPSHAREDIMG"])? $xmlArr["ATTRIBUTES"]["GROUPSHAREDIMG"]: "{RESOURCE_URL}/common/images/icon_data_shared_group.gif";
        $this->m_OtherSharedImg = isset($xmlArr["ATTRIBUTES"]["OTHERSHAREDIMG"])? $xmlArr["ATTRIBUTES"]["OTHERSHAREDIMG"]: "{RESOURCE_URL}/common/images/icon_data_shared_other.gif";
        $this->m_DefaultImg = isset($xmlArr["ATTRIBUTES"]["DEFAULTIMG"])? $xmlArr["ATTRIBUTES"]["DEFAULTIMG"]: "{RESOURCE_URL}/common/images/icon_data_shared_other.gif";
        $this->m_RecordCreatorId = isset($xmlArr["ATTRIBUTES"]["CREATORID"])  ? $xmlArr["ATTRIBUTES"]["CREATORID"] : null;
        $this->m_RecordOwnerId = isset($xmlArr["ATTRIBUTES"]["OWNERID"])  ? $xmlArr["ATTRIBUTES"]["OWNERID"] : null;
        $this->m_RecordGroupId = isset($xmlArr["ATTRIBUTES"]["GROUPID"])  ? $xmlArr["ATTRIBUTES"]["GROUPID"] : null;
        $this->m_RecordGroupPerm= isset($xmlArr["ATTRIBUTES"]["GROUPPERM"]) ? $xmlArr["ATTRIBUTES"]["GROUPPERM"]: null;
        $this->m_RecordOtherPerm= isset($xmlArr["ATTRIBUTES"]["OTHERPERM"]) ? $xmlArr["ATTRIBUTES"]["OTHERPERM"]: null;
        $this->m_RecordOwnerId_AutoLoad  = isset($xmlArr["ATTRIBUTES"]["OWNERID"])?false:true;
        $this->m_RecordGroupId_AutoLoad  = isset($xmlArr["ATTRIBUTES"]["GROUPID"])?false:true;
        $this->m_RecordGroupPerm_AutoLoad = isset($xmlArr["ATTRIBUTES"]["GROUPPERM"])?false:true;
        $this->m_RecordOtherPerm_AutoLoad = isset($xmlArr["ATTRIBUTES"]["OTHERPERM"])?false:true;
    }
render ()
Render element, according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 174 of file ColumnShare.php.
References $m_DefaultImg, $m_GroupSharedImg, $m_MyAssignedImg, $m_MyDistributedImg, $m_MyPrivateImg, $m_MySharedImg, MetaObject\$m_Name, $m_OtherSharedImg, Expression\evaluateExpression(), Element\getFormObj(), Element\getFunction(), Resource\getImageUrl(), LabelText\getLink(), Element\getStyle(), LabelText\getTarget(), LabelText\getText(), and getValue().
    {
  $style = $this->getStyle();
        $text = $this->getText();
        $id = $this->m_Name;
        $func = $this->getFunction();
       switch($this->getValue()){
         case "0":
          $image_url = $this->m_MyPrivateImg;
          break;
         case "1":
          $image_url = $this->m_MySharedImg;
          break;
         case "2":
          $image_url = $this->m_GroupSharedImg;
          break;
         case "3":
          $image_url = $this->m_OtherSharedImg;
          break;
         case "4":
          $image_url = $this->m_MyAssignedImg;
          break;
         case "5":
          $image_url = $this->m_MyDistributedImg;
          break;
         default:
          if($this->m_DefaultImg=='{RESOURCE_URL}/common/images/icon_data_shared_other.gif'){
           $this->m_DefaultImg = $this->m_OtherSharedImg;
          }
          $image_url = $this->m_DefaultImg;
          break;
       }
        if(preg_match("/\{.*\}/si",$image_url))
        {
         $formobj = $this->getFormObj();
         $image_url =  Expression::evaluateExpression($image_url, $formobj);
        }else{
         $image_url = Resource::getImageUrl()."/".$image_url;
        }
        if($this->m_Width)
        {
         $width = "width=\"$this->m_Width\"";
        }
     if ($this->m_Link)
        {
            $link = $this->getLink();
            $target = $this->getTarget();
            $sHTML = "<a   id=\"$id\" href=\"$link\" $target $func $style><img $width src='$image_url' /></a>";
        }else{
         $sHTML = "<img id=\"$id\"  alt=\"".$text."\" title=\"".$text."\" $width src='$image_url' />";
        }
        return  $sHTML;
    }
setValue ($value)
Definition at line 80 of file ColumnShare.php.
References Element\getFormObj(), and hasOwnerField().
{
  $formObj = $this->getFormObj();
        $rec = $formObj->getActiveRecord();
        if($this->m_RecordOwnerId_AutoLoad)
        {
         $this->m_hasOwnerField = $this->hasOwnerField();
         if($this->m_hasOwnerField){
          $this->m_RecordOwnerId = $rec['owner_id'];
          $this->m_RecordCreatorId = $rec['create_by'];
         }else{
          $this->m_RecordOwnerId = $rec['create_by'];
         }
        }
     if($this->m_RecordGroupId_AutoLoad)
        {
         $this->m_RecordGroupId = $rec['group_id'];
        }
        if($this->m_RecordGroupPerm_AutoLoad)
        {
         $this->m_RecordGroupPerm = $rec['group_perm'];
        }
        if($this->m_RecordOtherPerm_AutoLoad)
        {
         $this->m_RecordOtherPerm = $rec['other_perm'];
        }
    }
Field Documentation
$m_DefaultImg
Definition at line 36 of file ColumnShare.php.
Referenced by render().
$m_GroupSharedImg
Definition at line 34 of file ColumnShare.php.
Referenced by render().
$m_hasOwnerField
Definition at line 49 of file ColumnShare.php.
$m_MyAssignedImg
Definition at line 32 of file ColumnShare.php.
Referenced by render().
$m_MyDistributedImg
Definition at line 33 of file ColumnShare.php.
Referenced by render().
$m_MyPrivateImg
Definition at line 30 of file ColumnShare.php.
Referenced by render().
$m_MySharedImg
Definition at line 31 of file ColumnShare.php.
Referenced by render().
$m_OtherSharedImg
Definition at line 35 of file ColumnShare.php.
Referenced by render().
$m_RecordCreatorId
Definition at line 42 of file ColumnShare.php.
$m_RecordGroupId
Definition at line 39 of file ColumnShare.php.
$m_RecordGroupId_AutoLoad protected
Definition at line 45 of file ColumnShare.php.
$m_RecordGroupPerm
Definition at line 40 of file ColumnShare.php.
$m_RecordGroupPerm_AutoLoad protected
Definition at line 46 of file ColumnShare.php.
$m_RecordOtherPerm
Definition at line 41 of file ColumnShare.php.
$m_RecordOtherPerm_AutoLoad protected
Definition at line 47 of file ColumnShare.php.
$m_RecordOwnerId
Definition at line 38 of file ColumnShare.php.
$m_RecordOwnerId_AutoLoad protected
Definition at line 44 of file ColumnShare.php.