Openbiz Framework API: LabelTextarea Class Reference
LabelTextarea Class Reference
Public Member Functions
render ()
Public Member Functions inherited from LabelText
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Additional Inherited Members
Data Fields inherited from LabelText
$m_DisplayFormat
$m_FieldName
$m_Label
$m_Link
$m_MaxLength
$m_Percent
$m_StripTags
$m_Target
$m_Text
Protected Member Functions inherited from LabelText
getLink ()
getTarget ()
getText ()
readMetaData (&$xmlArr)
Detailed Description
Definition at line 29 of file LabelTextarea.php.
Member Function Documentation
render ()
Render, draw the element according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 36 of file LabelTextarea.php.
References MetaObject\$m_Name, Element\$m_Value, Element\getFunction(), Resource\getImageUrl(), LabelText\getLink(), Element\getStyle(), LabelText\getTarget(), LabelText\getText(), and Element\translateString().
    {
       $value = $this->m_Text ? $this->getText() : $this->m_Value;
        if ($value == null || $value =="")
            return "";
        $style = $this->getStyle();
        $id = $this->m_Name;
        $func = $this->getFunction();
        if ($this->m_Translatable == 'Y')
            $value = $this->translateString($value);
        if((int)$this->m_MaxLength>0){
         if(function_exists('mb_strlen') && function_exists('mb_substr')){
          if(mb_strlen($value,'UTF8') > (int)$this->m_MaxLength){
           $value = mb_substr($value,0,(int)$this->m_MaxLength,'UTF8').'...';
          }
         }else{
          if(strlen($value) > (int)$this->m_MaxLength){
           $value = substr($value,0,(int)$this->m_MaxLength).'...';
          }
         }
        }
        /*
         * it is important converting not just nl2br
         *
         */
        //$value = htmlentities($value);
        $value = htmlentities($value, ENT_QUOTES, "UTF-8");
        $value = str_replace("\n\n","\n<img src=\"".Resource::getImageUrl()."/spacer.gif\" style=\"display:block;height:10px;\">",$value);
        $value = nl2br($value);
        if ($value!=null)
        {
         if($this->m_DisplayFormat)
         {
          $value = sprintf($this->m_DisplayFormat,$value);
         }
         if($this->m_Percent=='Y')
         {
          $value = sprintf("%.2f",$value*100).'%';
         }
            if ($this->m_Link)
            {
                $link = $this->getLink();
                $target = $this->getTarget();
                //$sHTML = "<a href=\"$link\" onclick=\"SetOnLoadNewView();\" $style>" . $val . "</a>";
                $sHTML = "<a id=\"$id\" href=\"$link\" $target $func $style>" . $value . "</a>";
            }
            else
            {
                $sHTML = "<span $style $func>" . $value . "</span>";
            }
        }
        return $sHTML;    }