Openbiz Framework API: genIdService Class Reference
genIdService Class Reference
Public Member Functions
__construct ()
getNewID ($idGeneration, $conn, $dbType, $table=null, $column=null)
Protected Member Functions
getNewGUID ($conn, $dbType, $table=null, $column=null)
getNewIdentity ($conn, $dbType, $table=null, $column=null)
getNewSequence ($conn, $dbtype, $sequenceName)
getNewSYSID ($conn, $tableName, $includePrefix=false, $base=-1)
getNewUUID ()
Detailed Description
Definition at line 25 of file genIdService.php.
Constructor & Destructor Documentation
__construct ()
Initialize excelService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 34 of file genIdService.php.
    {
    }
Member Function Documentation
getNewGUID ($conn, $dbType, $table = null, $column = null) protected
Get new GUID ID is generated before executing insert sql
Parameters
Zend_Db_Adapter_Abstract $conn database connection
string $dbType database type
string $table table name
string $column column name
Returns
mixed new Id
Definition at line 226 of file genIdService.php.
Referenced by getNewID().
    {
        $dbType = strtoupper($dbType);
        if ($dbType == 'mysql' || $dbType == 'PDO_DBLIB')
            $sql = "select uuid()";
        else if ($dbType == 'oracle' || $dbType == 'oci8' || $dbType == 'PDO_OCI')
            $sql = "select rawtohex(sys_guid()) from dual";
        else if ($dbType == 'msql' || $dbType == 'PDO_MYSQL')
            $sql = "select newid()";
        else
            throw new Exception("Error in generating new GUID: unsupported database type.");
        // execute sql to get the id
        $newId = $this->_getIdWithSql($conn, $sql);
        if ($newId === false)
            throw new Exception("Error in generating new GUID: unable to get a valid id.");
        return $newId;
    }
getNewID ($idGeneration, $conn, $dbType, $table = null, $column = null)
Get new Id
Parameters
string $idGeneration
Zend_Db_Adapter_Abstract $conn database connection
string $dbType database type
string $table table name
string $column column name
Returns
mixed
Definition at line 48 of file genIdService.php.
References getNewGUID(), getNewSYSID(), and getNewUUID().
    {
        try
        {
            if (!$idGeneration || $idGeneration == 'Openbiz')
            {
                $newid = $this->getNewSYSID($conn, $table, true);
            }
            elseif ($idGeneration == 'Identity')
            {
                //$newid = $this->getNewIdentity($conn, $dbtype, $table, $column);
                $newid = $conn->lastInsertId($table, $column);   // user zend_db method
            }
            elseif (strpos($idGeneration, 'Sequence:')===0)
            {
                $seqname = substr($idGeneration, 9);
                //$newid = $this->getNewSequence($conn, $dbtype, $seqname);
                $newid = $conn->nextSequenceId($seqname);   // user zend_db method
            }
            elseif ($idGeneration == 'GUID')
            {
                $newid = $this->getNewGUID($conn, $dbType, $table, $column);
            }
            elseif ($idGeneration == 'UUID')
            {
                $newid = $this->getNewUUID();
            }
            else
            {
                throw new Exception("Error in generating new ID: unsupported generation type.");
            }
        }
        catch (Exception $e)
        {
            throw new Exception($e->getMessage());
        }
        return $newid;
    }
getNewIdentity ($conn, $dbType, $table = null, $column = null) protected
Get new Identity * NOTE: ID is generated after insert sql is executed
Parameters
Zend_Db_Adapter_Abstract $conn database connection
string $dbType database type
string $table table name
string $column column name
Returns
mixed new Id
Definition at line 162 of file genIdService.php.
    {
        $dbType = strtoupper($dbType);
        if ($dbType == 'mysql' || $dbType == 'PDO_MYSQL')
        {
            $sql = "select last_insert_id()";
        }
        else if ($dbType == 'mssql' || $dbType == 'PDO_DBLIB')
            $sql = "select @@identity";
        else if ($dbType == 'sybase' || $dbType == 'PDO_DBLIB')
            $sql = "select @@identity";
        else if ($dbType == 'db2' || $dbType == 'PDO_ODBC')
            $sql = "values identity_val_local()";
        else if ($dbType == 'postgresql' || $dbType == 'PDO_PGSQL')
            $sql = "select currval('$table_$column_seq')";
        else
            throw new Exception("Error in generating new identity: unsupported database type.");
        // execute sql to get the id
        $newid = $this->_getIdWithSql($conn, $sql);
        if ($newid === false)
            throw new Exception("Error in generating new identity: unable to get a valid id.");
        return $newid;
    }
getNewSequence ($conn, $dbtype, $sequenceName) protected
Get new sequence NOTE: // ID is generated before executing insert sql
Parameters
Zend_Db_Adapter_Abstract $conn database connection
string $dbType database type
string $sequenceName
Returns
mixed
Definition at line 196 of file genIdService.php.
    {
        $dbtype = strtoupper($dbtype);
        if ($dbtype == 'oracle' || $dbtype == 'oci8' || $dbtype == 'PDO_OCI')
            $sql = "select $sequenceName.nextval from dual";
        else if ($dbtype == 'db2' || $dbtype == 'PDO_ODBC')
            $sql = "values nextval for $sequenceName";
        else if ($dbtype == 'postgresql' || $dbtype == 'PDO_PGSQL')
            $sql = "select nextval('$sequenceName')";
        else if ($dbtype == 'informix' || $dbtype == 'PDO_INFORMIX')
            "select $sequenceName.nextval from systables where tabid=1";
        else
            throw new Exception("Error in generating new sequence: unsupported database type.");
        // execute sql to get the id
        $newId = $this->_getIdWithSql($conn, $sql);
        if ($newId === false)
            throw new Exception("Error in generating new sequence: unable to get a valid id.");
        return $newId;
    }
getNewSYSID ($conn, $tableName, $includePrefix = false, $base = -1) protected
Get a new SYSID from the id_table. You can get SYSID for a table with prefix and base converting
Parameters
Zend_Db_Adapter_Abstract $conn database connection
string $tableName table name
boolean $includePrefix
integer $base to encode
Returns
string
Definition at line 96 of file genIdService.php.
Referenced by getNewID().
    {
        $maxRetry = 10;
        // try to update the table idbody column
        for ($try=1; $try <= $maxRetry; $try++)
        {
            $sql = "SELECT * FROM ob_sysids WHERE TABLENAME='$tableName'";
            try
            {
                $rs = $conn->query($sql);
            }
            catch (Exception $e)
            {
                throw new Exception("Error in query: " . $sql . ". " . $e->getMessage());
                return false;
            }
            $row = $rs->fetch();
            unset($rs);
            list($tblname, $prefix, $idbody) = $row;
            if (!$row)
                throw new Exception("Error in generating new system id: '$tableName' is not in ob_sysids table.");
            if ($row)
            {
                if ($idbody == null && $prefix) // idbody is empty, return false
                    throw new Exception("Error in generating new system id: ob_sysids table does not have a valid sequence for '$tableName'.");
            }
            // try to update the table idbody column
            $sql = "UPDATE ob_sysids SET IDBODY=IDBODY+1 WHERE TABLENAME='$tableName' AND IDBODY=$idbody";
            try
            {
                $rs = $conn->query($sql);
            }
            catch (Exception $e)
            {
                throw new Exception("Error in query: " . $sql . ". " . $e->getMessage());
                return false;
            }
            if ($rs->rowCount() > 0)
            {
                $idbody += 1;
                break;
            }
        }
        if ($try <= $maxRetry)
        {
            if ($base>=2 && $base<=36)
                $idbody = dec2base($idbody, $base);
            if ($includePrefix)
                return $prefix."_".$idbody;
            return $idbody;
        }
        else
            throw new Exception("Error in generating new system id: unable to get a valid id.");
        return false;
    }
getNewUUID () protected
Get new UUID ID is generated before executing insert sql
Returns
string the unique identifier, as a string.
Definition at line 250 of file genIdService.php.
Referenced by getNewID().
    {
        return uniqid();
    }