Openbiz Framework API: ClientProxy Class Reference
ClientProxy Class Reference
Public Member Functions
appendScripts ($scriptKey, $scripts, $isFile=true)
appendStyles ($scriptKey, $styles, $isFile=true)
closePopup ()
getAppendedScripts ()
getAppendedStyles ($comb=0)
getFormInputs ($controlName=null, $toString=TRUE)
getFormOutput ($formName)
getRequestParam ($name)
hasFormRerendered ($formName)
hasOtherOutput ()
hasOutput ()
includeBaseClientScripts ()
includeCalendarScripts ()
includeCKEditorScripts ()
includeColorPickerScripts ()
includePropWindowScripts ()
includeRTEScripts ()
includeValidatorScripts ()
printOutput ()
redirectPage ($pageURL)
redirectView ($view, $rule=null)
redrawForm ($formName, $sHTML)
runClientFunction ($scriptStr)
runClientScript ($scriptStr)
setRPCFlag ($flag)
showClientAlert ($alertText)
showErrorMessage ($errMsg, $flush=false)
showPopup ($baseForm, $popupForm, $ctrlName="")
showPopupWindow ($content, $w, $h)
updateClientElement ($elementId, $content)
updateFormElements ($formName, $recArr, $rawData=false)
Protected Member Functions
printJSONOuput ()
Protected Attributes
$m_bRPCFlag
$m_FormInputArray
$m_RequestArgs
Detailed Description
Definition at line 28 of file ClientProxy.php.
Member Function Documentation
appendScripts ($scriptKey, $scripts, $isFile = true)
Append more scripts - js include, js code
Parameters
mixed $scriptKey
string $scripts
boolean $isFile
Returns
void
Definition at line 508 of file ClientProxy.php.
Referenced by includeCalendarScripts(), includeCKEditorScripts(), includeColorPickerScripts(), includePropWindowScripts(), includeRTEScripts(), and includeValidatorScripts().
    {
        // if has the script key already, ignore
        if (isset($this->_extraScripts[$scriptKey]))
            return;
        // add the scripts
        if ($isFile)
        {
            $_scripts = "<script type='text/javascript' src=\"".Resource::getJsUrl()."/$scripts\"></script>";
            $this->_extraScripts[$scriptKey] = $_scripts;
        } else
            $this->_extraScripts[$scriptKey] = $scripts;
    }
appendStyles ($scriptKey, $styles, $isFile = true)
Append more styles - include and sections
Parameters
<type> $scriptKey
string $styles
boolean $isFile
Returns
void
Definition at line 563 of file ClientProxy.php.
References Resource\getCssUrl().
Referenced by includeCalendarScripts(), includeColorPickerScripts(), includePropWindowScripts(), and includeValidatorScripts().
    {
     // if has the script key already, ignore
        if (isset($this->_extraStyles[$scriptKey]))
            return;
        // add the styles
        $css = Resource::getCssUrl();
        if ($isFile)
        {
            $_styles = "<link rel=\"stylesheet\" href=\"$css/" . $styles . "\" type=\"text/css\">";
            $this->_extraStyles[$scriptKey] = $_styles;
        } else
            $this->_extraStyles[$scriptKey] = $styles;
    }
closePopup ()
Close popup window
Returns
void
Definition at line 366 of file ClientProxy.php.
    {
        if ($this->m_bRPCFlag){
            $this->_formsOutput[] = $this->_callClientFunction("Openbiz.Window.closePopup()");
            $this->_otherOutput[] = $this->_callClientFunction("Openbiz.Window.closePopup()");
        }
    }
getAppendedScripts ()
Get append scripts
Returns
string
Definition at line 527 of file ClientProxy.php.
References BizSystem\instance().
    {
        $currentView = BizSystem::instance()->getCurrentViewName();
        $initScripts = "<script>var APP_URL='".APP_URL."'; var APP_CONTROLLER='".APP_URL."/bin/controller.php';</script>\n";
        $initScripts .= "<script>var APP_VIEWNAME='".$currentView."';</script>\n";
        $extraScripts = implode("", $this->_extraScripts);
        $extraScript_array = explode("</script>", $extraScripts);
        /*if (defined("RESOURCE_PHP")) {
            $js_scripts = RESOURCE_PHP."?f=";
            foreach ($extraScript_array as $script)
            {
                // extract src part from each line
                if (preg_match('/.+src="([^"]+)".+/', $script, $matches) > 0 && !empty($matches[1])) {
                    if (substr($js_scripts, -2)=='f=') $js_scripts .= $matches[1];
                    else $js_scripts .= ','.$matches[1];
                }
            }
            return $initScripts."<script type=\"text/javascript\" src=\"".$js_scripts."\"></script>";
        }*/
        $cleanScript_array = array();
        foreach ($extraScript_array as $script)
        {
            if (in_array($script . "</script>", $cleanScript_array) == FALSE and strlen($script) != 0)
                $cleanScript_array[] = $script . "</script>";
        }
        return $initScripts.implode("\n", $cleanScript_array);
    }
getAppendedStyles ($comb = 0)
Get appended styles
Returns
string
Definition at line 583 of file ClientProxy.php.
References APP_HOME, I18n\getCurrentLangCode(), and RESOURCE_PHP.
    {
        $extraStyles = implode("", $this->_extraStyles);
        $extraStyle_array = explode("type=\"text/css\">", $extraStyles);
        if (defined("RESOURCE_PHP") && $comb) {
            $css_scripts = RESOURCE_PHP."?f=";
            foreach ($extraStyle_array as $style)
            {
                // extract href part from each line
                if (preg_match('/.+href="([^"]+)".+/', $style, $matches) > 0 && !empty($matches[1])) {
                    if (substr($css_scripts, -2)=='f=') $css_scripts .= $matches[1];
                    else $css_scripts .= ','.$matches[1];
                }
            }
            return "<link rel=\"stylesheet\" href=\"".$css_scripts."\" type=\"text/css\"/>";
        }
        $cleanStyle_array = array();
        foreach ($extraStyle_array as $style)
        {
            if (in_array($style . "type=\"text/css\">", $cleanStyle_array) == FALSE and strlen($style) != 0)
                $cleanStyle_array[] = $style . "type=\"text/css\">";
        }
        //added by Jixian for supports localization display styles
        // eg.: override button width for specified languages
        $lang = I18n::getCurrentLangCode();
        $localization_css_file = APP_HOME.DIRECTORY_SEPARATOR."languages".DIRECTORY_SEPARATOR.$lang.DIRECTORY_SEPARATOR."localization.css";
        if(is_file($localization_css_file)){
         $cleanStyle_array[] = "<link rel=\"stylesheet\" href=\"".APP_URL."/languages/$lang/localization.css\" type=\"text/css\">";
        }
        return implode("\n", $cleanStyle_array);
    }
getFormInputs ($controlName = null, $toString = TRUE)
Get form all inputs or one input if controlName is given
Parameters
string $controlName
boolean $toString - Convert array oriented form controls to string?
Returns
array|string
Definition at line 167 of file ClientProxy.php.
    {
        if ($controlName)
        {
            if (isset($_GET[$controlName]))
            {
                $_POST[$controlName] = $_GET[$controlName];
            }
            if (isset($_POST[$controlName]))
            {
                if (is_array($_POST[$controlName]) and $toString == TRUE)
                {
                    $array_string = '';
                    foreach ($_POST[$controlName] as $rec)
                    {
                        $array_string .= $rec . ",";
                    }
                    $result = substr($array_string, 0, strlen($array_string) - 1);
                }
                else
                {
                    $result = $_POST[$controlName];
                }
                if (get_magic_quotes_gpc() == 1)
                {
                    if (!is_array($result))
                        $result = stripslashes($result);
                }
                return $result;
            }
            else
            {
                if(isset($_FILES[$controlName])){
                 $result =true;
                 return $result;
             }else{
                 return null;
             }
            }
        }
        else
        {
            return $_POST;
        }
    }
getFormOutput ($formName)
Get form output.
Parameters
string $formName
Returns
string HTML output of form
Definition at line 76 of file ClientProxy.php.
    {
        return $this->_formsOutput[$formName];
    }
getRequestParam ($name)
Get request parameter, get the client form data passed by GET or POST NOTE: NYU - not yet used
Parameters
string $name name of parameter
Returns
string value of paramater
Definition at line 154 of file ClientProxy.php.
    {
        $val = (isset($_REQUEST[$name]) ? $_REQUEST[$name] : "");
        return $val;
    }
hasFormRerendered ($formName)
Check has form rendered?
Form has rendered if _formsOutput[$formName] exist. See ReDrawForm method.
Parameters
string $formName
Returns
boolean true if form rendered (formName exist on _formsOutput)
Definition at line 65 of file ClientProxy.php.
    {
        return array_key_exists($formName, $this->_formsOutput);
    }
hasOtherOutput ()
Check has other output? NOTE: NYU - not yet used
Returns
boolean true if has other output
Definition at line 87 of file ClientProxy.php.
    {
        return count($this->_otherOutput) > 0;
    }
hasOutput ()
Check has output (other output and/or forms output)
Returns
boolean true if has output
Definition at line 97 of file ClientProxy.php.
    {
        return count($this->_otherOutput) + count($this->_formsOutput) > 0;
    }
includeBaseClientScripts ()
Include base client library scripts
Returns
void
Definition at line 620 of file ClientProxy.php.
References BizSystem\clientProxy().
    {
        if (defined('JSLIB_BASE') && JSLIB_BASE == 'JQUERY') {
   BizSystem::clientProxy()->appendScripts("jquery", "jquery.js");
   BizSystem::clientProxy()->appendScripts("jquery_class", "jquery.class.js");
   BizSystem::clientProxy()->appendScripts("jquery_dollarj", "<script>try{var \$j=\$;}catch(e){}</script>", false);
   BizSystem::clientProxy()->appendStyles("default", "openbiz.css");
   if (DeviceUtil::$PHONE_TOUCH) {
    BizSystem::clientProxy()->appendScripts("openbiz", "openbiz.mobile.js");
    BizSystem::clientProxy()->appendScripts("jquery_mobile", "jqm/jquery.mobile-1.0.js");
    $style = "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/jqm/jquery.mobile-1.0.css\" type=\"text/css\">";
    BizSystem::clientProxy()->appendStyles("jquery_mobile_css", $style, false);
   }
   else {
    BizSystem::clientProxy()->appendScripts("openbiz", "openbiz.js");
    BizSystem::clientProxy()->appendScripts("jquery_ui", "jquery-ui-1.8.16.custom.min.js");
    $style = "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/jquery-ui/ui-lightness/jquery-ui-1.8.16.custom.css\" type=\"text/css\">";
    $style .= "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/jquery-ui/ui-openbiz/jquery.css\" type=\"text/css\">";
    BizSystem::clientProxy()->appendStyles("jquery_ui_css", $style, false);
   }
   return;
  }
  // prototype is still the default js lib
        BizSystem::clientProxy()->appendScripts("prototype", "prototype.js");
        BizSystem::clientProxy()->appendScripts("scriptaculous", "scriptaculous.js");
        BizSystem::clientProxy()->appendScripts("effects", "effects.js");
        BizSystem::clientProxy()->appendScripts("controls", "controls.js");
        BizSystem::clientProxy()->appendScripts("cookies", "cookies.js");
        BizSystem::clientProxy()->appendScripts("openbiz", "openbiz.js");
        BizSystem::clientProxy()->appendStyles("default", "openbiz.css");
        // window lib
        BizSystem::clientProxy()->includePropWindowScripts();
        // validator lib
        //BizSystem::clientProxy()->includeValidatorScripts();
    }
includeCalendarScripts ()
Include calendar scripts
Returns
void
Definition at line 661 of file ClientProxy.php.
References appendScripts(), and appendStyles().
    {
        if (isset($this->_extraScripts['calendar']))
            return;
        $style = "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/jscalendar/calendar-system.css\" type=\"text/css\">";
        $script = "<script type='text/javascript' src='".Resource::getJsUrl()."/jscalendar/calendar.js'></script>";
        $script .= "<script type='text/javascript' src='".Resource::getJsUrl()."/jscalendar/lang/calendar-en.js'></script>";
        $script .= "<script type='text/javascript' src='".Resource::getJsUrl()."/jscalendar/calendar-setup.js'></script>";
        $script .= "<script type='text/javascript' src='".Resource::getJsUrl()."/calendar.js'></script>";
        $this->appendStyles("calendar", $style, false);
        $this->appendScripts("calendar", $script, false);
    }
includeCKEditorScripts ()
Include CKEditor scripts
Returns
void
Definition at line 713 of file ClientProxy.php.
References appendScripts().
    {
        if (isset($this->_extraScripts['ckeditor']))
            return;
        $script = "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/ckeditor/ckeditor.js\"></script>";
        $this->appendScripts("ckeditor", $script, false);
    }
includeColorPickerScripts ()
Include calendar scripts
Returns
void
Definition at line 680 of file ClientProxy.php.
References appendScripts(), and appendStyles().
    {
        if (isset($this->_extraScripts['colorpicker']))
            return;
        $style = "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/colorpicker/css/colorpicker.css\" type=\"text/css\">";
        if(JSLIB_BASE != 'JQUERY'){
         $script = "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/jquery.js\"></script>";
        }
        $script .= "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/colorpicker/js/eye.js\"></script>";
        $script .= "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/colorpicker/js/utils.js\"></script>";
        $script .= "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/colorpicker/js/colorpicker.js\"></script>";
        $this->appendStyles("colorpicker", $style, false);
        $this->appendScripts("colorpicker", $script, false);
    }
includePropWindowScripts ()
Include PropWindow scripts
Returns
void
Definition at line 728 of file ClientProxy.php.
References appendScripts(), and appendStyles().
    {
        $this->appendScripts("scriptaculous", "scriptaculous.js");
        $this->appendScripts("prop_window", "window.js");
        $style = "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/window/default.css\" type=\"text/css\">";
        //$style .= "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/window/spread.css\" type=\"text/css\">";
        //$style .= "<link rel=\"stylesheet\" href=\"".Resource::getJsUrl()."/window/lighting.css\" type=\"text/css\">";
        $this->appendStyles("prop_window", $style, false);
    }
includeRTEScripts ()
Include RTE scripts
Returns
void
Definition at line 699 of file ClientProxy.php.
References appendScripts().
    {
        if (isset($this->_extraScripts['rte']))
            return;
        $script = "<script type=\"text/javascript\" src=\"".Resource::getJsUrl()."/richtext.js\"></script>";
        $script .= "<script language=\"JavaScript\">initRTE('".Resource::getImageUrl()."/rte/', '../pages/rte/', '', false);</script>";
        $this->appendScripts("rte", $script, false);
    }
includeValidatorScripts ()
Include validator scripts
Returns
void
Definition at line 743 of file ClientProxy.php.
References appendScripts(), and appendStyles().
    {
        $this->appendScripts("yav", "yav/yav.js");
        $this->appendScripts("yav-cfg", "yav/yav-config.js");
        //$this->appendScripts("validator", "validator.js");
        $style = "<link rel=\"stylesheet\" href=\"".Resource::getCssUrl()."/validator.css\" type=\"text/css\">";
        $this->appendStyles("yav", $style, false);
    }
printJSONOuput () protected
Definition at line 118 of file ClientProxy.php.
Referenced by printOutput().
    {
        $outs = array();
        // output JSON
        foreach ($this->_otherOutput as $output)
            $outs[] = $output;
        foreach ($this->_formsOutput as $output)
            $outs[] = $output;
        if (function_exists("json_encode"))
            echo json_encode($outs);
        else
        {
            require_once 'Zend/Json.php';
            echo Zend_Json::encode($outs);
        }
    }
printOutput ()
Print output.
Returns
void
Definition at line 107 of file ClientProxy.php.
References printJSONOuput().
    {
        if ($this->m_bRPCFlag == true)
            return $this->printJSONOuput();
        foreach ($this->_otherOutput as $output)
            print $output;
        foreach ($this->_formsOutput as $output)
            print $output;
    }
redirectPage ($pageURL)
Redirect page to the given url. Encoded html string returns to browser, it'll be processed by client javascript. NOTE: NYU - not yet used
Parameters
string $pageURL
Returns
void
Definition at line 457 of file ClientProxy.php.
Referenced by redirectView().
    {
        if (!$this->m_bRPCFlag) {
            $func = (isset($_REQUEST['F']) ? $_REQUEST['F'] : "");
            if ($func == "RPCInvoke")
                $this->m_bRPCFlag = true;
        }
  if (!$this->m_bRPCFlag)
        {
            ob_clean();
            header("Location: $pageURL");
            return;
        }
        if ($pageURL == "#back")
            $this->_otherOutput[] = $this->_callClientFunction("history.go(-1)");
        else
        {
         $pageURL = str_replace("&", "&amp;", $pageURL);
            $this->_otherOutput[] = $this->_callClientFunction("Openbiz.Net.redirectPage('$pageURL')");
        }
    }
redirectView ($view, $rule = null)
Redirect page to the given view. Encoded html string returns to browser, it'll be processed by client javascript.
Parameters
string $view full name of view (with package)
string $rule
Returns
void
Definition at line 487 of file ClientProxy.php.
References APP_INDEX, BizSystem\clientProxy(), and redirectPage().
    {
        // get the view url form view name
        $viewParts = explode('.',$view);
        $viewMod = $viewParts[0];
        $viewName = $viewParts[count($viewParts)-1];
        $viewName = strtolower(str_replace("View","",$viewName));
        $url = APP_INDEX."/$viewMod/$viewName";
        //echo "$view page url is $url. $this->m_bRPCFlag";
        $this->redirectPage($url);
        BizSystem::clientProxy()->printOutput();
    }
redrawForm ($formName, $sHTML)
Replace the form content with the provided html text, encoded html string returns to browser, it'll be processed by client javascript.
Parameters
string $formName - name of the html form on client
string $sHTML - html text to redraw the form
Returns
void
Definition at line 248 of file ClientProxy.php.
    {
        if ($this->m_bRPCFlag)
            $this->_formsOutput[$formName] = $this->_buildTargetContent($formName, $sHTML);
        else
            $this->_formsOutput[$formName] = $sHTML;
    }
runClientFunction ($scriptStr)
Definition at line 417 of file ClientProxy.php.
    {
        $msg = addslashes($alertText);
        if ($this->m_bRPCFlag)
            $this->_otherOutput[] = $this->_callClientFunction($scriptStr);
    }
runClientScript ($scriptStr)
Run client script
Parameters
string $scriptStr
Returns
void
Definition at line 407 of file ClientProxy.php.
Referenced by updateClientElement().
    {
        if ($this->m_bRPCFlag)
            $this->_otherOutput[] = $this->_buildTargetContent("SCRIPT", $scriptStr);
        else
        {
            echo $script;
        }
    }
setRPCFlag ($flag)
Set RPC flag.
Parameters
boolean $flag
Returns
void
Definition at line 141 of file ClientProxy.php.
    {
        $this->m_bRPCFlag = $flag;
    }
showClientAlert ($alertText)
Show popup an alert window on the client browser. Encoded html string returns to browser, it'll be processed by client javascript.
Parameters
string $alertText
Returns
void
Definition at line 263 of file ClientProxy.php.
    {
        $msg = addslashes($alertText);
        if ($this->m_bRPCFlag)
            $this->_otherOutput[] = $this->_callClientFunction("alert('" . $msg . "')");
    }
showErrorMessage ($errMsg, $flush = false)
Show error message.
If its a remote call, it uses javascript If it is not a remote call, it outputs to the page's html
Parameters
char $errMsg
Returns
void
Definition at line 279 of file ClientProxy.php.
References BizSystem\getObject().
    {
        if(!$errMsg){
      return;
     }
        if ($this->m_bRPCFlag)
        {
            /*
         $this->_otherOutput[] = $this->_buildTargetContent("ERROR", $errMsg);
            if ($flush) {
                $this->printOutput();
                exit;
            }*/
         $_GET['ob_err_msg']=$errMsg;
         ob_end_clean();
         $form = "common.form.ErrorPopupForm";
         $html = BizSystem::getObject($form)->render();
         $html = $this->_buildTargetContent("DIALOG", $html);
         $this->_formsOutput[]=$html;
        }
        else
        {
            $this->_errorOutput($errMsg);
        }
    }
showPopup ($baseForm, $popupForm, $ctrlName = "")
Show popup window
Parameters
string $baseForm
string $popupForm
string $ctrlName
Returns
void
Definition at line 313 of file ClientProxy.php.
    {
        if ($this->m_bRPCFlag)
        {
            $function = $baseForm . ".ShowPopup(" . $popupForm . "," . $ctrlName . ")";
            $this->_otherOutput[] = $this->_callClientFunction("CallFunction('$function','Popup')");
        }
    }
showPopupWindow ($content, $w, $h)
Show popup window
Parameters
string $content
number $w width of window
number $h height of window
Returns
void
Definition at line 382 of file ClientProxy.php.
    {
        if ($this->m_bRPCFlag)
            $this->_formsOutput[] = $this->_callClientFunction("popupWindow(\"$content\", $w, $h)");
    }
updateClientElement ($elementId, $content)
Update client element
Parameters
string $elementId
string $content
Returns
void
Definition at line 395 of file ClientProxy.php.
References runClientScript().
    {
        $scriptStr = "<script>$('".$elementId."').innerHTML='".$content."';</script>";
        $this->runClientScript($scriptStr);
    }
updateFormElements ($formName, $recArr, $rawData = false)
Update the form elements/controls on the client UI Return to client browser : array or string
Parameters
string $formName - name of the html form on client
array $recArr - name/value pairs
Returns
void
Definition at line 221 of file ClientProxy.php.
    {
        if ($this->m_bRPCFlag)
        {
            if ($rawData)
            {
             $fieldsOutput = $recArr;
             $this->_otherOutput[] = $this->_buildTargetContent($formName,$fieldsOutput);
            }
            else
            {
          foreach ($recArr as $fld => $val)
              $fieldsOutput[] = $this->_buildTargetContent($fld,$val);
             $this->_otherOutput[] = $this->_buildTargetContent($formName,$fieldsOutput);
            }
        }
    }
Field Documentation
$m_bRPCFlag protected
Definition at line 32 of file ClientProxy.php.
$m_FormInputArray protected
Definition at line 31 of file ClientProxy.php.
$m_RequestArgs protected
Definition at line 30 of file ClientProxy.php.