Openbiz Framework API: BizDataObj_Abstract Class Reference
BizDataObj_Abstract Class Reference
Public Member Functions
__construct (&$xmlArr)
clearAllRules ()
clearOtherSQLRule ()
clearSearchRule ()
clearSortRule ()
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0)
fetch ()
find ()
getAssociation ()
getDBConnection ($type='default')
getParameter ($paramName)
getProperty ($propertyName)
getRefObject ($objName)
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
resetRules ()
setLimit ($count, $offset=0)
setOtherSQLRule ($rule)
setQueryParam ($queryStr, $paramValues)
setSearchRule ($rule, $overWrite=false)
setSessionVars ($sessionContext)
setSortRule ($rule)
updateRecord ($recArr, $oldRec=null)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_AccessRule
$m_BaseOtherSQLRule
$m_BaseSearchRule
$m_BaseSortRule
$m_BizRecord
$m_CacheLifeTime
$m_Database
$m_DataPermControl
$m_DeleteCondition
$m_IdGeneration
$m_InheritFrom
$m_MainTable
$m_MessageFile
$m_ObjReferences
$m_OtherSQLRule
$m_Parameters
$m_SearchRule
$m_SortRule
$m_Stateless
$m_TableJoins
$m_Uniqueness
$m_UpdateCondition
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getMessage ($msgid, $params=array())
inheritParentObj ()
readMetadata (&$xmlArr)
setAssociation ($objRef, $asscObj)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_Limit
$m_Messages
Detailed Description
Definition at line 32 of file BizDataObj_Abstract.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize BizDataObj_Abstract with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 192 of file BizDataObj_Abstract.php.
References inheritParentObj(), and readMetadata().
    {
        $this->readMetadata($xmlArr);
        $this->inheritParentObj();
    }
Member Function Documentation
clearAllRules ()
Reset all rules (search, sort, other SQL rule)
Returns
void
Definition at line 369 of file BizDataObj_Abstract.php.
References $m_BaseOtherSQLRule, $m_BaseSearchRule, and $m_BaseSortRule.
    {
        $this->m_SearchRule = $this->m_BaseSearchRule;
        $this->m_SortRule = $this->m_BaseSortRule;
        $this->m_OtherSQLRule = $this->m_BaseOtherSQLRule;
        $this->m_Limit = array();
        return $this;
    }
clearOtherSQLRule ()
Clear other SQL rule. Reset the other SQL rule to default other SQL rule set in metadata
Returns
void
Definition at line 357 of file BizDataObj_Abstract.php.
References $m_BaseOtherSQLRule.
    {
        $this->m_OtherSQLRule = $this->m_BaseOtherSQLRule;
        return $this;
    }
clearSearchRule ()
Clear search rule. Reset the search rule to default search rule set in metadata
Returns
void
Definition at line 332 of file BizDataObj_Abstract.php.
References $m_BaseSearchRule.
Referenced by BizDataObj_Lite\directFetch(), and BizDataObj_Lite\fetchRecords().
    {
        $this->m_SearchRule = $this->m_BaseSearchRule;
        return $this;
    }
clearSortRule ()
Clear sort rule. Reset the sort rule to default sort rule set in metadata
Returns
void
Definition at line 344 of file BizDataObj_Abstract.php.
References $m_BaseSortRule.
Referenced by BizDataObj_Lite\directFetch().
    {
        $this->m_SortRule = $this->m_BaseSortRule;
        return $this;
    }
count () abstract
Count the number of record according to the search results set before. it ignores limit setting
Returns
int number of records
deleteRecord ($recArr) abstract
Delete current record or delete the given input record
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
directFetch ($searchRule = "", $count = -1, $offset = 0) abstract
Fetches SQL result rows as a sequential array without using query rules set before. Sample code:
  // fetch all record with firstname starting with Mike
  $do->directFetch("[FirstName] LIKE 'Mike%'");
  // fetch first 10 records with firstname starting with Mike
  $do->directFetch("[FirstName] LIKE 'Mike%'", 10);
  // fetch 20th-30th records with firstname starting with Mike
  $do->directFetch("[FirstName] LIKE 'Mike%'", 10, 20);
Parameters
string $searchRule the search rule string
int $count number of records to return
int $offset the starting point of the return records
Returns
array array of records
fetch () abstract
Fetches SQL result rows as a sequential array according the query rules set before. Sample code:
  $do->resetRules();
  $do->setSearchRule($search_rule1);
  $do->setSearchRule($search_rule2);
  $do->setSortRule($sort_rule);
  $do->SetOtherRule($groupby);
  $total = $do->count();
  $do->setLimit($count, $offset=0);
  $recordSet = $do->fetch();
Returns
array array of records
find () abstract
Do the search query and return results set as PDOStatement. Sample code:
  $do->resetRules();
  $do->setSearchRule($search_rule1);
  $do->setSearchRule($search_rule2);
  $do->setSortRule($sort_rule);
  $do->SetOtherRule($groupby);
  $total = $do->count();
  $do->setLimit($count, $offset=0);
  $resultSet = $do->find();
  $do->getDBConnection()->setFetchMode(PDO::FETCH_ASSOC);
  while ($record = $resultSet->fetch())
  {
      print_r($record);
  }
Returns
PDOStatement PDO statement object
getAssociation ()
Get the Association (array)
Returns
array array of association
Definition at line 555 of file BizDataObj_Abstract.php.
    {
        return $this->m_Association;
    }
getDBConnection ($type = 'default')
Get database connection
Returns
Zend_Db_Adapter_Abstract
Definition at line 463 of file BizDataObj_Abstract.php.
References $m_Database, and BizSystem\dbConnection().
Referenced by BizDataObj_Lite\_run_search(), BizDataObj_Lite\count(), BizDataObj\deleteRecord(), BizDataObj\deleteRecords(), BizDataObj\generateId(), BizDataObj\insertRecord(), BizDataObj\processCascadeAction(), BizDataObj\updateRecord(), and BizDataObj\updateRecords().
    {
     switch(strtolower($type))
     {
      case "default":
      case "read":
       if($this->m_DatabaseforRead){
        $dbName = $this->m_DatabaseforRead;
       }
       else
       {
        $dbName = $this->m_Database;
       }
       break;
      case "write":
       if($this->m_DatabaseforWrite){
        $dbName = $this->m_DatabaseforWrite;
       }
       else
       {
        $dbName = $this->m_Database;
       }
       break;
     }
        return BizSystem::dbConnection($dbName);
    }
getMessage ($msgid, $params = array()) protected
Get Message
Parameters
<type> $msgid message Id
array $params
Returns
string
Definition at line 288 of file BizDataObj_Abstract.php.
References MetaObject\getModuleName(), and I18n\t().
Referenced by BizDataObj_Lite\_run_search(), BizDataObj\deleteRecord(), BizDataObj\deleteRecords(), BizDataObj\insertRecord(), BizDataObj\processCascadeAction(), BizDataObj\updateRecord(), BizDataObj\updateRecords(), BizDataObj\validateInput(), and BizDataObj\validateUniqueness().
    {
        $message = isset($this->m_Messages[$msgid]) ? $this->m_Messages[$msgid] : constant($msgid);
        //$message = I18n::getInstance()->translate($message);
        $message = I18n::t($message, $msgid, $this->getModuleName($this->m_Name));
        return vsprintf($message,$params);
    }
getParameter ($paramName)
Get object parameter value
Parameters
string $paramName name of the parameter
Returns
string parameter value
Definition at line 523 of file BizDataObj_Abstract.php.
    {
        return $this->m_Parameters[$paramName]->m_Value;
    }
getProperty ($propertyName)
Get the property of the object. Used in expression language
Parameters
string $propertyName name of the property
Returns
BizField|string property value
Definition at line 496 of file BizDataObj_Abstract.php.
References $m_SearchRule.
    {
        $ret = parent::getProperty($propertyName);
        if ($ret) return $ret;
        if ($propertyName == "Table") return $this->m_Table;
        if ($propertyName == "SearchRule") return $this->m_SearchRule;
        // get control object if propertyName is "Field[fldname]"
        $pos1 = strpos($propertyName, "[");
        $pos2 = strpos($propertyName, "]");
        if ($pos1>0 && $pos2>$pos1)
        {
            $propType = substr($propertyName, 0, $pos1);
            $fieldName = substr($propertyName, $pos1+1,$pos2-$pos1-1);
            if ($propType == "param")
            {   // get parameter
                return $this->m_Parameters->get($fieldName);
            }
            return $this->getField($fieldName);
        }
    }
getRefObject ($objName)
Get the object instance defined in the object reference
Parameters
string $objName the object name list in the ObjectReference part
Returns
BizDataObj object instance
Definition at line 534 of file BizDataObj_Abstract.php.
References BizSystem\getObject().
Referenced by BizDataObj\processCascadeAction().
    {
        // see if there is such object in the ObjReferences
        $objRef = $this->m_ObjReferences->get($objName);
        if (!$objRef)
            return null;
        // apply association on the object
        // $assc = $this->EvaluateExpression($objRef->m_Association);
        // get the object instance
        $obj = BizSystem::getObject($objName);
        $obj->setAssociation($objRef, $this);
        return $obj;
    }
getSessionVars ($sessionContext)
Get session variables
Parameters
SessionContext $sessionContext
Implements iSessionObject.
Definition at line 301 of file BizDataObj_Abstract.php.
    {}
inheritParentObj () protected
Inherit from parent object. Name, Package, Class cannot be inherited
Returns
void
Definition at line 252 of file BizDataObj_Abstract.php.
References $m_SearchRule, $m_SortRule, and BizSystem\getObject().
Referenced by __construct().
    {
        if (!$this->m_InheritFrom) return;
        $parentObj = BizSystem::getObject($this->m_InheritFrom);
        $this->m_Description  = $this->m_Description ? $this->m_Description : $parentObj->m_Description;
        $this->m_SearchRule   = $this->m_SearchRule ? $this->m_SearchRule : $parentObj->m_SearchRule;
        $this->m_BaseSearchRule = $this->m_SearchRule;
        $this->m_SortRule     = $this->m_SortRule ? $this->m_SortRule: $parentObj->m_SortRule;
        $this->m_BaseSortRule = $this->m_SortRule;
        $this->m_OtherSQLRule = $this->m_OtherSQLRule ? $this->m_OtherSQLRule: $parentObj->m_OtherSQLRule;
        $this->m_AccessRule   = $this->m_AccessRule ? $this->m_AccessRule: $parentObj->m_AccessRule;
        $this->m_UpdateCondition = $this->m_UpdateCondition ? $this->m_UpdateCondition: $parentObj->m_UpdateCondition;
        $this->m_DeleteCondition = $this->m_DeleteCondition ? $this->m_DeleteCondition: $parentObj->m_DeleteCondition;
        $this->m_Database     = $this->m_Database ? $this->m_Database: $parentObj->m_Database;
        $this->m_MainTable    = $this->m_MainTable ? $this->m_MainTable: $parentObj->m_MainTable;
        $this->m_IdGeneration = $this->m_IdGeneration ? $this->m_IdGeneration: $parentObj->m_IdGeneration;
        $this->m_Stateless    = $this->m_Stateless ? $this->m_Stateless: $parentObj->m_Stateless;
  $this->m_DataPermControl = $this->m_DataPermControl ? $this->m_DataPermControl : $parentObj->m_DataPermControl;
        $this->m_BizRecord->merge($parentObj->m_BizRecord);
        foreach ($this->m_BizRecord as $field)
            $field->adjustBizObjName($this->m_Name);
        $this->m_TableJoins->merge($parentObj->m_TableJoins);
        $this->m_ObjReferences->merge($parentObj->m_ObjReferences);
        $this->m_Parameters->merge($parentObj->m_Parameters);
    }
insertRecord ($recArr) abstract
Insert record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
newRecord () abstract
Create an new (empty) record
Returns
array - empty record array with default values
readMetadata (& $xmlArr) protected
Read Metadata from xml array
Parameters
array $xmlArr
Returns
void
Definition at line 204 of file BizDataObj_Abstract.php.
References $m_OtherSQLRule, $m_SearchRule, $m_SortRule, Resource\loadMessage(), and MetaObject\prefixPackage().
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_InheritFrom = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["INHERITFROM"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["INHERITFROM"] : null;
        $this->m_SearchRule = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["SEARCHRULE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["SEARCHRULE"] : null;
        $this->m_BaseSearchRule = $this->m_SearchRule;
        $this->m_SortRule = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["SORTRULE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["SORTRULE"] : null;
        $this->m_BaseSortRule = $this->m_SortRule;
        $this->m_OtherSQLRule = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["OTHERSQLRULE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["OTHERSQLRULE"] : null;
        $this->m_BaseOtherSQLRule = $this->m_OtherSQLRule;
        $this->m_AccessRule = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["ACCESSRULE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["ACCESSRULE"] : null;
        $this->m_UpdateCondition = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["UPDATECONDITION"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["UPDATECONDITION"] : null;
        $this->m_DeleteCondition = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DELETECONDITION"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DELETECONDITION"] : null;
        $this->m_Database = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DBNAME"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DBNAME"] : null;
        if ($this->m_Database == null)
            $this->m_Database = "Default";
        $this->m_MainTable = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["TABLE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["TABLE"] : null;
        $this->m_IdGeneration = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["IDGENERATION"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["IDGENERATION"] : null;
        $this->m_Stateless = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["STATELESS"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["STATELESS"] : null;
        // read in uniqueness attribute
        $this->m_Uniqueness = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["UNIQUENESS"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["UNIQUENESS"] : null;
        $this->m_CacheLifeTime = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["CACHELIFETIME"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["CACHELIFETIME"] : "0";
        $this->m_Name = $this->prefixPackage($this->m_Name);
        if ($this->m_InheritFrom == '@sourceMeta') $this->m_InheritFrom = '@'.$this->m_Name;
        else $this->m_InheritFrom = $this->prefixPackage($this->m_InheritFrom);
        // build BizRecord
        $this->m_BizRecord = new BizRecord($xmlArr["BIZDATAOBJ"]["BIZFIELDLIST"]["BIZFIELD"],"BizField",$this);
        // build TableJoins
        $this->m_TableJoins = new MetaIterator($xmlArr["BIZDATAOBJ"]["TABLEJOINS"]["JOIN"],"TableJoin",$this);
        // build ObjReferences
        $this->m_ObjReferences = new MetaIterator($xmlArr["BIZDATAOBJ"]["OBJREFERENCES"]["OBJECT"],"ObjReference",$this);
        // read in parameters
        $this->m_Parameters = new MetaIterator($xmlArr["BIZDATAOBJ"]["PARAMETERS"]["PARAMETER"],"Parameter");
        $this->m_MessageFile = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["MESSAGEFILE"]) ? $xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["MESSAGEFILE"] : null;
        $this->m_Messages = Resource::loadMessage($this->m_MessageFile , $this->m_Package);
        $this->m_DataPermControl = isset($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DATAPERMCONTROL"]) ? strtoupper($xmlArr["BIZDATAOBJ"]["ATTRIBUTES"]["DATAPERMCONTROL"]) : 'N';
    }
resetRules ()
Reset rules
Returns
void
Definition at line 318 of file BizDataObj_Abstract.php.
References $m_BaseOtherSQLRule, $m_BaseSearchRule, and $m_BaseSortRule.
    {
        $this->m_SearchRule = $this->m_BaseSearchRule;
        $this->m_SortRule = $this->m_BaseSortRule;
        $this->m_OtherSQLRule = $this->m_BaseOtherSQLRule;
        return $this;
    }
setAssociation ($objRef, $asscObj) protected
Set the association of the object
Parameters
ObjReference $objRef
BizDataObj $asscObj
Returns
void
Definition at line 567 of file BizDataObj_Abstract.php.
    {
        $this->m_Association["AsscObjName"] = $asscObj->m_Name;
        $this->m_Association["Relationship"] = $objRef->m_Relationship;
        $this->m_Association["Table"] = $objRef->m_Table;
        $this->m_Association["Column"] = $objRef->m_Column;
        $this->m_Association["FieldRef"] = $objRef->m_FieldRef;
        $this->m_Association["FieldRefVal"] = $asscObj->getFieldValue($objRef->m_FieldRef);
        $this->m_Association["CondColumn"] = $objRef->m_CondColumn;
        $this->m_Association["CondValue"] = $objRef->m_CondValue;
        $this->m_Association["Condition"] = $objRef->m_Condition;
        if ($objRef->m_Relationship == "M-M" || $objRef->m_Relationship  == "Self-Self")
        {
            $this->m_Association["XTable"] = $objRef->m_XTable;
            $this->m_Association["XColumn1"] = $objRef->m_XColumn1;
            $this->m_Association["XColumn2"] = $objRef->m_XColumn2;
            $this->m_Association["XKeyColumn"] = $objRef->m_XKeyColumn;
            $this->m_Association["XDataObj"] = $objRef->m_XDataObj;
        }
    }
setLimit ($count, $offset = 0)
Set limit of the query.
Parameters
int $count the number of records to return
int $offset the starting position of the result records
Returns
void
Definition at line 444 of file BizDataObj_Abstract.php.
    {
     if($count<0)
     {
      $count = 0;
     }
        if($offset<0)
     {
      $offset = 0;
     }
        $this->m_Limit['count'] = $count;
        $this->m_Limit['offset'] = $offset;
    }
setOtherSQLRule ($rule)
Set other SQL rule, append extra SQL statment in sql. i.e. GROUP BY [fieldName]
Parameters
string $rule search rule with SQL format "GROUP BY [fieldName] HAVING ..."
Returns
void
Definition at line 431 of file BizDataObj_Abstract.php.
    {
        // $rule has SQL format "GROUP BY [fieldName] HAVING ...". replace [fieldName] with table.column
        $this->m_OtherSQLRule = $rule;
    }
setQueryParam ($queryStr, $paramValues)
Set query parameter for parameter binding in the query
Parameters
string $queryStr
array $paramValues
Returns
void
Definition at line 406 of file BizDataObj_Abstract.php.
References setSearchRule().
    {
        $this->setSearchRule($queryStr);
        foreach ($paramValues as $param=>$value)
            $this->m_QueryParams[$param] = $value;
    }
setSearchRule ($rule, $overWrite = false)
Set search rule as text in sql where clause. i.e. [fieldName] opr Value
Parameters
string $rule search rule has format "[fieldName] opr Value"
boolean $overWrite specify if this rule should overwrite any existing rule
Returns
void
Definition at line 385 of file BizDataObj_Abstract.php.
Referenced by BizDataObj_Lite\directFetch(), BizDataObj_Lite\fetchRecords(), and setQueryParam().
    {
        if (!$rule || $rule == "")
            return;
        if (!$this->m_SearchRule || $overWrite == true)
        {
            $this->m_SearchRule = $rule;
        }
        elseif (strpos($this->m_SearchRule, $rule) === false)
        {
            $this->m_SearchRule .= " AND " . $rule;
        }
    }
setSessionVars ($sessionContext)
Set session variables
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 310 of file BizDataObj_Abstract.php.
    {}
setSortRule ($rule)
Set search rule as text in sql order by clause. i.e. [fieldName] DESC|ASC
Parameters
string $rule sort rule has format "[fieldName] DESC|ASC"
Returns
void
Definition at line 419 of file BizDataObj_Abstract.php.
Referenced by BizDataObj_Lite\directFetch().
    {
        // sort rule has format "[fieldName] DESC|ASC", replace [fieldName] with table.column
        $this->m_SortRule = $rule;
    }
updateRecord ($recArr, $oldRec = null) abstract
Update record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
array $oldRec - associated array who is the old record field name / value pairs
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Field Documentation
$m_AccessRule
Definition at line 91 of file BizDataObj_Abstract.php.
$m_BaseOtherSQLRule
Definition at line 62 of file BizDataObj_Abstract.php.
Referenced by clearAllRules(), clearOtherSQLRule(), and resetRules().
$m_BaseSearchRule
Definition at line 48 of file BizDataObj_Abstract.php.
Referenced by BizDataObj\addRecord(), clearAllRules(), clearSearchRule(), and resetRules().
$m_BaseSortRule
Definition at line 55 of file BizDataObj_Abstract.php.
Referenced by clearAllRules(), clearSortRule(), and resetRules().
$m_BizRecord
Definition at line 76 of file BizDataObj_Abstract.php.
$m_CacheLifeTime
Definition at line 159 of file BizDataObj_Abstract.php.
$m_Database
Definition at line 41 of file BizDataObj_Abstract.php.
Referenced by getDBConnection().
$m_DataPermControl
Definition at line 184 of file BizDataObj_Abstract.php.
$m_DeleteCondition
Definition at line 103 of file BizDataObj_Abstract.php.
$m_IdGeneration
Definition at line 110 of file BizDataObj_Abstract.php.
$m_InheritFrom
Definition at line 83 of file BizDataObj_Abstract.php.
$m_Limit protected
Definition at line 175 of file BizDataObj_Abstract.php.
$m_MainTable
Definition at line 69 of file BizDataObj_Abstract.php.
Referenced by BizDataObj\generateId().
$m_MessageFile
Definition at line 166 of file BizDataObj_Abstract.php.
$m_Messages protected
Definition at line 182 of file BizDataObj_Abstract.php.
$m_ObjReferences
Definition at line 117 of file BizDataObj_Abstract.php.
$m_OtherSQLRule
Definition at line 152 of file BizDataObj_Abstract.php.
Referenced by readMetadata().
$m_Parameters
Definition at line 130 of file BizDataObj_Abstract.php.
$m_SearchRule
Definition at line 139 of file BizDataObj_Abstract.php.
Referenced by BizDataObj_Lite\directFetch(), BizDataObj_Lite\fetchRecords(), getProperty(), inheritParentObj(), and readMetadata().
$m_SortRule
Definition at line 145 of file BizDataObj_Abstract.php.
Referenced by BizDataObj_Lite\directFetch(), inheritParentObj(), and readMetadata().
$m_Stateless
Definition at line 131 of file BizDataObj_Abstract.php.
$m_TableJoins
Definition at line 124 of file BizDataObj_Abstract.php.
$m_Uniqueness
Definition at line 132 of file BizDataObj_Abstract.php.
$m_UpdateCondition
Definition at line 97 of file BizDataObj_Abstract.php.