Openbiz Framework API: EasyView Class Reference
EasyView Class Reference
Public Member Functions
__construct (&$xmlArr)
curPageURL ()
getCurrentPageUrl ()
getSessionVars ($sessionContext)
getViewSet ()
isInFormRefLibs ($formName)
outputAttrs ()
processRule ()
render ()
setConsoleOutput ($consoleOutput)
setParameters ()
setSessionVars ($sessionContext)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_CacheLifeTime
$m_ConsoleOutput
$m_FormRefs
$m_Height
$m_IsPopup
$m_Keywords
$m_LastRenderedForm
$m_MessageFile
$m_Tab
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_ViewSet
$m_Widgets
$m_Width
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
_render ()
getMessage ($msgId, $params=array())
getTransKey ($name)
getTransPrefix ()
initAllForms ()
processRequest ()
readMetadata (&$xmlArr)
readTile (&$xmlArr)
setClientScripts ()
translate ()
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_Messages
Detailed Description
Definition at line 26 of file EasyView.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize EasyView with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 54 of file EasyView.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
_render () protected
Render this view. This function is called by Render() or ReRender()
Returns
mixed either print html content or return html content if called by Render(), or void if called by ReRender()
Definition at line 254 of file EasyView.php.
References curPageURL(), BizSystem\getService(), BizSystem\log(), ViewRenderer\render(), and setClientScripts().
Referenced by render().
    {
        $this->setClientScripts();
        if($this->m_CacheLifeTime>0)
        {
            $pageUrl = $this->curPageURL();
            $cache_id = md5($pageUrl);
            //try to process cache service.
            $cacheSvc = BizSystem::getService(CACHE_SERVICE,1);
            $cacheSvc->init($this->m_Name,$this->m_CacheLifeTime);
            if($cacheSvc->test($cache_id))
            {
                BizSystem::log(LOG_DEBUG, "VIEW", "Cache Hit. url = ".$pageUrl);
                $output = $cacheSvc->load($cache_id);
            }
            else
            {
                //include_once(OPENBIZ_BIN."/easy/ViewRenderer.php");
                $this->m_ConsoleOutput = false;
                $output = ViewRenderer::render($this);
                BizSystem::log(LOG_DEBUG, "VIEW", "Set cache. url = ".$pageUrl);
                $cacheSvc->save($output, $cache_id);
            }
            print $output;
        }
        else
        {
            //include_once(OPENBIZ_BIN."/easy/ViewRenderer.php");
            ViewRenderer::render($this);
        }
        return;
        /*
        $this->setClientScripts();
       //include_once(OPENBIZ_BIN."/easy/ViewRenderer.php");
     return ViewRenderer::render($this);
         */
    }
curPageURL ()
Get current page URL NOTE: This method on next version maybe removed. New method is getCurrentPageUrl
Returns
string page URL
Definition at line 301 of file EasyView.php.
References getCurrentPageUrl().
Referenced by _render().
    {
        return $this->getCurrentPageUrl();
    }
getCurrentPageUrl ()
Get current page URL
Returns
string page URL
Definition at line 312 of file EasyView.php.
Referenced by curPageURL().
    {
        $pageURL = 'http';
        if ($_SERVER["HTTPS"] == "on")
        {
            $pageURL .= "s";
        }
        $pageURL .= "://";
        if ($_SERVER["SERVER_PORT"] != "80")
        {
            $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
        }
        else
        {
            $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
        }
        return $pageURL;
    }
getMessage ($msgId, $params = array()) protected
Get message, and translate it
Parameters
<type> $msgId message Id
array $params
Returns
string message string
Definition at line 160 of file EasyView.php.
References MetaObject\getModuleName(), and I18n\t().
    {
        $message = isset($this->m_Messages[$msgId]) ? $this->m_Messages[$msgId] : constant($msgId);
        //$message = I18n::getInstance()->translate($message);
        $message = I18n::t($message, $msgId, $this->getModuleName($this->m_Name));
        return vsprintf($message,$params);
    }
getSessionVars ($sessionContext)
Get/Retrieve Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 175 of file EasyView.php.
    {
        $sessionContext->getObjVar($this->m_Name, "LastRenderedForm", $this->m_LastRenderedForm);
    }
getTransKey ($name) protected
Definition at line 447 of file EasyView.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_Name,intval(strrpos($this->m_Name,'.'))+1);
     return strtoupper($shortFormName.'_'.$name);
    }
getTransPrefix () protected
Definition at line 437 of file EasyView.php.
Referenced by translate().
    {
     $nameArr = explode(".",$this->m_Name);
     for($i=1;$i<count($nameArr)-1;$i++)
     {
      $prefix .= strtoupper($nameArr[$i])."_";
     }
     return $prefix;
    }
getViewSet ()
Get view set name
Returns
mixed viewset name or null
Definition at line 196 of file EasyView.php.
References $m_ViewSet.
    {
        return $this->m_ViewSet;
    }
initAllForms () protected
Initialize all form objects.
Returns
void
Definition at line 346 of file EasyView.php.
References BizSystem\objectFactory().
Referenced by render().
    {
        foreach ($this->m_FormRefs as $formRef)
        {
            $formRef->setViewName($this->m_Name);
            $formName = $formRef->m_Name;
            $formObj = BizSystem::objectFactory()->getObject($formName);
            if ($formRef->m_SubForms && method_exists($formObj,"SetSubForms"))
                $formObj->setSubForms($formRef->m_SubForms);
        }
    }
isInFormRefLibs ($formName)
Check the Form is in the lib
Parameters
string $formName form name
Returns
bool inside or not
Definition at line 131 of file EasyView.php.
Referenced by DynaView\processURL().
    {
     if($this->m_FormRefLibs)
     {
      $this->m_FormRefLibs->rewind();
      while($this->m_FormRefLibs->valid())
      {
       $reference = $this->m_FormRefLibs->current();
       if($reference->m_Name == $formName)
       {
        return true;
       }
       $this->m_FormRefLibs->next();
      }
      return false;
     }
     else
     {
      return true;
     }
    }
outputAttrs ()
Get output attributs
Returns
array
Definition at line 410 of file EasyView.php.
References MetaObject\$m_Description, $m_Keywords, MetaObject\$m_Name, Expression\evaluateExpression(), and MetaObject\getModuleName().
    {
        $out['name'] = $this->m_Name;
        $out['module'] = $this->getModuleName($this->m_Name);
        $out['description'] = $this->m_Description;
        $out["keywords"] = $this->m_Keywords;
        if ($this->m_Title)
            $title = Expression::evaluateExpression($this->m_Title,$this);
        else
         $title = $this->m_Description;
        $out['title'] = $title;
        return $out;
    }
processRequest () protected
Process request
Returns
void
Definition at line 363 of file EasyView.php.
References BizSystem\objectFactory(), and MetaObject\prefixPackage().
Referenced by render().
    {
        // if url has form=...
        $paramForm = isset($_REQUEST['form']) ? $_REQUEST['form'] : null;
        // check url arg as fld:name=val
        $getKeys = array_keys($_REQUEST);
        $pageid = $_GET["pageid"];
        $paramFields = null;
        foreach ($getKeys as $key)
        {
            if (substr($key, 0, 4) == "fld:")
            {
                $fieldName = substr($key, 4);
                $fieldValue = $_REQUEST[$key];
                $paramFields[$fieldName] = $fieldValue;
            }
        }
        if (!$paramFields && !$pageid)
            return;
        // get the form object
        if (!$paramForm)
        { // get the first form name if no form is given
            foreach ($this->m_FormRefs as $formRef)
            {
                $paramForm = $formRef->m_Name;
                break;
            }
        }
        if (!$paramForm)
            return;
        $paramForm = $this->prefixPackage($paramForm);
        $formObj = BizSystem::objectFactory()->getObject($paramForm);
        $formObj->setRequestParams($paramFields);
        if($pageid){
   $formObj->setCurrentPage($pageid);
        }
    }
processRule ()
Proses rule
Returns
void
Definition at line 217 of file EasyView.php.
    {}
readMetadata (& $xmlArr) protected
Read Metadata from xml array
Parameters
array $xmlArr
Returns
void
Definition at line 65 of file EasyView.php.
References MetaObject\$m_Description, Resource\loadMessage(), MetaObject\prefixPackage(), readTile(), and translate().
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $this->m_Name = $this->prefixPackage($this->m_Name);
        $this->m_Title = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["TITLE"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["TITLE"] : null;
        $this->m_Keywords = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["KEYWORDS"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["KEYWORDS"] : null;
        $this->m_TemplateEngine = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["TEMPLATEENGINE"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["TEMPLATEENGINE"] : null;
        $this->m_TemplateFile = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["TEMPLATEFILE"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["TEMPLATEFILE"] : null;
        $this->m_ViewSet = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["VIEWSET"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["VIEWSET"] : null;
        $this->m_Tab = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["TAB"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["TAB"] : null;
        $this->m_FormRefs = new MetaIterator($xmlArr["EASYVIEW"]["FORMREFERENCES"]["REFERENCE"],"FormReference",$this);
        if($xmlArr["EASYVIEW"]["FORMREFERENCELIBS"])
        {
         $this->m_FormRefLibs = new MetaIterator($xmlArr["EASYVIEW"]["FORMREFERENCELIBS"]["REFERENCE"],"FormReference",$this);
        }
     if($xmlArr["EASYVIEW"]["WIDGETS"])
        {
         $this->m_Widgets = new MetaIterator($xmlArr["EASYVIEW"]["WIDGETS"]["REFERENCE"],"FormReference",$this);
        }
        $this->m_MessageFile = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["MESSAGEFILE"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["MESSAGEFILE"] : null;
        $this->m_Messages = Resource::loadMessage($this->m_MessageFile, $this->m_Package);
        $this->m_CacheLifeTime = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["CACHELIFETIME"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["CACHELIFETIME"] : "0";
        $this->readTile($xmlArr); // TODO: is this needed as title supports expression?
        $this->translate(); // translate for multi-language support
        if (empty($this->m_Title))
         $this->m_Title = $this->m_Description;
    }
readTile (& $xmlArr) protected
Definition at line 96 of file EasyView.php.
Referenced by readMetadata().
    {
     if (isset($xmlArr["EASYVIEW"]["TILE"]))
        {
         $this->m_FormRefs = array();
         if (isset($xmlArr["EASYVIEW"]["TILE"]["ATTRIBUTES"]))
         {
          $tileName = $xmlArr["EASYVIEW"]["TILE"]["ATTRIBUTES"]["NAME"];
          $this->m_Tiles[$tileName] = new MetaIterator($xmlArr["EASYVIEW"]["TILE"]["REFERENCE"],"FormReference",$this);
         }
         else
         {
          foreach ($xmlArr["EASYVIEW"]["TILE"] as $child)
          {
           $tileName = $child["ATTRIBUTES"]["NAME"];
           $this->m_Tiles[$tileName] = new MetaIterator($child["REFERENCE"],"FormReference",$this);
          }
         }
         //echo "<pre>"; print_r($this->m_Tiles); echo "</pre>";
         $tmp = array();
         $this->m_FormRefs = new MetaIterator($tmp,"",$this);
         foreach ($this->m_Tiles as $tile)
         {
          foreach ($tile as $ref)
           $this->m_FormRefs->set($ref->m_Name, $ref);
         }
        }
    }
render ()
Definition at line 234 of file EasyView.php.
References _render(), ACCESS_DENIED_VIEW, MetaObject\allowAccess(), initAllForms(), BizSystem\objectFactory(), and processRequest().
    {
     if (!$this->allowAccess())
        {
            $accessDenyView = BizSystem::objectFactory()->getObject(ACCESS_DENIED_VIEW);
            return $accessDenyView->render();
        }
        $this->initAllForms();
        // check the "fld_..." arg in url and put it in the search rule
        $this->processRequest();
        return $this->_render();
    }
setClientScripts () protected
Set default client javascript and css that included in the html content
Returns
void
Definition at line 336 of file EasyView.php.
References BizSystem\clientProxy().
Referenced by _render().
    {
  BizSystem::clientProxy()->includeBaseClientScripts();
    }
setConsoleOutput ($consoleOutput)
Set the Render output to console (as calling print ...) or to a string buffer
Parameters
boolean $consoleOutput
Returns
void
Definition at line 207 of file EasyView.php.
    {
        $this->m_ConsoleOutput = $consoleOutput;
    }
setParameters ()
Set parameters
Returns
void
Definition at line 225 of file EasyView.php.
    {}
setSessionVars ($sessionContext)
Save Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 186 of file EasyView.php.
    {
        $sessionContext->setObjVar($this->m_Name, "LastRenderedForm", $this->m_LastRenderedForm);
    }
translate () protected
Definition at line 424 of file EasyView.php.
References MetaObject\getModuleName(), getTransKey(), getTransPrefix(), and I18n\t().
Referenced by readMetadata().
    {
     $module = $this->getModuleName($this->m_Name);
     $trans_string = I18n::t($this->m_Title, $this->getTransKey('Title'), $module, $this->getTransPrefix());
     if($trans_string){
      $this->m_Title =  $trans_string;
     }
     $trans_string = I18n::t($this->m_Description, $this->getTransKey('Description'), $module, $this->getTransPrefix());
     if($trans_string){
      $this->m_Description = $trans_string;
     }
    }
Field Documentation
$m_CacheLifeTime
Definition at line 44 of file EasyView.php.
$m_ConsoleOutput
Definition at line 40 of file EasyView.php.
$m_FormRefs
Definition at line 34 of file EasyView.php.
Referenced by EasyViewWizard\outputAttrs().
$m_Height
Definition at line 38 of file EasyView.php.
$m_IsPopup
Definition at line 37 of file EasyView.php.
$m_Keywords
Definition at line 29 of file EasyView.php.
Referenced by outputAttrs().
$m_LastRenderedForm
Definition at line 46 of file EasyView.php.
$m_MessageFile
Definition at line 42 of file EasyView.php.
$m_Messages protected
Definition at line 43 of file EasyView.php.
$m_Tab
Definition at line 33 of file EasyView.php.
$m_TemplateEngine
Definition at line 30 of file EasyView.php.
$m_TemplateFile
Definition at line 31 of file EasyView.php.
$m_Title
Definition at line 28 of file EasyView.php.
$m_ViewSet
Definition at line 32 of file EasyView.php.
Referenced by getViewSet().
$m_Widgets
Definition at line 35 of file EasyView.php.
$m_Width
Definition at line 39 of file EasyView.php.