Openbiz Framework API: BizDataTree Class Reference
BizDataTree Class Reference
Public Member Functions
fetchNodePath ($nodeSearchRule, &$pathArray)
fetchTree ($rootSearchRule, $depth, $globalSearchRule="")
Public Member Functions inherited from BizDataObj
__construct (&$xmlArr)
addRecord ($recArr, &$isParentObjUpdated)
canDeleteRecord ($record=null)
canDeleteRecordCondition ()
canUpdateRecord ($record=null)
canUpdateRecordCondition ()
cleanCache ()
deleteRecord ($recArr)
deleteRecords ($condition=null)
getJoinFields ($joinDataObj)
getOnAuditFields ()
insertRecord ($recArr)
joinRecord ($joinDataObj, $joinName="")
newRecord ()
removeRecord ($recArr, &$isParentObjUpdated)
updateRecord ($recArr, $oldRecord=null)
updateRecords ($setValue, $condition=null)
validateInput ()
Public Member Functions inherited from BizDataObj_Lite
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0, $sortRule="")
fetch ()
fetchById ($id)
fetchByName ($nameVal)
fetchOne ($searchRule, $sortRule="")
fetchRecords ($searchRule, &$resultRecords, $count=-1, $offset=0, $clearSearchRule=true, $noAssociation=false)
find ()
getActiveRecord ()
getErrorFields ()
getErrorMessage ()
getField ($fieldName)
getFieldNameByColumn ($column)
getFieldValue ($fieldName)
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
setActiveRecord ($currentRecord)
setActiveRecordId ($recordId)
setSessionVars ($sessionContext)
updateRecord ($recArr, $oldRec=null)
validateInput ()
Public Member Functions inherited from BizDataObj_Abstract
__construct (&$xmlArr)
clearAllRules ()
clearOtherSQLRule ()
clearSearchRule ()
clearSortRule ()
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0)
fetch ()
find ()
getAssociation ()
getDBConnection ($type='default')
getParameter ($paramName)
getProperty ($propertyName)
getRefObject ($objName)
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
resetRules ()
setLimit ($count, $offset=0)
setOtherSQLRule ($rule)
setQueryParam ($queryStr, $paramValues)
setSearchRule ($rule, $overWrite=false)
setSessionVars ($sessionContext)
setSortRule ($rule)
updateRecord ($recArr, $oldRec=null)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Attributes
$m_Depth
$m_globalSearchRule
$m_RootNodes
Additional Inherited Members
Data Fields inherited from BizDataObj_Abstract
$m_AccessRule
$m_BaseOtherSQLRule
$m_BaseSearchRule
$m_BaseSortRule
$m_BizRecord
$m_CacheLifeTime
$m_Database
$m_DataPermControl
$m_DeleteCondition
$m_IdGeneration
$m_InheritFrom
$m_MainTable
$m_MessageFile
$m_ObjReferences
$m_OtherSQLRule
$m_Parameters
$m_SearchRule
$m_SortRule
$m_Stateless
$m_TableJoins
$m_Uniqueness
$m_UpdateCondition
Protected Member Functions inherited from BizDataObj
cascadeDelete ()
cascadeUpdate ()
generateId ($isBeforeInsert=true, $tableName=null, $idCloumnName=null)
processCascadeAction ($objRef, $cascadeType)
validateUniqueness ()
Detailed Description
Definition at line 27 of file BizDataTree.php.
Member Function Documentation
fetchNodePath ($nodeSearchRule, & $pathArray)
Fetch node path
Parameters
string $nodeSearchRule
array $pathArray
Returns
<type>
Definition at line 84 of file BizDataTree.php.
References BizDataObj_Lite\count(), and BizDataObj_Lite\directFetch().
    {
        $recordList = $this->directFetch($nodeSearchRule);
        if(count($recordList)>=1)
        {
            if($recordList[0]['PId']!='0')
            {
                $searchRule = "[Id]='".$recordList[0]['PId']."'";
                $this->fetchNodePath($searchRule, $pathArray);
            }
            $nodes = new NodeRecord($recordList[0]);
            array_push($pathArray,$nodes);
            return $pathArray;
        }
    }
fetchTree ($rootSearchRule, $depth, $globalSearchRule = "")
Fetch records in tree structure
Returns
<type>
Definition at line 47 of file BizDataTree.php.
References $m_RootNodes, and BizDataObj_Lite\directFetch().
    {
        $this->m_Depth = $depth;
        $this->m_globalSearchRule = $globalSearchRule;
        // query on given search rule
        $searchRule = "(" . $rootSearchRule . ")";
        if ($globalSearchRule!="")
            $searchRule .= " AND (" . $globalSearchRule . ")";
        $recordList = $this->directFetch($searchRule);
        if (!$recordList)
        {
            $this->m_RootNodes = array();
            return;
        }
        foreach ($recordList as $rec)
        {
            $this->m_RootNodes[] = new NodeRecord($rec);
        }
        if ($this->m_Depth <= 1)
            return $this->m_RootNodes;
        if(is_array($this->m_RootNodes)){
         foreach ($this->m_RootNodes as $node)
         {
             $this->_getChildrenNodes($node, 1);
         }
        }
        return $this->m_RootNodes;
    }
Field Documentation
$m_Depth protected
Definition at line 34 of file BizDataTree.php.
$m_globalSearchRule protected
Definition at line 40 of file BizDataTree.php.
$m_RootNodes protected
Definition at line 29 of file BizDataTree.php.
Referenced by fetchTree().