Openbiz Framework API: MetaObject Class Reference
MetaObject Class Reference
Public Member Functions
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 25 of file sysclass_inc.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Definition at line 58 of file sysclass_inc.php.
    {
    }
Member Function Documentation
allowAccess ($access = null)
Check is allow access?
BizSystem $g_BizSystem
Parameters
<type> $access
Returns
<type>
Definition at line 147 of file sysclass_inc.php.
References $m_Access, ALLOW, and BizSystem\allowUserAccess().
Referenced by BizDataObj\canDeleteRecordCondition(), Element\canDisplayed(), BizDataObj\canUpdateRecordCondition(), FormElement\getValue(), EasyView\render(), and FormElement\setValue().
    {
     if(CLI){
      return ALLOW;
     }
     if (!$access) $access = $this->m_Access;
        if ($access)
        {
         return BizSystem::allowUserAccess($access);
        }
        return ALLOW;
    }
getElementObject (& $xmlArr, $defaultClassName, $parentObj = null) protected
Definition at line 160 of file sysclass_inc.php.
References BizSystem\loadClass().
 {
  // find the class attribute
  $className = isset($xmlArr["ATTRIBUTES"]['CLASS']) ? $xmlArr["ATTRIBUTES"]['CLASS'] : $defaultClassName;
  if ((bool) strpos($className, "."))
  {
   $a_package_name = explode(".", $className);
   $className  = array_pop($a_package_name);
   $clsLoaded = BizSystem::loadClass($className, implode(".", $a_package_name));
   if (!$clsLoaded) trigger_error("Cannot find the load class $className", E_USER_ERROR);
  }
  //echo "classname is $className\n";
  $obj = new $className($xmlArr, $parentObj);
  return $obj;
 }
getModuleName ($name)
Definition at line 90 of file sysclass_inc.php.
Referenced by EasyView\getMessage(), EasyForm\getMessage(), BizDataObj_Abstract\getMessage(), EasyView\outputAttrs(), HTMLTree\translate(), HTMLMenus\translate(), EasyView\translate(), Element\translate(), EasyForm\translate(), OptionElement\translateList(), DropDownList\translateList(), and Element\translateString().
    {
     return substr($name,0,intval(strpos($name,'.')));
    }
getProperty ($propertyName)
Get property
Parameters
string $propertyName
Returns
<type>
Definition at line 133 of file sysclass_inc.php.
    {
        // TODO: really like this?
        if (isset($this->$propertyName)) return $this->$propertyName;
        return null;
    }
prefixPackage ($name) protected
Set Prefix Package
Parameters
string $name
Returns
string
Definition at line 119 of file sysclass_inc.php.
Referenced by ObjReference\__construct(), TableJoin\__construct(), BizField\__construct(), EasyView\processRequest(), DynaView\processURL(), InputPicker\readMetaData(), InputElement\readMetaData(), EasyView\readMetadata(), doTriggerService\readMetadata(), EasyForm\readMetadata(), BizDataObj_Abstract\readMetadata(), and EasyForm\setSubForms().
    {
        if ($name && !strpos($name, ".") && ($this->m_Package)) // no package prefix as package.object, add it
            $name = $this->m_Package.".".$name;
        return $name;
    }
readMetaCollection (& $xmlArr, & $metaList) protected
Read metadata collection
Parameters
array $xmlArr
array $metaList
Returns
void
Definition at line 102 of file sysclass_inc.php.
Referenced by TriggerAction\__construct(), and doTriggerService\readMetadata().
    {
        if (!$xmlArr)
        {
            $metaList = null;
            return;
        }
        if (isset($xmlArr["ATTRIBUTES"]))  $metaList[] = $xmlArr;
        else $metaList = $xmlArr;
    }
readMetadata (& $xmlArr) protected
Read meta data
Parameters
array $xmlArr
Returns
void
Definition at line 70 of file sysclass_inc.php.
    {
        $rootKeys = array_keys($xmlArr);
        $rootKey = $rootKeys[0];
        if ($rootKey != "ATTRIBUTES") {
            $this->m_Name = isset($xmlArr[$rootKey]["ATTRIBUTES"]["NAME"]) ? $xmlArr[$rootKey]["ATTRIBUTES"]["NAME"] : null;
            $this->m_Description = isset($xmlArr[$rootKey]["ATTRIBUTES"]["DESCRIPTION"]) ? $xmlArr[$rootKey]["ATTRIBUTES"]["DESCRIPTION"] : null;
            $this->m_Package = isset($xmlArr[$rootKey]["ATTRIBUTES"]["PACKAGE"]) ? $xmlArr[$rootKey]["ATTRIBUTES"]["PACKAGE"] : null;
            $this->m_Class = isset($xmlArr[$rootKey]["ATTRIBUTES"]["CLASS"]) ? $xmlArr[$rootKey]["ATTRIBUTES"]["CLASS"] : null;
            $this->m_Access = isset($xmlArr[$rootKey]["ATTRIBUTES"]["ACCESS"]) ? $xmlArr[$rootKey]["ATTRIBUTES"]["ACCESS"] : null;
        }
        else {
            $this->m_Name = isset($xmlArr["ATTRIBUTES"]["NAME"]) ? $xmlArr["ATTRIBUTES"]["NAME"] : null;
            $this->m_Description = isset($xmlArr["ATTRIBUTES"]["DESCRIPTION"]) ? $xmlArr["ATTRIBUTES"]["DESCRIPTION"] : null;
            $this->m_Package = isset($xmlArr["ATTRIBUTES"]["PACKAGE"]) ? $xmlArr["ATTRIBUTES"]["PACKAGE"] : null;
            $this->m_Class = isset($xmlArr["ATTRIBUTES"]["CLASS"]) ? $xmlArr["ATTRIBUTES"]["CLASS"] : null;
            $this->m_Access = isset($xmlArr["ATTRIBUTES"]["ACCESS"]) ? $xmlArr["ATTRIBUTES"]["ACCESS"] : null;
        }
    }
Field Documentation
$m_Access
Definition at line 56 of file sysclass_inc.php.
Referenced by allowAccess().
$m_Class
Definition at line 40 of file sysclass_inc.php.
$m_Description
Definition at line 54 of file sysclass_inc.php.
Referenced by EasyView\outputAttrs(), and EasyView\readMetadata().
$m_Name
Definition at line 33 of file sysclass_inc.php.
Referenced by EasyForm\_showForm(), ColumnSorting\getBtnFunction(), EasyForm\getDataObj(), Element\getDefaultValue(), Element\getEvents(), ColorPicker\getFunctionByEvent(), DropDownList\getOnChangeFunction(), EasyView\outputAttrs(), EasyForm\outputAttrs(), LabelBar\render(), ColumnSorting\render(), Spacer\render(), ColumnBar\render(), LabelTextPaging\render(), RichText\render(), LabelTextarea\render(), ColorPicker\render(), IDCardReader\render(), BarcodeScanner\render(), AutoSuggest\render(), LabelBool\render(), CKEditor\render(), Button\render(), ColumnBool\render(), LabelList\render(), HTMLPreview\render(), LabelText\render(), ColumnShare\render(), EasyForm\renderHTML(), ColumnListbox\renderLabel(), ColumnInputText\renderLabel(), ColumnText\renderLabel(), ColumnList\renderLabel(), Button\renderLabel(), ColumnListbox\setValue(), ColumnInputText\setValue(), ImageUploader\setValue(), and FileUploader\setValue().
$m_Package
Definition at line 47 of file sysclass_inc.php.