Openbiz Framework API: I18n Class Reference
I18n Class Reference
Static Public Member Functions
static AddLangData ($from_module, $to_module=null)
static getCurrentLangCode ()
static t ($text, $key=null, $module, $prefix=null)
Data Fields
const DEFAULT_LANGUAGE
const LANGUAGE_PATH_1
const LANGUAGE_PATH_2
Static Protected Member Functions
static loadLangData ($module)
Static Protected Attributes
static $_langCode
static $_langData
Detailed Description
Definition at line 30 of file I18n.php.
Member Function Documentation
static AddLangData ($from_module, $to_module = null) static
Definition at line 104 of file I18n.php.
References $_langData, getCurrentLangCode(), and LANGUAGE_PATH.
    {
     if($to_module==null){
      $to_module = $from_module;
     }
     $langCode = I18n::getCurrentLangCode();
     $filename = "mod.$from_module.ini";
     $langFile = LANGUAGE_PATH."/$langCode/$filename";
     if (!file_exists($langFile)) return false;
     $inidata = parse_ini_file($langFile, false);
     if(is_array(I18n::$_langData[$to_module])){
      I18n::$_langData[$to_module] = array_merge(I18n::$_langData[$to_module],$inidata);
     }else{
      I18n::$_langData[$to_module] = $inidata;
     }
     return true;
    }
static getCurrentLangCode () static
Definition at line 122 of file I18n.php.
References $_langCode, DEFAULT_LANGUAGE, BizSystem\getUserPreference(), and BizSystem\sessionContext().
Referenced by TypeManager\__construct(), AddLangData(), ClientProxy\getAppendedStyles(), Resource\getSmartyTemplate(), Resource\getZendTemplate(), loadLangData(), and CKEditor\render().
    {
     if (I18n::$_langCode != null)
            return I18n::$_langCode;
        $currentLanguage = BizSystem::sessionContext()->getVar("LANG");
        // default language
        if ($currentLanguage == ""){
         $currentLanguage = BizSystem::getUserPreference("language");
        }
        if($currentLanguage == ""){
            $currentLanguage = I18n::DEFAULT_LANGUAGE;
        }
        // language from url
        if (isset($_GET['lang'])){
            $currentLanguage = $_GET['lang'];
            BizSystem::sessionContext()->setVar("LANG",$currentLanguage );
        }
        // TODO: user pereference has language setting
        BizSystem::sessionContext()->setVar("LANG", $currentLanguage);
        I18n::$_langCode = $currentLanguage;
        return $currentLanguage;
    }
static loadLangData ($module) static protected
Definition at line 76 of file I18n.php.
References $_langData, getCurrentLangCode(), and LANGUAGE_PATH.
Referenced by t().
    {
     if (isset(I18n::$_langData[$module])) {
      return true;
     }
     // get language code
     $langCode = I18n::getCurrentLangCode();
     // load language file
     if ($module == '_system') $filename = 'system.ini';
  else if ($module == '_theme') { $filename = 'theme.'.THEME_NAME.'.ini'; }
     else $filename = "mod.$module.ini";
     $langFile = LANGUAGE_PATH."/$langCode/$filename";
     //echo "check ini file $langFile".nl;
     if (!file_exists($langFile)) {
   I18n::$_langData[$module] = array();
   return false;
     }
     //echo "parse ini file $langFile".nl;
     $inidata = parse_ini_file($langFile, false);
     I18n::$_langData[$module] = $inidata;
     //print_r(I18n::$_langData[$module]);
     return true;
    }
static t ($text, $key = null, $module, $prefix = null) static
Definition at line 39 of file I18n.php.
References $_langData, and loadLangData().
Referenced by Resource\getMessage(), EasyView\getMessage(), EasyForm\getMessage(), BizDataObj_Abstract\getMessage(), smarty_block_t(), HTMLTree\translate(), HTMLMenus\translate(), TabView\translate(), EasyView\translate(), FormReference\translate(), Element\translate(), EventHandler\translate(), EasyForm\translate(), OptionElement\translateList(), DropDownList\translateList(), and Element\translateString().
    {
     // TODO: use cache, apc cache? special handling for menu?
     //echo "to translate $text, $key, $module".nl;
     if (!I18n::loadLangData($module)) // cannot load lang data, return orig text
   return $text;
  if ($key && isset(I18n::$_langData[$module][$prefix.$key]) && I18n::$_langData[$module][$prefix.$key]!=$text)
      return I18n::$_langData[$module][$prefix.$key];
     $str_key = strtoupper('STRING_'.md5($text));
     if ($key && isset(I18n::$_langData[$module][$str_key])  && I18n::$_langData[$module][$str_key]!=$text)
      return I18n::$_langData[$module][$str_key];
     if ($key && isset(I18n::$_langData[$module][$key]))
      return I18n::$_langData[$module][$key];
  // try to load theme.THEME_NAME.ini
  $module = '_theme';
  if (!I18n::loadLangData($module))
   return $text;
     if ($key && isset(I18n::$_langData[$module][$key]))
      return I18n::$_langData[$module][$key];
     // try to load system.ini if previous steps can't find match
     $module != '_system';
     if (!I18n::loadLangData($module))
   return $text;
     if ($key && isset(I18n::$_langData[$module][$key]))
      return I18n::$_langData[$module][$key];
     return $text;
    }
Field Documentation
$_langCode static protected
Definition at line 37 of file I18n.php.
Referenced by getCurrentLangCode().
$_langData static protected
Definition at line 36 of file I18n.php.
Referenced by AddLangData(), loadLangData(), and t().
const DEFAULT_LANGUAGE
Definition at line 34 of file I18n.php.
Referenced by getCurrentLangCode().
const LANGUAGE_PATH_1
Definition at line 32 of file I18n.php.
const LANGUAGE_PATH_2
Definition at line 33 of file I18n.php.