Openbiz Framework API: EasyViewWizard Class Reference
EasyViewWizard Class Reference
Public Member Functions
cancel ()
commit ()
getCurrentStep ()
getFormInputs ($formName)
getSessionVars ($sessionContext)
outputAttrs ()
renderStep ($step)
setFormState ($formName, $state, $value)
setSessionVars ($sessionContext)
Public Member Functions inherited from EasyView
__construct (&$xmlArr)
curPageURL ()
getCurrentPageUrl ()
getSessionVars ($sessionContext)
getViewSet ()
isInFormRefLibs ($formName)
outputAttrs ()
processRule ()
render ()
setConsoleOutput ($consoleOutput)
setParameters ()
setSessionVars ($sessionContext)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
getStepName ($step)
initAllForms ()
processRequest ()
readMetadata (&$xmlArr)
Protected Member Functions inherited from EasyView
_render ()
getMessage ($msgId, $params=array())
getTransKey ($name)
getTransPrefix ()
initAllForms ()
processRequest ()
readMetadata (&$xmlArr)
readTile (&$xmlArr)
setClientScripts ()
translate ()
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_CurrentStep
$m_DropSession
$m_FormStates
$m_NaviMethod
Protected Attributes inherited from EasyView
$m_Messages
Additional Inherited Members
Data Fields inherited from EasyView
$m_CacheLifeTime
$m_ConsoleOutput
$m_FormRefs
$m_Height
$m_IsPopup
$m_Keywords
$m_LastRenderedForm
$m_MessageFile
$m_Tab
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_ViewSet
$m_Widgets
$m_Width
Detailed Description
Definition at line 25 of file EasyViewWizard.php.
Member Function Documentation
cancel ()
Cancel, clean up the sessions of view and all forms
Returns
void
Definition at line 245 of file EasyViewWizard.php.
References BizSystem\objectFactory().
    {
        // call all step forms Cancel method
        if(is_array($this->m_FormStates)){
         foreach ($this->m_FormStates as $formName=>$state)
         {
             if ($state['visited'])
                 BizSystem::objectFactory()->getObject($formName)->cancel();
         }
        }
        $this->m_DropSession = true;
    }
commit ()
Save wizard data of current+previous pages into database or other storage
Returns
void
Definition at line 211 of file EasyViewWizard.php.
References BizSystem\objectFactory().
    {
        // call all step forms Commit method
        foreach ($this->m_FormStates as $formName=>$state)
        {
            if ($state['visited'])
            {
                $r = BizSystem::objectFactory()->getObject($formName)->commit();
                if (!$r)
                {
                 return false;
                }
            }
        }
        foreach ($this->m_FormStates as $formName=>$state)
        {
            if ($state['visited'])
            {
                $r = BizSystem::objectFactory()->getObject($formName)->dropSession();
                if (!$r)
                {
                    return false;
                }
            }
        }
        $this->m_DropSession = true;
        return true;
    }
getCurrentStep ()
Get current step
Returns
number
Definition at line 116 of file EasyViewWizard.php.
References $m_CurrentStep.
Referenced by processRequest(), and renderStep().
    {   if($_GET['step'])
     {
      $this->m_CurrentStep=$_GET['step'];
      return $this->m_CurrentStep;
     }
     elseif($this->m_CurrentStep)
     {
      if($this->m_CurrentStep > $this->m_FormRefs->count()){
       return $this->m_FormRefs->count();
      }else{
       return $this->m_CurrentStep;
      }
     }
     else
     {
         $step = isset($_GET['step']) ? $_GET['step'] : 1;
         $numForms = 0;
         foreach ($this->m_FormRefs as $formRef)
             $numForms++;
         if ($step < 1)
             $step = 1;
         if ($step > $numForms)
             $step = $numForms;
         $this->m_CurrentStep = $step;
         return $step;
     }
    }
getFormInputs ($formName)
Get form inputs
Parameters
string $formName
Returns
array
Definition at line 186 of file EasyViewWizard.php.
References BizSystem\objectFactory().
    {
        $formObj = BizSystem::objectFactory()->getObject($formName);
        $rec = $formObj->getActiveRecord();
        return $rec;
    }
getSessionVars ($sessionContext)
Get/Retrieve Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 43 of file EasyViewWizard.php.
    {
        $sessionContext->getObjVar($this->m_Name, "FormStates", $this->m_FormStates, true);
        $sessionContext->getObjVar($this->m_Name, "CurrentStep", $this->m_CurrentStep, true);
    }
getStepName ($step) protected
Definition at line 99 of file EasyViewWizard.php.
Referenced by renderStep().
    {
  $i = 1;
        foreach ($this->m_FormRefs as $formRef){
            if($i == $step){
             return $formRef->m_Name;
            }
            $i++;
        }
        return "";
    }
initAllForms () protected
Initialize all form objects. NOTE: Do not initiate the all forms
Returns
void
Definition at line 72 of file EasyViewWizard.php.
    {
    }
outputAttrs ()
Get output attributs
Returns
array
Definition at line 264 of file EasyViewWizard.php.
References $m_CurrentStep, and EasyView\$m_FormRefs.
    {
        $out = parent::outputAttrs();
        $out['step'] = $this->m_CurrentStep;
        $out['forms'] = $this->m_FormRefs;
        return $out;
    }
processRequest () protected
Process request
Returns
void
Definition at line 81 of file EasyViewWizard.php.
References getCurrentStep().
    {
        parent::processRequest();
        $step = $this->getCurrentStep();
        // only display given step form
        $i = 1;
        foreach ($this->m_FormRefs as $formRef)
        {
            if ($i == $step)
                $formRef->m_Display = true;
            else
                $formRef->m_Display = false;
            $i++;
        }
    }
readMetadata (& $xmlArr) protected
Definition at line 32 of file EasyViewWizard.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_NaviMethod = isset($xmlArr["EASYVIEW"]["ATTRIBUTES"]["NAVIMETHOD"]) ? $xmlArr["EASYVIEW"]["ATTRIBUTES"]["NAVIMETHOD"] :'SwitchPage';
    }
renderStep ($step)
Render step
Parameters
number $step
Returns
void
Definition at line 152 of file EasyViewWizard.php.
References $m_CurrentStep, APP_INDEX, BizSystem\clientProxy(), getCurrentStep(), BizSystem\getService(), getStepName(), BizSystem\objectFactory(), and UTIL_SERVICE.
    {
     if($this->m_CurrentStep){
      $currentStep = $this->m_CurrentStep;
     }else{
         $currentStep = $this->getCurrentStep();
     }
        if ($currentStep == $step)
            return;
  switch(strtoupper($this->m_NaviMethod)){
   case "SWITCHFORM":
    $targetForm = $this->getStepName($step);
    $currentForm = $this->getStepName($currentStep);
    $this->m_CurrentStep = $step;
    $formObj = BizSystem::objectFactory()->getObject($currentForm);
    $formObj->switchForm($targetForm);
    break;
   case "SWITCHPAGE":
   default:
    $currentURL = BizSystem::getService(UTIL_SERVICE)->getViewURL($this->m_Name);
          $url = APP_INDEX.'/'.$currentURL.'/step_'.$step;
    BizSystem::clientProxy()->ReDirectPage($url);
    break;
  }
    }
setFormState ($formName, $state, $value)
Set form state
Parameters
string $formName form name
mixed $state state key
mixed $value
Returns
void
Definition at line 201 of file EasyViewWizard.php.
    {
        $this->m_FormStates[$formName][$state] = $value;
    }
setSessionVars ($sessionContext)
Save Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 55 of file EasyViewWizard.php.
    {
        if ($this->m_DropSession){
            $sessionContext->cleanObj($this->m_Name, true);
        }else{
            $sessionContext->setObjVar($this->m_Name, "FormStates", $this->m_FormStates, true);
            $sessionContext->setObjVar($this->m_Name, "CurrentStep", $this->m_CurrentStep, true);
        }
    }
Field Documentation
$m_CurrentStep protected
Definition at line 27 of file EasyViewWizard.php.
Referenced by getCurrentStep(), outputAttrs(), and renderStep().
$m_DropSession protected
Definition at line 29 of file EasyViewWizard.php.
$m_FormStates protected
Definition at line 28 of file EasyViewWizard.php.
$m_NaviMethod protected
Definition at line 30 of file EasyViewWizard.php.