Openbiz Framework API: ColumnImage Class Reference
ColumnImage Class Reference
Public Member Functions
render ()
Public Member Functions inherited from ColumnText
matchRemoteMethod ($method)
renderLabel ()
setSortFlag ($flag=null)
Public Member Functions inherited from LabelText
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_Alt
$m_ImgUrl
$m_Title
Data Fields inherited from ColumnText
$m_ColumnStyle
$m_Sortable
Data Fields inherited from LabelText
$m_DisplayFormat
$m_FieldName
$m_Label
$m_Link
$m_MaxLength
$m_Percent
$m_StripTags
$m_Target
$m_Text
Data Fields inherited from Element
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getAlt ()
getTitle ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from ColumnText
readMetaData (&$xmlArr)
Protected Member Functions inherited from LabelText
getLink ()
getTarget ()
getText ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 28 of file ColumnImage.php.
Member Function Documentation
getAlt () protected
Get image alternate(ALT) attribut
Returns
string
Definition at line 66 of file ColumnImage.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by render().
    {
        if ($this->m_Alt == null)
            return null;
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Alt, $formobj);
    }
getTitle () protected
Get image title
Returns
string
Definition at line 79 of file ColumnImage.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by render().
    {
        if ($this->m_Title == null)
            return null;
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Title, $formobj);
    }
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 53 of file ColumnImage.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_Alt = isset($xmlArr["ATTRIBUTES"]["ALT"]) ? $xmlArr["ATTRIBUTES"]["ALT"] : null;
        $this->m_Title = isset($xmlArr["ATTRIBUTES"]["TITLE"]) ? $xmlArr["ATTRIBUTES"]["TITLE"] : null;
        $this->m_ImgUrl = isset($xmlArr["ATTRIBUTES"]["IMGURL"]) ? $xmlArr["ATTRIBUTES"]["IMGURL"] : '';
    }
render ()
Render element, according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 92 of file ColumnImage.php.
References $m_ImgUrl, getAlt(), Element\getFunction(), Resource\getImageUrl(), LabelText\getLink(), Element\getStyle(), LabelText\getTarget(), LabelText\getText(), and getTitle().
    {
     if(!$this->getText())
     {
      $val = ($this->m_ImgUrl) ? $this->m_ImgUrl.$this->m_Value : $this->m_Value;
     }else{
      if(preg_match("/\{RESOURCE_URL\}/si",$this->m_Text)){
       $val = $this->getText();
      }else{
       $val = Resource::getImageUrl()."/".$this->getText();
      }
     }
        if ($val == null || $val =="")
            return "";
        $style = $this->getStyle();
        $func = $this->getFunction();
        $alt = $this->getAlt();
        $title = $this->getTitle();
        if ($val)
        {
            if($height = $this->m_Height)
            {
                $height = 'height="' . $height . '"';
            }
            if($width = $this->m_Width)
            {
                $width = 'width="' . $width . '"';
            }
            $alt = 'alt="' . $alt . '"';
            $title = 'title="' . $title . '"';
            if ($this->m_Link)
            {
                $link = $this->getLink();
                $target = $this->getTarget();
                $sHTML = "<a href=\"$link\" $target $func $style>" . "<img src=\"{$val}\" border=\"0\" $height $width $alt $title />" . "</a>";
            }
            else
            {
                $sHTML =  "<img $style $func border=\"0\" src=\"{$val}\" $height $width $alt $title />" ;
            }
        }
        return $sHTML;
    }
Field Documentation
$m_Alt
Definition at line 36 of file ColumnImage.php.
$m_ImgUrl
Definition at line 45 of file ColumnImage.php.
Referenced by render().
$m_Title
Definition at line 44 of file ColumnImage.php.