Openbiz Framework API: IDCardReader Class Reference
IDCardReader Class Reference
Public Member Functions
render ()
Public Member Functions inherited from InputElement
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
readMetaData (&$xmlArr)
Protected Member Functions inherited from InputElement
addSCKeyScript ()
getEnabled ()
getRequired ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Additional Inherited Members
Data Fields inherited from InputElement
$m_DefaultValue
$m_DefaultValueRename
$m_Description
$m_Enabled
$m_FieldName
$m_Hint
$m_Label
$m_Required
$m_Text
Detailed Description
Definition at line 27 of file IDCardReader.php.
Member Function Documentation
readMetaData (& $xmlArr) protected
Definition at line 29 of file IDCardReader.php.
{
  parent::readMetaData($xmlArr);
  $this->m_cssClass = isset($xmlArr["ATTRIBUTES"]["CSSCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSCLASS"] : "input_cardreader";
  $this->m_cssErrorClass = isset($xmlArr["ATTRIBUTES"]["CSSERRORCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSERRORCLASS"] : $this->m_cssClass."_error";
  $this->m_cssFocusClass = isset($xmlArr["ATTRIBUTES"]["CSSFOCUSCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSFOCUSCLASS"] : $this->m_cssClass."_focus";
 }
render ()
Render, draw the control according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 40 of file IDCardReader.php.
References MetaObject\$m_Name, Element\$m_Value, Element\getDefaultValue(), InputElement\getEnabled(), Element\getFunction(), Element\getStyle(), and Element\getText().
    {
     if($this->m_Value!=null){
      $value = $this->m_Value;
     }else{
      $value = $this->getText();
     }
     if($value==""){
      $value = $this->getDefaultValue();
     }
        $disabledStr = ($this->getEnabled() == "N") ? "READONLY=\"true\"" : "";
        $style = $this->getStyle();
        $func = $this->getFunction();
        $formobj = $this->GetFormObj();
     if($formobj->m_Errors[$this->m_Name]){
   $func .= "onchange=\"this.className='$this->m_cssClass'\"";
  }else{
   $func .= "onfocus=\"this.className='$this->m_cssFocusClass'\" onblur=\"this.className='$this->m_cssClass'\"";
  }
        //$sHTML = "<INPUT ReadOnly=\"Enabled\" NAME=\"" . $this->m_Name . "\" ID=\"" . $this->m_Name ."\" VALUE=\"" . $value . "\" $disabledStr $this->m_HTMLAttr $style $func />";
        //$sHTML .= "<br/><span ID=\"" . $this->m_Name ."_status\" >Standing By</span>";
        $sHTML = " <div id=\"" . $this->m_Name . "_reader\" $disabledStr $this->m_HTMLAttr $style $func >
            <span class=\"cardcode\" ID=\"" . $this->m_Name ."_code\" >$value</span>
            <div style=\"display:none;\" ><input ReadOnly=\"Enabled\" type=\"hidden\" NAME=\"" . $this->m_Name . "\" ID=\"" . $this->m_Name ."\" VALUE=\"\" /></div>
           </div>";
  $elementName = $this->m_Name;
        $sHTML .= "<script>Openbiz.IDCardReader.init('$elementName');\n</script>";
        return $sHTML;
    }