Openbiz Framework API: openbiz/bin/sysheader_inc.php File Reference
sysheader_inc.php File Reference
Namespaces
namespace openbiz\bin
Functions
__autoload_openbiz ($className)
dump ($arr, $debug=false)
setDocumentRoot ()
userErrorHandler ($errno, $errmsg, $filename, $linenum, $vars)
userExceptionHandler ($exc)
vdump ($arr, $debug=false)
Variables
$default_error_handler
$default_exception_handler
if(!function_exists("__autoload")) $g_BizSystem
if(!defined('ACCESS_SERVICE'))
define('ACCESS_SERVICE'service accessService
if(!defined('ACL_SERVICE'))
define('ACL_SERVICE'service aclService
if(!defined('AUTH_SERVICE'))
define('AUTH_SERVICE'service authService
if(!defined('OPENBIZ_BIN'))
define('OPENBIZ_BIN'OPENBIZ_HOME bin
if(!defined('CACHE_SERVICE'))
define('CACHE_SERVICE'service cacheService
if(!defined('CRYPT_SERVICE'))
define('CRYPT_SERVICE'service cryptService
if(!defined('DOTRIGGER_SERVICE'))
define('DOTRIGGER_SERVICE'service doTriggerService
if(isset($_SERVER['SERVER_NAME'])) else
if(!defined('EMAIL_SERVICE'))
define('EMAIL_SERVICE'service emailService
if(!defined('EVENTLOG_SERVICE'))
define('EVENTLOG_SERVICE'service eventlogService
if(!defined('EXCEL_SERVICE'))
define('EXCEL_SERVICE'service excelService
if(!defined('GENID_SERVICE'))
define('GENID_SERVICE'service genIdService
if (!defined('DEBUG')) define("DEBUG"
if(!defined('IO_SERVICE'))
define('IO_SERVICE'service ioService
if(!defined('SMARTY_DIR'))
define('SMARTY_DIR'OPENBIZ_HOME
others Smarty libs
if(!defined('LOCALEINFO_SERVICE'))
define('LOCALEINFO_SERVICE'service localeInfoService
if(!defined('LOG_SERVICE'))
define('LOG_SERVICE'service logService
if(!defined('OPENBIZ_META'))
define('OPENBIZ_META'OPENBIZ_HOME metadata
const nl
if(!defined('PDF_SERVICE'))
define('PDF_SERVICE'service pdfService
const Popup_Suffix
if(!defined('PROFILE_SERVICE'))
define('PROFILE_SERVICE'service profileService
if(!defined('QUERY_SERVICE'))
define('QUERY_SERVICE'service queryService
if(!defined('SECURITY_SERVICE'))
define('SECURITY_SERVICE'service securityService
if(!defined('VALIDATE_SERVICE'))
define('VALIDATE_SERVICE'service validateService
const ZEND_FRWK_HOME
Function Documentation
__autoload_openbiz ($className)
Definition at line 100 of file sysheader_inc.php.
References BizClassLoader\loadClass().
{
    /*$filePath = BizSystem::getLibFileWithPath($className);
    if ($filePath)
    {
        include_once($filePath);
        return;
    }*/
 BizClassLoader::loadClass($className);
}
if(!function_exists("__autoload"))
{
 spl_autoload_register("__autoload_openbiz");
}
dump ($arr, $debug = false)
formatted output given variable by using print_r() function
Author
Garbin
Parameters
any
Returns
void
Definition at line 160 of file sysheader_inc.php.
{
 if($debug)
  $debug_fun='debug_print_backtrace();';
 echo '<pre>';
 array_walk(func_get_args(), create_function('&$item, $key', 'print_r($item);'.$debug_fun.''));
 echo '</pre>';
 exit();
}
setDocumentRoot ()
Definition at line 142 of file sysheader_inc.php.
{
    if(!isset($_SERVER['DOCUMENT_ROOT'])){ if(isset($_SERVER['SCRIPT_FILENAME'])){
    $_SERVER['DOCUMENT_ROOT'] = str_replace( '\\', '/', substr($_SERVER['SCRIPT_FILENAME'], 0, 0-strlen($_SERVER['PHP_SELF'])));
    }; };
    if(!isset($_SERVER['DOCUMENT_ROOT'])){ if(isset($_SERVER['PATH_TRANSLATED'])){
    $_SERVER['DOCUMENT_ROOT'] = str_replace( '\\', '/', substr(str_replace('\\\\', '\\', $_SERVER['PATH_TRANSLATED']), 0, 0-strlen($_SERVER['PHP_SELF'])));
    }; };
}
userErrorHandler ($errno, $errmsg, $filename, $linenum, $vars)
Definition at line 122 of file sysheader_inc.php.
{
    //include_once(OPENBIZ_BIN.'ErrorHandler.php');
    OB_ErrorHandler::ErrorHandler($errno, $errmsg, $filename, $linenum, $vars);
}
userExceptionHandler ($exc)
Definition at line 133 of file sysheader_inc.php.
{
    //include_once(OPENBIZ_BIN.'ErrorHandler.php');
    OB_ErrorHandler::ExceptionHandler($exc);
}
vdump ($arr, $debug = false)
formatted output given variable by using var_dump() function
Author
Garbin
Parameters
any
Returns
void
Definition at line 177 of file sysheader_inc.php.
{
 if($debug)
  $debug_fun='debug_print_backtrace();';
 echo '<pre>';
 array_walk(func_get_args(), create_function('&$item, $key', 'var_dump($item);'.$debug_fun.''));
 echo '</pre>';
 exit();
}
Variable Documentation
$default_error_handler
Definition at line 87 of file sysheader_inc.php.
$default_exception_handler
Definition at line 88 of file sysheader_inc.php.
if (!function_exists("__autoload")) $g_BizSystem
Definition at line 116 of file sysheader_inc.php.
Referenced by EasyForm\getViewObject(), HTMLTabs\render(), ioService\reportError(), and HTMLTabs\setClientScripts().
if (!defined('ACCESS_SERVICE')) define('ACCESS_SERVICE' service accessService
Definition at line 40 of file sysheader_inc.php.
if (!defined('ACL_SERVICE')) define('ACL_SERVICE' service aclService
Definition at line 41 of file sysheader_inc.php.
if (!defined('AUTH_SERVICE')) define('AUTH_SERVICE' service authService
Definition at line 39 of file sysheader_inc.php.
if (!defined('OPENBIZ_BIN')) define('OPENBIZ_BIN' OPENBIZ_HOME bin
Definition at line 27 of file sysheader_inc.php.
if (!defined('CACHE_SERVICE')) define('CACHE_SERVICE' service cacheService
Definition at line 54 of file sysheader_inc.php.
if (!defined('CRYPT_SERVICE')) define('CRYPT_SERVICE' service cryptService
Definition at line 55 of file sysheader_inc.php.
if (!defined('DOTRIGGER_SERVICE')) define('DOTRIGGER_SERVICE' service doTriggerService
Definition at line 48 of file sysheader_inc.php.
if (isset($_SERVER['SERVER_NAME'])) else
Definition at line 20 of file sysheader_inc.php.
if (!defined('EMAIL_SERVICE')) define('EMAIL_SERVICE' service emailService
Definition at line 47 of file sysheader_inc.php.
if (!defined('EVENTLOG_SERVICE')) define('EVENTLOG_SERVICE' service eventlogService
Definition at line 53 of file sysheader_inc.php.
if (!defined('EXCEL_SERVICE')) define('EXCEL_SERVICE' service excelService
Definition at line 44 of file sysheader_inc.php.
if (!defined('GENID_SERVICE')) define('GENID_SERVICE' service genIdService
Definition at line 49 of file sysheader_inc.php.
if
Definition at line 59 of file sysheader_inc.php.
if (!defined('IO_SERVICE')) define('IO_SERVICE' service ioService
Definition at line 46 of file sysheader_inc.php.
if (!defined('SMARTY_DIR')) define('SMARTY_DIR' OPENBIZ_HOME others Smarty libs
Definition at line 34 of file sysheader_inc.php.
if (!defined('LOCALEINFO_SERVICE')) define('LOCALEINFO_SERVICE' service localeInfoService
Definition at line 56 of file sysheader_inc.php.
if (!defined('LOG_SERVICE')) define('LOG_SERVICE' service logService
Definition at line 43 of file sysheader_inc.php.
if (!defined('OPENBIZ_META')) define('OPENBIZ_META' OPENBIZ_HOME metadata
Definition at line 28 of file sysheader_inc.php.
const nl
Definition at line 20 of file sysheader_inc.php.
if (!defined('PDF_SERVICE')) define('PDF_SERVICE' service pdfService
Definition at line 45 of file sysheader_inc.php.
const Popup_Suffix
Definition at line 74 of file sysheader_inc.php.
Referenced by BizController\invoke().
if (!defined('PROFILE_SERVICE')) define('PROFILE_SERVICE' service profileService
Definition at line 42 of file sysheader_inc.php.
if (!defined('QUERY_SERVICE')) define('QUERY_SERVICE' service queryService
Definition at line 51 of file sysheader_inc.php.
if (!defined('SECURITY_SERVICE')) define('SECURITY_SERVICE' service securityService
Definition at line 52 of file sysheader_inc.php.
if (!defined('VALIDATE_SERVICE')) define('VALIDATE_SERVICE' service validateService
Definition at line 50 of file sysheader_inc.php.
const ZEND_FRWK_HOME
Definition at line 71 of file sysheader_inc.php.