Openbiz Framework API: BizController Class Reference
BizController Class Reference
Public Member Functions
dispatchRequest ()
processSecurityFilters ()
renderView ($viewName, $form="", $rule="", $params=null, $hist="")
Protected Member Functions
invoke ()
validateRequest ($obj, $methodName)
Detailed Description
Definition at line 45 of file BizController.php.
Member Function Documentation
dispatchRequest ()
Dispatches client requests to proper objects, print the returned html text.
Returns
void
Definition at line 82 of file BizController.php.
References BizSystem\clientProxy(), and BizSystem\sessionContext().
    {
        if ($this->_hasView())
        {
            return $this->_dispatchView();
        } else
        {
         if ($this->_isSessionTimeout())  // show timeout view
         {
             BizSystem::sessionContext()->destroy();
             //return $this->renderView($this->_userTimeoutView);
             return BizSystem::clientProxy()->redirectView($this->_userTimeoutView);
         }
         $this->_dispatchRPC();
        }
    }
invoke () protected
Invoke the action passed from browser
Returns
HTML content
Definition at line 216 of file BizController.php.
References BizSystem\clientProxy(), BizSystem\getMessage(), BizSystem\getObject(), Popup_Suffix, and validateRequest().
    {
        //patched by jixian for fix ajax post data
        if (isset($_POST['__url']))
        {
            $getUrl = parse_url($_POST['__url']);
            $query = $getUrl['query'];
            $parameter = explode('&', $query);
            foreach ($parameter as $param)
            {
                $data = explode('=', $param);
                $name = $data[0];
                $value = $data[1];
                $_GET[$name] = $value;
            }
        }
        // get invocation type
        $invocationType = (isset($_REQUEST['F']) ? $_REQUEST['F'] : "");
        if ($invocationType == '') // is invocation?
            return;
        // check is valid invocation?
        if ($invocationType != "RPCInvoke" && $invocationType != "Invoke")
        {
            trigger_error("$invocationType is not a valid invocation", E_USER_ERROR);
            return;
        }
        // read parameters
        $arg_list = array();
        $i = 0;
        eval("\$P$i = (isset(\$_REQUEST['P$i']) ? \$_REQUEST['P$i']:'');");
        $Ptmp = "P" . $i;
        eval("\$P$i = (isset(\$_REQUEST['P$i']) ? \$_REQUEST['P$i']:'');");
        if (strstr($P0, Popup_Suffix)) // _popupx_?
        {
            $name_len = strlen($P0);
            $suffix_len = strlen(Popup_Suffix);
            $P0 = substr($P0, 0, $name_len - $suffix_len - 1) . "]";
        }
        while ($$Ptmp != "")
        {
            $parm = $$Ptmp;
            $parm = substr($parm, 1, strlen($parm) - 2);
            $arg_list[] = $parm;
            $i++;
            eval("\$P$i = (isset(\$_REQUEST['P$i']) ? \$_REQUEST['P$i']:'');");
            $Ptmp = "P" . $i;
        }
        if ($invocationType == "RPCInvoke")
            BizSystem::clientProxy()->setRPCFlag(true);
        // invoke the function
        $num_arg = count($arg_list);
        if ($num_arg < 2)
        {
            $errmsg = BizSystem::getMessage("SYS_ERROR_RPCARG", array($class));
            trigger_error($errmsg, E_USER_ERROR);
        } else
        {
            $objName = array_shift($arg_list);
            $methodName = array_shift($arg_list);
            $obj = BizSystem::getObject($objName);
            if ($obj)
            {
                if (method_exists($obj, $methodName))
                {
                    if (!$this->validateRequest($obj, $methodName))
                    {
                        $errmsg = BizSystem::getMessage("SYS_ERROR_REQUEST_REJECT", array($obj->m_Name, $methodName));
                        trigger_error($errmsg, E_USER_ERROR);
                    }
                    switch (count($arg_list))
                    {
                        case 0: $rt_val = $obj->$methodName();
                            break;
                        case 1: $rt_val = $obj->$methodName($arg_list[0]);
                            break;
                        case 2: $rt_val = $obj->$methodName($arg_list[0], $arg_list[1]);
                            break;
                        case 3: $rt_val = $obj->$methodName($arg_list[0], $arg_list[1], $arg_list[2]);
                            break;
                        default: $rt_val = call_user_func_array(array($obj, $methodName), $arg_list);
                    }
                } else
                {
                    $errmsg = BizSystem::getMessage("SYS_ERROR_METHODNOTFOUND", array($objName, $methodName));
                    trigger_error($errmsg, E_USER_ERROR);
                }
            } else
            {
                $errmsg = BizSystem::getMessage("SYS_ERROR_CLASSNOTFOUND", array($objName));
                trigger_error($errmsg, E_USER_ERROR);
            }
            if ($invocationType == "Invoke")  // no RPC invoke, page reloaded -> rerender view
            {
                if (BizSystem::clientProxy()->hasOutput())
                    BizSystem::clientProxy()->printOutput();
            }
            else if ($invocationType == "RPCInvoke")  // RPC invoke
            {
                if (BizSystem::clientProxy()->hasOutput())
                {
                    if ($_REQUEST['jsrs'] == 1)
                        echo "<html><body><form name=\"jsrs_Form\"><textarea name=\"jsrs_Payload\" id=\"jsrs_Payload\">";
                    BizSystem::clientProxy()->printOutput();
                    if ($_REQUEST['jsrs'] == 1)
                        echo "</textarea></form></body></html>";
                }
                else
                    return $rt_val;
            }
        }
    }
processSecurityFilters ()
Process Security Filters
Returns
boolean true if success, and false if have error
Definition at line 57 of file BizController.php.
References BizSystem\getService(), and renderView().
    {
        $securityService = BizSystem::getService(SECURITY_SERVICE);
        $securityService->processFilters();
        if ($err_msg = $securityService->getErrorMessage())
        {
            if ($this->_securityDeniedView)
            {
                $view = $this->_securityDeniedView;
            } else
            {
                $view = $this->_accessDeniedView;
            }
            $this->renderView($view);
            //BizSystem::clientProxy()->redirectView($view);
            return false;
        }
        return true;
    }
renderView ($viewName, $form = "", $rule = "", $params = null, $hist = "")
Render a bizview
Parameters
string $viewName name of bizview
string $rule the search rule of a bizform who is not depent on (a subctrl of) another bizform
Returns
void
Definition at line 161 of file BizController.php.
References BizSystem\getObject(), BizSystem\instance(), and BizSystem\sessionContext().
Referenced by processSecurityFilters().
    {
        $bizSystem = BizSystem::instance();
        /* @var $viewObj EasyView */
        if ($viewName == "__DynPopup")
        {
            $viewObj = BizSystem::getObject($viewName);
            $viewObj->render();
            return;
        }
        // if previous view is different with the to-be-loaded view,
        // clear the previous session objects
        $prevViewName = $bizSystem->getCurrentViewName();
        $prevViewSet = $bizSystem->getCurrentViewSet();
        // need to set current view before get view object
        $bizSystem->setCurrentViewName($viewName);
        $viewObj = BizSystem::getObject($viewName);
        if (!$viewObj)
            return;
        $viewSet = $viewObj->getViewSet();
        $bizSystem->setCurrentViewSet($viewSet);
        /*
          if ($prevViewSet && $viewSet && $prevViewSet == $viewSet)   // keep prev view session objects if they have same viewset
          BizSystem::sessionContext()->clearSessionObjects(true);
          else
          BizSystem::sessionContext()->clearSessionObjects(false);
         */
        BizSystem::sessionContext()->clearSessionObjects(true);
        if ($hist == "N") // clean view history
            $viewObj->cleanViewHistory();
        if ($form != "" && $rule != "")
            $viewObj->processRule($form, $rule, TRUE);
        if ($params)
            $viewObj->setParameters($params);
        if (isset($_GET['mode']))   // can specify mode of form
            $viewObj->setFormMode($form, $_GET['mode']);
        $viewObj->render();
        //BizController::hidePageLoading();
    }
validateRequest ($obj, $methodName) protected
Validate the request from client.
Parameters
object $obj the to be called object
string $methodName the to be called method name
Returns
boolean
Definition at line 350 of file BizController.php.
Referenced by invoke().
    {
        if (!is_a($obj, "EasyForm") && !is_a($obj, "BizForm"))
        {
            return false;
        }
        if (is_a($obj, "EasyForm"))
        {
            if (!$obj->validateRequest($methodName))
            {
                return false;
            }
        }
        return true;
    }