Openbiz Framework API: openbiz/bin/easy/SearchHelper.php File Reference
SearchHelper.php File Reference
Namespaces
namespace openbiz\bin\easy
Functions
inputValToRule ($fieldName, $inputVal, $formObj)
Function Documentation
inputValToRule ($fieldName, $inputVal, $formObj)
Convert the user input on a given fieldcontrol in query mode to search rule
Parameters
string $fieldName - fieldcontrol name
string $inputVal - use input text
EasyForm $formObj
Returns
string - searchRule
Definition at line 25 of file SearchHelper.php.
References QueryStringParam\formatQueryString(), and BizSystem\typeManager().
Referenced by EasyForm\runSearch().
{
    // todo: should check single quote for nonoperators clauses
    // find locations for all sql key words
    // search for starting ' and closing ' pair, check if sql key word in the pair
    $val = strtoupper(trim($inputVal));
    // check " AND ", " OR "
    if (($pos=strpos($val, " AND "))!==false)
    {
        $inputArr = explode(" AND ", $val);
        $retStr = null;
        foreach($inputArr as $v)
            $retStr .= ($retStr) ? " AND ".inputValToRule($fieldName, $v, $formObj) : inputValToRule($fieldName, $v, $formObj);
        return $retStr;
    }
    else if (($pos=strpos($val, " OR "))!==false)
    {
        $inputArr = explode(" OR ", $val);
        $retStr = null;
        foreach($inputArr as $v)
            $retStr .= ($retStr) ? " OR ".inputValToRule($fieldName, $v, $formObj) : inputValToRule($fieldName, $v, $formObj);
        return "(".$retStr.")";
    }
    // check >=, >, <=, <, =
    if (($pos=strpos($val, "<>"))!==false || ($pos=strpos($val, "!="))!==false)
    {
        $opr = "<>";
        $oprlen = 2;
    }
    else if (($pos=strpos($val, ">="))!==false)
    {
        $opr = ">=";
        $oprlen = 2;
    }
    else if (($pos=strpos($val, ">"))!==false)
    {
        $opr = ">";
        $oprlen = 1;
    }
    else if (($pos=strpos($val, "<="))!==false)
    {
        $opr = "<=";
        $oprlen = 2;
    }
    else if (($pos=strpos($val, "<"))!==false)
    {
        $opr = "<";
        $oprlen = 1;
    }
    else if (($pos=strpos($val, "="))!==false)
    {
        $opr = "=";
        $oprlen = 1;
    }
    if ($opr)
    {
        $val = trim(substr($val, $pos+$oprlen));
    }
    if (strpos($val, "*") !== false)
    {
        $opr = "LIKE";
        $val = str_replace("*", "%", $val);
    }
    //if (strpos($val, "'") !== false) {   // not needed since addslashes() is called before
    //   $val = str_replace("'", "\\'", $val);
    //}
    if (!$opr)
        $opr = "=";
    // unformat value to real value data
    if($formObj->getDataObj()){
     $bizField = $formObj->getDataObj()->getField($fieldName);
     $realValue = BizSystem::typeManager()->formattedStringToValue($bizField->m_Type, $bizField->m_Format, $val);
    }else{
     $realValue = $val;
    }
    // set the query param
    $queryString = QueryStringParam::formatQueryString("[$fieldName]", $opr, $realValue);
    return $queryString;
    //return "[" . $field . "] " . $opr . " '" . $realVal . "'";
}