Openbiz Framework API: InputElement Class Reference
InputElement Class Reference
Public Member Functions
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_DefaultValue
$m_DefaultValueRename
$m_Description
$m_Enabled
$m_FieldName
$m_Hint
$m_Label
$m_Required
$m_Text
Data Fields inherited from Element
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
addSCKeyScript ()
getEnabled ()
getRequired ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 27 of file InputElement.php.
Member Function Documentation
addSCKeyScript () protected
Add sort-cut key scripts
Returns
string
Definition at line 119 of file InputElement.php.
References BizSystem\clientProxy(), Element\getFormObj(), and Element\getSCKeyFuncMap().
Referenced by Button\render().
    {
        $keyMap = $this->getSCKeyFuncMap();
        if (count($keyMap) == 0)
            return "";
        BizSystem::clientProxy()->appendScripts("shortcut", "shortcut.js");
        $str = "<script>\n";
        $formObj = $this->getFormObj();
        if (!$formObj->removeall_sck) {
            $str .= " shortcut.removeall(); \n";
            $formObj->removeall_sck = true;
        }
        foreach ($keyMap as $key => $func)
            $str .= " shortcut.remove(\"$key\"); \n";
        $str .= " shortcut.add(\"$key\",function() { $func }); \n";
        $str .= "</script>\n";
        return $str;
    }
getEnabled () protected
Get enable status
Returns
string
Definition at line 70 of file InputElement.php.
References Expression\evaluateExpression(), and Element\getFormObj().
Referenced by ImageSelector\render(), HTMLButton\render(), FileInput\render(), Radio\render(), ResetButton\render(), File\render(), ColorPicker\render(), SubmitButton\render(), BarcodeScanner\render(), InputText\render(), Password\render(), IDCardReader\render(), Textarea\render(), Listbox\render(), Button\render(), DropDownList\render(), InputPassword\render(), Checkbox\render(), EditCombobox\render(), ColumnInputText\render(), ColumnListbox\render(), FileUploader\render(), and ImageUploader\render().
    {
        $formObj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Enabled, $formObj);
    }
getRequired () protected
Definition at line 76 of file InputElement.php.
References Expression\evaluateExpression(), and Element\getFormObj().
    {
        $formObj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Required, $formObj);
    }
getValue ()
Definition at line 82 of file InputElement.php.
Referenced by ImageSelector\render(), RichText\render(), Radio\render(), Listbox\render(), and CKEditor\render().
    {
     $value=parent::getValue();
     if($value==$this->m_Hint)
     {
      $this->m_Value = null;
      return null;
     }
     return $value;
    }
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 45 of file InputElement.php.
References MetaObject\prefixPackage().
    {
        parent::readMetaData($xmlArr);
        $this->m_FieldName = isset($xmlArr["ATTRIBUTES"]["FIELDNAME"]) ? $xmlArr["ATTRIBUTES"]["FIELDNAME"] : null;
        $this->m_Label = isset($xmlArr["ATTRIBUTES"]["LABEL"]) ? $xmlArr["ATTRIBUTES"]["LABEL"] : null;
        $this->m_Description = isset($xmlArr["ATTRIBUTES"]["DESCRIPTION"]) ? $xmlArr["ATTRIBUTES"]["DESCRIPTION"] : null;
        $this->m_DefaultValue = isset($xmlArr["ATTRIBUTES"]["DEFAULTVALUE"]) ? $xmlArr["ATTRIBUTES"]["DEFAULTVALUE"] : null;
        $this->m_DefaultValueRename = isset($xmlArr["ATTRIBUTES"]["DEFAULTVALUERENAME"]) ? $xmlArr["ATTRIBUTES"]["DEFAULTVALUERENAME"] : "Y";
        $this->m_Required = isset($xmlArr["ATTRIBUTES"]["REQUIRED"]) ? $xmlArr["ATTRIBUTES"]["REQUIRED"] : null;
        $this->m_Enabled = isset($xmlArr["ATTRIBUTES"]["ENABLED"]) ? $xmlArr["ATTRIBUTES"]["ENABLED"] : null;
        $this->m_Text = isset($xmlArr["ATTRIBUTES"]["TEXT"]) ? $xmlArr["ATTRIBUTES"]["TEXT"] : null;
        $this->m_Hint = isset($xmlArr["ATTRIBUTES"]["HINT"]) ? $xmlArr["ATTRIBUTES"]["HINT"] : null;
        // if no class name, add default class name. i.e. NewRecord => ObjName.NewRecord
        $this->m_ValuePicker = $this->prefixPackage($this->m_ValuePicker);
    }
render ()
Render, draw the element according to the mode just return element value
Returns
string HTML text
Implements iUIControl.
Definition at line 109 of file InputElement.php.
References Element\$m_Value.
    {
        return $this->m_Value;
    }
renderLabel ()
Render label, just return label value
Returns
string
Definition at line 97 of file InputElement.php.
References Element\translateString().
    {
        $sHTML = $this->translateString($this->m_Label);
        return $sHTML;
    }
Field Documentation
$m_DefaultValue
Definition at line 32 of file InputElement.php.
Referenced by Checkbox\getValue(), and Checkbox\render().
$m_DefaultValueRename
Definition at line 33 of file InputElement.php.
$m_Description
Definition at line 31 of file InputElement.php.
$m_Enabled
Definition at line 35 of file InputElement.php.
$m_FieldName
Definition at line 29 of file InputElement.php.
Referenced by InputDateRangePicker\getSearchRule(), FileInput\getValue(), and InputPassword\getValue().
$m_Hint
Definition at line 37 of file InputElement.php.
$m_Label
Definition at line 30 of file InputElement.php.
Referenced by ColumnInputText\renderLabel(), ColumnListbox\renderLabel(), ColumnList\renderLabel(), and Button\renderLabel().
$m_Required
Definition at line 34 of file InputElement.php.
$m_Text
Definition at line 36 of file InputElement.php.