Openbiz Framework API: ColumnBool Class Reference
ColumnBool Class Reference
Public Member Functions
render ()
Public Member Functions inherited from ColumnText
matchRemoteMethod ($method)
renderLabel ()
setSortFlag ($flag=null)
Public Member Functions inherited from LabelText
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_FlaseImg
$m_FlaseValue
$m_TrueImg
$m_TrueValue
Data Fields inherited from ColumnText
$m_ColumnStyle
$m_Sortable
Data Fields inherited from LabelText
$m_DisplayFormat
$m_FieldName
$m_Label
$m_Link
$m_MaxLength
$m_Percent
$m_StripTags
$m_Target
$m_Text
Data Fields inherited from Element
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
readMetaData (&$xmlArr)
Protected Member Functions inherited from ColumnText
readMetaData (&$xmlArr)
Protected Member Functions inherited from LabelText
getLink ()
getTarget ()
getText ()
readMetaData (&$xmlArr)
Protected Member Functions inherited from Element
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 28 of file ColumnBool.php.
Member Function Documentation
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 41 of file ColumnBool.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_TrueImg=isset($xmlArr["ATTRIBUTES"]["TRUEIMG"])?$xmlArr["ATTRIBUTES"]["TRUEIMG"]:"flag_y.gif";
        $this->m_FalseImg=isset($xmlArr["ATTRIBUTES"]["FALSEIMG"])?$xmlArr["ATTRIBUTES"]["FALSEIMG"]:"flag_n.gif";
        $this->m_TrueValue=isset($xmlArr["ATTRIBUTES"]["TRUEVALUE"])?$xmlArr["ATTRIBUTES"]["TRUEVALUE"]:true;
        $this->m_FalseValue=isset($xmlArr["ATTRIBUTES"]["FLASEVALUE"])?$xmlArr["ATTRIBUTES"]["FLASEVALUE"]:false;
    }
render ()
Render element, according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 55 of file ColumnBool.php.
References MetaObject\$m_Name, $m_TrueImg, Expression\evaluateExpression(), Element\getFormObj(), Element\getFunction(), Resource\getImageUrl(), LabelText\getLink(), Element\getStyle(), LabelText\getTarget(), LabelText\getText(), and Element\getValue().
    {
        $val=$this->getText()?$this->getText():$this->getValue();
        $style = $this->getStyle();
        $text = $this->getText();
        $id = $this->m_Name;
        $func = $this->getFunction();
        if($val==='1' || $val==='true' || strtoupper($val) == 'Y' || $val>0 || $val==$this->m_TrueValue)
        {
         $image_url  = $this->m_TrueImg;
        }
        else
        {
         $image_url  = $this->m_FalseImg;
        }
        if(preg_match("/\{.*\}/si",$image_url))
        {
         $formobj = $this->getFormObj();
         $image_url =  Expression::evaluateExpression($image_url, $formobj);
        }else{
         $image_url = Resource::getImageUrl()."/".$image_url;
        }
     if ($this->m_Link)
        {
            $link = $this->getLink();
            $target = $this->getTarget();
            $sHTML = "<a  id=\"$id\" href=\"$link\" $target $func $style><img src='$image_url' /></a>";
        }else{
         $sHTML = "<img id=\"$id\"  alt=\"".$text."\" title=\"".$text."\"  src='$image_url' />";
        }
        return $sHTML;
    }
Field Documentation
$m_FlaseImg
Definition at line 31 of file ColumnBool.php.
$m_FlaseValue
Definition at line 33 of file ColumnBool.php.
$m_TrueImg
Definition at line 30 of file ColumnBool.php.
Referenced by render().
$m_TrueValue
Definition at line 32 of file ColumnBool.php.