Openbiz Framework API: Resource Class Reference
Resource Class Reference
Static Public Member Functions
static getCoreLibFilePath ($className)
static getCssUrl ()
static getCurrentTheme ()
static getImageUrl ()
static getJsUrl ()
static getLibFileWithPath ($className, $packageName="")
static getMessage ($msgId, $params=array())
static getSmartyTemplate ()
static getTplFileWithPath ($templateFile, $packageName)
static & getXmlArray ($xmlFile)
static getXmlFileWithPath ($xmlObj)
static getZendTemplate ()
static loadMessage ($messageFile, $packageName="")
Data Fields
const DEFAULT_THEME
Detailed Description
Definition at line 30 of file Resource.php.
Member Function Documentation
static getCoreLibFilePath ($className) static
Get core path of class
Parameters
string $className class name
Returns
string full file name of class
Definition at line 366 of file Resource.php.
References BizClassLoader\getCoreLibFilePath().
{
        return BizClassLoader::getCoreLibFilePath($className);
    }
static getCssUrl () static
Get CSS URL
Returns
string
Definition at line 124 of file Resource.php.
References getCurrentTheme(), THEME_URL, and USE_THEME.
Referenced by ClientProxy\appendStyles().
    {
        if (isset(self::$_cssUrl))
            return self::$_cssUrl;
        $useTheme = !defined('USE_THEME') ? 0 : USE_THEME;
        $themeUrl = !defined('THEME_URL') ? APP_URL . "/themes" : THEME_URL;
  $themeName = Resource::getCurrentTheme();
        if ($useTheme)
            self::$_cssUrl = "$themeUrl/$themeName/css";
        else
            self::$_cssUrl = APP_URL . "/css";
        return self::$_cssUrl;
    }
static getCurrentTheme () static
Definition at line 447 of file Resource.php.
References DEFAULT_THEME, BizSystem\getUserPreference(), and BizSystem\sessionContext().
Referenced by getCssUrl(), getImageUrl(), getSmartyTemplate(), getTplFileWithPath(), getZendTemplate(), and EasyForm\outputAttrs().
    {
     if (Resource::$_currentTheme != null)
            return Resource::$_currentTheme;
  $currentTheme = "";
  if (isset($_GET['theme'])){
            $currentTheme = $_GET['theme'];
        }
  if ($currentTheme == ""){
         $currentTheme = BizSystem::sessionContext()->getVar("THEME");
        }
  if ($currentTheme == ""){
         $currentTheme = BizSystem::getUserPreference("theme");
        }
        if ($currentTheme == "" && defined('THEME_NAME')) {
   $currentTheme = THEME_NAME;
  }
        if($currentTheme == ""){
            $currentTheme = Resource::DEFAULT_THEME;
        }
        // TODO: user pereference has language setting
        BizSystem::sessionContext()->setVar("THEME", $currentTheme);
        Resource::$_currentTheme = $currentTheme;
        return $currentTheme;
    }
static getImageUrl () static
Get image URL
Returns
string
Definition at line 105 of file Resource.php.
References getCurrentTheme(), THEME_URL, and USE_THEME.
Referenced by ImageSelector\render(), LabelTextarea\render(), LabelBool\render(), ColumnBool\render(), Button\render(), ColumnImage\render(), ColumnShare\render(), and DropDownList\renderList().
    {
        if (isset(self::$_imageUrl))
            return self::$_imageUrl;
        $useTheme = !defined('USE_THEME') ? 0 : USE_THEME;
        $themeUrl = !defined('THEME_URL') ? "../themes" : THEME_URL;
        $themeName = Resource::getCurrentTheme();
        if ($useTheme)
            self::$_imageUrl = "$themeUrl/$themeName/images";
        else
            self::$_imageUrl = "../images";
        return self::$_imageUrl;
    }
static getJsUrl () static
Get JavaScript(JS) URL
Returns
string
Definition at line 142 of file Resource.php.
References JS_URL.
    {
        if (isset(self::$_jsUrl))
            return self::$_jsUrl;
        self::$_jsUrl = !defined('JS_URL') ? APP_URL . "/js" : JS_URL;
        return self::$_jsUrl;
    }
static getLibFileWithPath ($className, $packageName = "") static
Get openbiz library php file path by searching modules/package, /bin/package and /bin
Parameters
string $className
Returns
string php library file path
Definition at line 354 of file Resource.php.
References BizClassLoader\getLibFileWithPath().
Referenced by BizSystem\getLibFileWithPath().
    {
        return BizClassLoader::getLibFileWithPath($className, $packageName);
    }
static getMessage ($msgId, $params = array()) static
Get message from CONSTANT, translate and format it
Parameters
string $msgId ID if constant
array $params parameter for format (use vsprintf)
Returns
string
Definition at line 90 of file Resource.php.
References I18n\t().
Referenced by BizSystem\getMessage().
    {
        $message = constant($msgId);
        if (isset($message))
        {
            $message = I18n::t($message, $msgId, 'system');
            $result = vsprintf($message, $params);
        }
        return $result;
    }
static getSmartyTemplate () static
Get smarty template
Returns
Smarty smarty object
Definition at line 154 of file Resource.php.
References APP_INDEX, I18n\getCurrentLangCode(), getCurrentTheme(), JS_URL, RESOURCE_PHP, RESOURCE_URL, SMARTY_CPL_PATH, THEME_PATH, THEME_URL, and USE_THEME.
Referenced by BizSystem\getSmartyTemplate().
    {
     if(extension_loaded('ionCube Loader')){
         include_once(SMARTY_DIR . "Smarty.class.php");
     }else{
      include_once(SMARTY_DIR . "Smarty.class.src.php");
     }
        $smarty = new Smarty;
        $useTheme = !defined('USE_THEME') ? 0 : USE_THEME;
        if ($useTheme)
        {
            $theme = Resource::getCurrentTheme();
            $themePath = $theme;    // BizSystem::configuration()->GetThemePath($theme);
            if (is_dir(THEME_PATH . "/" . $themePath . "/template"))
            {
                $templateRoot = THEME_PATH . "/" . $themePath . "/template";
            } else
            {
                $templateRoot = THEME_PATH . "/" . $themePath . "/templates";
            }
            $smarty->template_dir = $templateRoot;
            $smarty->compile_dir = defined('SMARTY_CPL_PATH') ? SMARTY_CPL_PATH."/".$themePath : $templateRoot . "/cpl";
            $smarty->config_dir = $templateRoot . "/cfg";
   if (!file_exists($smarty->compile_dir)) {
                @mkdir($smarty->compile_dir, 0777);
            }
            // load the config file which has the images and css url defined
            $smarty->config_load('tpl.conf');
        } else
        {
            if (defined('SMARTY_TPL_PATH'))
                $smarty->template_dir = SMARTY_TPL_PATH;
            if (defined('SMARTY_CPL_PATH'))
                $smarty->compile_dir = SMARTY_CPL_PATH."/".$themePath;
            if (defined('SMARTY_CFG_PATH'))
                $smarty->config_dir = SMARTY_CFG_PATH;
        }
        if(!is_dir($smarty->compile_dir)){
         mkdir($smarty->compile_dir,0777);
        }
        // load the config file which has the images and css url defined
        $smarty->assign('app_url', APP_URL);
        $smarty->assign('app_index', APP_INDEX);
        $smarty->assign('js_url', JS_URL);
        $smarty->assign('css_url', THEME_URL . "/" . $theme . "/css");
        $smarty->assign('resource_url', RESOURCE_URL );
        $smarty->assign('resource_php', RESOURCE_PHP );
        $smarty->assign('theme_js_url', THEME_URL . "/" . $theme . "/js");
        $smarty->assign('theme_url', THEME_URL . "/" . $theme);
        $smarty->assign('image_url', THEME_URL . "/" . $theme . "/images");
        $smarty->assign('lang', strtolower(I18n::getCurrentLangCode()));
        $smarty->assign('lang_name', I18n::getCurrentLangCode());
        return $smarty;
    }
static getTplFileWithPath ($templateFile, $packageName) static
Get openbiz template file path by searching modules/package, /templates
Parameters
string $className
Returns
string php library file path
Definition at line 303 of file Resource.php.
References getCurrentTheme(), BizSystem\getMessage(), MODULE_EX_PATH, MODULE_PATH, and THEME_PATH.
Referenced by BizSystem\getTplFileWithPath().
    {
        //for not changing a lot things, the best injection point is added theme support here.
  $theme = Resource::getCurrentTheme();
        $themePath = $theme;    // BizSystem::configuration()->GetThemePath($theme);
        if ($themePath)
            $templateRoot = THEME_PATH . "/" . $themePath . "/template";
        else
            $templateRoot = SMARTY_TPL_PATH;
        $names = explode(".", $packageName);
        if (count($names) > 0)
            $moduleName = $names[0];
        $packagePath = str_replace('.', '/', $packageName);
        // check the leading char '@'
        $checkExtModule = true;
        if (strpos($packagePath, '@') === 0) {
            $packagePath = substr($packagePath, 1);
            $checkExtModule = false;
        }
        $searchTpls = array(
            MODULE_PATH . "/$packagePath/template/$templateFile",
            dirname(MODULE_PATH . "/$packagePath") . "/template/$templateFile",
            MODULE_PATH . "/$moduleName/template/$templateFile",
            //MODULE_PATH."/common/template/$templateFile",
            $templateRoot . "/$templateFile"
        );
        if ($checkExtModule && defined('MODULE_EX_PATH')) array_unshift($searchTpls, MODULE_EX_PATH . "/$packagePath/template/$templateFile");
  // device
  if (defined('CLIENT_DEVICE')) array_unshift($searchTpls, MODULE_PATH."/$moduleName/template/".CLIENT_DEVICE."/$templateFile");
        foreach ($searchTpls as $tplFile)
        {
            if (file_exists($tplFile))
            {
                return $tplFile;
            }
        }
        $errmsg = BizSystem::getMessage("UNABLE_TO_LOCATE_TEMPLATE_FILE", array($templateFile));
        trigger_error($errmsg, E_USER_ERROR);
        return null;
    }
static& getXmlArray ($xmlFile) static
Get Xml Array. If xml file has been compiled (has .cmp), load the cmp file as array; otherwise, compile the .xml to .cmp first new 2.2.3, .cmp files will be created in app/cache/metadata_cmp directory. replace '/' with '_' for example, /module/demo/BOEvent.xml has cmp file as _module_demo_BOEvent.xml
Parameters
string $xmlFile
Returns
array
Definition at line 381 of file Resource.php.
References CACHE_METADATA_PATH.
Referenced by BizSystem\getXmlArray().
    {
  if (isset(self::$_xmlArrayList[$xmlFile])) {
   return self::$_xmlArrayList[$xmlFile];
  }
        $objXmlFileName = $xmlFile;
  //echo "getXmlArray($xmlFile)\n";
        //$objCmpFileName = dirname($objXmlFileName) . "/__cmp/" . basename($objXmlFileName, "xml") . ".cmp";
        //$_crc32 = sprintf('%08X', crc32(dirname($objXmlFileName)));
        $_crc32 = strtoupper(md5(dirname($objXmlFileName)));
        $objCmpFileName = CACHE_METADATA_PATH . '/' . $_crc32 . '_'
                . basename($objXmlFileName, "xml") . "cmp";
        $xmlArr = null;
        //$cacheKey = substr($objXmlFileName, strlen(META_PATH)+1);
        $cacheKey = $objXmlFileName;
        $findInCache = false;
        if (file_exists($objCmpFileName)
                && (filemtime($objCmpFileName) > filemtime($objXmlFileName)))
        {
            // search in cache first
            if (!$xmlArr && extension_loaded('apc'))
            {
                if (($xmlArr = apc_fetch($cacheKey)) != null)
                {
                    $findInCache = true;
                }
            }
            if (!$xmlArr)
            {
                $content_array = file($objCmpFileName);
                $xmlArr = unserialize(implode("", $content_array));
            }
        } else
        {
         if(extension_loaded('ionCube Loader')){
             include_once(OPENBIZ_BIN . "util/xmltoarray.php");
         }else{
          include_once(OPENBIZ_BIN . "util/xmltoarray.src.php");
         }
            $parser = new XMLParser($objXmlFileName, 'file', 1);
            $xmlArr = $parser->getTree();
            // simple validate the xml array
            $root_keys = array_keys($xmlArr);
            $root_key = $root_keys[0];
            if (!$root_key || $root_key == "")
            {
                trigger_error("Metadata file parsing error for file $objXmlFileName. Please double check your metadata xml file again.", E_USER_ERROR);
            }
            $xmlArrStr = serialize($xmlArr);
            if (!file_exists(dirname($objCmpFileName)))
                mkdir(dirname($objCmpFileName));
            $cmp_file = fopen($objCmpFileName, 'w') or die("can't open cmp file to write");
            fwrite($cmp_file, $xmlArrStr) or die("can't write to the cmp file");
            fclose($cmp_file);
        }
        // save to cache to avoid file processing overhead
        if (!$findInCache && extension_loaded('apc'))
        {
            apc_store($cacheKey, $xmlArr);
        }
  self::$_xmlArrayList[$xmlFile] = $xmlArr;
        return $xmlArr;
    }
static getXmlFileWithPath ($xmlObj) static
Get Xml file with path
Search the object metedata file as objname+.xml in metedata directories name convension: demo.BOEvent points to metadata/demo/BOEvent.xml new in 2.2.3, demo.BOEvent can point to modules/demo/BOEvent.xml
Parameters
string $xmlObj xml object
Returns
string xml config file path
Definition at line 250 of file Resource.php.
References APP_HOME, MODULE_EX_PATH, and MODULE_PATH.
    {
        if (isset(self::$_xmlFileList[$xmlObj])) {
   return self::$_xmlFileList[$xmlObj];
  }
  $xmlFile = $xmlObj;
        if (strpos($xmlObj, ".xml") > 0)  // remove .xml suffix if any
            $xmlFile = substr($xmlObj, 0, strlen($xmlObj) - 4);
        // replace "." with "/"
        $xmlFile = str_replace(".", "/", $xmlFile);
        // check the leading char '@'
        $checkExtModule = true;
        if (strpos($xmlFile, '@') === 0) {
            $xmlFile = substr($xmlFile, 1);
            $checkExtModule = false;
        }
        $xmlFile .= ".xml";
        $xmlFile = "/" . $xmlFile;
  // find device path first
        if (defined('CLIENT_DEVICE')) {
            $path = dirname($xmlFile);
            if (strpos($path, 'view')>0 || strpos($path, 'form')>0 || strpos($path, 'widget')>0) {
                $fname = basename($xmlFile);
                $xmlFileList[] = MODULE_PATH."/$path/".CLIENT_DEVICE."/$fname";
            }
        }
        // search in modules directory first
        $xmlFileList[] = MODULE_PATH . $xmlFile;
        $xmlFileList[] = APP_HOME . $xmlFile;
        $xmlFileList[] = OPENBIZ_META . $xmlFile;
        if ($checkExtModule && defined('MODULE_EX_PATH')) array_unshift($xmlFileList, MODULE_EX_PATH . $xmlFile);
        foreach ($xmlFileList as $xmlFileItem)
        {
            //echo "file_exists($xmlFileItem)\n";
   if (file_exists($xmlFileItem)) {
    self::$_xmlFileList[$xmlObj] = $xmlFileItem;
                return $xmlFileItem;
   }
        }
  self::$_xmlFileList[$xmlObj] = null;
        return null;
    }
static getZendTemplate () static
Get Zend Template
Returns
Zend_View zend view template object
Definition at line 215 of file Resource.php.
References APP_INDEX, I18n\getCurrentLangCode(), getCurrentTheme(), JS_URL, RESOURCE_URL, and THEME_URL.
Referenced by BizSystem\getZendTemplate().
    {
        // now assign the book data to a Zend_View instance
        //Zend_Loader::loadClass('Zend_View');
        require_once 'Zend/View.php';
        $view = new Zend_View();
        if (defined('SMARTY_TPL_PATH'))
            $view->setScriptPath(SMARTY_TPL_PATH);
        $theme = Resource::getCurrentTheme();
        // load the config file which has the images and css url defined
        $view->app_url = APP_URL;
        $view->app_index = APP_INDEX;
        $view->js_url = JS_URL;
        $view->css_url = THEME_URL . "/" . $theme . "/css";
        $view->resource_url = RESOURCE_URL;
        $view->theme_js_url = THEME_URL . "/" . $theme . "/js";
        $view->theme_url = THEME_URL . "/" . $theme;
        $view->image_url = THEME_URL . "/" . $theme . "/images";
        $view->lang = strtolower(I18n::getCurrentLangCode());
        return $view;
    }
static loadMessage ($messageFile, $packageName = "") static
Load message from file
Parameters
string $messageFile
Returns
mixed
Definition at line 46 of file Resource.php.
References MESSAGE_PATH, and MODULE_PATH.
Referenced by EasyForm\inheritParentObj(), EasyView\readMetadata(), EasyForm\readMetadata(), and BizDataObj_Abstract\readMetadata().
    {
        if (isset($messageFile) && $messageFile != "")
        {
            // message file location order
            // 1. MESSAGE_PATH."/".$messageFile
            // 2. MODULE_PATH . "/$moduleName/message/" . $messageFile;
            // 3. CORE_MODULE_PATH . "/$moduleName/message/" . $messageFile;
            // APP_HOME / MESSAGE_PATH : APP_HOME / messages
            if (is_file(MESSAGE_PATH . "/" . $messageFile)) {
                return parse_ini_file(MESSAGE_PATH . "/" . $messageFile);
            } else if (is_file(MODULE_PATH . "/" . $messageFile)) {
    return parse_ini_file(MODULE_PATH . "/" . $messageFile);
   } else {
                if (isset($packageName) && $packageName != "")
                {
                    $dirs = explode('.', $packageName);
                    $moduleName = $dirs[0];
                    $msgFile = MODULE_PATH . "/$moduleName/message/" . $messageFile;
                    if (is_file($msgFile))
                    {
                        return parse_ini_file($msgFile);
                    } else
                    {
                        $errmsg = self::getMessage("SYS_ERROR_INVALID_MSGFILE", array($msgFile));
                        trigger_error($errmsg, E_USER_ERROR);
                    }
                } else
                {
                    $errmsg = self::getMessage("SYS_ERROR_INVALID_MSGFILE", array(MESSAGE_PATH . "/" . $messageFile));
                    trigger_error($errmsg, E_USER_ERROR);
                }
            }
        }
        return null;
    }
Field Documentation
const DEFAULT_THEME
Definition at line 39 of file Resource.php.
Referenced by getCurrentTheme().