Openbiz Framework API: Element Class Reference
Element Class Reference
Public Member Functions
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_AllowURLParam
$m_BackgroundColor
$m_ClientValidator
$m_CookieLifetime
$m_cssClass
$m_cssErrorClass
$m_DataRole
$m_ElementSet
$m_ElementSetCode
$m_EventHandlers
$m_Extra
$m_FieldName
$m_FormName
$m_FuzzySearch
$m_Height
$m_Hidden
$m_HTMLAttr
$m_KeepCookie
$m_Label
$m_OnEventLog
$m_Required
$m_SortFlag
$m_Style
$m_TabSet
$m_TabSetCode
$m_Translatable
$m_Validator
$m_Value
$m_Width
$m_XMLMeta
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
getBackgroundColor ()
getFormObj ()
getFunction ()
getHidden ()
getStyle ()
getText ()
getTransKey ($name)
getTransPrefix ()
readMetaData (&$xmlArr)
translate ()
translateString ($value)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 25 of file Element.php.
Constructor & Destructor Documentation
__construct (& $xmlArr, $formObj)
Initialize Element with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 66 of file Element.php.
References readMetaData(), and translate().
    {
     $this->m_XMLMeta = $xmlArr;
        $this->m_FormName = $formObj->m_Name;
        $this->m_Package = $formObj->m_Package;
        $this->readMetaData($xmlArr);
        $this->translate(); // translate for multi-language support
    }
Member Function Documentation
adjustFormName ($formName)
Adjust form (EasyForm) name change the form name after inherit from parent form
Parameters
string $formName
Returns
void
Definition at line 148 of file Element.php.
    {
        if ($this->m_FormName == $formName)
            return;
        $this->m_FormName = $formName;
        if ($this->m_EventHandlers != null)
        {
            foreach ($this->m_EventHandlers as $eventHandler)
                $eventHandler->adjustFormName($this->m_FormName);
        }
    }
canDisplayed ()
Check if the element can be displayed
Returns
boolean
Definition at line 215 of file Element.php.
References MetaObject\allowAccess(), and getHidden().
Referenced by getContextMenu(), and getSCKeyFuncMap().
    {
        if (!$this->allowAccess())
            return false;
        if ($this->getHidden() == "Y")
            return false;
        return true;
    }
checkRequired ()
Check if element must required (must have value)
Returns
boolean
Definition at line 513 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
    {
        if (!$this->m_Required || $this->m_Required == "")
            return false;
        else if ($this->m_Required == "Y")
            $required = true;
        else if($this->m_Required == "N")
            $required = false;
        else{
            $required = Expression::evaluateExpression($this->m_Required, $this->getFormObj());
            if(strtoupper($required)=='Y')
            {
             $required=true;
            }
            elseif(strtoupper($required)=='N')
            {
            }
            else
            {
             $required=false;
            }
        }
        return $required;
    }
getBackgroundColor () protected
Definition at line 324 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
Referenced by LabelList\render(), and LabelText\render().
    {
        if ($this->m_BackgroundColor == null)
            return null;
        $formObj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_BackgroundColor, $formObj);
    }
getClientValidator ()
Get client validator
Returns
string
Definition at line 557 of file Element.php.
References $m_ClientValidator.
    {
        if ($this->m_ClientValidator)
            return $this->m_ClientValidator;
        //return Expression::evaluateExpression($this->m_ClientValidator, $this->getFormObj());
        return null;
    }
getContextMenu ()
Get context menu
Returns
array
Definition at line 388 of file Element.php.
References canDisplayed(), and getFormObj().
    {
        if (!$this->canDisplayed()) return null;
        $menus = array();
        $formObj = $this->getFormObj();
        if ($this->m_EventHandlers == null)
            return null;
        $i = 0;
        foreach ($this->m_EventHandlers as $eventHandler)
        {
            if ($eventHandler->m_ContextMenu)
            {
                $menus[$i]['text'] = $eventHandler->m_ContextMenu;
                $menus[$i]['func'] = $eventHandler->getFormedFunction();
                $menus[$i]['key']  = $eventHandler->m_ShortcutKey;
            }
            $i++;
        }
        return $menus;
    }
getDefaultValue ()
Get default value
Returns
mixed
Definition at line 229 of file Element.php.
References MetaObject\$m_Name, Expression\evaluateExpression(), and getFormObj().
Referenced by ImageSelector\render(), Radio\render(), ColorPicker\render(), BarcodeScanner\render(), InputText\render(), IDCardReader\render(), Listbox\render(), InputDateRangePicker\render(), DropDownList\render(), EditCombobox\render(), ColumnInputText\render(), and ColumnListbox\render().
    {
        if ($this->m_DefaultValue == "" && $this->m_KeepCookie!='Y')
            return "";
        $formObj = $this->getFormObj();
        if($this->m_KeepCookie=='Y'){
         $cookieName = $formObj->m_Name."-".$this->m_Name;
         $cookieName = str_replace(".","_",$cookieName);
         $defValue = $_COOKIE[$cookieName];
        }
        if(!$defValue){
         $defValue = Expression::evaluateExpression($this->m_DefaultValue, $formObj);
        }
        //add automatic append like new record (2)
        if($this->m_DefaultValueRename!='N'){
         if(!is_numeric($defValue)){
          $dataobj = $formObj->getDataObj();
          if($this->m_FieldName && $dataobj){
           if(substr($this->m_FieldName,0,1)!='_'){
            $recs = $dataobj->directfetch("[".$this->m_FieldName."] = '$defValue' OR "."[".$this->m_FieldName."] LIKE '$defValue (%)'" );
            if($recs->count()>0){
             $defValue.= " ( ".$recs->count()." )";
            }
           }
          }
         }
        }
        return $defValue;
    }
getDescription ()
Definition at line 345 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
    {
        if ($this->m_Description == null)
            return null;
        $formobj = $this->getFormObj();
        $text =  Expression::evaluateExpression($this->m_Description, $formobj);
        $text = str_replace("[b]","<strong>",$text);
        $text = str_replace("[/b]","</strong>",$text);
        return $text;
    }
getEvents ()
Definition at line 430 of file Element.php.
References MetaObject\$m_Name, and getFormObj().
Referenced by getFunction(), and InputDateRangePicker\render().
{
     $name = $this->m_Name;
        // loop through the event handlers
        $func = "";
        $events = array();
        if ($this->m_EventHandlers == null)
            return $events;
        $formobj = $this->getFormObj();
        foreach ($this->m_EventHandlers as $eventHandler)
        {
            $ehName = $eventHandler->m_Name;
            $event = $eventHandler->m_Event;
            $type = $eventHandler->m_FunctionType;
            if (!$event) continue;
            if($events[$event]!=""){
             $events[$event]=array_merge(array($events[$event]),array($eventHandler->getFormedFunction()));
            }else{
             $events[$event]=$eventHandler->getFormedFunction();
            }
        }
        return $events;
    }
getFormObj () protected
Get form (EasyForm) object
Returns
EasyForm
Definition at line 135 of file Element.php.
References BizSystem\objectFactory().
Referenced by InputElement\addSCKeyScript(), checkRequired(), FormElement\FormRecordCount(), ColumnImage\getAlt(), getBackgroundColor(), ColumnSorting\getBtnFunction(), getContextMenu(), Checkbox\getDefaultChecked(), getDefaultValue(), getDescription(), TreeListbox\getDOFromList(), InputElement\getEnabled(), getEvents(), ColorPicker\getFunctionByEvent(), IFrameBox\getHeight(), getHidden(), IFrameBox\getLink(), LabelList\getLink(), RawData\getLink(), ColumnList\getLink(), HTMLPreview\getLink(), LabelText\getLink(), PageSelector\getList(), DropDownList\getOnChangeFunction(), getParameter(), getRedirectPage(), InputElement\getRequired(), OptionElement\getSelectedList(), DropDownList\getSelectedList(), OptionElement\getSelectFrom(), DropDownList\getSelectFrom(), OptionElement\getSelectFromSQL(), DropDownList\getSelectFromSQL(), OptionElement\getSQLFromList(), DropDownList\getSQLFromList(), EditCombobox\getStyle(), Radio\getStyle(), ColumnBar\getStyle(), getStyle(), RawData\getText(), HTMLPreview\getText(), LabelText\getText(), getText(), ColumnImage\getTitle(), FileInput\getValue(), InputPassword\getValue(), IFrameBox\getWidth(), ColumnShare\hasOwnerField(), LabelBar\render(), ColumnSorting\render(), ImageSelector\render(), ColumnBar\render(), LabelTextPaging\render(), Radio\render(), LabelBool\render(), RowCheckbox\render(), ColumnBool\render(), DropDownList\render(), FormElement\render(), ColumnInputText\render(), ColumnListbox\render(), ColumnShare\render(), DropDownList\renderList(), ColumnListbox\setValue(), ColumnInputText\setValue(), ColumnShare\setValue(), setValue(), and validate().
    {
        return BizSystem::objectFactory()->getObject($this->m_FormName);
    }
getFunction () protected
Get function of element in JavaScript format
Returns
string
Definition at line 414 of file Element.php.
References getEvents().
Referenced by LabelBar\render(), ImageSelector\render(), ColumnBar\render(), LabelTextPaging\render(), LabelImage\render(), HTMLButton\render(), FileInput\render(), Radio\render(), ResetButton\render(), CheckListbox\render(), File\render(), ColorPicker\render(), SubmitButton\render(), LabelTextarea\render(), HTMLBlock\render(), IDCardReader\render(), BarcodeScanner\render(), InputText\render(), Textarea\render(), LabelBool\render(), Listbox\render(), Button\render(), ColumnBool\render(), DropDownList\render(), LabelList\render(), Checkbox\render(), InputPassword\render(), EditCombobox\render(), ColumnInputText\render(), ColumnImage\render(), ColumnListbox\render(), ColumnList\render(), HTMLPreview\render(), LabelText\render(), FileUploader\render(), ColumnShare\render(), and ImageUploader\render().
    {
        $events = $this->getEvents();
  foreach ($events as $event=>$function){
   if(is_array($function)){
    foreach($function as $f){
     $function_str.=$f.";";
    }
    $func .= " $event=\"$function_str\"";
   }else{
    $func .= " $event=\"$function\"";
   }
  }
        return $func;
    }
getFunctionByEventHandlerName ($eventHandlerName)
Definition at line 456 of file Element.php.
References Expression\evaluateExpression().
    {
     if ($this->m_EventHandlers == null)
            return null;
     $eventHandler = $this->m_EventHandlers->get($eventHandlerName);
     if ($eventHandler)
      $func = Expression::evaluateExpression($eventHandler->m_Function, $formobj);
     return $func;
    }
getFunctionType ($eventHandlerName)
Get function type
Parameters
string $eventHandlerName event handler name
Returns
string function type in string format
Definition at line 501 of file Element.php.
    {
        $eventHandler = $this->m_EventHandlers->get($eventHandlerName);
        if (!$eventHandler) return null;
        return $eventHandler->m_FunctionType;
    }
getHidden () protected
Get hidden status
Returns
mixed
Definition at line 280 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
Referenced by canDisplayed().
    {
  if (!$this->m_Hidden || $this->m_Hidden=='N') return "N";
        $formObj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Hidden, $formObj);
    }
getParameter ($eventHandlerName)
Get parameter
Parameters
string $eventHandlerName
Returns
mixed
Definition at line 487 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
{
     $formObj = $this->getFormObj();
        $eventHandler = $this->m_EventHandlers->get($eventHandlerName);
        if (!$eventHandler) return null;
        //echo $evthandler->m_RedirectPage."<br>";
        return Expression::evaluateExpression($eventHandler->m_Parameter, $formObj);
    }
getProperty ($propertyName)
Get property of element
Parameters
string $propertyName
Returns
mixed
Definition at line 202 of file Element.php.
References getValue().
    {
        if ($propertyName == "Value") return $this->getValue();
        $ret = parent::getProperty($propertyName);
        if ($ret) return $ret;
        return $this->$propertyName;
    }
getRedirectPage ($eventHandlerName)
Get redirect page
Parameters
string $eventHandlerName event handler name
Returns
string
Definition at line 472 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
    {
        $formObj = $this->getFormObj();
        $eventHandler = $this->m_EventHandlers->get($eventHandlerName);
        if (!$eventHandler) return null;
        //echo $evthandler->m_RedirectPage."<br>";
        return Expression::evaluateExpression($eventHandler->m_RedirectPage, $formObj);
    }
getSCKeyFuncMap ()
Get shortcut key function map
Returns
array
Definition at line 361 of file Element.php.
References canDisplayed().
Referenced by InputElement\addSCKeyScript().
    {
        if (!$this->canDisplayed()) return null;
        $map = array();
        //$formObj = $this->getFormObj(); // not used
        if ($this->m_EventHandlers == null)
            return null;
        foreach ($this->m_EventHandlers as $eventHandler)
        {
            if ($eventHandler->m_ShortcutKey)
            {
                $map[$eventHandler->m_ShortcutKey] = $eventHandler->getFormedFunction();
            }
        }
        return $map;
    }
getStyle () protected
Get style of element
Returns
string
Definition at line 292 of file Element.php.
References $m_Style, Expression\evaluateExpression(), and getFormObj().
Referenced by ColumnSorting\render(), Spacer\render(), ImageSelector\render(), LabelTextPaging\render(), HTMLButton\render(), ResetButton\render(), RichText\render(), FileInput\render(), File\render(), CheckListbox\render(), SubmitButton\render(), ColorPicker\render(), LabelTextarea\render(), HTMLBlock\render(), Password\render(), BarcodeScanner\render(), IDCardReader\render(), InputText\render(), AutoSuggest\render(), Textarea\render(), LabelBool\render(), Listbox\render(), CKEditor\render(), RowCheckbox\render(), ColumnBool\render(), Button\render(), DropDownList\render(), LabelList\render(), Checkbox\render(), InputPassword\render(), ColumnInputText\render(), ColumnImage\render(), ColumnListbox\render(), ColumnList\render(), HTMLPreview\render(), LabelText\render(), FileUploader\render(), ColumnShare\render(), and ImageUploader\render().
    {
  $formobj = $this->getFormObj();
        $htmlClass = Expression::evaluateExpression($this->m_cssClass, $formobj);
        $htmlClass = "CLASS='$htmlClass'";
        if(!$htmlClass){
         $htmlClass = null;
        }
        $style ='';
        if ($this->m_Width && $this->m_Width>=0)
            $style .= "width:".$this->m_Width."px;";
        if ($this->m_Height && $this->m_Height>=0)
            $style .= "height:".$this->m_Height."px;";
        if ($this->m_Style)
            $style .= $this->m_Style;
        if (!isset($style) && !$htmlClass)
            return null;
        if (isset($style))
        {
            $style = Expression::evaluateExpression($style, $formobj);
            $style = "STYLE='$style'";
        }
        if($formobj->m_Errors[$this->m_Name])
        {
           $htmlClass = "CLASS='".$this->m_cssErrorClass."'";
        }
        if ($htmlClass)
            $style = $htmlClass." ".$style;
        return $style;
    }
getText () protected
Get text of element
Returns
string
Definition at line 337 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
Referenced by ColorPicker\render(), BarcodeScanner\render(), IDCardReader\render(), InputText\render(), IFrameBox\render(), Hidden\render(), InputDateRangePicker\render(), Button\render(), DropDownList\render(), LabelList\render(), Checkbox\render(), ColumnInputText\render(), and DropDownList\renderList().
    {
        if ($this->m_Text == null)
            return null;
        $formobj = $this->getFormObj();
        return Expression::evaluateExpression($this->m_Text, $formobj);
    }
getTransKey ($name) protected
Definition at line 602 of file Element.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_FormName,intval(strrpos($this->m_FormName,'.')+1));
     return strtoupper($shortFormName.'_'.$this->m_Name.'_'.$name);
    }
getTransPrefix () protected
Definition at line 592 of file Element.php.
Referenced by translate().
    {
     $nameArr = explode(".",$this->m_FormName);
     for($i=1;$i<count($nameArr)-1;$i++)
     {
      $prefix .= strtoupper($nameArr[$i])."_";
     }
     return $prefix;
    }
getValue ()
Get value of element
Returns
mixed
Definition at line 191 of file Element.php.
References $m_Value.
Referenced by getProperty(), LabelImage\render(), and ColumnBool\render().
    {
        return $this->m_Value;
    }
matchRemoteMethod ($method)
Definition at line 566 of file Element.php.
    {
        return false;
    }
readMetaData (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 83 of file Element.php.
References $m_DataRole.
Referenced by __construct().
    {
        $this->m_Name = isset($xmlArr["ATTRIBUTES"]["NAME"]) ? $xmlArr["ATTRIBUTES"]["NAME"] : null;
  $this->m_BackgroundColor = isset($xmlArr["ATTRIBUTES"]["BACKGROUNDCOLOR"]) ? $xmlArr["ATTRIBUTES"]["BACKGROUNDCOLOR"] : null;
        $this->m_Class = isset($xmlArr["ATTRIBUTES"]["CLASS"]) ? $xmlArr["ATTRIBUTES"]["CLASS"] : null;
        $this->m_Description = isset($xmlArr["ATTRIBUTES"]["DESCRIPTION"]) ? $xmlArr["ATTRIBUTES"]["DESCRIPTION"] : null;
        $this->m_Access = isset($xmlArr["ATTRIBUTES"]["ACCESS"]) ? $xmlArr["ATTRIBUTES"]["ACCESS"] : null;
        $this->m_DefaultValue = isset($xmlArr["ATTRIBUTES"]["DEFAULTVALUE"]) ? $xmlArr["ATTRIBUTES"]["DEFAULTVALUE"] : null;
        $this->m_cssClass = isset($xmlArr["ATTRIBUTES"]["CSSCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSCLASS"] : null;
        $this->m_cssErrorClass = isset($xmlArr["ATTRIBUTES"]["CSSERRORCLASS"]) ? $xmlArr["ATTRIBUTES"]["CSSERRORCLASS"] : "input_error";
        $this->m_Style = isset($xmlArr["ATTRIBUTES"]["STYLE"]) ? $xmlArr["ATTRIBUTES"]["STYLE"] : null;
        $this->m_Width = isset($xmlArr["ATTRIBUTES"]["WIDTH"]) ? $xmlArr["ATTRIBUTES"]["WIDTH"] : null;
        $this->m_Height = isset($xmlArr["ATTRIBUTES"]["HEIGHT"]) ? $xmlArr["ATTRIBUTES"]["HEIGHT"] : null;
        $this->m_Hidden = isset($xmlArr["ATTRIBUTES"]["HIDDEN"]) ? $xmlArr["ATTRIBUTES"]["HIDDEN"] : null;
        $this->m_HTMLAttr = isset($xmlArr["ATTRIBUTES"]["HTMLATTR"]) ? $xmlArr["ATTRIBUTES"]["HTMLATTR"] : null;
        $this->m_ElementSet = isset($xmlArr["ATTRIBUTES"]["ELEMENTSET"]) ? $xmlArr["ATTRIBUTES"]["ELEMENTSET"] : null;
        $this->m_ElementSetCode = isset($xmlArr["ATTRIBUTES"]["ELEMENTSET"]) ? $xmlArr["ATTRIBUTES"]["ELEMENTSET"] : null;
        $this->m_TabSet = isset($xmlArr["ATTRIBUTES"]["TABSET"]) ? $xmlArr["ATTRIBUTES"]["TABSET"] : null;
        $this->m_TabSetCode = isset($xmlArr["ATTRIBUTES"]["TABSET"]) ? $xmlArr["ATTRIBUTES"]["TABSET"] : null;
        $this->m_Text = isset($xmlArr["ATTRIBUTES"]["TEXT"]) ? $xmlArr["ATTRIBUTES"]["TEXT"] : null;
        $this->m_Translatable = isset($xmlArr["ATTRIBUTES"]["TRANSLATABLE"]) ? $xmlArr["ATTRIBUTES"]["TRANSLATABLE"] : null;
        $this->m_FuzzySearch = isset($xmlArr["ATTRIBUTES"]["FUZZYSEARCH"]) ? $xmlArr["ATTRIBUTES"]["FUZZYSEARCH"] : null;
        $this->m_OnEventLog = isset($xmlArr["ATTRIBUTES"]["ONEVENTLOG"]) ? $xmlArr["ATTRIBUTES"]["ONEVENTLOG"] : null;
        $this->m_Required = isset($xmlArr["ATTRIBUTES"]["REQUIRED"]) ? $xmlArr["ATTRIBUTES"]["REQUIRED"] : null;
        $this->m_Validator = isset($xmlArr["ATTRIBUTES"]["VALIDATOR"]) ? $xmlArr["ATTRIBUTES"]["VALIDATOR"] : null;
        $this->m_ClientValidator = isset($xmlArr["ATTRIBUTES"]["CLIENTVALIDATOR"]) ? $xmlArr["ATTRIBUTES"]["CLIENTVALIDATOR"] : null;
        $this->m_AllowURLParam = isset($xmlArr["ATTRIBUTES"]["ALLOWURLPARAM"]) ? $xmlArr["ATTRIBUTES"]["ALLOWURLPARAM"] : 'Y';
        $this->m_KeepCookie = isset($xmlArr["ATTRIBUTES"]["KEEPCOOKIE"]) ? $xmlArr["ATTRIBUTES"]["KEEPCOOKIE"] : 'N';
        $this->m_CookieLifetime = isset($xmlArr["ATTRIBUTES"]["COOKIELIFETIME"]) ? (int)$xmlArr["ATTRIBUTES"]["COOKIELIFETIME"] : '3600';
  $this->m_DataRole = isset($xmlArr["ATTRIBUTES"]["DATAROLE"]) ? $xmlArr["ATTRIBUTES"]["DATAROLE"] : null;
  $this->m_Extra = isset($xmlArr["ATTRIBUTES"]["EXTRA"]) ? $xmlArr["ATTRIBUTES"]["EXTRA"] : null;
        // read EventHandler element
        if (isset($xmlArr["EVENTHANDLER"]))  // 2.1 eventhanlders
            $this->m_EventHandlers = new MetaIterator($xmlArr["EVENTHANDLER"],"EventHandler");
        if ($this->m_EventHandlers != null)
        {
            foreach ($this->m_EventHandlers as $eventHandler)
                $eventHandler->setFormName($this->m_FormName, $this->m_Name);
        }
        // additional data in HTMLAttr
  $this->m_HTMLAttr .= ($this->m_DataRole) ? " data-role='".$this->m_DataRole."'" : "";
        $this->m_HTMLAttr .= " title='".$this->m_Description."'"." clientValidator='".$this->m_ClientValidator."'";
    }
render ()
Render the element by html
Returns
string HTML text
Implements iUIControl.
Definition at line 264 of file Element.php.
    {
      return "";
    }
renderLabel ()
Definition at line 269 of file Element.php.
References translateString().
    {
        $sHTML = $this->translateString($this->m_Label);
        return $sHTML;
    }
reset ()
Definition at line 160 of file Element.php.
    {
     $this->m_Value = null;
     if ($this->m_EventHandlers != null)
        {
            foreach ($this->m_EventHandlers as $eventHandler)
                $eventHandler->m_FormedFunction = null;
        }
    }
setValue ($value)
Set value of element
Parameters
mixed $value
Definition at line 175 of file Element.php.
References getFormObj().
Referenced by Listbox\render(), and DropDownList\render().
    {
        $this->m_Value = $value;
        if($this->m_KeepCookie=='Y'){
         if($value!=""){
          $formName = $this->getFormObj()->m_Name;
          setcookie($formName."-".$this->m_Name,$value,time()+(int)$this->m_CookieLifetime,"/");
         }
        }
    }
translate () protected
Definition at line 571 of file Element.php.
References MetaObject\getModuleName(), getTransKey(), getTransPrefix(), and I18n\t().
Referenced by ImageUploader\__construct(), and __construct().
    {
     $module = $this->getModuleName($this->m_FormName);
     if (!empty($this->m_Text))
      $this->m_Text = I18n::t($this->m_Text, $this->getTransKey('Text'), $module, $this->getTransPrefix());
     if (!empty($this->m_Label))
      $this->m_Label = I18n::t($this->m_Label, $this->getTransKey('Label'), $module, $this->getTransPrefix());
     if (!empty($this->m_Description))
      $this->m_Description = I18n::t($this->m_Description, $this->getTransKey('Description'), $module, $this->getTransPrefix());
        if (!empty($this->m_DefaultValue) && !preg_match("/\{/si",$this->m_DefaultValue))
      $this->m_DefaultValue = I18n::t($this->m_DefaultValue, $this->getTransKey('DefaultValue'), $module, $this->getTransPrefix());
  if (!empty($this->m_ElementSet))
      $this->m_ElementSet = I18n::t($this->m_ElementSet, $this->getTransKey('ElementSet'), $module, $this->getTransPrefix());
     if (!empty($this->m_BlankOption))
      $this->m_BlankOption = I18n::t($this->m_BlankOption, $this->getTransKey('BlankOption'), $module, $this->getTransPrefix());
     if (!empty($this->m_TabSet))
      $this->m_TabSet = I18n::t($this->m_TabSet, $this->getTransKey('TabSet'), $module, $this->getTransPrefix());
     if (!empty($this->m_Hint))
      $this->m_Hint = I18n::t($this->m_Hint, $this->getTransKey('Hint'), $module, $this->getTransPrefix());
    }
translateString ($value) protected
Definition at line 608 of file Element.php.
References MetaObject\getModuleName(), and I18n\t().
Referenced by DropDownList\readMetaData(), ColumnSorting\render(), LabelTextarea\render(), RawData\render(), HTMLPreview\render(), LabelText\render(), InputElement\renderLabel(), and renderLabel().
    {
        $module = $this->getModuleName($this->m_FormName);
        if(defined($value)) $value = constant($value);
        return I18n::t($value, 'STRING_'.$value, $module);
    }
validate ()
Validate element
Returns
boolean
Definition at line 544 of file Element.php.
References Expression\evaluateExpression(), and getFormObj().
    {
        $ret = true;
        if ($this->m_Validator)
            $ret = Expression::evaluateExpression($this->m_Validator, $this->getFormObj());
        return $ret;
    }
Field Documentation
$m_AllowURLParam
Definition at line 39 of file Element.php.
$m_BackgroundColor
Definition at line 56 of file Element.php.
$m_ClientValidator
Definition at line 53 of file Element.php.
Referenced by getClientValidator().
$m_CookieLifetime
Definition at line 55 of file Element.php.
$m_cssClass
Definition at line 28 of file Element.php.
$m_cssErrorClass
Definition at line 29 of file Element.php.
$m_DataRole
Definition at line 58 of file Element.php.
Referenced by readMetaData().
$m_ElementSet
Definition at line 46 of file Element.php.
Referenced by FormElement\FormRecordCount().
$m_ElementSetCode
Definition at line 47 of file Element.php.
$m_EventHandlers
Definition at line 35 of file Element.php.
$m_Extra
Definition at line 45 of file Element.php.
$m_FieldName
Definition at line 50 of file Element.php.
$m_FormName
Definition at line 44 of file Element.php.
Referenced by RowCheckbox\renderLabel().
$m_FuzzySearch
Definition at line 37 of file Element.php.
$m_Height
Definition at line 31 of file Element.php.
Referenced by LabelBar\render(), and ColumnBar\render().
$m_Hidden
Definition at line 32 of file Element.php.
$m_HTMLAttr
Definition at line 33 of file Element.php.
$m_KeepCookie
Definition at line 54 of file Element.php.
$m_Label
Definition at line 34 of file Element.php.
Referenced by RawData\renderLabel().
$m_OnEventLog
Definition at line 38 of file Element.php.
$m_Required
Definition at line 51 of file Element.php.
$m_SortFlag
Definition at line 42 of file Element.php.
$m_Style
Definition at line 27 of file Element.php.
Referenced by EditCombobox\getStyle(), Radio\getStyle(), ColumnBar\getStyle(), getStyle(), ColumnList\readMetaData(), and ColumnText\readMetaData().
$m_TabSet
Definition at line 48 of file Element.php.
$m_TabSetCode
Definition at line 49 of file Element.php.
$m_Translatable
Definition at line 36 of file Element.php.
$m_Validator
Definition at line 52 of file Element.php.
$m_Value
Definition at line 43 of file Element.php.
Referenced by ColumnListbox\getItemValue(), ColumnInputText\getItemValue(), Checkbox\getValue(), InputPassword\getValue(), ColumnShare\getValue(), getValue(), LabelBar\render(), ColumnSorting\render(), ColumnBar\render(), LabelTextarea\render(), ColorPicker\render(), BarcodeScanner\render(), InputText\render(), IDCardReader\render(), ColumnValue\render(), LabelBool\render(), Hidden\render(), InputDateRangePicker\render(), RowCheckbox\render(), DropDownList\render(), LabelList\render(), InputPassword\render(), RawData\render(), ColumnList\render(), InputElement\render(), HTMLPreview\render(), and LabelText\render().
$m_Width
Definition at line 30 of file Element.php.
Referenced by ColumnBar\render().
$m_XMLMeta
Definition at line 40 of file Element.php.
Referenced by FormElement\render().