Openbiz Framework API: BizDataSql Class Reference
BizDataSql Class Reference
Public Member Functions
__construct ()
addAssociation ($assoc)
addJoinTable ($tableJoin, $sqlHelper=null)
addMainTable ($mainTable)
addOrderBy ($orderBy)
addOtherSQL ($otherSQL)
addSqlExpression ($sqlExpr, $alias=null)
addSqlWhere ($sqlWhere)
addTableColumn ($join, $column, $alias=null)
getJoinAlias ($join)
getSqlStatement ()
getTableColumn ($join, $col)
getTableJoinStm ()
isfresh ()
resetSQL ()
setTableJoinStm ($tableJoinStm)
Data Fields
$hasJoinCondition
Protected Attributes
$_aliasIndex
$_joinAliasList
$_mainTable
$_orderBy
$_otherSQL
$_sqlWhere
$_tableAliasList
$_tableColumns
$_tableJoins
Detailed Description
Definition at line 24 of file BizDataSql.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 37 of file BizDataSql.php.
    {
    }
Member Function Documentation
addAssociation ($assoc)
Add association in the SQL
Parameters
array $assoc additional SQL statment
Returns
void
Definition at line 236 of file BizDataSql.php.
References addSqlWhere(), and getTableColumn().
    {
        $where = "";
        if ($assoc["Relationship"] == "1-M" || $assoc["Relationship"] == "M-1" || $assoc["Relationship"] == "1-1")
        {
            // assc table should same as maintable
            if ($assoc["Table"] != $this->_mainTable) return;
            // add table to join table
            $mytable_col = $this->getTableColumn(null, $assoc["Column"]);
            // construct table.column = 'field value'
            $where = $mytable_col." = '".$assoc["FieldRefVal"]."'";
            $mytable_col2 = $this->getTableColumn(null, $assoc["Column2"]);
            if($assoc["Column2"]){
             $where .= " AND ".$mytable_col2." = '".$assoc["FieldRefVal2"]."'";
            }
            $mytable_cond_col = $this->getTableColumn(null, $assoc["CondColumn"]);
            if($assoc["CondColumn"]){
             $where .= " AND $mytable_cond_col ='".$assoc["CondValue"]."' ";
            }
         if($assoc["Condition"]){
             $where .= " AND ".$assoc["Condition"]." ";
            }
        }
        elseif ($assoc["Relationship"] == "M-M" || $assoc["Relationship"] == "Self-Self")
        {
            // ... INNER JOIN xtable TX ON TX.column2 = T0.column
            // WHERE ... Tx.column1 = 'PrtTableColumnValue'
            $mytable_col = $this->getTableColumn(null, $assoc["Column"]);   // this table's alias.column
            $xtable = $assoc["XTable"];    // xtable's name
            $column1 = $assoc["XColumn1"]; // xtable column1
            $column2 = $assoc["XColumn2"]; // xtable column2
            $xalias = "TX";
            if (isset($this->_tableAliasList[$xtable]))
                $xalias = $this->_tableAliasList[$xtable];
            // add a table join for the xtable if such join of the table is not there before (note: may report error if has same join).
            //if (strpos($this->m_TableJoins, "JOIN $xtable") === false)
            if (!isset($this->_tableAliasList[$xtable]))
            {
                $this->_tableJoins .= " INNER JOIN `$xtable` $xalias ON $xalias.$column2 = $mytable_col ";
                $this->_tableAliasList[$xtable] = $xalias;
            }
            // add a new where condition
            if($assoc["Relationship"] == "Self-Self")
            {
             $columnId = $this->getTableColumn("", $assoc["ParentRecordIdColumn"]);
             $where = "($xalias.$column1 = '".$assoc["FieldRefVal"]."' OR $xalias.$column2 = '".$assoc["FieldRefVal"]."' ) AND $columnId != '".$assoc["FieldRefVal"]."'";
             $this->_tableJoins .=  " OR $xalias.$column1 = $mytable_col ";
            }else{
             $where = "$xalias.$column1 = '".$assoc["FieldRefVal"]."'";
            }
        }
        if (strlen($where) > 1)
            $this->addSqlWhere($where);
    }
addJoinTable ($tableJoin, $sqlHelper = null)
Add a join table in the sql statement Ti alias
  SELECT T1.col, T2.col
  FROM table1 T1
      INNER JOIN table2 T2 ON T1.col1=T2.col1
      LEFT JOIN  table3 T3 ON T1.col1=T3.col1
  WHERE
Parameters
TableJoin $tableJoin table join object
Returns
void
Definition at line 71 of file BizDataSql.php.
References getJoinAlias().
    {
        $table = $tableJoin->m_Table;
        $joinType = $tableJoin->m_JoinType;
        $column = $tableJoin->m_Column;
        $joinRef = $tableJoin->m_JoinRef;
        $columnRef = $tableJoin->m_ColumnRef;
  $joinCondition = $tableJoin->m_JoinCondition;
        $alias = "T".(count($this->_joinAliasList)+1);   // start with T1, T2
        $this->_joinAliasList[$tableJoin->m_Name] = $alias;
        $this->_tableAliasList[$table] = $alias;
        $aliasRef = $this->getJoinAlias($joinRef);
        $this->_tableJoins .= " $joinType `$table` $alias ON $alias.$column = $aliasRef.$columnRef ";
  if (!empty($joinCondition)) {
   $this->_tableJoins .= " AND $joinCondition";
   $this->hasJoinCondition = true;
  }
    }
addMainTable ($mainTable)
Add main table in the sql statement T0 alias
Parameters
string $mainTable main table name
Returns
void
Definition at line 52 of file BizDataSql.php.
    {
        $this->_mainTable = "$mainTable";
        $this->_tableJoins = " `$mainTable` T0 ";
    }
addOrderBy ($orderBy)
Add order by clause
Parameters
string $orderBy SQL ORDER BY clause
Returns
void
Definition at line 196 of file BizDataSql.php.
    {
        if ($orderBy == null)
            return;
        if ($this->_orderBy == null)
        {
            $this->_orderBy = $orderBy;
        }
        elseif (strpos($this->_orderBy, $orderBy) === false)
        {
            $this->_orderBy .= " AND " . $orderBy;
        }
    }
addOtherSQL ($otherSQL)
Add other SQL clause
Parameters
string $otherSQL additional SQL statment
Returns
void
Definition at line 216 of file BizDataSql.php.
    {
        if ($otherSQL == null)
            return;
        if ($this->_otherSQL == null)
        {
            $this->_otherSQL = $otherSQL;
        }
        elseif (strpos($this->_otherSQL, $otherSQL) === false)
        {
            $this->_otherSQL .= " AND " . $otherSQL;
        }
    }
addSqlExpression ($sqlExpr, $alias = null)
Add SQL expression in the sql statement sqlExpr has format of "...join1.column1, ... join2.column2...". Replace join with alias
Parameters
string $sqlExpr sql expression
string $alias sql alias
Returns
void
Definition at line 120 of file BizDataSql.php.
    {
        if ($alias)
            $sqlExpr .= ' AS '.$alias;
        if (!$this->_tableColumns)
            $this->_tableColumns = $sqlExpr;
        else
            $this->_tableColumns .= ", ".$sqlExpr;
    }
addSqlWhere ($sqlWhere)
Add the where clause (search rule) into the SQL statement
Parameters
string $sqlWhere SQL WHERE clause
Returns
void
Definition at line 176 of file BizDataSql.php.
Referenced by addAssociation().
    {
        if ($sqlWhere == null)
            return;
        if ($this->_sqlWhere == null)
        {
            $this->_sqlWhere = $sqlWhere;
        }
        elseif (strpos($this->_sqlWhere, $sqlWhere) === false)
        {
            $this->_sqlWhere .= " AND " . $sqlWhere;
        }
    }
addTableColumn ($join, $column, $alias = null)
Add a join table and cloumn in the sql statement
Parameters
string $join table join name
string $column column name
Returns
void
Definition at line 102 of file BizDataSql.php.
References getTableColumn().
    {
        $tcol = $this->getTableColumn($join, $column);
        if ($alias) $tcol .= " AS ".$alias;
        if (!$this->_tableColumns)
            $this->_tableColumns = $tcol;
        else
            $this->_tableColumns .= ", ".$tcol;
    }
getJoinAlias ($join)
Get join table alias
Parameters
string $join name of join
Returns
string join table alias
Definition at line 136 of file BizDataSql.php.
Referenced by addJoinTable(), and getTableColumn().
    {
        if (!$join) // main table, no join
            return "T0";
        else
            return $this->_joinAliasList[$join];
    }
getSqlStatement ()
Get the SQL statement
Returns
string SQL statement
Definition at line 300 of file BizDataSql.php.
References $_orderBy, $_otherSQL, $_sqlWhere, $_tableColumns, and $_tableJoins.
    {
        $ret = "SELECT " . $this->_tableColumns;
        $ret .= " FROM " . $this->_tableJoins;
        if ($this->_sqlWhere != null)
        {
            $ret .= " WHERE " . $this->_sqlWhere;
        }
        /*
        if ($this->m_OrderBy != null)
        {
            $ret .= " ORDER BY " . $this->m_OrderBy;
 }
        */
        if ($this->_otherSQL != null)
        {
            $ret .= " " . $this->_otherSQL;
        }
        if ($this->_orderBy != null)
        {
            $ret .= " ORDER BY " . $this->_orderBy;
        }
        return $ret;
    }
getTableColumn ($join, $col)
Get table column, combine a table with a column.
Parameters
string $join join name
string $col column
Returns
string table column combination string
Definition at line 151 of file BizDataSql.php.
References getJoinAlias().
Referenced by addAssociation(), and addTableColumn().
    {
        // check the function format on $col
        $alias = $this->getJoinAlias($join);
        return "$alias.`$col`";
    }
getTableJoinStm ()
Definition at line 91 of file BizDataSql.php.
References $_tableJoins.
{ return $this->_tableJoins; }
isfresh ()
Definition at line 41 of file BizDataSql.php.
 {
  return $this->_mainTable ? false : true;
 }
resetSQL ()
Reset SQL to be empty
Returns
avoid
Definition at line 163 of file BizDataSql.php.
    {
        $this->_sqlWhere = null;
        $this->_orderBy = null;
        $this->_otherSQL = null;
    }
setTableJoinStm ($tableJoinStm)
Definition at line 93 of file BizDataSql.php.
{ return $this->_tableJoins = $tableJoinStm; }
Field Documentation
$_aliasIndex protected
Definition at line 33 of file BizDataSql.php.
$_joinAliasList protected
Definition at line 28 of file BizDataSql.php.
$_mainTable protected
Definition at line 34 of file BizDataSql.php.
$_orderBy protected
Definition at line 31 of file BizDataSql.php.
Referenced by getSqlStatement().
$_otherSQL protected
Definition at line 32 of file BizDataSql.php.
Referenced by getSqlStatement().
$_sqlWhere protected
Definition at line 30 of file BizDataSql.php.
Referenced by getSqlStatement().
$_tableAliasList protected
Definition at line 29 of file BizDataSql.php.
$_tableColumns protected
Definition at line 26 of file BizDataSql.php.
Referenced by getSqlStatement().
$_tableJoins protected
Definition at line 27 of file BizDataSql.php.
Referenced by getSqlStatement(), and getTableJoinStm().
$hasJoinCondition
Definition at line 35 of file BizDataSql.php.