Openbiz Framework API: logService Class Reference
logService Class Reference
Public Member Functions
__construct (&$xmlArr)
closeFile ($path)
log ($priority, $package, $message)
logError ($level=7, $package, $message, $fileName=NULL, $backTrace= '')
prepFile ($path)
setExtension ()
setFormatter ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
readMetadata (&$xmlArr)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Additional Inherited Members
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Detailed Description
Definition at line 28 of file logService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize logService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 84 of file logService.php.
References readMetadata(), setExtension(), and setFormatter().
    {
        $this->readMetadata($xmlArr);
        //Check that logging is enabled
        if (is_int($this->_level) == FALSE)
            return;
        $this->setFormatter();
        $this->setExtension();
    }
Member Function Documentation
closeFile ($path)
Close a file with the correct string depending on the configured format
Returns
void
Definition at line 335 of file logService.php.
Referenced by log(), and logError().
    {
        //Close up the file if needed
        switch ($this->_format)
        {
            case 'HTML':
                $html = "</table></body></html>";
                $file = fopen($path, 'a');
                fwrite($file, $html);
                fclose($file);
                break;
            case 'XML':
                $xml = "</log>";
                $file = fopen($path, 'a');
                fwrite($file, $xml);
                fclose($file);
                break;
            default:
                break;
        }
    }
log ($priority, $package, $message)
The primary log function that will take an incoming message and specified paramter and log in the appropriate location and format
Parameters
int $level - Follow common BSD error levels
string $package - A way to group log messages
string $message - The actual message to log
Returns
boolean -TRUE on success otherwise FALSE
Definition at line 119 of file logService.php.
References closeFile(), DEBUG, and prepFile().
    {
        if (DEBUG == 0 && $priority == LOG_DEBUG)
         return true;
     //Adapt PHP LOG priority
        switch ($priority)
        {
            case LOG_EMERG : //  system is unusable
            case LOG_ALERT : // action must be taken immediately
            case LOG_CRIT : // critical conditions
                $level = 2;
                break;
            case LOG_ERR : // error conditions
                $level = 3;
                break;
            case LOG_WARNING : // warning conditions
                $level = 4;
                break;
            case LOG_NOTICE : // normal, but significant, condition
            case LOG_INFO : // informational message
            case LOG_DEBUG : // debug-level message
                $level = 7;
                break;
        }
        //echo "log levels: ".LOG_EMERG.", ".LOG_ALERT.", ".LOG_CRIT.", ".LOG_ERR.", ".LOG_WARNING.", ".LOG_NOTICE.", ".LOG_INFO.", ".LOG_DEBUG."<br>";
        if ($this->_level == FALSE)
            return true;
        //Get the file path
        $this->_level = $level;
        $path = $this->_getPath($file_name);
        if(!is_file($path))
        {
         @touch($path);
         @chmod($path,0777);
        }
        if (!is_writable($path))
            return false;
        $this->prepFile($path);
        //Create the log writer object
        $writer = new Zend_Log_Writer_Stream($path);
        $writer->setFormatter($this->_formatter);
        //Instantiate logging object
        $logger = new Zend_Log($writer);
        //Filter log entries to those allowed by configuration
        $filter = new Zend_Log_Filter_Priority($this->_level);
        $logger->addFilter($filter);
        $logger->setEventItem('back_trace', 'n/a');
        $logger->setEventItem('package', $package);
        $logger->setEventItem('date', date("m/d/Y"));
        $logger->setEventItem('time', date("H:i:s"));
        //Write Log Entry
        $logger->log($message, $level);
        $this->closeFile($path);
        return TRUE;
    }
logError ($level = 7, $package, $message, $fileName = NULL, $backTrace = '')
The primary log function that will take an incoming message and specified paramter and log in the appropriate location and format
Parameters
int $level - Follow common BSD error levels
string $package - A way to group log messages
string $message - The actual message to log
string $fileName - An optional specific file name where the message should be logged
string $string - An optional list of the Application stack at the time of error
Returns
boolean -TRUE on success otherwise FALSE
Definition at line 189 of file logService.php.
References closeFile(), and prepFile().
    {
        //Adapt PHP Errors
        switch ($level)
        {
            case 8:          // E_NOTICE
            case 1024:       // E_USER_NOTICE
                $level = 4;
                break;
            case 2048:       //E_STRICT
            case 8192:       //E_DEPRICIATED
            case 16384:      //E_DEPRICIATED
                $level = 5;
                break;
            case 2:          //E_WARNING
            case 512:        //E_USER_WARNING
                $level = 3;
                break;
            case 256:
                $level = 2;
                break;
            default:
                $level = 2;
        }
        if ($this->_level == FALSE)
            return true;
        //Get the file path
        $this->_level = $level;
        $path = $this->_getPath($fileName);
        if (!is_writable($path))
            return false;
        $this->prepFile($path);
        //Create the log writer object
        $writer = new Zend_Log_Writer_Stream($path);
        $writer->setFormatter($this->_formatter);
        //Instantiate logging object
        $logger = new Zend_Log($writer);
        //Filter log entries to those allowed by configuration
        $filter = new Zend_Log_Filter_Priority($this->_level);
        $logger->addFilter($filter);
        //Set additional information about the class and function that called the log
        // Add custom elements to default log package
        $logger->setEventItem('back_trace', $backTrace);
        $logger->setEventItem('package', $package);
        $logger->setEventItem('date', date("m/d/Y"));
        $logger->setEventItem('time', date("H:i:s"));
        //Write Log Entry
        $logger->log($message, $level);
        $this->closeFile($path);
        return TRUE;
    }
prepFile ($path)
Either open a new file with the correct string or remove a previous closing string
Returns
void
Definition at line 302 of file logService.php.
Referenced by log(), and logError().
    {
        //Check for existing file and HTML format
        if (file_exists($path) and $this->_format == 'HTML')
        {
            $file = file($path);
            array_pop($file);
            file_put_contents($path, $file);
        } elseif ($this->_format == 'HTML')
        {
            $html = '<html><head></head><body><table border="1">' . PHP_EOL;
            $file = fopen($path, 'a');
            fwrite($file, $html);
            fclose($file);
        } elseif (file_exists($path) and $this->_format == 'XML')
        {
            $file = file($path);
            array_pop($file);
            file_put_contents($path, $file);
        } elseif ($this->_format == 'XML')
        {
            $xml = '<?xml version="1.0" standalone="no"?><log>' . PHP_EOL;
            $file = fopen($path, 'a');
            fwrite($file, $xml);
            fclose($file);
        }
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 100 of file logService.php.
Referenced by __construct().
    {
        parent::readMetaData($xmlArr);
        $level = strtoupper($xmlArr["PLUGINSERVICE"]["LOG_CONFIG"]["ATTRIBUTES"]["LEVEL"]);
        $this->_level = (int) $level;
        $this->_format = strtoupper($xmlArr["PLUGINSERVICE"]["LOG_CONFIG"]["ATTRIBUTES"]["FORMAT"]);
        $this->_org = strtoupper($xmlArr["PLUGINSERVICE"]["LOG_CONFIG"]["ATTRIBUTES"]["ORG"]);
        $this->_daystolive = $xmlArr["PLUGINSERVICE"]["LOG_CONFIG"]["ATTRIBUTES"]["DAYSTOLIVE"]?strtoupper($xmlArr["PLUGINSERVICE"]["LOG_CONFIG"]["ATTRIBUTES"]["DAYSTOLIVE"]):'0';
    }
setExtension ()
Set the extension based on the type of format selected in app.inc
Returns
void
Definition at line 281 of file logService.php.
Referenced by __construct().
    {
        switch ($this->_format)
        {
            case 'HTML':
                $this->_extension = '.html';
                break;
            case 'XML':
                $this->_extension = '.xml';
                break;
            case 'CSV':
            default:
                $this->_extension = '.log';
                break;
        }
    }
setFormatter ()
Set the formatter based on the type of format selected in app.inc
Returns
void
Definition at line 256 of file logService.php.
Referenced by __construct().
    {
        switch ($this->_format)
        {
            case 'HTML':
            //HTML Format
                $this->_formatter = new Zend_Log_Formatter_Simple('<tr><td>%date%</td> <td>%time%</td> <td>%priorityName%</td> <td>%package%</td> <td>%message%</td> <td>%back_trace%</td> </tr>' . PHP_EOL);
                break;
            case 'XML':
            //XML Format
                require_once 'Zend/Log/Formatter/Xml.php';
                $this->_formatter = new Zend_Log_Formatter_Xml();
                break;
            case 'CSV':
            default:
            //CSV Format
                $this->_formatter = new Zend_Log_Formatter_Simple("'%date%','%time%','%priorityName%','%package%','%message%','%back_trace%'" . PHP_EOL);
                break;
        }
    }