Openbiz Framework API: accessService Class Reference
accessService Class Reference
Public Member Functions
__construct (&$xmlArr)
allowViewAccess ($viewName, $role=null)
Protected Member Functions
getMatchView ($viewName)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 39 of file accessService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize accessService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 50 of file accessService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
allowViewAccess ($viewName, $role = null)
Allow view access
Parameters
string $viewName
<type> $role
Returns
boolean
Definition at line 74 of file accessService.php.
References getMatchView().
    {
        if (!$role)
            $role = "";
        $view = $this->getMatchView($viewName);
        if (!$view)
            return true;
        $roleList = $view->getRoleList();
        if (!$roleList)
            return true;
        if ($roleList->get($role))
            return true;
        return false;
    }
getMatchView ($viewName) protected
Get match view
Parameters
string $viewName
Returns
EasyView|null
Definition at line 98 of file accessService.php.
Referenced by allowViewAccess().
    {
        /* @var $viewObj EasyView */
        $viewObj = $this->_restrictedViewList->get($viewName);
        if ($viewObj)
            return $viewObj;
        foreach ($this->_restrictedViewList as $view => $viewObj)
        {
            $preg_view = "/".$view."/";
            if (preg_match($preg_view, $viewName))
            {
                return $viewObj;
            }
        }
        return null;
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 61 of file accessService.php.
Referenced by __construct().
    {
        $viewCollection = $xmlArr["PLUGINSERVICE"]["ACCESS-CONSTRAINT"]["VIEW-COLLECTION"];
        $this->_restrictedViewList = new MetaIterator($xmlArr["PLUGINSERVICE"]["ACCESS-CONSTRAINT"]["VIEW-COLLECTION"]["VIEW"],"RestrictedView");
    }