/* below for uninstall help tutorial */
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/contact_list');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/event_assign');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/event_type');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/event_manage');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/project_gantt');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/statistics_.*');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/task_manage');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/task_timesheet');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/worklog_.*');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/announcement_manage');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/bookmark_manage');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/document_manage');
DELETE FROM `help_tutorial_user` WHERE `tutorial_id`=(SELECT `id` FROM `help_tutorial` WHERE `url_match`='/collab/note_manage');
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/contact_list';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/event_assign';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/event_type';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/event_manage';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/project_gantt';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/statistics_.*';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/task_manage';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/task_timesheet';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/worklog_.*';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/announcement_manage';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/bookmark_manage';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/document_manage';
DELETE FROM `help_tutorial` WHERE `url_match`='/collab/note_manage';