Openbiz Framework API: authService Class Reference
authService Class Reference
Public Member Functions
__construct (&$xmlArr)
authenticateUser ($userName, $password)
Data Fields
$m_AuthticationDataObj
$m_AuthticationType
Protected Member Functions
authDBUser ($userName, $password)
checkPassword ($encType, $password, $realPassword)
readMetadata (&$xmlArr)
Detailed Description
Definition at line 70 of file authService.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize auditService with xml array metadata
Parameters
array $xmlArr
Returns
void
Definition at line 81 of file authService.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
authDBUser ($userName, $password) protected
Authenticate User that stored in database
Parameters
string $userName
string $password
Returns
boolean
Definition at line 119 of file authService.php.
References checkPassword(), and BizSystem\getObject().
Referenced by authenticateUser().
    {
        $boAuth = BizSystem::getObject($this->m_AuthticationDataObj);
        if (!$boAuth)
            return false;
        $searchRule = "[login]='$userName'";
        $recordList = array();
        $boAuth->fetchRecords($searchRule, $recordList, 1);
        $encType   = $recordList[0]["enctype"];
        $realPassword = $recordList[0]["password"];
        if ($this->checkPassword($encType,$password,$realPassword))
            return true;
        return false;
    }
authenticateUser ($userName, $password)
Authenticate User
Parameters
string $userName
string $password
Returns
boolean
Definition at line 105 of file authService.php.
References authDBUser().
    {
        if ($this->m_AuthticationType == "database")
            return $this->authDBUser($userName, $password);
        return false;
    }
checkPassword ($encType, $password, $realPassword) protected
Check Password
Parameters
string $encType encryption type
string $password
string $realPassword
Returns
boolean
Definition at line 144 of file authService.php.
Referenced by authDBUser().
    {
        foreach(hash_algos() as $algos)
        {
            if(strtoupper($encType)==strtoupper($algos))
            {
                $password=hash($algos, $password);
            }
        }
        if($password==$realPassword)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
readMetadata (& $xmlArr) protected
Read array meta data, and store to meta object
Parameters
array $xmlArr
Returns
void
Definition at line 92 of file authService.php.
Referenced by __construct().
    {
        $this->m_AuthticationType  = $xmlArr["PLUGINSERVICE"]["ATTRIBUTES"]["AUTHTYPE"];
        $this->m_AuthticationDataObj  = $xmlArr["PLUGINSERVICE"]["ATTRIBUTES"]["BIZDATAOBJ"];
    }
Field Documentation
$m_AuthticationDataObj
Definition at line 73 of file authService.php.
$m_AuthticationType
Definition at line 72 of file authService.php.