Openbiz Framework API: HTMLTree Class Reference
HTMLTree Class Reference
Public Member Functions
__construct (&$xmlArr)
render ()
rerender ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
getTransKey ($name)
readMetadata (&$xmlArr)
renderNodeItems (&$nodeItemArray)
renderSingleNodeItem (&$nodeItem)
translate ($caption)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_NodesXml
Additional Inherited Members
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Detailed Description
Definition at line 26 of file HTMLTree.php.
Constructor & Destructor Documentation
__construct (& $xmlArr)
Initialize HTMLTree with xml array
Parameters
array $xmlArr
Returns
void
Definition at line 36 of file HTMLTree.php.
References readMetadata().
    {
        $this->readMetadata($xmlArr);
    }
Member Function Documentation
getTransKey ($name) protected
Definition at line 150 of file HTMLTree.php.
Referenced by translate().
    {
     $shortFormName = substr($this->m_Name,intval(strrpos($this->m_Name,'.'))+1);
     return strtoupper($shortFormName.'_'.$name);
    }
readMetadata (& $xmlArr) protected
Read Metadata from xml array
Parameters
array $xmlArr
Definition at line 46 of file HTMLTree.php.
Referenced by __construct().
    {
        $this->m_Name = $xmlArr["TREE"]["ATTRIBUTES"]["NAME"];
        $this->m_Package = $xmlArr["TREE"]["ATTRIBUTES"]["PACKAGE"];
        $this->m_Class = $xmlArr["TREE"]["ATTRIBUTES"]["CLASS"];
        $this->m_NodesXml = $xmlArr["TREE"]["NODE"];
    }
render ()
Render HTML Tree
Returns
string html content of the tree
Implements iUIControl.
Definition at line 60 of file HTMLTree.php.
References renderNodeItems().
Referenced by rerender().
    {
        // preload images
        $sHTML = "<script language=\"JavaScript\">\n".
                " minus = new Image();\n minus.src = \"".Resource::getImageUrl()."/minus.gif\";\n".
                " plus = new Image();\n plus.src = \"".Resource::getImageUrl()."/plus.gif\";\n".
                "</script>\n";
        // list all views and highlight the current view
        $sHTML .= "<ul class='expanded'>\n";
        $sHTML .= $this->renderNodeItems($this->m_NodesXml);
        $sHTML .= "</ul>";
        return $sHTML;
    }
renderNodeItems (& $nodeItemArray) protected
Render the html tree
Returns
string html content of the tree
Definition at line 80 of file HTMLTree.php.
References renderSingleNodeItem().
Referenced by render(), and renderSingleNodeItem().
    {
        $sHTML = "";
        if (isset($nodeItemArray["ATTRIBUTES"]))
        {
            $sHTML .= $this->renderSingleNodeItem($nodeItemArray);
        }
        else
        {
            foreach ($nodeItemArray as $nodeItem)
            {
                $sHTML .= $this->renderSingleNodeItem($nodeItem);
            }
        }
        return $sHTML;
    }
renderSingleNodeItem (& $nodeItem) protected
Render single node item
Parameters
array $nodeItem
Returns
<type>
Definition at line 103 of file HTMLTree.php.
References renderNodeItems(), and translate().
Referenced by renderNodeItems().
    {
        $url = $nodeItem["ATTRIBUTES"]["URL"];
        $caption = $this->translate($nodeItem["ATTRIBUTES"]["CAPTION"]);
        $target = $nodeItem["ATTRIBUTES"]["TARGET"];
        //$img = $nodeItem["ATTRIBUTES"]["IMAGE"];
        if ($nodeItem["NODE"])
            $image = "<img src='".Resource::getImageUrl()."/plus.gif' class='collapsed' onclick='mouseClickHandler(this)'>";
        else
            $image = "<img src='".Resource::getImageUrl()."/topic.gif'>";
        if ($target)
            if ($url)
                $sHTML .= "<li class='tree'>$image <a href=\"".$url."\" target='$target'>".$caption."</a>";
            else
                $sHTML .= "<li class='tree'>$image $caption";
        else
        if ($url)
            $sHTML .= "<li class='tree'>$image <a href=\"".$url."\">".$caption."</a>";
        else
            $sHTML .= "<li class='tree'>$image $caption";
        if ($nodeItem["NODE"])
        {
            $sHTML .= "\n<ul class='collapsed'>\n";
            $sHTML .= $this->renderNodeItems($nodeItem["NODE"]);
            $sHTML .= "</ul>";
        }
        $sHTML .= "</li>\n";
        return $sHTML;
    }
rerender ()
Rerender the menu
Returns
string html content of the menu
Definition at line 139 of file HTMLTree.php.
References render().
    {
        return $this->render();
    }
translate ($caption) protected
Definition at line 144 of file HTMLTree.php.
References MetaObject\getModuleName(), getTransKey(), and I18n\t().
Referenced by renderSingleNodeItem().
    {
     $module = $this->getModuleName($this->m_Name);
     return I18n::t($caption, $this->getTransKey(caption), $module);
    }
Field Documentation
$m_NodesXml protected
Definition at line 28 of file HTMLTree.php.