Openbiz Framework API: BizDataObj_Lite Class Reference
BizDataObj_Lite Class Reference
Public Member Functions
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0, $sortRule="")
fetch ()
fetchById ($id)
fetchByName ($nameVal)
fetchOne ($searchRule, $sortRule="")
fetchRecords ($searchRule, &$resultRecords, $count=-1, $offset=0, $clearSearchRule=true, $noAssociation=false)
find ()
getActiveRecord ()
getErrorFields ()
getErrorMessage ()
getField ($fieldName)
getFieldNameByColumn ($column)
getFieldValue ($fieldName)
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
setActiveRecord ($currentRecord)
setActiveRecordId ($recordId)
setSessionVars ($sessionContext)
updateRecord ($recArr, $oldRec=null)
validateInput ()
Public Member Functions inherited from BizDataObj_Abstract
__construct (&$xmlArr)
clearAllRules ()
clearOtherSQLRule ()
clearSearchRule ()
clearSortRule ()
count ()
deleteRecord ($recArr)
directFetch ($searchRule="", $count=-1, $offset=0)
fetch ()
find ()
getAssociation ()
getDBConnection ($type='default')
getParameter ($paramName)
getProperty ($propertyName)
getRefObject ($objName)
getSessionVars ($sessionContext)
insertRecord ($recArr)
newRecord ()
resetRules ()
setLimit ($count, $offset=0)
setOtherSQLRule ($rule)
setQueryParam ($queryStr, $paramValues)
setSearchRule ($rule, $overWrite=false)
setSessionVars ($sessionContext)
setSortRule ($rule)
updateRecord ($recArr, $oldRec=null)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Protected Member Functions
_fetch_record (&$resultSet)
_run_search ($limit=null)
getSQLHelper ()
Protected Member Functions inherited from BizDataObj_Abstract
getMessage ($msgid, $params=array())
inheritParentObj ()
readMetadata (&$xmlArr)
setAssociation ($objRef, $asscObj)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$_fetch4countQuery
$m_CurrentRecord
$m_ErrorFields
$m_ErrorMessage
$m_RecordId
Protected Attributes inherited from BizDataObj_Abstract
$m_Limit
$m_Messages
Additional Inherited Members
Data Fields inherited from BizDataObj_Abstract
$m_AccessRule
$m_BaseOtherSQLRule
$m_BaseSearchRule
$m_BaseSortRule
$m_BizRecord
$m_CacheLifeTime
$m_Database
$m_DataPermControl
$m_DeleteCondition
$m_IdGeneration
$m_InheritFrom
$m_MainTable
$m_MessageFile
$m_ObjReferences
$m_OtherSQLRule
$m_Parameters
$m_SearchRule
$m_SortRule
$m_Stateless
$m_TableJoins
$m_Uniqueness
$m_UpdateCondition
Detailed Description
Definition at line 33 of file BizDataObj_Lite.php.
Member Function Documentation
_fetch_record (& $resultSet) protected
Get record from result setand move the cursor to next row
Returns
array record array
Definition at line 580 of file BizDataObj_Lite.php.
References $m_CurrentRecord.
Referenced by directFetch(), fetch(), and fetchRecords().
    {
     if(!is_array($resultSet)){
      return null;
     }
        if ($sqlArr = current($resultSet))
        {
            $this->m_CurrentRecord = $this->m_BizRecord->convertSqlArrToRecArr($sqlArr);
            $this->m_CurrentRecord = $this->m_BizRecord->getRecordArr($sqlArr);
            $this->m_RecordId = $this->m_CurrentRecord["Id"];
            next($resultSet);
        }
        else
        {
            return null;
        }
        return $this->m_CurrentRecord;
    }
_run_search ($limit = null) protected
Run query with current search rule and returns PDO statement
Parameters
array $limit - if limit is not null, do the limit search
Returns
PDOStatement
Definition at line 447 of file BizDataObj_Lite.php.
References count(), QueryStringParam\getBindValues(), QueryStringParam\getBindValueString(), BizDataObj_Abstract\getDBConnection(), BizDataObj_Abstract\getMessage(), BizSystem\getService(), getSQLHelper(), and BizSystem\log().
Referenced by directFetch(), fetch(), fetchRecords(), and find().
    {
        // get database connection
        $db = $this->getDBConnection("READ");
        $querySQL = $this->getSQLHelper()->buildQuerySQL($this);
        $this->_fetch4countQuery = $querySQL;
        if ($limit && count($limit) > 0 && $limit['count'] > 0)
            $sql = $db->limit($querySQL, $limit['count'], $limit['offset']);
        else
            $sql = $querySQL;
        try
        {
            $bindValues = QueryStringParam::getBindValues();
            $bindValueString = QueryStringParam::getBindValueString();
            if($this->m_CacheLifeTime>0)
            {
                $cache_id = md5($this->m_Name . $sql . serialize($bindValues));
                //try to process cache service.
                $cacheSvc = BizSystem::getService(CACHE_SERVICE,1);
                $cacheSvc->init($this->m_Name,$this->m_CacheLifeTime);
                if($cacheSvc->test($cache_id))
                {
                    //BizSystem::log(LOG_DEBUG, "DATAOBJ", "Cache Hit. Query Sql = ".$sql." BIND: $bindValueString");
                    $resultSetArray = $cacheSvc->load($cache_id);
                }
                else
                {
                    BizSystem::log(LOG_DEBUG, "DATAOBJ", "Query Sql = ".$sql." BIND: $bindValueString");
                    $resultSet = $db->query($sql, $bindValues);
                    $resultSetArray = $resultSet->fetchAll();
                    $cacheSvc->save($resultSetArray,$cache_id);
                }
            }
            else
            {
                BizSystem::log(LOG_DEBUG, "DATAOBJ", "Query Sql = ".$sql." BIND: $bindValueString");
                $resultSet = $db->query($sql, $bindValues);
                $resultSetArray = $resultSet->fetchAll();
            }
        }
        catch (Exception $e)
        {
            BizSystem::log(LOG_ERR, "DATAOBJ", "Query Error: ".$e->getMessage());
            $this->m_ErrorMessage = $this->getMessage("DATA_ERROR_QUERY").": ".$sql.". ".$e->getMessage();
            throw new BDOException($this->m_ErrorMessage);
            return null;
        }
        return $resultSetArray;
    }
count ()
Count the number of record according to the search results set before. It ignores limit setting
Returns
int number of records
Definition at line 429 of file BizDataObj_Lite.php.
References $_fetch4countQuery, BizDataObj_Abstract\getDBConnection(), and getSQLHelper().
Referenced by _run_search(), directFetch(), BizDataTree\fetchNodePath(), fetchOne(), getActiveRecord(), BizDataObj\processCascadeAction(), BizDataObj\validateInput(), and BizDataObj\validateUniqueness().
    {
        // get database connection
        $db = $this->getDBConnection("READ");
        if ($this->_fetch4countQuery)
            $querySQL = $this->_fetch4countQuery;
        else
            $querySQL = $this->getSQLHelper()->buildQuerySQL($this);
        $this->_fetch4countQuery = null;
        return $this->_getNumberRecords($db, $querySQL);
    }
deleteRecord ($recArr)
Delete current record or delete the given input record
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 648 of file BizDataObj_Lite.php.
    {
    }
directFetch ($searchRule = "", $count = -1, $offset = 0, $sortRule = "")
Fetches SQL result rows as a sequential array without using query rules set before.
Parameters
string $searchRule the search rule string
int $count number of records to return
int $offset the starting point of the return records
Returns
array array of records
Definition at line 271 of file BizDataObj_Lite.php.
References $m_CurrentRecord, $m_RecordId, BizDataObj_Abstract\$m_SearchRule, BizDataObj_Abstract\$m_SortRule, _fetch_record(), _run_search(), BizDataObj_Abstract\clearSearchRule(), BizDataObj_Abstract\clearSortRule(), count(), BizDataObj_Abstract\setSearchRule(), and BizDataObj_Abstract\setSortRule().
Referenced by BizDataTree\fetchNodePath(), fetchOne(), BizDataTree\fetchTree(), getActiveRecord(), and BizDataObj\validateUniqueness().
    {
        $curRecord = $this->m_CurrentRecord;
        $recId = $this->m_RecordId;
        $this->m_CurrentRecord = null;
        $oldSearchRule = $this->m_SearchRule;
        $this->clearSearchRule();
        $this->setSearchRule($searchRule);
        $oldSortRule = $this->m_SortRule;
        $this->clearSortRule();
        if($sortRule){
         $this->setSortRule($sortRule);
        }else{
         $this->setSortRule($this->m_SortRule);
        }
        $limit = ($count == -1) ? null : array('count'=>$count, 'offset'=>$offset);
        $dataSet = new DataSet($this);
        $resultSet = $this->_run_search($limit);
        if ($resultSet !== null)
        {
            $i = 0;
            while ($recArray = $this->_fetch_record($resultSet))
            {
                $dataSet[$i++] = $recArray;
            }
        }
        $this->m_SortRule = $oldSortRule;
        $this->m_SearchRule = $oldSearchRule;
        $this->m_CurrentRecord = $curRecord;
        $this->m_RecordId = $recId;
        if (count($dataSet) == 0)
            return new DataSet(null);
        return $dataSet;
    }
fetch ()
Fetches SQL result rows as a sequential array according the query rules set before.
Returns
array array of records
Definition at line 244 of file BizDataObj_Lite.php.
References _fetch_record(), and _run_search().
    {
        $dataSet = new DataSet($this);
        $this->_fetch4countQuery = null;
        $resultSet = $this->_run_search($this->m_Limit);  // regular search or page search
        if ($resultSet !== null)
        {
            $i = 0;
            while ($recArray = $this->_fetch_record($resultSet))
            {
                $dataSet[$i++] = $recArray;
            }
        }
        else
            return null;
        return $dataSet;
    }
fetchById ($id)
Fetch a data record by specified Id
Parameters
$Id the Id value of this data object, typically its a numerical value. but also could be string if the DO is defined for expected a string as Id.
Returns
DataRecord
Definition at line 318 of file BizDataObj_Lite.php.
References fetchOne().
    {
        $searchRule = "[Id] = '$id'";
        return $this->fetchOne($searchRule);
    }
fetchByName ($nameVal)
Fetch a data record by specified value of name field. its only used if the current data object has a name field. like typical Openbiz Cubi's data object does.
Parameters
string $nameVal
Returns
DataRecord
Definition at line 332 of file BizDataObj_Lite.php.
References fetchOne().
    {
        $searchRule = "[name] = '$nameVal'";
        return $this->fetchOne($searchRule);
    }
fetchOne ($searchRule, $sortRule = "")
Fetch a data record by specified search condition, if the query can return more than one record, the sort rule will be used for decide which record will be record, like if sort by [Id] ASC, then the smallest id record will be return.
Parameters
string $searchRule
string $sortRule
Returns
DataRecord
Definition at line 346 of file BizDataObj_Lite.php.
References count(), and directFetch().
Referenced by fetchById(), and fetchByName().
    {
        $recordList = $this->directFetch($searchRule, 1,0,$sortRule);
        if (count($recordList) >= 1)
            return new DataRecord($recordList[0], $this);
        else
            return null;
    }
fetchRecords ($searchRule, & $resultRecords, $count = -1, $offset = 0, $clearSearchRule = true, $noAssociation = false)
Run query and get the query results without affecting DataObject internal state by default it gets number of records starting from the first row. if pageNum > 0, it gets number of records starting from the first row of the page
Parameters
$searchRule search rule applied on the query
$resultRecord returned result record array
$recNum number of records to be returned. if -1, all query results returned
$clearSearchRule indicates if search rule need to be cleared before query
$noAssociation indicates if current association condition is not used in query
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 367 of file BizDataObj_Lite.php.
References $m_CurrentRecord, $m_RecordId, BizDataObj_Abstract\$m_SearchRule, _fetch_record(), _run_search(), BizDataObj_Abstract\clearSearchRule(), and BizDataObj_Abstract\setSearchRule().
    {
        if ($count == 0) return;
        $curRecord = $this->m_CurrentRecord;
        $recId = $this->m_RecordId;
        $oldSearchRule = $this->m_SearchRule;
        $this->m_CurrentRecord = null;
        if ($clearSearchRule)
            $this->clearSearchRule();
        $this->setSearchRule($searchRule);
        if ($noAssociation)
        {
            $oldAssociation = $this->m_Association;
            $this->m_Association = null;
        }
        $limit = ($count == -1) ? null : array('count'=>$count, 'offset'=>$offset);
        $resultRecords = array();
        $resultSet = $this->_run_search($limit);
        if ($resultSet !== null)
        {
            while ($recArray = $this->_fetch_record($resultSet))
            {
                $resultRecords[] = $recArray;
            }
        }
        if ($noAssociation)
            $this->m_Association = $oldAssociation;
        $this->m_SearchRule = $oldSearchRule;
        $this->m_CurrentRecord = $curRecord;
        $this->m_RecordId = $recId;
        return true;
    }
find ()
Do the search query and return results set as PDOStatement
Returns
PDOStatement PDO statement object
Definition at line 408 of file BizDataObj_Lite.php.
References _run_search().
    {
        return $this->_run_search($this->m_Limit);
    }
getActiveRecord ()
Get the active record
Returns
array - record array
Definition at line 201 of file BizDataObj_Lite.php.
References $m_CurrentRecord, count(), and directFetch().
Referenced by BizDataObj\canDeleteRecord(), BizDataObj\canUpdateRecord(), BizDataObj\deleteRecord(), getFieldValue(), and BizDataObj\updateRecord().
    {
        if ($this->m_RecordId == null || $this->m_RecordId == "")
            return null;
        if ($this->m_CurrentRecord == null)
        {
            // query on $recordId
            $records = $this->directFetch("[Id]='".$this->m_RecordId."'", 1);
            if (count($records) == 1)
            {
                $this->m_CurrentRecord = $records[0];
                $this->m_RecordId = $this->m_CurrentRecord["Id"];
            }
            else
                $this->m_CurrentRecord = null;
        }
        return $this->m_CurrentRecord;
    }
getErrorFields ()
Get error fields
Returns
array
Definition at line 116 of file BizDataObj_Lite.php.
References $m_ErrorFields.
    {
        return $this->m_ErrorFields;
    }
getErrorMessage ()
Get the error message caused by data action
Returns
string the error message string
Definition at line 106 of file BizDataObj_Lite.php.
References $m_ErrorMessage.
    {
        return $this->m_ErrorMessage;
    }
getField ($fieldName)
Get the BizField object
Parameters
string $fieldName field name
Returns
BizField BizField object
Definition at line 127 of file BizDataObj_Lite.php.
Referenced by BizDataObj\generateId(), getProperty(), and BizDataObj\processCascadeAction().
    {
        return $this->m_BizRecord->get($fieldName);
    }
getFieldNameByColumn ($column)
Get field name by column
Parameters
string $column column name
Returns
BizField BizField object
Definition at line 164 of file BizDataObj_Lite.php.
    {
        // Todo_Maynotuse: since column and join column can have the same name
        // TODO: ??? get field name but return BizField object ???
        return $this->m_BizRecord->getFieldByColumn($column); // main table column
    }
getFieldValue ($fieldName)
Get the BizField value
Parameters
string $fieldName field name
Returns
mixed BizField value
Definition at line 177 of file BizDataObj_Lite.php.
References getActiveRecord().
Referenced by BizDataObj\processCascadeAction(), and BizDataObj\updateRecord().
    {
        $rec = $this->getActiveRecord();
        return $rec[$fieldName];
    }
getProperty ($propertyName)
Get object property
Parameters
string $propertyName
Returns
BizField|string|mixed
Definition at line 138 of file BizDataObj_Lite.php.
References getField().
    {
        $ret = parent::getProperty($propertyName);
        if ($ret !== null) return $ret;
        // get control object if propertyName is "Control[ctrlname]"
        $pos1 = strpos($propertyName, "[");
        $pos2 = strpos($propertyName, "]");
        if ($pos1>0 && $pos2>$pos1)
        {
            $propType = substr($propertyName, 0, $pos1);
            $fieldName = substr($propertyName, $pos1+1,$pos2-$pos1-1);
            /*if ($propType == "param") {   // get parameter
                return $this->m_Parameters->get($ctrlname);
            }*/
            return $this->getField($fieldName);
        }
    }
getRecordId ()
Definition at line 221 of file BizDataObj_Lite.php.
References $m_RecordId.
{
     return $this->m_RecordId;
    }
getSessionVars ($sessionContext)
Get session variables data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 71 of file BizDataObj_Lite.php.
    {
        if ($this->m_Stateless == "Y")
            return;
        $sessionContext->getObjVar($this->m_Name, "RecordId", $this->m_RecordId);
        $sessionContext->getObjVar($this->m_Name, "SearchRule", $this->m_SearchRule);
        $sessionContext->getObjVar($this->m_Name, "SortRule", $this->m_SortRule);
        $sessionContext->getObjVar($this->m_Name, "OtherSqlRule", $this->m_OtherSQLRule);
        $sessionContext->getObjVar($this->m_Name, "Association", $this->m_Association);
    }
getSQLHelper () protected
Get SQL helper
Returns
BizDataObj_SQLHelper
Definition at line 418 of file BizDataObj_Lite.php.
References BizDataObj_SQLHelper\instance().
Referenced by _run_search(), count(), BizDataObj\deleteRecord(), BizDataObj\deleteRecords(), BizDataObj\insertRecord(), BizDataObj\updateRecord(), and BizDataObj\updateRecords().
    {
        return BizDataObj_SQLHelper::instance();
    }
insertRecord ($recArr)
Insert record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 625 of file BizDataObj_Lite.php.
    {
    }
newRecord ()
Create an empty new record
Returns
array - empty record array with default values
Definition at line 614 of file BizDataObj_Lite.php.
    {
    }
setActiveRecord ($currentRecord)
Set the current working record values
Parameters
array $currentRecord record array
Returns
void
Definition at line 189 of file BizDataObj_Lite.php.
    {
        $this->m_CurrentRecord = $currentRecord;
        $this->m_RecordId = $this->m_CurrentRecord['Id'];
    }
setActiveRecordId ($recordId)
Set the active record according to the record id
Parameters
mixed $recordId record id
Returns
void
Definition at line 230 of file BizDataObj_Lite.php.
    {
        if ($this->m_RecordId != $recordId)
        {
            $this->m_RecordId = $recordId;
            $this->m_CurrentRecord = null;
        }
    }
setSessionVars ($sessionContext)
Save Session variables/data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 88 of file BizDataObj_Lite.php.
    {
        if ($this->m_Stateless == "Y")
            return;
        $sessionContext->setObjVar($this->m_Name, "RecordId", $this->m_RecordId);
        $sessionContext->setObjVar($this->m_Name, "SearchRule", $this->m_SearchRule);
        $sessionContext->setObjVar($this->m_Name, "SortRule", $this->m_SortRule);
        $sessionContext->setObjVar($this->m_Name, "OtherSqlRule", $this->m_OtherSQLRule);
        if(is_array($this->m_Association)){
         $sessionContext->setObjVar($this->m_Name, "Association", $this->m_Association);
        }
    }
updateRecord ($recArr, $oldRec = null)
Update record using given input record array
Parameters
array $recArr - associated array whose keys are field names of this BizDataObj
array $oldRec - associated array who is the old record field name / value pairs
Returns
boolean - if return false, the caller can call GetErrorMessage to get the error.
Definition at line 637 of file BizDataObj_Lite.php.
    {
    }
validateInput ()
Validate user input data and trigger error message and adjust BizField if invalid.
Returns
boolean
Definition at line 604 of file BizDataObj_Lite.php.
    {
    }
Field Documentation
$_fetch4countQuery protected
Definition at line 63 of file BizDataObj_Lite.php.
Referenced by count().
$m_CurrentRecord protected
Definition at line 47 of file BizDataObj_Lite.php.
Referenced by _fetch_record(), directFetch(), fetchRecords(), and getActiveRecord().
$m_ErrorFields protected
Definition at line 61 of file BizDataObj_Lite.php.
Referenced by getErrorFields().
$m_ErrorMessage protected
Definition at line 54 of file BizDataObj_Lite.php.
Referenced by getErrorMessage(), BizDataObj\validateInput(), and BizDataObj\validateUniqueness().
$m_RecordId protected
Definition at line 40 of file BizDataObj_Lite.php.
Referenced by directFetch(), fetchRecords(), and getRecordId().