; ini file format
; example
FORM_ELEMENT_REQUIRED = "%s is required. Please enter a valid value."
MESSAGE_HAS_BEEN_SENT = "Selected messages has been sent."
MESSAGE_HAS_BEEN_DELETED = "Selected messages has been deleted."
PLEASE_SELECT_MESSAGE_TO_CHANGE_TYPE = "Please select message to change its type."
MESSAGE_PREFIX_REPLY = "Re: ";
MESSAGE_PREFIX_FORWARD = "Fwd: ";
FORM_OPEATION_NOT_PERMITTED = "You don't have enough permission to do this operation."