; ini file format
; example
FORM_ELEMENT_REQUIRED = "%s is required. Please enter a valid value."
DEFAULT_PROJECT = "Default Project"
DEFAULT_PROJECT_COLOR = "ff3300"
TASK_DESCRIPTION = "%s - %s,  %s h"
TASK_START_TIME_SHOULD_BE_IN = "Should be within %s - %s"
TASK_START_TIME_SHOULD_BE_LATER_THAN = "Should be later than %s"
TASK_FINISH_TIME_SHOULD_BE_EARLIER_THAN = "Should be earlier than %s"
TASK_TIME_BUDGET_SHOULD_BE_DECRASED = "Should be decrased"
TASK_DEPENDENCY_FINISH_TOO_LATE = "Task finish time is later than parent task."
TASK_PARENT_DEPENDENCY_CAN_NOT_BE_SAME = "Parent and Dependency can not be same"
FORM_OPEATION_NOT_PERMITTED = "You don't have enough permission to do this operation."