Openbiz Framework API: File Class Reference
File Class Reference
Public Member Functions
render ()
Public Member Functions inherited from InputElement
getValue ()
render ()
renderLabel ()
Public Member Functions inherited from Element
__construct (&$xmlArr, $formObj)
adjustFormName ($formName)
canDisplayed ()
checkRequired ()
getClientValidator ()
getContextMenu ()
getDefaultValue ()
getDescription ()
getEvents ()
getFunctionByEventHandlerName ($eventHandlerName)
getFunctionType ($eventHandlerName)
getParameter ($eventHandlerName)
getProperty ($propertyName)
getRedirectPage ($eventHandlerName)
getSCKeyFuncMap ()
getValue ()
matchRemoteMethod ($method)
render ()
renderLabel ()
reset ()
setValue ($value)
validate ()
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Additional Inherited Members
Data Fields inherited from InputElement
$m_DefaultValue
$m_DefaultValueRename
$m_Description
$m_Enabled
$m_FieldName
$m_Hint
$m_Label
$m_Required
$m_Text
Protected Member Functions inherited from InputElement
addSCKeyScript ()
getEnabled ()
getRequired ()
readMetaData (&$xmlArr)
Detailed Description
Definition at line 27 of file File.php.
Member Function Documentation
render ()
Render the element, according to the mode
Returns
string HTML text
Implements iUIControl.
Definition at line 35 of file File.php.
References InputElement\getEnabled(), Element\getFunction(), and Element\getStyle().
    {
        $disabledStr = ($this->getEnabled() == "N") ? "disabled=\"true\"" : "";
        $style = $this->getStyle();
        $func = $this->getFunction();
  $sHTML .= "<input type=\"file\" name='$this->m_Name' id=\"" . $this->m_Name ."\" value='$this->m_Value' $disabledStr $this->m_HTMLAttr $style $func />";
        return $sHTML;
    }