Openbiz Framework API: EasyFormWizard Class Reference
EasyFormWizard Class Reference
Public Member Functions
cancel ()
commit ()
doCancel ()
doFinish ()
dropSession ()
getSessionVars ($sessionContext)
goBack ()
goNext ($commit=false)
outputAttrs ()
render ()
setSessionVars ($sessionContext)
skip ()
Public Member Functions inherited from EasyForm
__construct (&$xmlArr)
allowAccess ($access=null)
autoSuggest ($input)
callService ($class, $method, $param=null)
cancel ()
canDeleteRecord ($rec)
canDisplayForm ()
close ()
copyRecord ($id=null)
deleteRecord ($id=null)
editRecord ($id=null)
fetchData ()
fetchDataSet ()
getActiveRecord ($recId=null)
getDataObj ()
getElement ($elementName)
getElementID ()
getElementSet ($panel=null)
getErrorElements ($fields)
getMessage ($messageId, $params=array())
getProperty ($propertyName)
getRecordId ()
getSessionVars ($sessionContext)
getSubForms ()
getTabSet ($panel=null)
getViewObject ()
gotoPage ($page=1)
gotoSelectedPage ($elemName)
insertRecord ()
invoke ()
loadDialog ($formName, $id=null, $transId=false)
loadPicker ($formName, $elementName="")
newRecord ()
outputAttrs ()
parentSwitchForm ($formName=null, $id=null, $params=null, $target=null)
processBDOException ($e)
processDataObjError ($errCode=0)
processFormObjError ($errors)
removeRecord ()
render ()
renderParent ()
rerender ($redrawForm=true, $hasRecordChange=true)
resetSearch ()
runSearch ()
saveRecord ()
selectRecord ($recId)
setCurrentPage ($pageid)
setDataObj ($dataObj)
setFixSearchRule ($rule=null, $cleanActualRule=true)
setFormInputs ($inputArr=null)
setPageSize ($elemName)
setParentForm ($parentFormName)
setRecordId ($val)
setRequestParams ($paramFields)
setSearchRule ($searchRule, $searchRuleBindValues=null)
setSessionVars ($sessionContext)
setSubForms ($subForms)
sortRecord ($sortCol, $order='ASC')
switchForm ($formName=null, $id=null, $params=null, $target=null)
targetSwitchForm ($targetForm, $formName=null, $id=null, $params=null, $target=null)
updateFieldValue ($Id, $fld_name, $value)
updateFieldValueAdd ($id, $fld_name, $value, $min, $max)
updateFieldValueXor ($id, $fld_name, $value)
updateForm ()
updateRecord ()
validateRequest ($methodName)
Public Member Functions inherited from MetaObject
__construct (&$xmlArr)
allowAccess ($access=null)
getModuleName ($name)
getProperty ($propertyName)
Data Fields
$m_WizardPanel
Data Fields inherited from EasyForm
$DATAFORMAT
$m_ActionPanel
$m_ActiveRecord
$m_AutoRefresh
$m_CacheLifeTime
$m_CanUpdateRecord
$m_DataObjName
$m_DataPanel
$m_DefaultForm
$m_DefaultFormName
$m_Description
$m_DirectMethodList
$m_Errors
$m_EventName
$m_FixSearchRule
$m_FormInputs
$m_FormParams
$m_FormType
$m_Height
$m_Icon
$m_InheritFrom
$m_jsClass
$m_MessageFile
$m_NavPanel
$m_Notices
$m_Panels
$m_ParentFormName
$m_QueryStringParam
$m_Range
$m_ReferenceFormName
$m_SearchPanel
$m_SearchRule
$m_SortRule
$m_SubForms
$m_TemplateEngine
$m_TemplateFile
$m_Title
$m_TotalPages
$m_Width
Data Fields inherited from MetaObject
$m_Access
$m_Class
$m_Description
$m_Name
$m_Package
Protected Member Functions
readMetadata (&$xmlArr)
Protected Member Functions inherited from EasyForm
_doInsert ($inputRecord)
_doUpdate ($inputRecord, $currentRecord)
_showForm ($formName, $target, $paramFields)
commitFormElements ()
getEventLogMsg ()
getInvokingElement ()
getNewRecord ()
getOnEventElements ()
getRedirectPage ()
getTransKey ($name)
getTransPrefix ()
inheritParentObj ()
processPostAction ()
readInputRecord ()
readInputs ()
readMetadata (&$xmlArr)
renderContextMenu ()
renderHTML ()
rerenderSubForms ()
runEventLog ()
setActiveRecord ($record)
setClientScripts ()
translate ()
validateForm ($cleanError=true)
Protected Member Functions inherited from MetaObject
getElementObject (&$xmlArr, $defaultClassName, $parentObj=null)
prefixPackage ($name)
readMetaCollection (&$xmlArr, &$metaList)
readMetadata (&$xmlArr)
Protected Attributes
$m_DropSession
Protected Attributes inherited from EasyForm
$m_CurrentPage
$m_DataObj
$m_DefaultFixSearchRule
$m_hasError
$m_InvokingElement
$m_Messages
$m_RecordAllowAccess
$m_RecordId
$m_RecordSet
$m_Referer
$m_RefreshData
$m_Resource
$m_SearchRuleBindValues
$m_StartItem
$m_TotalRecords
$m_ValidateErrors
Detailed Description
Definition at line 25 of file EasyFormWizard.php.
Member Function Documentation
cancel ()
Clean up the sessions of view and all forms
Returns
void
Definition at line 261 of file EasyFormWizard.php.
References BizSystem\sessionContext().
    {
        // clean the session record
        $this->m_DropSession = true;
        BizSystem::sessionContext()->cleanObj($this->m_Name, true);
    }
commit ()
Save wizard data of current+previous pages into database or other storage
Returns
void
Definition at line 218 of file EasyFormWizard.php.
References EasyForm\$m_ActiveRecord, EasyForm\getDataObj(), and EasyForm\processBDOException().
    {
  if(!$this->getDataObj()){
   return true;
  }
     // commit the form input. call SaveRecord()
        $recArr = $this->m_ActiveRecord;
        if (strtoupper($this->m_FormType) == "NEW")
            $dataRec = new DataRecord(null, $this->getDataObj());
        else
        {
            //$currentRec = $this->fetchData(); // wrong way to get current data. need to query the old one
            $currentRec = array(); // to get record with "" values
            $dataRec = new DataRecord($currentRec, $this->getDataObj());
        }
        foreach ($recArr as $k => $v)
            $dataRec[$k] = $v; // or $dataRec->$k = $v;
        try
        {
            $dataRec->save();
        } catch (BDOException $e)
        {
            $this->processBDOException($e);
            return false;
        }
        return true;
    }
doCancel ()
Cancel the wizard process
Returns
void remote
Definition at line 203 of file EasyFormWizard.php.
References EasyForm\getViewObject(), and EasyForm\processPostAction().
    {
        /* @var $viewObj EasyViewWizard */
        $viewObj = $this->getViewObject();
        $viewObj->cancel();
        $this->processPostAction();
    }
doFinish ()
Finish the wizard process
Returns
void remote
Definition at line 167 of file EasyFormWizard.php.
References EasyForm\getViewObject(), EasyForm\processFormObjError(), EasyForm\processPostAction(), EasyForm\readInputRecord(), EasyForm\setActiveRecord(), and EasyForm\setFormInputs().
    {
        // call ValidateForm()
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
     $this->setFormInputs($this->m_FormInputs);
      try
        {
             if ($this->ValidateForm() == false)
            return;
        }catch (ValidationException $e)
        {
         $this->processFormObjError($e->m_Errors);
            return;
        }
        $this->m_ActiveRecord = $this->readInputRecord();
        /* @var $viewObj EasyViewWizard */
        $viewObj = $this->getViewObject();
        $r = $viewObj->commit();
        if (!$r)
            return;
        $this->processPostAction();
    }
dropSession ()
Definition at line 249 of file EasyFormWizard.php.
{
     // clean the session record
        $this->m_DropSession = true;
        return true;
    }
getSessionVars ($sessionContext)
Get/Retrieve Session data of this object
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 42 of file EasyFormWizard.php.
References EasyForm\setActiveRecord().
    {
     parent::getSessionVars($sessionContext);
        $sessionContext->getObjVar($this->m_Name, "ActiveRecord", $this->m_ActiveRecord, true);
        $sessionContext->getObjVar($this->m_Name, "FormInputs", $this->m_FormInputs, true);
        $this->setActiveRecord($this->m_ActiveRecord);
    }
goBack ()
Go to previous wizard page
Returns
void remote
Definition at line 140 of file EasyFormWizard.php.
References EasyForm\getViewObject(), EasyForm\readInputRecord(), and EasyForm\setActiveRecord().
    {
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
  $this->m_ActiveRecord = $this->readInputRecord();
        $viewObj = $this->getViewObject();
        // get the step
        if($viewObj->getCurrentStep()){
         $step = $viewObj->getCurrentStep();
        }else{
         $step = $_GET['step'];
        }
        // redirect the prev step
        /* @var $viewObj EasyViewWizard */
        $viewObj->renderStep($step-1);
    }
goNext ($commit = false)
Go to next wizard page
Parameters
boolean $commit true if need to commit current form data
Returns
void remote
Definition at line 80 of file EasyFormWizard.php.
References EasyForm\getViewObject(), EasyForm\processFormObjError(), EasyForm\readInputRecord(), and EasyForm\setActiveRecord().
    {
        // call ValidateForm()
        $recArr = $this->readInputRecord();
        $this->setActiveRecord($recArr);
      try
        {
             if ($this->ValidateForm() == false)
            return;
        }catch (ValidationException $e)
        {
            $this->processFormObjError($e->m_Errors);
            return;
        }
        $this->m_ActiveRecord = $this->readInputRecord();
  $viewObj = $this->getViewObject();
        // get the step
     if($viewObj->getCurrentStep()){
         $step = $viewObj->getCurrentStep();
        }else{
         $step = $_GET['step'];
        }
        if (!$step || $step=="")
            $step=1;
        // redirect the prev step
        /* @var $viewObj EasyViewWizard */
        $viewObj->renderStep($step+1);
    }
outputAttrs ()
Definition at line 280 of file EasyFormWizard.php.
References EasyForm\getViewObject().
    {
        $output = parent::outputAttrs();
        $viewobj = $this->getViewObject();
        $forms = array();
        $viewobj->m_FormRefs->rewind();
        while($viewobj->m_FormRefs->valid()){
         $form=$viewobj->m_FormRefs->current();
         $forms[$form->m_Name] = $form;
         $viewobj->m_FormRefs->next();
        }
        $output['forms'] = $forms;
        $output['step'] = $viewobj->getCurrentStep();
        return $output;
    }
readMetadata (& $xmlArr) protected
Definition at line 50 of file EasyFormWizard.php.
    {
        parent::readMetaData($xmlArr);
        $this->m_WizardPanel = new Panel($xmlArr["EASYFORM"]["WIZARDPANEL"]["ELEMENT"],"",$this);
    }
render ()
Render this form
Returns
string - HTML text of this form's read mode
Definition at line 273 of file EasyFormWizard.php.
References EasyForm\getViewObject().
    {
        $viewobj = $this->getViewObject();
        $viewobj->setFormState($this->m_Name, 'visited', 1);
        return parent::render();
    }
setSessionVars ($sessionContext)
Save object variable to session context
Parameters
SessionContext $sessionContext
Returns
void
Implements iSessionObject.
Definition at line 62 of file EasyFormWizard.php.
    {
        if ($this->m_DropSession)
            $sessionContext->cleanObj($this->m_Name, true);
        else {
         parent::setSessionVars($sessionContext);
            $sessionContext->setObjVar($this->m_Name, "ActiveRecord", $this->m_ActiveRecord, true);
            $sessionContext->setObjVar($this->m_Name, "FormInputs", $this->m_FormInputs, true);
        }
    }
skip ()
Skip current wizard page
Returns
void remote
Definition at line 119 of file EasyFormWizard.php.
References EasyForm\getViewObject().
    {
  $viewObj = $this->getViewObject();
        // get the step
     if($viewObj->getCurrentStep()){
         $step = $viewObj->getCurrentStep();
        }else{
         $step = $_GET['step'];
        }
        if (!$step || $step=="")
            $step=1;
        $viewObj->renderStep($step+2);
    }
Field Documentation
$m_DropSession protected
Definition at line 27 of file EasyFormWizard.php.
$m_WizardPanel
Definition at line 34 of file EasyFormWizard.php.