Openbiz Framework API: XMLParser Class Reference
XMLParser Class Reference
Public Member Functions
buildtag ($thisvals, $vals, &$i, $type)
getchildren ($vals, &$i)
& getTree ()
XMLParser ($data_source, $data_source_type='raw', $collapse_dups=0, $index_numeric=0)
Data Fields
$collapse_dups
$data
$index_numeric
$vals
Detailed Description
Definition at line 33 of file xmltoarray.src.php.
Member Function Documentation
buildtag ($thisvals, $vals, & $i, $type)
Definition at line 100 of file xmltoarray.src.php.
References $vals, and getchildren().
Referenced by getchildren().
{
  if (isset($thisvals['attributes']))
   $tag['ATTRIBUTES'] = $thisvals['attributes'];
  // complete tag, just return it for storage in array
  if ($type === 'complete')
   $tag['VALUE'] = $thisvals['value'];
  // open tag, recurse
  else
   $tag = array_merge((array)$tag, (array)$this->getchildren($vals, $i));
  return $tag;
 }
getchildren ($vals, & $i)
Definition at line 117 of file xmltoarray.src.php.
References $vals, and buildtag().
Referenced by buildtag(), and getTree().
{
  $children = array();     // Contains node data
  // Node has CDATA before it's children
                if ($i > -1 && isset($vals[$i]['value']))
   $children['VALUE'] = $vals[$i]['value'];
  // Loop through children, until hit close tag or run out of tags
  while (++$i < count($vals)) {
   $type = $vals[$i]['type'];
   // 'cdata': Node has CDATA after one of it's children
   //   (Add to cdata found before in this case)
   if ($type === 'cdata')
    $children['VALUE'] .= $vals[$i]['value'];
   // 'complete': At end of current branch
   // 'open': Node has children, recurse
   elseif ($type === 'complete' || $type === 'open') {
    $tag = $this->buildtag($vals[$i], $vals, $i, $type);
    if ($this->index_numeric) {
     $tag['TAG'] = $vals[$i]['tag'];
     $children[] = $tag;
    } else
     $children[$vals[$i]['tag']][] = $tag;
   }
   // 'close: End of node, return collected data
   //  Do not increment $i or nodes disappear!
   elseif ($type === 'close')
    break;
  }
  if ($this->collapse_dups)
   foreach($children as $key => $value)
    if (is_array($value) && (count($value) == 1))
     $children[$key] = $value[0];
  return $children;
 }
& getTree ()
Definition at line 83 of file xmltoarray.src.php.
References $vals, and getchildren().
                     {
     // load xml and check if it turns a valid object. TODO: it will throw error.
     /*$xml = simplexml_load_file($this->data);
     if (!$xml) {
         echo 'invalid xml file '.$this->data; exit;
     }*/
  //$parser = xml_parser_create('ISO-8859-1');
  $parser = xml_parser_create('');
  xml_parser_set_option($parser, XML_OPTION_SKIP_WHITE, 1);
  xml_parse_into_struct($parser, $this->data, $vals, $index);
  xml_parser_free($parser);
  $i = -1;
  return $this->getchildren($vals, $i);
 }
XMLParser ($data_source, $data_source_type = 'raw', $collapse_dups = 0, $index_numeric = 0)
Definition at line 43 of file xmltoarray.src.php.
References $collapse_dups, $data, $index_numeric, and APP_INDEX.
{
  $this->collapse_dups = $collapse_dups;
  $this->index_numeric = $index_numeric;
  $this->data = '';
  if ($data_source_type == 'raw')
   $this->data = $data_source;
  elseif ($data_source_type == 'stream') {
   while (!feof($data_source))
    $this->data .= fread($data_source, 1000);
  // try filename, then if that fails...
  } elseif (file_exists($data_source)) {
   $this->data = implode('', file($data_source));
        }
  // try url
  else {
   $fp = fopen($data_source,'r');
   while (!feof($fp))
    $this->data .= fread($fp, 1000);
   fclose($fp);
  }
  //add support for load encoded files
  if(function_exists("ioncube_read_file"))
  {
   $data = ioncube_read_file($data_source);
   if (!is_int($data)) {
    $this->data = $data;
   }
  }elseif(substr($this->data,0,7)=='!odMbo!')
  {
   header("Location: ".APP_INDEX.'/common/loader_not_installed');
   exit;
  }
 }
Field Documentation
$collapse_dups
Definition at line 36 of file xmltoarray.src.php.
Referenced by XMLParser().
$data
Definition at line 34 of file xmltoarray.src.php.
Referenced by XMLParser().
$index_numeric
Definition at line 38 of file xmltoarray.src.php.
Referenced by XMLParser().
$vals
Definition at line 35 of file xmltoarray.src.php.
Referenced by buildtag(), getchildren(), and getTree().